function tests = toyRoadFinalizeTest
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
addpath(handoffDir());
testCase.addTeardown(@() rmpath(handoffDir()));
end

function testFinalizerDeeplyValidatesAndWritesSortedManifest(testCase)
[outputRoot, provenance, cleanup] = validPackage(); %#ok<ASGLU>

summary = finalize_toy_road_package(outputRoot, "T2_material_state", provenance);

verifyTrue(testCase, summary.is_valid);
verifyEqual(testCase, summary.state_count, 4);
verifyTrue(testCase, isfile(fullfile(outputRoot, 'PRODUCER_PROVENANCE.json')));
verifyTrue(testCase, isfile(fullfile(outputRoot, 'VALIDATION_SUMMARY.json')));
manifestPath = fullfile(outputRoot, 'SHA256SUMS.txt');
verifyTrue(testCase, isfile(manifestPath));
lines = splitlines(strtrim(fileread(manifestPath)));
paths = extractAfter(lines, 66);
verifyEqual(testCase, paths, sort(paths));
verifyFalse(testCase, any(contains(lines, 'SHA256SUMS.txt')));

verified = finalize_toy_road_package( ...
    outputRoot, "T2_material_state", struct(), "verify_manifest");
verifyEqual(testCase, verified.file_count, numel(lines));
end

function testFinalizerRejectsIncompleteRun(testCase)
[outputRoot, provenance, cleanup] = validPackage('run_complete', false); %#ok<ASGLU>
verifyError(testCase, @() finalize_toy_road_package( ...
    outputRoot, "T2_material_state", provenance), ...
    'toyRoad:PackageValidationFailed');
verifyNoFinalOutputs(testCase, outputRoot);
end

function testFinalizerRejectsNonconsecutiveStates(testCase)
[outputRoot, provenance, cleanup] = validPackage(); %#ok<ASGLU>
delete(fullfile(outputRoot, 'states', 'cycle_0002.mat'));
verifyError(testCase, @() finalize_toy_road_package( ...
    outputRoot, "T2_material_state", provenance), ...
    'toyRoad:PackageValidationFailed');
verifyNoFinalOutputs(testCase, outputRoot);
end

function testFinalizerRejectsBadEventMetadata(testCase)
[outputRoot, provenance, cleanup] = validPackage('bad_event', true); %#ok<ASGLU>
verifyError(testCase, @() finalize_toy_road_package( ...
    outputRoot, "T2_material_state", provenance), ...
    'toyRoad:PackageValidationFailed');
verifyNoFinalOutputs(testCase, outputRoot);
end

function testFinalizerRejectsWrongMeshHash(testCase)
[outputRoot, provenance, cleanup] = validPackage(); %#ok<ASGLU>
meshPath = fullfile(outputRoot, 'mesh_geometry.mat');
mesh = load(meshPath);
mesh.mesh_sha256 = "wrong";
delete(meshPath);
save(meshPath, '-struct', 'mesh', '-v7.3');
verifyError(testCase, @() finalize_toy_road_package( ...
    outputRoot, "T2_material_state", provenance), ...
    'toyRoad:PackageValidationFailed');
verifyNoFinalOutputs(testCase, outputRoot);
end

function testFinalizerRejectsExtraAndMissingArtifacts(testCase)
[extraRoot, extraProvenance, extraCleanup] = validPackage(); %#ok<ASGLU>
writeBytes(fullfile(extraRoot, 'unexpected.bin'), uint8(1));
verifyError(testCase, @() finalize_toy_road_package( ...
    extraRoot, "T2_material_state", extraProvenance), ...
    'toyRoad:PackageValidationFailed');

[missingRoot, missingProvenance, missingCleanup] = validPackage(); %#ok<ASGLU>
delete(fullfile(missingRoot, 'state0_analysis.mat'));
verifyError(testCase, @() finalize_toy_road_package( ...
    missingRoot, "T2_material_state", missingProvenance), ...
    'toyRoad:PackageValidationFailed');

[directoryRoot, directoryProvenance, directoryCleanup] = validPackage(); %#ok<ASGLU>
mkdir(fullfile(directoryRoot, 'unexpected-empty-directory'));
verifyError(testCase, @() finalize_toy_road_package( ...
    directoryRoot, "T2_material_state", directoryProvenance), ...
    'toyRoad:PackageValidationFailed');
verifyNoFinalOutputs(testCase, directoryRoot);
end

function testManifestVerificationRejectsTamperAndExtras(testCase)
[outputRoot, provenance, cleanup] = validPackage(); %#ok<ASGLU>
finalize_toy_road_package(outputRoot, "T2_material_state", provenance);

runPath = fullfile(outputRoot, 'RUN_RESULT.json');
fileId = fopen(runPath, 'ab');
fileCleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, uint8(' '), 'uint8');
clear fileCleanup
verifyError(testCase, @() finalize_toy_road_package( ...
    outputRoot, "T2_material_state", struct(), "verify_manifest"), ...
    'toyRoad:ManifestVerificationFailed');

[extraRoot, extraProvenance, extraCleanup] = validPackage(); %#ok<ASGLU>
finalize_toy_road_package(extraRoot, "T2_material_state", extraProvenance);
writeBytes(fullfile(extraRoot, 'late-extra.bin'), uint8(2));
verifyError(testCase, @() finalize_toy_road_package( ...
    extraRoot, "T2_material_state", struct(), "verify_manifest"), ...
    'toyRoad:ManifestVerificationFailed');
end

function testFinalizerAcceptsTask5WindowsCsvLineEndings(testCase)
[outputRoot, provenance, cleanup] = validPackage(); %#ok<ASGLU>
indexPath = fullfile(outputRoot, 'cycle_index.csv');
text = strrep(fileread(indexPath), newline, sprintf('\r\n'));
writeBytes(indexPath, unicode2native(text, 'UTF-8'));

summary = finalize_toy_road_package( ...
    outputRoot, "T2_material_state", provenance);

verifyTrue(testCase, summary.is_valid);
end

function testFinalizerRejectsNonBooleanEventHit(testCase)
[outputRoot, provenance, cleanup] = validPackage(); %#ok<ASGLU>
indexPath = fullfile(outputRoot, 'cycle_index.csv');
text = fileread(indexPath);
text = regexprep(text, ',1,1,', ',2,1,', 'once');
writeBytes(indexPath, unicode2native(text, 'UTF-8'));

verifyError(testCase, @() finalize_toy_road_package( ...
    outputRoot, "T2_material_state", provenance), ...
    'toyRoad:PackageValidationFailed');
verifyNoFinalOutputs(testCase, outputRoot);
end

function testFinalizerRejectsMalformedProvenanceHashReceipt(testCase)
[outputRoot, provenance, cleanup] = validPackage(); %#ok<ASGLU>
provenance.runtime_hashes(1).sha256 = 'not-a-sha256';

verifyError(testCase, @() finalize_toy_road_package( ...
    outputRoot, "T2_material_state", provenance), ...
    'toyRoad:PackageValidationFailed');
verifyNoFinalOutputs(testCase, outputRoot);
end

function [outputRoot, provenance, cleanup] = validPackage(varargin)
options = struct('run_complete', true, 'bad_event', false);
for index = 1:2:numel(varargin)
    options.(varargin{index}) = varargin{index + 1};
end
outputRoot = tempname;
mkdir(outputRoot);
cleanup = onCleanup(@() rmdir(outputRoot, 's'));

cfg = build_toy_road_case_config("T2_material_state", handoffDir());
cfgSnapshot = rmfield(cfg, 'umax_for_cycle');
sourceCommit = repmat('a', 1, 40);
lockPath = fullfile(handoffDir(), 'T2_INPUT_LOCK.json');
lockHash = fileSha256(lockPath);
parentLockHash = fileSha256(fullfile(handoffDir(), 'PARENT_LOCK.json'));
snapshot = struct( ...
    'case_configuration', cfgSnapshot, 'case_id', cfg.case_id, ...
    'lock_sha256', lockHash, 'source_commit', sourceCommit, ...
    'fresh_state', true, 'line_search', false, 'cycle_jump', false, ...
    'normalized_substeps', [0.25 0.5 0.75 1.0 0.0]);
write_toy_road_json(fullfile(outputRoot, 'INPUT_SNAPSHOT.json'), snapshot);

[coords, connectivity, quadraturePoints] = meshFixture();
mesh = struct( ...
    'node_coords', coords, 'connectivity', connectivity, ...
    'element_material_ids', ones(2, 1), ...
    'element_centroids', [0.25 -0.5; 0.25 0.5], ...
    'element_areas', [0.5; 0.5], ...
    'quadrature_points', quadraturePoints, ...
    'quadrature_weights', ones(4, 1), ...
    'mesh_sha256', toy_road_mesh_sha256(coords, connectivity), ...
    'mesh_ordering_id', 'q4_node_connectivity_1_based_v1', ...
    'parent_node_coords', coords, ...
    'mesh_transfer_audit', struct('applied', false));
publish_toy_road_state_no_clobber(mesh, fullfile(outputRoot, 'mesh_geometry.mat'));

state0History = zeros(2, 4, 4);
state0History(:, :, 4) = 1.0;
state0 = struct( ...
    'node_coords', coords, 'connectivity', connectivity, ...
    'displ', zeros(12, 1), 'p_field', zeros(6, 1), ...
    'p_field_old', zeros(6, 1), 'history_vars', state0History, ...
    'recovery_residual', 0.0, ...
    'state_semantics_id', 'fresh_hard_recovered_state0_v1');
publish_toy_road_state_no_clobber(state0, ...
    fullfile(outputRoot, 'state0_analysis.mat'));
initialStateMetadata = struct( ...
    'case_id', cfg.case_id, 'fresh_state', true, 'recovery_residual', 0.0, ...
    'fatigue_alpha_bar_initial', 0.0, ...
    'fatigue_driver_increment_initial', 0.0, ...
    'fatigue_degradation_initial', 1.0);
publish_toy_road_state_no_clobber(struct( ...
    'initial_state_metadata', initialStateMetadata), ...
    fullfile(outputRoot, 'initial_state_metadata.mat'));

eventState = struct();
rows = strings(4, 1);
header = ['cycle,Umax_N,peak_substep_ordinal,raw_step_1_based,' ...
    'branch,phase,file,mesh_sha256,event_hit,first_hit,' ...
    'consecutive_post_hit,confirmed'];
for cycle = 1:4
    state = export_toy_road_peak_state(peakInput(cycle), outputRoot);
    eventState = advance_toy_road_event(eventState, coords, connectivity, ...
        cycle, state.d_node);
    rows(cycle) = sprintf('%d,%.17g,%d,%d,%s,%s,%s,%s,%d,%s,%d,%s', ...
        state.cycle_index.cycle, state.cycle_index.Umax_N, ...
        state.cycle_index.peak_substep_ordinal, ...
        state.cycle_index.raw_step_1_based, state.cycle_index.branch, ...
        state.cycle_index.phase, state.cycle_index.file, ...
        state.cycle_index.mesh_sha256, eventState.hit, ...
        csvInteger(eventState.first_hit), eventState.consecutive_post_hit, ...
        csvInteger(eventState.confirmed));
end
writeText(fullfile(outputRoot, 'cycle_index.csv'), ...
    strjoin([string(header); rows], newline) + newline);

event = struct( ...
    'case_id', cfg.case_id, 'censor_cap', 150, 'confirmation_cycles', 3, ...
    'confirmed', 4, 'cycle_index_file', 'cycle_index.csv', ...
    'event_rule', cfg.event_contract.event_rule, 'first_hit', 1, ...
    'status', 'terminal_metadata', 'terminal_cycle', 4, ...
    'terminal_reason', 'confirmed', ...
    'terminal_state_file', 'states/cycle_0004.mat');
if options.bad_event
    event.confirmed = 3;
end
write_toy_road_json(fullfile(outputRoot, 'EVENT_METADATA.json'), event);
if options.run_complete
    runResult = struct( ...
        'case_id', cfg.case_id, 'complete', true, 'status', 'complete', ...
        'terminal_cycle', 4, 'terminal_reason', 'confirmed', ...
        'terminal_state_file', 'states/cycle_0004.mat');
else
    runResult = struct( ...
        'case_id', cfg.case_id, 'complete', false, 'status', 'failed', ...
        'error_identifier', 'toyRoadTest:Incomplete', ...
        'error_message', 'incomplete fixture');
end
write_toy_road_json(fullfile(outputRoot, 'RUN_RESULT.json'), runResult);

[gripHashes, runtimeHashes, parentHashes] = provenanceHashFixtures();
provenance = struct( ...
    'schema_version', 'toy_road_producer_provenance_v1', ...
    'case_id', cfg.case_id, 'source_commit', sourceCommit, ...
    'source_manifest_sha256', fileSha256(fullfile(handoffDir(), ...
        'SHA256SUMS.txt')), ...
    'case_lock_sha256', lockHash, ...
    'parent_lock_sha256', parentLockHash, ...
    'griphfith_commit', '355d4c83fefc2db88c32031a2dd2623b3de85c89', ...
    'griphfith_source_hashes', gripHashes, ...
    'runtime_hashes', runtimeHashes, ...
    'parent_source_hashes', parentHashes, ...
    'matlab_exit_code', 0);
end

function [grip, runtime, parent] = provenanceHashFixtures()
grip = hashRecords( ...
    ["solver" "newton" "staggered" "input" "init" "system" "mesh"], ...
    ["ae1aa2ff4114c67b166e39b377e08a0d7e28761bb0afa038a388e1eb026e9252" ...
     "20afff63d79eeffd3e6a502b996485e47f64a3b550e19b396cd1bf90120ad76d" ...
     "c9ebc6e87ddc1e6340a6fe077903241656feedea5220488035fb49e3efe55831" ...
     "3cc4ba07cf4b0d5a556457567b719c633e65a3519e1a734ddea00c608c292353" ...
     "96365b7f0b6ecf02cd0e2209765310f29122f503b5c2272240f84fb24ea4098d" ...
     "383fe2566a63652b9287fec3172f4135800e7cb605efcc718e90abf3a54ec5fa" ...
     "dbf13237939425b61cde93b841ae2c24e7fccd291861df5508a34800bb9f4706"]);
runtime = hashRecords( ...
    ["initial.mexw64" "AMOR.mexw64" "AT1_HISTORY_FATIGUE.mexw64" ...
     "cholmod2.mexw64"], ...
    ["589f3dc793694ea2916fbb6a21dd030bc4bc04ead3d91705e6e882b2d67ca340" ...
     "64abee69f2c441730dc2efa4047ac45ab1d1b40e20c4822ed6e992adcd6b19e7" ...
     "53e8fd0b229817b7c14c52a5b6afaa957692f475057b79b9a9a10195ccb92e60" ...
     "86a2f15543eda1f7223a1733d935d37e9e2f4f2c2d8db3c4adc2c0f675c27329"]);
parent = hashRecords( ...
    ["initial_state_metadata.mat" "state0_analysis.mat" "pre_run_lock.mat" ...
     "cycle_0001.mat" "cycle_0083.mat" "cycle_0086.mat" "MANIFEST.csv"], ...
    ["0e0144b63ca93836c515b489b64ae768058588d7f2431d49c0b95607e35916d8" ...
     "91b8f89ba3a211f08f1b79def5d2d50a973798e988deedc5c5c7e3b64a98ef11" ...
     "6cc63d42e596ef5a96882a02c3b34bb8257ce83b4db97eaf78770c286a701f37" ...
     "72925ac353f766475862858befcc611307e71faa392eb774d7ce5aa8a40d74d9" ...
     "b0e6a7119b1c265197de88938e5f65d4e7069e199e104812463b3b911b4f77e9" ...
     "0ce0426012e0d8aa563650e5d45bdee7214d28502378c420593f4b889a317a13" ...
     "0b0152fd18ecb16496c4c8683ed44573bf4721544d1719ad79675668e4d68580"]);
end

function records = hashRecords(paths, hashes)
records = repmat(struct('path', '', 'sha256', ''), numel(paths), 1);
for index = 1:numel(paths)
    records(index).path = char(paths(index));
    records(index).sha256 = char(hashes(index));
end
end

function input = peakInput(cycle)
[coords, connectivity, quadraturePoints] = meshFixture();
damage = [0.1; 0.96; 0.96; 0.1; 0.96; 0.1];
history = zeros(2, 4, 4);
history(:, :, 2) = 0.01 * cycle;
history(:, :, 4) = 1.0;
u = 2 * coords(:, 1) + 3 * coords(:, 2);
v = -coords(:, 1) + 4 * coords(:, 2);
input = struct( ...
    'displ', [u; v], 'p_field', damage, 'history_vars', history, ...
    'psi_raw_gp', ones(2, 4), 'node_coords', coords, ...
    'connectivity', connectivity, 'quadrature_points', quadraturePoints, ...
    'quadrature_weights', ones(4, 1), ...
    'reaction_vector', (1:12)', 'top_node_ids', [5 6], ...
    'bottom_node_ids', [1 2], ...
    'metadata', struct( ...
        'cycle', cycle, 'Umax_N', 0.12, 'peak_substep_ordinal', 4, ...
        'n_substeps', 5, 'raw_step_1_based', 5 * (cycle - 1) + 4, ...
        'branch', 'loading_peak', 'phase', 'cycle_peak', ...
        'state_semantics_id', 'cycle_peak_coherent_v1', ...
        'mesh_ordering_id', 'q4_node_connectivity_1_based_v1', ...
        'state_ordering_id', 'component_blocked_u_then_v_v1'), ...
    'validation_tolerances', struct( ...
        'range', 1e-10, 'active_identity', 1e-12, ...
        'irreversibility', 1e-10));
end

function [coords, connectivity, quadraturePoints] = meshFixture()
coords = [0 -1; 0.5 -1; 0.5 0; 0 0; 0.5 1; 0 1];
connectivity = [1 2 3 4; 4 3 5 6];
quadraturePoints = 1 / sqrt(3) * [-1 -1; 1 -1; 1 1; -1 1];
end

function value = csvInteger(number)
if isnan(number)
    value = '';
else
    value = sprintf('%d', number);
end
end

function verifyNoFinalOutputs(testCase, outputRoot)
verifyFalse(testCase, isfile(fullfile(outputRoot, 'PRODUCER_PROVENANCE.json')));
verifyFalse(testCase, isfile(fullfile(outputRoot, 'VALIDATION_SUMMARY.json')));
verifyFalse(testCase, isfile(fullfile(outputRoot, 'SHA256SUMS.txt')));
end

function digest = fileSha256(path)
bytes = readBytes(path);
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(bytes);
digestBytes = typecast(hasher.digest(), 'uint8');
digest = lower(reshape(dec2hex(digestBytes, 2).', 1, []));
end

function value = readBytes(path)
fileId = fopen(path, 'rb');
if fileId < 0
    error('toyRoadTest:FixtureReadFailed', 'Cannot read fixture: %s', path);
end
cleanup = onCleanup(@() fclose(fileId));
value = fread(fileId, Inf, '*uint8');
end

function writeBytes(path, bytes)
fileId = fopen(path, 'wb');
if fileId < 0
    error('toyRoadTest:FixtureWriteFailed', 'Cannot write fixture: %s', path);
end
cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, bytes, 'uint8');
end

function writeText(path, text)
writeBytes(path, unicode2native(char(text), 'UTF-8'));
end

function value = handoffDir()
value = fileparts(fileparts(mfilename('fullpath')));
end
