function tests = toyRoadFinalizeTest
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
handoff = fileparts(fileparts(mfilename('fullpath')));
addpath(handoff);
testCase.addTeardown(@() rmpath(handoff));
end

function testFinalizesAndValidatesExactPackage(testCase)
[root, contractPath, attemptPath] = makeRawPackage(testCase);
summary = finalize_toy_road_family_package(root, ...
    'T1_initial_defect', contractPath, attemptPath);
verifyTrue(testCase, summary.is_valid);
verifyTrue(testCase, isfile(fullfile(root, 'TERMINAL_MANIFEST.json')));
verifyTrue(testCase, isfile(fullfile(root, 'SHA256SUMS.txt')));
verifyTrue(testCase, isfile(fullfile(root, 'VALIDATION_SUMMARY.json')));
verifyTrue(testCase, validate_toy_road_terminal_package(root, ...
    'T1_initial_defect', contractPath).is_valid);
end

function testRefusesToClobberFinalizedPackage(testCase)
[root, contractPath, attemptPath] = makeRawPackage(testCase);
finalize_toy_road_family_package(root, 'T1_initial_defect', ...
    contractPath, attemptPath);
verifyError(testCase, @() finalize_toy_road_family_package(root, ...
    'T1_initial_defect', contractPath, attemptPath), ...
    'toyRoadP0:FinalizationClobber');
end

function testRejectsIncompleteCycleCoverageBeforePublication(testCase)
[root, contractPath, attemptPath] = makeRawPackage(testCase);
delete(fullfile(root, 'substeps', 'cycle_0003.mat'));
verifyError(testCase, @() finalize_toy_road_family_package(root, ...
    'T1_initial_defect', contractPath, attemptPath), ...
    'toyRoadP0:InvalidFinalizationInput');
verifyFalse(testCase, isfile(fullfile(root, 'TERMINAL_MANIFEST.json')));
end

function testRejectsAttemptBoundToDifferentRuntime(testCase)
[root, contractPath, attemptPath] = makeRawPackage(testCase);
attempt = jsondecode(fileread(attemptPath));
attempt.runtime_lock_sha256 = repmat('0', 1, 64);
delete(attemptPath);
writeJson(attemptPath, attempt);
verifyError(testCase, @() finalize_toy_road_family_package(root, ...
    'T1_initial_defect', contractPath, attemptPath), ...
    'toyRoadP0:InvalidFinalizationInput');
end

function testRejectsAttemptBoundToDifferentPhysicalInput(testCase)
[root, contractPath, attemptPath] = makeRawPackage(testCase);
attempt = jsondecode(fileread(attemptPath));
attempt.physical_input_sha256 = repmat('0', 1, 64);
delete(attemptPath);
writeJson(attemptPath, attempt);
verifyError(testCase, @() finalize_toy_road_family_package(root, ...
    'T1_initial_defect', contractPath, attemptPath), ...
    'toyRoadP0:InvalidFinalizationInput');
end

function testRejectsFileAddedAfterManifestClosure(testCase)
[root, contractPath, attemptPath] = makeRawPackage(testCase);
finalize_toy_road_family_package(root, 'T1_initial_defect', ...
    contractPath, attemptPath);
writeText(fullfile(root, 'unmanifested.txt'), 'extra');
verifyError(testCase, @() validate_toy_road_terminal_package(root, ...
    'T1_initial_defect', contractPath), ...
    'toyRoadP0:InvalidTerminalPackage');
end

function [root, contractPath, attemptPath] = makeRawPackage(testCase)
fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
root = fullfile(fixture.Folder, 'T1_initial_defect');
mkdir(root); mkdir(fullfile(root, 'substeps')); mkdir(fullfile(root, 'qualification'));
scope = 'test_only_non_authorizing';
[~, ~, state0, contract] = toyRoadShardFixture(1);
lockPath = fullfile(root, 'EXECUTION_INPUT_LOCK.json');
lock = fixtureLock(scope, contract, root);
writeJson(lockPath, lock);
contract.execution_input_lock_sha256 = fileSha256(lockPath);
snapshotPath = fullfile(root, 'INPUT_SNAPSHOT.json');
snapshot = struct('schema_version','toy_road_p0_input_snapshot_v1', ...
    'case_id','T1_initial_defect','source_commit',lock.source_commit, ...
    'runtime_lock_sha256',lock.runtime_lock_sha256, ...
    'family_contract_sha256',contract.family_contract_sha256, ...
    'case_physics_contract_sha256',contract.case_physics_contract_sha256, ...
    'execution_input_lock_sha256',contract.execution_input_lock_sha256);
writeJson(snapshotPath, snapshot);
contractPath = fullfile(fixture.Folder, 'contract.mat');
save(contractPath, 'contract');
save(fullfile(root, 'STATE0.mat'), 'state0');
for cycle = 1:5
    [shard, ~, ~, ~] = toyRoadShardFixture(cycle);
    shard = applyContract(shard, contract);
    save(fullfile(root, 'substeps', sprintf('cycle_%04d.mat', cycle)), 'shard');
end
tracePath = fullfile(root, 'qualification', 'C5_STAGGER_TRACE.csv');
trace = sprintf(['authorization_scope,case_id,cycle,substep_ordinal,' ...
    'stagger_iteration,reassembly_ordinal,displacement_residual,' ...
    'raw_phase_residual,projected_phase_kkt,consecutive_stagger_delta,' ...
    'primal_feasibility\n%s,T1_initial_defect,5,4,1,1,0.0002,' ...
    '0.0008,0.0003,0.0008,1e-13\n%s,T1_initial_defect,5,4,2,2,' ...
    '1e-05,0.0006,2e-05,3e-05,0\n'], scope, scope);
writeText(tracePath, trace);
receipt = c5Receipt(scope, tracePath);
writeJson(fullfile(root, 'qualification', ...
    'C5_NUMERICAL_GATE_RECEIPT.json'), receipt);
cycle5 = fullfile(root, 'substeps', 'cycle_0005.mat');
event = struct('authorization_scope', scope, 'case_id', 'T1_initial_defect', ...
    'first_hit_cycle', 2, 'confirmed_cycle', 5, 'terminal_cycle', 5, ...
    'peak_substep_ordinal', 4, 'cycle_shard', 'substeps/cycle_0005.mat', ...
    'cycle_shard_sha256', fileSha256(cycle5));
writeJson(fullfile(root, 'EVENT_METADATA.json'), event);
terminal = struct('authorization_scope', scope, 'case_id', ...
    'T1_initial_defect', 'terminal_reason', 'confirmed_penetration', ...
    'terminal_cycle', 5, 'first_hit_cycle', 2, 'confirmed_cycle', 5);
writeJson(fullfile(root, 'TERMINAL_RESULT.json'), terminal);
attempt = struct('attempt_id', 'fixture-attempt', 'case_id', ...
    'T1_initial_defect', 'source_commit', lock.source_commit, ...
    'family_contract_sha256', contract.family_contract_sha256, ...
    'case_physics_contract_sha256', contract.case_physics_contract_sha256, ...
    'execution_input_lock_sha256', contract.execution_input_lock_sha256, ...
    'runtime_lock_sha256', contract.runtime_lock_sha256, ...
    'physical_input_sha256', fileSha256(snapshotPath), ...
    'solver_sha256', repmat('6',1,64), 'recovery_sha256', repmat('7',1,64), ...
    'exporter_sha256', repmat('8',1,64), ...
    'numerical_gate_contract_sha256', repmat('9',1,64), ...
    'event_contract_sha256', repmat('0',1,64));
attemptPath = fullfile(fixture.Folder, 'attempt.json');
writeJson(attemptPath, attempt);
end

function lock = fixtureLock(scope, contract, root)
matlabIdentity = struct('release','R2025b','update','Update 5', ...
    'version','25.2','computer','PCWIN64','executable_sha256',repmat('a',1,64), ...
    'blas','fixture','lapack','fixture','absolute_path_order',{{root}});
runtime = struct('matlab',matlabIdentity,'binary_sha256',struct( ...
    'initial',repmat('b',1,64),'AMOR',repmat('c',1,64), ...
    'AT1_HISTORY_FATIGUE',repmat('d',1,64),'cholmod2',repmat('e',1,64)));
roots = struct('output',root,'work',[root '-work'],'temp',[root '-temp'], ...
    'tmp',[root '-tmp'],'pref',[root '-pref'],'cache',[root '-cache'], ...
    'matlab_startup_pref',[root '-startup']);
lock = struct('schema_version','toy_road_execution_input_lock_v1', ...
    'protocol_version','toy-road-p0-repeatability-v2.1', ...
    'authorization_scope',scope,'case_id','T1_initial_defect', ...
    'family_contract_sha256',contract.family_contract_sha256, ...
    'case_physics_contract_sha256',contract.case_physics_contract_sha256, ...
    'source_commit',repmat('a',1,40), ...
    'runtime_lock_sha256',contract.runtime_lock_sha256, ...
    'source_manifest_sha256',repmat('f',1,64), ...
    'runtime_expectations',runtime,'writable_roots',roots, ...
    'launch_timestamp_utc','2026-08-03T12:00:00Z', ...
    'no_clobber_receipt_id','fixture','resume_allowed',false);
end

function receipt = c5Receipt(scope, tracePath)
receipt = struct('authorization_scope',scope,'case_id','T1_initial_defect', ...
    'cycle',5,'substep_ordinal',4,'status','PASS','passed',true, ...
    'trace_sha256',fileSha256(tracePath),'trace_row_count',2, ...
    'reassembly_count',2,'final_stagger_iteration',2, ...
    'final_reassembly_ordinal',2,'final_displacement_residual',1e-5, ...
    'final_raw_phase_residual',6e-4,'final_projected_phase_kkt',2e-5, ...
    'final_consecutive_stagger_delta',3e-5,'final_primal_feasibility',0, ...
    'displacement_residual_threshold',4e-4, ...
    'projected_phase_kkt_threshold',4e-4, ...
    'consecutive_stagger_delta_threshold',1e-3, ...
    'primal_feasibility_threshold',1e-12);
end

function shard = applyContract(shard, contract)
fields = {'mesh_sha256','element_ordering_id','gp_ordering_id', ...
    'state_semantics_id','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256'};
for index = 1:numel(fields), shard.(fields{index}) = contract.(fields{index}); end
end

function writeJson(path, value), writeText(path, [jsonencode(value) newline]); end
function writeText(path, value)
fileId = fopen(path,'wb'); cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId,unicode2native(value,'UTF-8'),'uint8');
end

function digest = fileSha256(path)
fileId = fopen(path,'rb'); cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId,Inf,'*uint8');
hasher = java.security.MessageDigest.getInstance('SHA-256'); hasher.update(bytes);
raw = typecast(hasher.digest(),'uint8');
digest = lower(reshape(dec2hex(raw,2).',1,[]));
end
