function tests = toyRoadDriverContractTest
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
addpath(handoffDir());
addpath(fileparts(mfilename('fullpath')));
testCase.addTeardown(@() rmpath(handoffDir()));
testCase.addTeardown(@() rmpath(fileparts(mfilename('fullpath'))));
end

function setup(testCase)
root = tempname;
mkdir(root);
testCase.TestData.root = root;
testCase.addTeardown(@() removeRoot(root));
end

function testControlledInjectionCannotEnterProductionDriver(testCase)
request = fixtureRequest(testCase.TestData.root, 'P0_parent');
dependencies = fixtureDependencies();

verifyError(testCase, @() main_toy_road_family_case(request,dependencies), ...
    'toyRoadP0:AuthorizationRejected');
verifyFalse(testCase, isfolder(request.output_root));
verifyFalse(testCase, isfolder(request.work_root));
end

function testAuthorizationMismatchStopsBeforeCreatingRoots(testCase)
request = fixtureRequest(testCase.TestData.root, 'P0_parent');
request.authorization_receipt.case_id = 'P0R_parent_repeat';

verifyError(testCase, @() main_toy_road_family_case( ...
    request, fixtureDependencies()), 'toyRoadP0:AuthorizationRejected');
verifyFalse(testCase, isfolder(request.output_root));
verifyFalse(testCase, isfolder(request.work_root));
end

function testPreflightScopeCannotRunDriver(testCase)
request = fixtureRequest(testCase.TestData.root, 'T1_initial_defect');
request.authorization_scope = 'preflight_only_non_authorizing';
request.authorization_receipt.authorization_scope = ...
    'preflight_only_non_authorizing';

verifyError(testCase, @() main_toy_road_family_case( ...
    request, fixtureDependencies()), 'toyRoadP0:AuthorizationRejected');
verifyFalse(testCase, isfolder(request.output_root));
end

function testReusedOrAliasedWritableRootsFailClosed(testCase)
request = fixtureRequest(testCase.TestData.root, 'P0_parent');
mkdir(request.work_root);
verifyError(testCase, @() reserve_toy_road_writable_roots(request), ...
    'toyRoadP0:FreshRootRequired');
verifyFalse(testCase, isfolder(request.output_root));

rmdir(request.work_root);
request.temp_root = request.cache_root;
verifyError(testCase, @() reserve_toy_road_writable_roots(request), ...
    'toyRoadP0:FreshRootRequired');
verifyFalse(testCase, isfolder(request.output_root));
end

function testResumeOrCheckpointInjectionIsRejected(testCase)
request = fixtureRequest(testCase.TestData.root, 'P0R_parent_repeat');
request.resume_root = fullfile(testCase.TestData.root, 'p0_output');

verifyError(testCase, @() main_toy_road_family_case( ...
    request, fixtureDependencies()), 'toyRoadP0:AuthorizationRejected');
verifyFalse(testCase, isfolder(request.output_root));
end

function testDriverRequiresAllProvenanceAndDigests(testCase)
request = rmfield(fixtureRequest(testCase.TestData.root, 'T2_material_state'), ...
    'execution_input_lock_sha256');

verifyError(testCase, @() main_toy_road_family_case( ...
    request, fixtureDependencies()), 'toyRoadP0:AuthorizationRejected');
end

function testEntrypointDeclaresProductionEnvironmentContract(testCase)
source = fileread(fullfile(handoffDir(), 'main_toy_road_family_case.m'));
required = {'TOY_ROAD_CASE_ROLE','TOY_ROAD_SOURCE_COMMIT', ...
    'TOY_ROAD_RUNTIME_LOCK_SHA256','TOY_ROAD_FAMILY_CONTRACT_SHA256', ...
    'TOY_ROAD_CASE_PHYSICS_CONTRACT_SHA256', ...
    'TOY_ROAD_EXECUTION_INPUT_LOCK_SHA256','TOY_ROAD_OUTPUT_ROOT', ...
    'TOY_ROAD_WORK_ROOT','TOY_ROAD_TEMP_ROOT','TOY_ROAD_TMP_ROOT', ...
    'TOY_ROAD_PREF_ROOT','TOY_ROAD_CACHE_ROOT', ...
    'TOY_ROAD_INPUT_ASSETS_ROOT','TOY_ROAD_AUTHORIZATION_RECEIPT'};
for index = 1:numel(required)
    verifyNotEmpty(testCase, strfind(source, required{index}));
end
verifyNotEmpty(testCase, strfind(source, 'solve_toy_road_family_case'));
verifyEmpty(testCase, strfind(source, 'toy_to_road_independent_fem_20260731'));
verifyNotEmpty(testCase, strfind(source, ...
    'sys.CC,d,snapshot.d_lb,raw'));
end

function request = fixtureRequest(root, role)
request = struct( ...
    'authorization_scope', 'test_only_non_authorizing', ...
    'authorization_receipt', struct(), ...
    'case_id', role, ...
    'source_commit', repmat('a',1,40), ...
    'runtime_lock_sha256', repmat('2',1,64), ...
    'family_contract_sha256', repmat('3',1,64), ...
    'case_physics_contract_sha256', repmat('4',1,64), ...
    'execution_input_lock_sha256', repmat('5',1,64), ...
    'output_root', fullfile(root, ['output_' role]), ...
    'work_root', fullfile(root, ['work_' role]), ...
    'temp_root', fullfile(root, ['temp_' role]), ...
    'tmp_root', fullfile(root, ['tmp_' role]), ...
    'pref_root', fullfile(root, ['pref_' role]), ...
    'cache_root', fullfile(root, ['cache_' role]), ...
    'input_assets_root', fullfile(root, 'input_assets'));
if ~isfolder(request.input_assets_root)
    mkdir(request.input_assets_root);
end
request.authorization_receipt = struct( ...
    'status','PASS', ...
    'authorization_scope',request.authorization_scope, ...
    'authorized_entrypoint','main_toy_road_family_case', ...
    'case_id',request.case_id, ...
    'source_commit',request.source_commit, ...
    'runtime_lock_sha256',request.runtime_lock_sha256, ...
    'family_contract_sha256',request.family_contract_sha256, ...
    'case_physics_contract_sha256',request.case_physics_contract_sha256, ...
    'execution_input_lock_sha256',request.execution_input_lock_sha256);
end

function dependencies = fixtureDependencies()
dependencies = struct( ...
    'load_parent_mesh', @loadParentMesh, ...
    'build_recovery_input', @buildRecoveryInput, ...
    'build_solver_context', @buildSolverContext, ...
    'runtime_receipt', @runtimeReceipt, ...
    'solve_family_case', @solve_toy_road_family_case);
end

function mesh = loadParentMesh(~)
mesh = struct( ...
    'node_coords', [-.5 -.5; .5 -.5; .5 .5; -.5 .5], ...
    'connectivity', [1 2 3 4]);
end

function input = buildRecoveryInput(~,~)
input = struct( ...
    'p_field', zeros(4,1), ...
    'p_field_old', zeros(4,1), ...
    'history_vars_old', zeros(1,4,4), ...
    'num_elem', 1, 'num_gauss_pts', 4, ...
    'sol_step_par', struct('n_step',5,'line_search',false), ...
    'sol_par', struct('max_iter_pf',25,'tol_p_field',4e-4), ...
    'system_factory', @systemFactory, ...
    'recovery_newton', @recoveryNewton);
end

function sys = systemFactory(d)
sys = struct('phase_field_input',d);
end

function [d,history,residual,failed,details] = recoveryNewton(varargin)
d = 0.1*ones(4,1);
history = 9*ones(1,4,4);
residual = 1e-5;
failed = false;
details = struct('kind','controlled');
end

function context = buildSolverContext(~,~,request)
double = ToyRoadP0SolverDouble();
context = double.makeContext(request.output_root, request.case_id);
end

function receipt = runtimeReceipt(request)
receipt = struct( ...
    'status','PASS', ...
    'authorization_scope',request.authorization_scope, ...
    'case_id',request.case_id, ...
    'source_commit',request.source_commit, ...
    'runtime_lock_sha256',request.runtime_lock_sha256);
end

function removeRoot(root)
if isfolder(root)
    rmdir(root,'s');
end
end

function value = handoffDir()
value = fileparts(fileparts(mfilename('fullpath')));
end
