classdef (Sealed) ToyRoadP0ControlledDriverAdapter < handle
    properties (Constant)
        CONTROLLED_IDENTITY = 'toy_road_p0_controlled_driver_adapter_v1'
    end

    properties (SetAccess = private)
        SolverInvocationCount = 0
        LastSolverContext = struct()
        FactoryInputs = {}
    end

    methods
        function dependencies = sealedDependencies(obj)
            dependencies = struct( ...
                'load_parent_mesh',@(root) obj.loadParentMesh(root), ...
                'build_recovery_input',@(cfg,mesh) ...
                    obj.buildRecoveryInput(cfg,mesh), ...
                'build_solver_context',@(cfg,recovery,request) ...
                    obj.buildSolverContext(cfg,recovery,request), ...
                'runtime_receipt',@(request) obj.runtimeReceipt(request), ...
                'solve_family_case',@(context) obj.solveControlled(context));
        end
    end

    methods (Access = private)
        function mesh = loadParentMesh(~,~)
            mesh = struct( ...
                'node_coords',[-.5 -.5;.5 -.5;.5 .5;-.5 .5], ...
                'connectivity',[1 2 3 4]);
        end

        function input = buildRecoveryInput(obj,cfg,~)
            input = struct( ...
                'p_field',zeros(4,1), ...
                'p_field_old',zeros(4,1), ...
                'history_vars_old',zeros(1,4,4), ...
                'num_elem',1, ...
                'num_gauss_pts',4, ...
                'sol_step_par',cfg.sol_step_par, ...
                'sol_par',struct('max_iter_pf',25,'tol_p_field',4e-4), ...
                'system_factory',@(d) obj.systemFactory(d), ...
                'recovery_newton',@(varargin) ...
                    obj.recoveryNewton(varargin{:}));
        end

        function [system,record] = systemFactory(obj,d)
            obj.FactoryInputs{end+1} = d;
            ordinal = numel(obj.FactoryInputs);
            system = ToyRoadP0RecoverySystem(d);
            record = struct( ...
                'construction_ordinal',ordinal, ...
                'phase_field',d, ...
                'system_class',class(system), ...
                'system_identity',sprintf('sealed_controlled_system_%d',ordinal));
        end

        function [d,history,residual,failed,details] = ...
                recoveryNewton(~,varargin)
            d = [-1e-8;0.25;0.75;1+1e-8];
            history = 7*ones(1,4,4);
            residual = 2e-5;
            failed = false;
            details = struct('kind','sealed_controlled_zero_load');
        end

        function context = buildSolverContext(~,~,~,request)
            double = ToyRoadP0SolverDouble();
            context = double.makeContext(request.output_root,request.case_id);
        end

        function receipt = runtimeReceipt(~,request)
            receipt = struct( ...
                'status','PASS', ...
                'authorization_scope',request.authorization_scope, ...
                'case_id',request.case_id, ...
                'source_commit',request.source_commit, ...
                'runtime_lock_sha256',request.runtime_lock_sha256);
        end

        function result = solveControlled(obj,context)
            obj.SolverInvocationCount = obj.SolverInvocationCount + 1;
            obj.LastSolverContext = context;
            result = struct( ...
                'complete',true, ...
                'case_id',context.case_id, ...
                'controlled_solver_invocations',obj.SolverInvocationCount);
        end
    end
end
