function [shard, previous, state0, contract] = toyRoadShardFixture(cycle)
nNode = 4; nElem = 1; nGp = 4;
contract = toyRoadFixtureContract();
N = 0.25 * ones(nGp, nNode);
dNode = repmat(linspace(0.10, 0.14, 5) + 0.04*(cycle-1), nNode, 1);
dGp = zeros(nElem, nGp, 5);
for s = 1:5
    dGp(:,:,s) = dNode(:,s).' * N.';
end
alpha = reshape(linspace(0.01, 0.05, 5) + 0.05*(cycle-1), 1, 1, 5) .* ...
    ones(nElem,nGp,5);
f = min(1, (1 - ((alpha - 0.5) ./ (alpha + 0.5))).^2);
raw = ones(nElem,nGp,5) .* reshape(1:5,1,1,5);
g = (1-dGp).^2;
shard = struct('cycle',cycle,'d_node',dNode,'d_gp',dGp, ...
    'alpha_bar_gp',alpha,'f_alpha_gp',f,'psi_raw_gp',raw, ...
    'g_gp',g,'psi_active_gp',g.*raw, ...
    'psi_raw_cyclemax_gp',max(raw,[],3), ...
    'substep_ordinal',1:5,'load_factor',[.25 .5 .75 1 0], ...
    'raw_step_zero_based',5*(cycle-1)+(0:4), ...
    'branch',{{'loading','loading','loading','loading','unloading'}}, ...
    'mesh_sha256',contract.mesh_sha256, ...
    'element_ordering_id',contract.element_ordering_id, ...
    'gp_ordering_id',contract.gp_ordering_id, ...
    'state_semantics_id',contract.state_semantics_id, ...
    'runtime_lock_sha256',contract.runtime_lock_sha256, ...
    'family_contract_sha256',contract.family_contract_sha256, ...
    'case_physics_contract_sha256',contract.case_physics_contract_sha256, ...
    'execution_input_lock_sha256',contract.execution_input_lock_sha256);
state0 = struct('d_node',0.09*ones(nNode,1), ...
    'alpha_bar_gp',zeros(nElem,nGp));
previous = [];
end

function contract = toyRoadFixtureContract()
contract = struct('eta',0,'alpha_T',0.5,'p',2, ...
    'mesh_sha256',repmat('1',1,64), ...
    'element_ordering_id','q4_connectivity_1_based_v1', ...
    'gp_ordering_id','q4_2x2_native_order_v1', ...
    'state_semantics_id','five_substep_post_commit_history_v1', ...
    'runtime_lock_sha256',repmat('2',1,64), ...
    'family_contract_sha256',repmat('3',1,64), ...
    'case_physics_contract_sha256',repmat('4',1,64), ...
    'execution_input_lock_sha256',repmat('5',1,64));
end
