function tests = rebuiltMexQ2ReplayContractTest
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
handoff = fileparts(fileparts(mfilename('fullpath')));
family = fullfile(fileparts(handoff), ...
    'toy_to_road_independent_fem_20260731');
familyTests = fullfile(family, 'tests');
addpath(familyTests);
testCase.addTeardown(@() rmpath(familyTests));
end

function testCurrentParentBlocksBeforeAnySolverStage(testCase)
folder = matlab.unittest.fixtures.TemporaryFolderFixture;
testCase.applyFixture(folder);
handoff = fileparts(fileparts(mfilename('fullpath')));
family = fullfile(fileparts(handoff), ...
    'toy_to_road_independent_fem_20260731');
config = struct( ...
    'output_root', fullfile(folder.Folder, 'q2_blocked'), ...
    'parent_root', 'C:/q4diag/toy-road-parent-20260729', ...
    'parent_lock_path', fullfile(family, 'PARENT_LOCK.json'), ...
    'runtime_lock_path', fullfile(folder.Folder, 'must_not_be_read.json'), ...
    'runtime_root', fullfile(folder.Folder, 'must_not_be_read_runtime'), ...
    'source_root', fullfile(folder.Folder, 'must_not_be_read_source'));

receipt = run_q2_parent_cycle1_replay(config);

verifyEqual(testCase, receipt.status, 'blocked');
verifyEqual(testCase, sort(receipt.blockers), sort({ ...
    'blocked_missing_parent_damage_degradation_field', ...
    'blocked_missing_parent_active_field'}));
verifyEqual(testCase, receipt.stage, 'parent_evidence_gate');
verifyFalse(testCase, receipt.recovery_started);
verifyFalse(testCase, receipt.system_started);
verifyFalse(testCase, receipt.newton_started);
verifyFalse(testCase, receipt.cycle_started);
verifyTrue(testCase, isfile(fullfile(config.output_root, ...
    'Q2_PARENT_BLOCKER.json')));
verifyFalse(testCase, isfile(fullfile(config.output_root, ...
    'Q2_CYCLE1_TERMINAL.json')));
verifyFalse(testCase, isfile(fullfile(config.output_root, ...
    'Q2_PARENT_MASKS.mat')));
verifyEqual(testCase, receipt.replay_source_mesh_sha256, ...
    'd9ad5545e42e4d700600a69f18b625f90456253295095fdf644c55b7968b068b');
verifyEqual(testCase, receipt.parent_vtk_mesh_sha256, ...
    '4d01985bfe2e80afe7140ab1ead905ddce5843f8495a3558d2d4da3b237df5af');
end

function testHistoricalRecoveryClipsResetsAndKeepsOriginalSystem(testCase)
dofs = struct('active_dof_pf', [2; 3]);
stiffness = struct('i_row_pf', [1; 2], 'j_col_pf', [1; 2]);
initialSystem = ToyRoadRecoverySystem(struct(), struct(), struct(), dofs, ...
    struct(), struct(), struct(), struct(), zeros(4, 1), 'AT1', stiffness);
history = zeros(2, 2, 4);
input = struct( ...
    'sys', initialSystem, ...
    'assembly_pf_fh', @unusedAssembly, ...
    'p_field', [1; 0; 0; 1], ...
    'p_field_old', zeros(4, 1), ...
    'history_vars_old', history, ...
    'num_elem', 2, 'num_gauss_points', 2, ...
    'max_iter_pf', 250, 'tol_p_field', 4e-4);
operators = struct('newton_raphson', @recoveryNewton);

[sys, damage, damageOld, recoveredHistory, residual, audit] = ...
    recover_q2_parent_initial_state(input, operators);

verifyEqual(testCase, sys, initialSystem);
verifyEqual(testCase, damage, [0; 0.2; 1; 1]);
verifyEqual(testCase, damageOld, damage);
verifyEqual(testCase, recoveredHistory(:, :, 2:3), zeros(2, 2, 2));
verifyEqual(testCase, recoveredHistory(:, :, 4), ones(2, 2));
verifyEqual(testCase, residual, 2e-5);
verifyEqual(testCase, audit.recovery_projection, 'clip_[0,1]');
verifyFalse(testCase, audit.rebuild_sys_after_recovery);
verifyTrue(testCase, audit.reset_fatigue_after_recovery);

    function [initialResidual, finalResidual, field, coupling, h, failed] = ...
            recoveryNewton(varargin)
        verifyEqual(testCase, varargin{2}, initialSystem);
        verifyEqual(testCase, varargin{5}, zeros(2, 2));
        initialResidual = 1;
        finalResidual = 2e-5;
        field = [-1e-8; 0.2; 1.2; 1];
        coupling = zeros(4, 1);
        h = zeros(2, 2, 4);
        h(:, :, 1) = 0.3;
        failed = false;
    end
end

function testExporterUsesGaussPointProductAndExactElementOrder(testCase)
input = exportFixture();

state = export_q2_cycle1_fields(input);

expectedDamageGp = input.p_field(input.connectivity) * ...
    q4ShapeFunctions(input.quadrature_points).';
expectedG = (1 - expectedDamageGp) .^ 2;
verifyEqual(testCase, state.element_ids, int64((1:2)'));
verifyEqual(testCase, state.d_elem, mean(expectedDamageGp, 2), 'AbsTol', 0);
verifyEqual(testCase, state.psi_raw_GP, input.psi_raw_GP, 'AbsTol', 0);
verifyEqual(testCase, state.psi_raw_elem, mean(input.psi_raw_GP, 2), 'AbsTol', 0);
verifyEqual(testCase, state.g_GP, expectedG, 'AbsTol', 0);
verifyEqual(testCase, state.g_elem, mean(expectedG, 2), 'AbsTol', 0);
verifyEqual(testCase, state.psi_active_elem, ...
    mean(expectedG .* input.psi_raw_GP, 2), 'AbsTol', 0);
verifyNotEqual(testCase, state.psi_active_elem, ...
    mean(expectedG, 2) .* mean(input.psi_raw_GP, 2));
verifyEqual(testCase, state.field_sources.psi_active_elem, ...
    'sealed_gp:mean_gp(g_gp.*psi_raw_gp)');
verifyEqual(testCase, state.mesh_ordering_sha256, ...
    canonicalMeshHash(input.node_coords, input.connectivity));
verifyFalse(testCase, state.family_terminal_eligible);
end

function testControlledReplayDisclosesConstructorAndEffectiveCadence(testCase)
folder = matlab.unittest.fixtures.TemporaryFolderFixture;
testCase.applyFixture(folder);
context = controlledContext(folder.Folder);
preSteps = [];
newtonCalls = 0;
expectedIncrements = historicalUyIncrements();
context.operators = struct( ...
    'pre_iter_update', @preStep, ...
    'stag_vars', @(~) struct(), ...
    'newton_raphson', @newton, ...
    'stag_post_iter_update', @postStagger, ...
    'assembly_pf', @assemblyPf, ...
    'assembly_equilibrium', @assemblyEquilibrium);

result = solve_q2_parent_cycle1(context);

verifyEqual(testCase, preSteps, 1:5);
verifyEqual(testCase, newtonCalls, 10);
verifyEqual(testCase, result.status, 'q2_cycle1_diagnostic_complete');
verifyEqual(testCase, result.cycle, 1);
verifyEqual(testCase, result.constructor_request.n_step, 8);
verifyEqual(testCase, result.constructor_return.n_step, 5);
verifyEqual(testCase, result.constructor_return.uy_increment, ...
    expectedIncrements, 'AbsTol', 0);
verifyEqual(testCase, result.nominal_retained_factors, ...
    [0.25 0.5 0.75 1.0 0.0], 'AbsTol', 0);
verifyEqual(testCase, result.effective_retained_factors, ...
    cumsum(expectedIncrements) / 0.12, 'AbsTol', 0);
verifyEqual(testCase, result.effective_retained_factors(4) * 0.12, ...
    0.11999988, 'AbsTol', 1e-15);
verifyNotEqual(testCase, result.effective_retained_factors(4), 1.0);
verifyEqual(testCase, result.peak_substep_ordinal, 4);
verifyEqual(testCase, result.mesh_ordering_sha256, ...
    context.contract.replay_source_mesh_sha256);
verifyEqual(testCase, result.parent_vtk_mesh_sha256, ...
    context.contract.parent_vtk_mesh_sha256);
verifyTrue(testCase, result.mesh_bridge.connectivity_exact);
verifyEqual(testCase, result.state.replay_source_mesh_sha256, ...
    context.contract.replay_source_mesh_sha256);
verifyEqual(testCase, result.state.parent_vtk_mesh_sha256, ...
    context.contract.parent_vtk_mesh_sha256);
verifyEqual(testCase, result.state.mesh_bridge.coordinate_max_abs_error, 0);
verifyFalse(testCase, result.family_terminal_eligible);
verifyTrue(testCase, isfile(fullfile(folder.Folder, ...
    'Q2_CYCLE1_STATE.mat')));
verifyTrue(testCase, isfile(fullfile(folder.Folder, ...
    'Q2_CYCLE1_TERMINAL.json')));

    function [displ, residual, traction] = preStep(index, ~, displ, step)
        preSteps(end + 1) = index;
        verifyEqual(testCase, step.n_step, 5);
        verifyEqual(testCase, step.uy_increment, ...
            expectedIncrements, 'AbsTol', 0);
        residual = 0;
        traction = zeros(12, 1);
    end

    function [r0, r, field, raw, coupling, failed] = newton(assembly, ~, ...
            field, ~, raw, varargin)
        newtonCalls = newtonCalls + 1;
        r0 = 1;
        r = 0;
        coupling = zeros(size(field));
        failed = false;
        if isequal(assembly, context.assembly_equilibrium_fh)
            raw = [0.1 0.4; 0.2 0.8];
        end
    end

    function [vars, raw, converged, stiffness] = postStagger(varargin)
        vars = varargin{3};
        raw = [0.1 0.4; 0.2 0.8];
        converged = true;
        stiffness = speye(12);
    end

    function [a, b, c, h] = assemblyPf(varargin)
        a = [];
        b = [];
        c = [];
        h = varargin{11};
        h(:, :, 2) = 0.2;
        h(:, :, 4) = 1;
    end

    function [stiffness, reaction, raw, h] = assemblyEquilibrium(varargin)
        stiffness = [];
        reaction = zeros(12, 1);
        raw = [0.1 0.4; 0.2 0.8];
        h = [];
    end
end

function testReplayRejectsMappedOrReorderedActualMesh(testCase)
folder = matlab.unittest.fixtures.TemporaryFolderFixture;
testCase.applyFixture(folder);
context = controlledContext(folder.Folder);
solverStarted = false;
context.operators.pre_iter_update = @markStarted;

context.sys.MESH.node(1, 1) = context.sys.MESH.node(1, 1) + 0.01;
verifyError(testCase, @() solve_q2_parent_cycle1(context), ...
    'rebuiltMexQ2:ReplayMeshMismatch');
verifyFalse(testCase, solverStarted);

context = controlledContext(folder.Folder);
context.operators.pre_iter_update = @markStarted;
context.sys.MESH.elem = context.sys.MESH.elem([2 1], :);
verifyError(testCase, @() solve_q2_parent_cycle1(context), ...
    'rebuiltMexQ2:ReplayMeshMismatch');
verifyFalse(testCase, solverStarted);

    function varargout = markStarted(varargin)
        solverStarted = true;
        varargout = cell(1, max(nargout, 1));
    end
end

function testReadyMasksPublishBeforeRuntimeAndSurviveSolveFailure(testCase)
folder = matlab.unittest.fixtures.TemporaryFolderFixture;
testCase.applyFixture(folder);
parent = readyParentReceipt(2);
outputRoot = fullfile(folder.Folder, 'ready_failure');
mkdir(outputRoot);

[masks, artifact] = prepare_q2_parent_masks_for_replay(parent, outputRoot);
context = controlledContext(outputRoot);
context.operators.pre_iter_update = @failSolve;
verifyError(testCase, @() solve_q2_parent_cycle1(context), ...
    'rebuiltMexQ2:InjectedSolveFailure');

maskPath = fullfile(outputRoot, 'Q2_PARENT_MASKS.mat');
verifyTrue(testCase, isfile(maskPath));
verifyEqual(testCase, artifact.relative_path, 'Q2_PARENT_MASKS.mat');
verifyEqual(testCase, artifact.sha256, sha256File(maskPath));
verifyEqual(testCase, masks.mask_set_sha256, artifact.mask_set_sha256);

handoff = fileparts(fileparts(mfilename('fullpath')));
source = fileread(fullfile(handoff, 'run_q2_parent_cycle1_replay.m'));
maskIndex = strfind(source, 'prepare_q2_parent_masks_for_replay');
runtimeIndex = strfind(source, 'validate_runtime_lock');
solveIndex = strfind(source, 'solve_q2_parent_cycle1');
verifyLessThan(testCase, maskIndex(1), runtimeIndex(1));
verifyLessThan(testCase, maskIndex(1), solveIndex(1));

    function varargout = failSolve(varargin) %#ok<STOUT>
        error('rebuiltMexQ2:InjectedSolveFailure', 'controlled solve failure');
    end
end

function testFinalReceiptHashesArtifactsAndBindsIdentities(testCase)
folder = matlab.unittest.fixtures.TemporaryFolderFixture;
testCase.applyFixture(folder);
outputRoot = folder.Folder;
writeBytes(fullfile(outputRoot, 'Q2_CYCLE1_STATE.mat'), uint8('state'));
writeBytes(fullfile(outputRoot, 'Q2_CYCLE1_TERMINAL.json'), uint8('terminal'));
writeBytes(fullfile(outputRoot, 'Q2_METRICS.mat'), uint8('metrics'));
writeBytes(fullfile(outputRoot, 'Q2_PARENT_MASKS.mat'), uint8('masks'));
runtime = struct('lock_sha256', repmat('a', 1, 64), ...
    'initial_sha256', repmat('b', 1, 64), ...
    'source_commit', repmat('c', 1, 40));
parent = readyParentReceipt(2);
replay = struct('status', 'q2_cycle1_diagnostic_complete', ...
    'constructor_request', struct('n_step', 8), ...
    'constructor_return', struct('n_step', 5, ...
    'uy_increment', historicalUyIncrements()), ...
    'nominal_retained_factors', [0.25 0.5 0.75 1 0], ...
    'effective_retained_factors', cumsum(historicalUyIncrements()) / 0.12, ...
    'mesh_ordering_sha256', parent.replay_source_mesh_sha256, ...
    'replay_source_mesh_sha256', parent.replay_source_mesh_sha256, ...
    'parent_vtk_mesh_sha256', parent.parent_vtk_mesh_sha256, ...
    'mesh_bridge', fixtureBridge(parent.replay_source_mesh_sha256, ...
    parent.parent_vtk_mesh_sha256));
metrics = struct('passed', true, 'mask_set_sha256', repmat('d', 1, 64));
maskArtifact = struct('relative_path', 'Q2_PARENT_MASKS.mat', ...
    'sha256', sha256File(fullfile(outputRoot, 'Q2_PARENT_MASKS.mat')), ...
    'mask_set_sha256', metrics.mask_set_sha256);

receipt = build_q2_final_receipt(runtime, parent, replay, metrics, ...
    maskArtifact, outputRoot);

verifyTrue(testCase, receipt.passed);
verifyEqual(testCase, receipt.runtime_lock_sha256, runtime.lock_sha256);
verifyEqual(testCase, receipt.runtime_initial_sha256, runtime.initial_sha256);
verifyEqual(testCase, receipt.source_commit, runtime.source_commit);
verifyEqual(testCase, receipt.parent_lock_sha256, parent.parent_lock_sha256);
verifyEqual(testCase, receipt.parent_cycle1_sha256, parent.parent_cycle1_sha256);
verifyEqual(testCase, receipt.q2_input_lock_sha256, parent.q2_input_lock_sha256);
verifyEqual(testCase, receipt.mesh_ordering_sha256, ...
    parent.replay_source_mesh_sha256);
verifyEqual(testCase, receipt.parent_vtk_mesh_sha256, ...
    parent.parent_vtk_mesh_sha256);
verifyTrue(testCase, receipt.mesh_bridge.connectivity_exact);
verifyEqual(testCase, receipt.mesh_bridge.coordinate_max_abs_error, 0);
names = {'state', 'terminal', 'metrics', 'parent_masks'};
for index = 1:numel(names)
    item = receipt.artifacts.(names{index});
    verifyEqual(testCase, item.sha256, ...
        sha256File(fullfile(outputRoot, item.relative_path)));
end
verifyEqual(testCase, receipt.artifacts.parent_masks.mask_set_sha256, ...
    metrics.mask_set_sha256);

mismatchedMask = maskArtifact;
mismatchedMask.mask_set_sha256 = repmat('9', 1, 64);
verifyError(testCase, @() build_q2_final_receipt(runtime, parent, replay, ...
    metrics, mismatchedMask, outputRoot), ...
    'rebuiltMexQ2:FinalReceiptIdentityMismatch');
end

function testReplayRejectsHandSetOrIncompleteContracts(testCase)
folder = matlab.unittest.fixtures.TemporaryFolderFixture;
testCase.applyFixture(folder);
context = controlledContext(folder.Folder);
context.contract.constructor_request.n_step = 5;
verifyError(testCase, @() solve_q2_parent_cycle1(context), ...
    'rebuiltMexQ2:ReplayContractMismatch');

context = controlledContext(folder.Folder);
context.contract.constructor_return.n_step = 8;
verifyError(testCase, @() solve_q2_parent_cycle1(context), ...
    'rebuiltMexQ2:ReplayContractMismatch');

context = controlledContext(folder.Folder);
context.operators = rmfield(context.operators, 'newton_raphson');
verifyError(testCase, @() solve_q2_parent_cycle1(context), ...
    'rebuiltMexQ2:MissingSolverApi');
end

function testQ2TerminalMarkerCannotAppearInFamilyRunner(testCase)
handoff = fileparts(fileparts(mfilename('fullpath')));
familySolver = fileread(fullfile(fileparts(handoff), ...
    'toy_to_road_independent_fem_20260731', 'solve_toy_to_road_case.m'));
q2Solver = fileread(fullfile(handoff, 'solve_q2_parent_cycle1.m'));
verifyFalse(testCase, contains(familySolver, ...
    'q2_cycle1_diagnostic_complete'));
verifyTrue(testCase, contains(q2Solver, ...
    'q2_cycle1_diagnostic_complete'));
end

function context = controlledContext(outputRoot)
mesh = struct('num_node', 6, 'num_elem', 2, 'nel', 4, ...
    'node', [0 0; 1 0; 2 0; 0 1; 1 1; 2 1], ...
    'elem', [1 2 5 4; 2 3 6 5]);
quadrature = struct('num_gauss_pts', 2, ...
    'gauss_pts', [-0.5 -0.5; 0.5 0.5], 'gauss_W', [1; 1]);
sys = struct('MESH', mesh, 'QUADRATURE', quadrature, ...
    'DOFS', struct('active_dof', (1:12)', 'active_dof_pf', (1:6)'), ...
    'STIFFNESS_MATRIX', struct('i_row', (1:12)', 'j_col', (1:12)', ...
    'i_row_pf', (1:6)', 'j_col_pf', (1:6)', 'KK', speye(12)), ...
    'GEOM', struct('t', 1), 'MAT_CHAR', struct('res_stiff', 0), ...
    'CC', eye(3), 'stress_state', struct('as_number', 2));
operators = struct( ...
    'pre_iter_update', @unusedAssembly, 'stag_vars', @unusedAssembly, ...
    'newton_raphson', @unusedAssembly, ...
    'stag_post_iter_update', @unusedAssembly, ...
    'assembly_pf', @unusedAssembly, ...
    'assembly_equilibrium', @unusedAssembly);
contract = struct( ...
    'case_id', 'Q2_native_parent_cycle1', 'unmapped_mesh', true, ...
    'eta', 0, 'Umax', 0.12, 'R', 0, 'one_cycle_only', true, ...
    'constructor_request', struct('n_step', 8, 'loading', 'cyclic', ...
    'discretization', 'loading', 'R', 0), ...
    'constructor_return', struct('n_step', 5, ...
    'uy_increment', historicalUyIncrements()), ...
    'nominal_retained_factors', [0.25 0.5 0.75 1 0], ...
    'effective_retained_factors', cumsum(historicalUyIncrements()) / 0.12, ...
    'peak_substep_ordinal', 4, ...
    'rebuild_sys_after_recovery', false);
sourceMeshHash = canonicalMeshHash(mesh.node, mesh.elem);
parentVtkHash = repmat('6', 1, 64);
contract.replay_source_mesh_sha256 = sourceMeshHash;
contract.parent_vtk_mesh_sha256 = parentVtkHash;
contract.mesh_bridge = fixtureBridge(sourceMeshHash, parentVtkHash);
context = struct('output_root', outputRoot, 'contract', contract, ...
    'sys', sys, 'sol_par', struct('max_iter_displ', 250, ...
    'tol_displ', 1e-6, 'max_iter_pf', 250, 'tol_p_field', 4e-4), ...
    'sol_stag_par', struct('max_iter', 1, 'tol', 4e-4), ...
    'sol_step_par', struct('n_step', 5, ...
    'uy_increment', historicalUyIncrements()), ...
    'assembly_pf_fh', @unusedAssembly, ...
    'assembly_equilibrium_fh', @unusedAssembly, ...
    'displ', zeros(12, 1), 'p_field', [1; 0.2; 0.1; 1; 0.4; 0.2], ...
    'p_field_old', [1; 0.2; 0.1; 1; 0.4; 0.2], ...
    'history_vars_old', zeros(2, 2, 4), 'operators', operators, ...
    'identity', replayIdentity(sourceMeshHash, parentVtkHash));
end

function input = exportFixture()
nodeCoords = [0 0; 1 0; 1 1; 0 1];
connectivity = [1 2 3 4; 1 2 3 4];
input = struct( ...
    'connectivity', connectivity, ...
    'node_coords', nodeCoords, ...
    'element_ids', int64((1:2)'), ...
    'quadrature_points', [-0.5 -0.5; 0.5 0.5], ...
    'p_field', [1; 0.2; 0.4; 1], ...
    'history_vars', cat(3, zeros(2, 2), [0.1 0.2; 0.3 0.4], ...
    zeros(2, 2), ones(2, 2)), ...
    'psi_raw_GP', [0.1 0.4; 0.2 0.8], ...
    'eta', 0, 'cycle', 1, 'peak_substep_ordinal', 4, ...
    'replay_source_mesh_sha256', ...
    canonicalMeshHash(nodeCoords, connectivity));
end

function value = historicalUyIncrements()
value = 0.12 * [0.25 - 1e-6, 0.25, 0.25, 0.25, 1e-6 - 1];
end

function digest = canonicalMeshHash(coords, connectivity)
md = java.security.MessageDigest.getInstance('SHA-256');
md.update(typecast(double(coords(:)), 'uint8'));
md.update(typecast(int64(connectivity(:)), 'uint8'));
digest = lower(reshape(dec2hex(typecast(md.digest(), 'uint8'), 2).', 1, []));
end

function parent = readyParentReceipt(n)
values = linspace(0.1, 0.9, n)';
fields = struct;
names = {'damage', 'history', 'fatigue_degradation', 'raw', ...
    'damage_degradation', 'active'};
sources = {'native:d_elem', 'native:alpha_bar_elem', 'native:f_alpha_elem', ...
    'native:psi_raw_elem', 'native:g_elem', 'native:psi_active_elem'};
for index = 1:numel(names)
    fieldValues = values;
    if strcmp(names{index}, 'fatigue_degradation')
        fieldValues = ones(n, 1);
    end
    fields.(names{index}) = struct('source', sources{index}, ...
        'values', fieldValues);
end
parent = struct('schema_version', ...
    'rebuilt_initial_mex_q2_parent_receipt_v2', 'status', 'ready', ...
    'blockers', {{}}, 'q2_input_lock_sha256', repmat('1', 1, 64), ...
    'parent_lock_sha256', repmat('2', 1, 64), ...
    'parent_cycle1_sha256', repmat('3', 1, 64), ...
    'parent_reference_id', 'fixture_parent', ...
    'mesh_ordering_sha256', repmat('4', 1, 64), ...
    'replay_source_mesh_sha256', repmat('5', 1, 64), ...
    'replay_source_mesh_sha256_semantics', ...
    'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1', ...
    'parent_vtk_mesh_sha256', repmat('6', 1, 64), ...
    'parent_vtk_mesh_sha256_semantics', ...
    'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1', ...
    'num_elem', n, 'fields', fields);
end

function identity = replayIdentity(meshHash, parentVtkHash)
identity = struct('runtime_lock_sha256', repmat('a', 1, 64), ...
    'runtime_initial_sha256', repmat('b', 1, 64), ...
    'source_commit', repmat('c', 1, 40), ...
    'parent_lock_sha256', repmat('d', 1, 64), ...
    'parent_cycle1_sha256', repmat('e', 1, 64), ...
    'q2_input_lock_sha256', repmat('f', 1, 64), ...
    'mask_set_sha256', repmat('1', 1, 64), ...
    'mesh_ordering_sha256', meshHash, ...
    'replay_source_mesh_sha256', meshHash, ...
    'replay_source_mesh_sha256_semantics', ...
    'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1', ...
    'parent_vtk_mesh_sha256', parentVtkHash, ...
    'parent_vtk_mesh_sha256_semantics', ...
    'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1', ...
    'mesh_bridge', fixtureBridge(meshHash, parentVtkHash));
end

function receipt = fixtureBridge(sourceHash, parentVtkHash)
receipt = struct('schema_version', ...
    'rebuilt_initial_mex_q2_mesh_bridge_receipt_v1', ...
    'passed', true, 'semantics_id', ...
    'q2_source_to_parent_vtk_mesh_bridge_v1', ...
    'replay_source_mesh_sha256', sourceHash, ...
    'replay_source_mesh_sha256_semantics', ...
    'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1', ...
    'parent_vtk_relative_path', 'fixture.vtk', ...
    'parent_vtk_sha256', repmat('7', 1, 64), ...
    'parent_vtk_mesh_sha256', parentVtkHash, ...
    'parent_vtk_mesh_sha256_semantics', ...
    'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1', ...
    'connectivity_requirement', 'exact_q4_row_and_local_node_order', ...
    'connectivity_exact', true, 'num_node', 6, 'num_elem', 2, ...
    'coordinate_max_abs_tolerance', 1e-14, ...
    'coordinate_max_abs_error', 0, 'coordinate_rms_error', 0);
end

function writeBytes(path, bytes)
fileId = fopen(path, 'wb');
cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, bytes, 'uint8');
end

function digest = sha256File(path)
fileId = fopen(path, 'rb');
cleanup = onCleanup(@() fclose(fileId));
md = java.security.MessageDigest.getInstance('SHA-256');
md.update(fread(fileId, Inf, '*uint8'));
digest = lower(reshape(dec2hex(typecast(md.digest(), 'uint8'), 2).', 1, []));
end

function values = q4ShapeFunctions(points)
xi = points(:, 1);
eta = points(:, 2);
values = 0.25 * [(1-xi).*(1-eta), (1+xi).*(1-eta), ...
    (1+xi).*(1+eta), (1-xi).*(1+eta)];
end

function varargout = unusedAssembly(varargin)
varargout = cell(1, max(nargout, 1));
end
