#!/usr/bin/env python3
"""Infer an elementwise effective c86 degradation from fixed synthetic DIC.

This is an exploratory inverse-crime diagnostic: the peak displacement field is
synthetic and was generated by the same AMOR equilibrium model used here.  The
inverted scalar ``g_e`` is one effective degradation per element, not the Q4
Gauss-point degradation produced by a nodal phase-field damage field.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
import time

import meshio
import numpy as np
from scipy import sparse
from scipy.optimize import least_squares


HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "source"))

from damage_conditioned_equilibrium import (  # noqa: E402
    Q4Kinematics,
    build_q4_kinematics,
    element_to_nodal_damage,
    equilibrium_internal_force,
    plane_strain_tensors,
    sens_displacement_boundary_conditions,
    solve_amor_equilibrium,
)


EFFECTIVE_G_WARNING = (
    "elementwise g_e is an effective fixed-u AMOR approximation, not a recovered "
    "nodal phase field or Gauss-point constitutive degradation"
)
INVERSE_CRIME_WARNING = (
    "synthetic peak DIC was generated by the same AMOR model used by the inverse"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prior-damage-vtk", type=Path, required=True)
    parser.add_argument("--synthetic-dic", type=Path, required=True)
    parser.add_argument("--sealed-c86-observation", type=Path, required=True)
    parser.add_argument("--reaction-calibrated-prior", type=Path, required=True)
    parser.add_argument("--prelock-dataset", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--youngs-modulus", type=float, default=1.0)
    parser.add_argument("--poisson-ratio", type=float, default=0.3)
    parser.add_argument("--tikhonov", type=float, default=1.0e-2)
    parser.add_argument("--smoothness", type=float, default=1.0e-2)
    parser.add_argument("--reaction-weight", type=float, default=1.0)
    parser.add_argument("--max-nfev", type=int, default=100)
    parser.add_argument("--max-equilibrium-iterations", type=int, default=50)
    parser.add_argument("--equilibrium-tolerance", type=float, default=1.0e-9)
    parser.add_argument(
        "--equilibrium-residual-tolerance", type=float, default=1.0e-8
    )
    parser.add_argument("--minimum-pivot-ratio", type=float, default=1.0e-14)
    args = parser.parse_args()
    if args.tikhonov < 0.0 or args.smoothness < 0.0:
        parser.error("regularization weights must be non-negative")
    if args.reaction_weight < 0.0:
        parser.error("--reaction-weight must be non-negative")
    if args.max_nfev < 1:
        parser.error("--max-nfev must be positive")
    return args


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def require_shape(name: str, array: np.ndarray, shape: tuple[int, ...]) -> None:
    if array.shape != shape:
        raise ValueError(f"{name} has shape {array.shape}, expected {shape}")


def effective_amor_force_basis(
    kinematics: Q4Kinematics,
    displacement: np.ndarray,
    *,
    youngs_modulus: float,
    poisson_ratio: float,
) -> tuple[np.ndarray, sparse.csr_matrix]:
    """Return ``f_const + A @ g`` for fixed-u elementwise effective AMOR g."""
    element_u = displacement[kinematics.element_dofs]
    strains = np.einsum("egij,ej->egi", kinematics.b_matrices, element_u)
    positive = strains[:, :, 0] + strains[:, :, 1] >= 0.0
    elasticity, i_vol, i_dev, bulk, shear = plane_strain_tensors(
        youngs_modulus, poisson_ratio
    )
    degraded_tensor = 2.0 * shear * i_dev
    element_const = np.zeros((len(kinematics.cells), 8), dtype=np.float64)
    element_coeff = np.zeros_like(element_const)
    for gp in range(4):
        strain = strains[:, gp]
        coeff_stress = np.einsum("ij,ej->ei", degraded_tensor, strain)
        coeff_stress[positive[:, gp]] = np.einsum(
            "ij,ej->ei", elasticity, strain[positive[:, gp]]
        )
        const_stress = np.zeros_like(strain)
        negative = ~positive[:, gp]
        const_stress[negative] = np.einsum(
            "ij,ej->ei", bulk * i_vol, strain[negative]
        )
        weight = kinematics.det_jacobians[:, gp]
        b = kinematics.b_matrices[:, gp]
        element_coeff += np.einsum("eji,ej->ei", b, coeff_stress) * weight[:, None]
        element_const += np.einsum("eji,ej->ei", b, const_stress) * weight[:, None]

    dof_count = 2 * len(kinematics.points)
    constant = np.zeros(dof_count, dtype=np.float64)
    np.add.at(constant, kinematics.element_dofs.reshape(-1), element_const.reshape(-1))
    rows = kinematics.element_dofs.reshape(-1)
    cols = np.repeat(np.arange(len(kinematics.cells)), 8)
    matrix = sparse.coo_matrix(
        (element_coeff.reshape(-1), (rows, cols)),
        shape=(dof_count, len(kinematics.cells)),
    ).tocsr()
    return constant, matrix


def adjacency_rows(
    edge_index: np.ndarray,
    active_elements: np.ndarray,
    prior_g: np.ndarray,
) -> tuple[sparse.csr_matrix, np.ndarray, int]:
    """Build g_i-g_j rows for unique edges incident to the active set."""
    active_lookup = np.full(len(prior_g), -1, dtype=np.int32)
    active_lookup[active_elements] = np.arange(len(active_elements), dtype=np.int32)
    edges = np.asarray(edge_index, dtype=np.int64).T
    edges = np.sort(edges, axis=1)
    edges = np.unique(edges[edges[:, 0] != edges[:, 1]], axis=0)
    incident = (active_lookup[edges[:, 0]] >= 0) | (active_lookup[edges[:, 1]] >= 0)
    edges = edges[incident]
    row_ids: list[int] = []
    col_ids: list[int] = []
    values: list[float] = []
    target = np.zeros(len(edges), dtype=np.float64)
    for row, (left, right) in enumerate(edges):
        left_col = int(active_lookup[left])
        right_col = int(active_lookup[right])
        if left_col >= 0:
            row_ids.append(row)
            col_ids.append(left_col)
            values.append(1.0)
        else:
            target[row] -= prior_g[left]
        if right_col >= 0:
            row_ids.append(row)
            col_ids.append(right_col)
            values.append(-1.0)
        else:
            target[row] += prior_g[right]
    matrix = sparse.coo_matrix(
        (values, (row_ids, col_ids)), shape=(len(edges), len(active_elements))
    ).tocsr()
    return matrix, target, len(edges)


def relative_norm(value: np.ndarray, scale: np.ndarray) -> float:
    denominator = max(float(np.linalg.norm(scale)), np.finfo(float).eps)
    return float(np.linalg.norm(value) / denominator)


def main() -> None:
    args = parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()

    prior_mesh = meshio.read(args.prior_damage_vtk)
    points = np.asarray(prior_mesh.points, dtype=np.float64)[:, :2]
    connectivity = np.asarray(prior_mesh.cells_dict["quad"], dtype=np.int32)
    prior_c84 = np.clip(
        np.asarray(prior_mesh.point_data["d"], dtype=np.float64).reshape(-1),
        0.0,
        1.0,
    )
    kinematics = build_q4_kinematics(points, connectivity)

    with np.load(args.prelock_dataset, allow_pickle=False) as prelock:
        prelock_connectivity = np.asarray(prelock["connectivity"], dtype=np.int32)
        areas = np.asarray(prelock["areas"], dtype=np.float64)
        edge_index = np.asarray(prelock["edge_index"], dtype=np.int64)
        hidden_target_max_cycle = int(
            np.asarray(prelock["hidden_target_max_cycle"]).item()
        )
    if hidden_target_max_cycle != 85:
        raise ValueError("prelock dataset hidden-target boundary is not c85")
    if not np.array_equal(prelock_connectivity, connectivity):
        raise ValueError("prelock dataset and c84 VTK connectivity differ")

    with np.load(args.reaction_calibrated_prior, allow_pickle=False) as calibrated:
        prior_nodal = np.clip(
            np.asarray(calibrated["nodal_damage"], dtype=np.float64), 0.0, 1.0
        )
        front_mask = np.asarray(calibrated["front_mask"], dtype=bool)
        nodal_front_mask = np.asarray(calibrated["nodal_front_mask"], dtype=bool)
    require_shape("reaction-calibrated nodal damage", prior_nodal, prior_c84.shape)
    require_shape("front mask", front_mask, (len(connectivity),))
    require_shape("nodal front mask", nodal_front_mask, (len(points),))

    with np.load(args.sealed_c86_observation, allow_pickle=False) as sealed:
        visible_core = np.asarray(sealed["core95"], dtype=bool)
        observed_reaction = float(np.asarray(sealed["peak_reaction"]).item())
        peak_displacement = float(np.asarray(sealed["peak_displacement"]).item())
        core_threshold = float(np.asarray(sealed["threshold"]).item())
        observation_cycle = int(np.asarray(sealed["observation_cycle"]).item())
    require_shape("sealed visible core", visible_core, prior_c84.shape)
    if observation_cycle != 86:
        raise ValueError("sealed observation is not c86")

    with np.load(args.synthetic_dic, allow_pickle=False) as dic:
        observed_u = np.asarray(dic["displacement"], dtype=np.float64).reshape(-1)
    require_shape("synthetic DIC displacement", observed_u, (2 * len(points),))
    if not np.all(np.isfinite(observed_u)):
        raise ValueError("synthetic DIC displacement contains non-finite values")
    prescribed_dofs, prescribed_values = sens_displacement_boundary_conditions(
        points, peak_displacement
    )
    prescribed_error = float(
        np.max(np.abs(observed_u[prescribed_dofs] - prescribed_values))
    )
    if prescribed_error > 1.0e-8:
        raise ValueError(
            "synthetic DIC violates declared displacement boundary conditions: "
            f"{prescribed_error:.3e}"
        )

    prior_nodal = np.maximum(prior_nodal, prior_c84)
    prior_nodal[visible_core] = np.maximum(prior_nodal[visible_core], core_threshold)
    c84_element_damage = prior_c84[connectivity].mean(axis=1)
    prior_element_damage = prior_nodal[connectivity].mean(axis=1)
    g84 = (1.0 - c84_element_damage) ** 2
    prior_g = np.minimum((1.0 - prior_element_damage) ** 2, g84)
    active_elements = np.flatnonzero(front_mask)
    if not len(active_elements):
        raise ValueError("reaction-calibrated prior has an empty front mask")

    constant_force, force_basis = effective_amor_force_basis(
        kinematics,
        observed_u,
        youngs_modulus=args.youngs_modulus,
        poisson_ratio=args.poisson_ratio,
    )
    free = np.setdiff1d(
        np.arange(2 * len(points), dtype=np.int32), prescribed_dofs, assume_unique=True
    )
    outside = np.flatnonzero(~front_mask)
    outside_force = np.asarray(force_basis[:, outside] @ prior_g[outside])
    fixed_force = constant_force + outside_force.reshape(-1)
    equilibrium_matrix = force_basis[free][:, active_elements].tocsr()
    equilibrium_target = -fixed_force[free]
    prior_free_force = constant_force[free] + np.asarray(
        force_basis[free] @ prior_g
    ).reshape(-1)
    equilibrium_scale = max(
        float(np.linalg.norm(prior_free_force)), abs(observed_reaction), 1.0e-15
    )
    equilibrium_matrix = equilibrium_matrix / equilibrium_scale
    equilibrium_target = equilibrium_target / equilibrium_scale

    top = np.flatnonzero(np.isclose(points[:, 1], points[:, 1].max()))
    top_y = 2 * top + 1
    reaction_active = np.asarray(
        force_basis[top_y][:, active_elements].sum(axis=0)
    ).reshape(-1)
    reaction_outside = np.asarray(
        force_basis[top_y][:, outside].sum(axis=0)
    ).reshape(-1)
    reaction_matrix = sparse.csr_matrix(reaction_active.reshape(1, -1))
    fixed_reaction = float(constant_force[top_y].sum()) + float(
        np.dot(reaction_outside, prior_g[outside])
    )
    reaction_scale = max(abs(observed_reaction), 1.0e-15)
    reaction_matrix *= args.reaction_weight / reaction_scale
    reaction_target = np.asarray(
        [(observed_reaction - fixed_reaction) * args.reaction_weight / reaction_scale]
    )

    blocks: list[sparse.spmatrix] = [equilibrium_matrix, reaction_matrix]
    targets = [equilibrium_target, reaction_target]
    if args.tikhonov > 0.0:
        weight = np.sqrt(args.tikhonov / len(active_elements))
        blocks.append(weight * sparse.eye(len(active_elements), format="csr"))
        targets.append(weight * prior_g[active_elements])
    smooth_matrix, smooth_target, adjacency_count = adjacency_rows(
        edge_index, active_elements, prior_g
    )
    if args.smoothness > 0.0 and adjacency_count:
        weight = np.sqrt(args.smoothness / adjacency_count)
        blocks.append(weight * smooth_matrix)
        targets.append(weight * smooth_target)
    design = sparse.vstack(blocks, format="csr")
    target = np.concatenate(targets)

    lower = np.zeros(len(active_elements), dtype=np.float64)
    upper = g84[active_elements]
    strict_upper = np.maximum(upper, np.finfo(float).eps)
    initial = np.clip(prior_g[active_elements], lower, strict_upper)
    inverse_started = time.perf_counter()
    fit = least_squares(
        lambda value: np.asarray(design @ value).reshape(-1) - target,
        initial,
        jac=lambda _value: design,
        bounds=(lower, strict_upper),
        method="trf",
        x_scale="jac",
        max_nfev=args.max_nfev,
    )
    inverse_seconds = time.perf_counter() - inverse_started
    if not fit.success or not np.all(np.isfinite(fit.x)):
        raise RuntimeError(
            f"bounded effective-degradation inverse failed: {fit.message}"
        )
    effective_g = prior_g.copy()
    effective_g[active_elements] = np.minimum(fit.x, upper)
    effective_damage_element = 1.0 - np.sqrt(np.clip(effective_g, 0.0, 1.0))

    candidate_damage = element_to_nodal_damage(
        effective_damage_element, connectivity, element_weights=areas
    )
    candidate_damage = np.maximum(candidate_damage, prior_c84)
    candidate_damage[visible_core] = np.maximum(
        candidate_damage[visible_core], core_threshold
    )
    restore = ~nodal_front_mask & ~visible_core
    candidate_damage[restore] = prior_nodal[restore]
    candidate_damage = np.maximum(candidate_damage, prior_c84)

    forward_started = time.perf_counter()
    forward = solve_amor_equilibrium(
        kinematics,
        candidate_damage,
        prescribed_dofs,
        prescribed_values,
        youngs_modulus=args.youngs_modulus,
        poisson_ratio=args.poisson_ratio,
        residual_stiffness=0.0,
        max_iterations=args.max_equilibrium_iterations,
        tolerance=args.equilibrium_tolerance,
        residual_tolerance=args.equilibrium_residual_tolerance,
        minimum_pivot_ratio=args.minimum_pivot_ratio,
    )
    forward_seconds = time.perf_counter() - forward_started
    forward_force = equilibrium_internal_force(
        kinematics,
        candidate_damage,
        forward.displacement,
        youngs_modulus=args.youngs_modulus,
        poisson_ratio=args.poisson_ratio,
        residual_stiffness=0.0,
    )
    forward_reaction = float(forward_force[top_y].sum())

    inverse_force = constant_force + np.asarray(force_basis @ effective_g).reshape(-1)
    metrics = {
        "warnings": [EFFECTIVE_G_WARNING, INVERSE_CRIME_WARNING],
        "inverse": {
            "success": bool(fit.success),
            "status": int(fit.status),
            "message": fit.message,
            "nfev": int(fit.nfev),
            "cost": float(fit.cost),
            "optimality": float(fit.optimality),
            "free_force_residual_l2": float(np.linalg.norm(inverse_force[free])),
            "free_force_residual_relative_to_prior": relative_norm(
                inverse_force[free], prior_free_force
            ),
            "predicted_top_reaction": float(inverse_force[top_y].sum()),
            "observed_top_reaction": observed_reaction,
            "top_reaction_relative_error": abs(
                float(inverse_force[top_y].sum()) - observed_reaction
            )
            / max(abs(observed_reaction), np.finfo(float).eps),
            "lower_bound_count": int(np.count_nonzero(fit.x <= 1.0e-10)),
            "upper_bound_count": int(
                np.count_nonzero((upper - fit.x) <= 1.0e-10)
            ),
            "wall_seconds": inverse_seconds,
        },
        "forward": {
            "free_force_residual_l2": forward.residual_norm,
            "normalized_free_force_residual": forward.normalized_residual,
            "dic_displacement_relative_l2": relative_norm(
                forward.displacement - observed_u, observed_u
            ),
            "dic_free_displacement_relative_l2": relative_norm(
                forward.displacement[free] - observed_u[free], observed_u[free]
            ),
            "predicted_top_reaction": forward_reaction,
            "observed_top_reaction": observed_reaction,
            "top_reaction_relative_error": abs(forward_reaction - observed_reaction)
            / max(abs(observed_reaction), np.finfo(float).eps),
            "active_set_stable": forward.active_set_stable,
            "iterations": forward.iterations,
            "minimum_pivot_ratio": forward.minimum_pivot_ratio,
            "wall_seconds": forward_seconds,
        },
    }
    metrics_path = args.out / "inverse_forward_metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")

    candidate_path = args.out / "dic_conditioned_candidate_damage.npz"
    np.savez_compressed(
        candidate_path,
        nodal_damage=candidate_damage,
        effective_damage_element=effective_damage_element,
        effective_g_element=effective_g,
        g84_upper_bound=g84,
        gnn_prior_g_element=prior_g,
        front_mask=front_mask.astype(np.uint8),
        nodal_front_mask=nodal_front_mask.astype(np.uint8),
        visible_core=visible_core.astype(np.uint8),
        observed_displacement=observed_u,
        forward_displacement=forward.displacement,
        effective_g_semantics=np.asarray(EFFECTIVE_G_WARNING),
        dic_semantics=np.asarray(INVERSE_CRIME_WARNING),
    )

    manifest = {
        "scope": "exploratory_fixed_u_amor_effective_degradation_inverse",
        "observation_cycle": observation_cycle,
        "claim_limits": [EFFECTIVE_G_WARNING, INVERSE_CRIME_WARNING],
        "constitutive": {
            "split": "AMOR volumetric-deviatoric",
            "stress_state": "plane strain",
            "youngs_modulus": args.youngs_modulus,
            "poisson_ratio": args.poisson_ratio,
            "residual_stiffness": 0.0,
        },
        "inverse": {
            "unknown": "one effective g_e per element in saved front_mask",
            "outside_policy": "fixed to reaction-calibrated GNN prior",
            "bounds": "0 <= g_e <= g84_e",
            "equations": "fixed observed-u free-DOF equilibrium plus top reaction",
            "tikhonov": args.tikhonov,
            "adjacency_smoothness": args.smoothness,
            "reaction_weight": args.reaction_weight,
            "front_element_count": int(len(active_elements)),
            "adjacency_row_count": adjacency_count,
            "free_dof_count": int(len(free)),
        },
        "projection": (
            "d_e=1-sqrt(g_e), area-weighted element-to-node projection, c84 "
            "irreversibility, sealed observed core, reaction-calibrated prior "
            "restored outside nodal_front_mask"
        ),
        "mesh": {"node_count": len(points), "element_count": len(connectivity)},
        "boundary_prescription_max_abs_error": prescribed_error,
        "input_sha256": {
            "prior_damage_vtk": sha256(args.prior_damage_vtk),
            "synthetic_dic": sha256(args.synthetic_dic),
            "sealed_c86_observation": sha256(args.sealed_c86_observation),
            "reaction_calibrated_prior": sha256(args.reaction_calibrated_prior),
            "prelock_dataset": sha256(args.prelock_dataset),
        },
        "output_sha256": {
            candidate_path.name: sha256(candidate_path),
            metrics_path.name: sha256(metrics_path),
        },
        "wall_seconds": time.perf_counter() - started,
    }
    manifest_path = args.out / "RUN_MANIFEST.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"manifest": str(manifest_path), **metrics}, indent=2))


if __name__ == "__main__":
    main()
