#!/usr/bin/env python3
"""Infer front-local nodal c86 damage from fixed synthetic peak DIC.

The inverse uses the same nodal Q4 AMOR degradation as the unchanged forward
solve. It is an exploratory synthetic-DIC inverse crime, not evidence of
identifiability under real DIC noise or across trajectories.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
import time

import meshio
import numpy as np
from scipy import sparse
from scipy.optimize import least_squares


HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "source"))

from damage_conditioned_equilibrium import (  # noqa: E402
    Q4Kinematics,
    build_q4_kinematics,
    equilibrium_internal_force,
    plane_strain_tensors,
    sens_displacement_boundary_conditions,
    solve_amor_equilibrium,
)


INVERSE_CRIME_WARNING = (
    "synthetic peak DIC was generated by the same AMOR model used by the inverse"
)
TRUTH_FIREWALL = (
    "c86 diffuse damage truth is not loaded; only displacement is read from the "
    "synthetic-DIC NPZ"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prior-damage-vtk", type=Path, required=True)
    parser.add_argument("--synthetic-dic", type=Path, required=True)
    parser.add_argument("--sealed-c86-observation", type=Path, required=True)
    parser.add_argument("--reaction-calibrated-prior", type=Path, required=True)
    parser.add_argument("--prelock-dataset", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--youngs-modulus", type=float, default=1.0)
    parser.add_argument("--poisson-ratio", type=float, default=0.3)
    parser.add_argument("--tikhonov", type=float, default=1.0e-2)
    parser.add_argument("--smoothness", type=float, default=1.0e-2)
    parser.add_argument("--reaction-weight", type=float, default=1.0)
    parser.add_argument("--max-nfev", type=int, default=100)
    parser.add_argument("--max-equilibrium-iterations", type=int, default=50)
    parser.add_argument("--equilibrium-tolerance", type=float, default=1.0e-9)
    parser.add_argument(
        "--equilibrium-residual-tolerance", type=float, default=1.0e-8
    )
    parser.add_argument("--minimum-pivot-ratio", type=float, default=1.0e-14)
    args = parser.parse_args()
    if args.tikhonov < 0.0 or args.smoothness < 0.0:
        parser.error("regularization weights must be non-negative")
    if args.reaction_weight < 0.0:
        parser.error("--reaction-weight must be non-negative")
    if args.max_nfev < 1:
        parser.error("--max-nfev must be positive")
    return args


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def require_shape(name: str, array: np.ndarray, shape: tuple[int, ...]) -> None:
    if array.shape != shape:
        raise ValueError(f"{name} has shape {array.shape}, expected {shape}")


def assemble_vector(
    element_vectors: np.ndarray, element_dofs: np.ndarray, dof_count: int
) -> np.ndarray:
    vector = np.zeros(dof_count, dtype=np.float64)
    np.add.at(vector, element_dofs.reshape(-1), element_vectors.reshape(-1))
    return vector


def fixed_u_amor_terms(
    kinematics: Q4Kinematics,
    displacement: np.ndarray,
    *,
    youngs_modulus: float,
    poisson_ratio: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return per-element constant force and force multiplying each Gauss g."""
    element_u = displacement[kinematics.element_dofs]
    strains = np.einsum("egij,ej->egi", kinematics.b_matrices, element_u)
    positive = strains[:, :, 0] + strains[:, :, 1] >= 0.0
    elasticity, i_vol, i_dev, bulk, shear = plane_strain_tensors(
        youngs_modulus, poisson_ratio
    )
    degraded_tensor = 2.0 * shear * i_dev
    constant = np.zeros((len(kinematics.cells), 8), dtype=np.float64)
    coefficient = np.empty((len(kinematics.cells), 4, 8), dtype=np.float64)
    for gp in range(4):
        strain = strains[:, gp]
        degraded_stress = np.einsum("ij,ej->ei", degraded_tensor, strain)
        degraded_stress[positive[:, gp]] = np.einsum(
            "ij,ej->ei", elasticity, strain[positive[:, gp]]
        )
        constant_stress = np.zeros_like(strain)
        negative = ~positive[:, gp]
        constant_stress[negative] = np.einsum(
            "ij,ej->ei", bulk * i_vol, strain[negative]
        )
        b = kinematics.b_matrices[:, gp]
        weight = kinematics.det_jacobians[:, gp, None]
        coefficient[:, gp] = (
            np.einsum("eji,ej->ei", b, degraded_stress) * weight
        )
        constant += np.einsum("eji,ej->ei", b, constant_stress) * weight
    return constant, coefficient


def element_forces(
    nodal_damage: np.ndarray,
    cells: np.ndarray,
    shape_values: np.ndarray,
    constant: np.ndarray,
    coefficient: np.ndarray,
) -> np.ndarray:
    element_damage = nodal_damage[cells]
    damage_gp = np.einsum("ei,gi->eg", element_damage, shape_values)
    degradation_gp = (1.0 - damage_gp) ** 2
    return constant + np.einsum("eg,egi->ei", degradation_gp, coefficient)


def nodal_edges(cells: np.ndarray) -> np.ndarray:
    local_edges = ((0, 1), (1, 2), (2, 3), (3, 0))
    edges = np.concatenate([cells[:, pair] for pair in local_edges], axis=0)
    edges = np.sort(edges, axis=1)
    return np.unique(edges[edges[:, 0] != edges[:, 1]], axis=0)


def smoothness_rows(
    cells: np.ndarray,
    unknown_nodes: np.ndarray,
    fixed_damage: np.ndarray,
) -> tuple[sparse.csr_matrix, np.ndarray, int]:
    """Build nodal d_i-d_j rows, including fixed neighbors as anchors."""
    lookup = np.full(len(fixed_damage), -1, dtype=np.int32)
    lookup[unknown_nodes] = np.arange(len(unknown_nodes), dtype=np.int32)
    edges = nodal_edges(cells)
    incident = (lookup[edges[:, 0]] >= 0) | (lookup[edges[:, 1]] >= 0)
    edges = edges[incident]
    row_ids: list[int] = []
    col_ids: list[int] = []
    values: list[float] = []
    target = np.zeros(len(edges), dtype=np.float64)
    for row, (left, right) in enumerate(edges):
        left_col = int(lookup[left])
        right_col = int(lookup[right])
        if left_col >= 0:
            row_ids.append(row)
            col_ids.append(left_col)
            values.append(1.0)
        else:
            target[row] -= fixed_damage[left]
        if right_col >= 0:
            row_ids.append(row)
            col_ids.append(right_col)
            values.append(-1.0)
        else:
            target[row] += fixed_damage[right]
    matrix = sparse.coo_matrix(
        (values, (row_ids, col_ids)), shape=(len(edges), len(unknown_nodes))
    ).tocsr()
    return matrix, target, len(edges)


class FixedUNodalModel:
    """Fixed-u nodal AMOR force and exact sparse damage Jacobian."""

    def __init__(
        self,
        kinematics: Q4Kinematics,
        displacement: np.ndarray,
        fixed_damage: np.ndarray,
        unknown_nodes: np.ndarray,
        *,
        youngs_modulus: float,
        poisson_ratio: float,
    ) -> None:
        self.kinematics = kinematics
        self.fixed_damage = fixed_damage.copy()
        self.unknown_nodes = unknown_nodes
        self.lookup = np.full(len(fixed_damage), -1, dtype=np.int32)
        self.lookup[unknown_nodes] = np.arange(len(unknown_nodes), dtype=np.int32)
        constant, coefficient = fixed_u_amor_terms(
            kinematics,
            displacement,
            youngs_modulus=youngs_modulus,
            poisson_ratio=poisson_ratio,
        )
        variable_mask = np.any(self.lookup[kinematics.cells] >= 0, axis=1)
        self.variable_elements = np.flatnonzero(variable_mask)
        self.variable_cells = kinematics.cells[variable_mask]
        self.variable_dofs = kinematics.element_dofs[variable_mask]
        self.variable_constant = constant[variable_mask]
        self.variable_coefficient = coefficient[variable_mask]
        fixed_element_force = element_forces(
            fixed_damage,
            kinematics.cells[~variable_mask],
            kinematics.shape_values,
            constant[~variable_mask],
            coefficient[~variable_mask],
        )
        self.fixed_force = assemble_vector(
            fixed_element_force,
            kinematics.element_dofs[~variable_mask],
            2 * len(kinematics.points),
        )

    def force_and_jacobian(
        self, unknown_damage: np.ndarray
    ) -> tuple[np.ndarray, sparse.csr_matrix]:
        damage = self.fixed_damage.copy()
        damage[self.unknown_nodes] = unknown_damage
        element_damage = damage[self.variable_cells]
        damage_gp = np.einsum(
            "ei,gi->eg", element_damage, self.kinematics.shape_values
        )
        degradation_gp = (1.0 - damage_gp) ** 2
        variable_force = self.variable_constant + np.einsum(
            "eg,egi->ei", degradation_gp, self.variable_coefficient
        )
        force = self.fixed_force + assemble_vector(
            variable_force,
            self.variable_dofs,
            2 * len(self.kinematics.points),
        )

        row_parts: list[np.ndarray] = []
        col_parts: list[np.ndarray] = []
        data_parts: list[np.ndarray] = []
        for gp in range(4):
            for local in range(4):
                columns = self.lookup[self.variable_cells[:, local]]
                valid = columns >= 0
                if not np.any(valid):
                    continue
                derivative = (
                    -2.0
                    * (1.0 - damage_gp[valid, gp])
                    * self.kinematics.shape_values[gp, local]
                )
                contribution = (
                    self.variable_coefficient[valid, gp] * derivative[:, None]
                )
                row_parts.append(self.variable_dofs[valid].reshape(-1))
                col_parts.append(np.repeat(columns[valid], 8))
                data_parts.append(contribution.reshape(-1))
        jacobian = sparse.coo_matrix(
            (
                np.concatenate(data_parts),
                (np.concatenate(row_parts), np.concatenate(col_parts)),
            ),
            shape=(2 * len(self.kinematics.points), len(self.unknown_nodes)),
        ).tocsr()
        return force, jacobian


class InverseObjective:
    """Scaled data and regularization residual with a shared evaluation cache."""

    def __init__(
        self,
        model: FixedUNodalModel,
        free_dofs: np.ndarray,
        top_y_dofs: np.ndarray,
        observed_reaction: float,
        equilibrium_scale: float,
        reaction_weight: float,
        prior_unknown: np.ndarray,
        tikhonov: float,
        smooth_matrix: sparse.csr_matrix,
        smooth_target: np.ndarray,
        smoothness: float,
    ) -> None:
        self.model = model
        self.free = free_dofs
        self.top_y = top_y_dofs
        self.observed_reaction = observed_reaction
        self.equilibrium_scale = equilibrium_scale
        self.reaction_scale = max(abs(observed_reaction), 1.0e-15)
        self.reaction_weight = reaction_weight
        self.prior = prior_unknown
        self.tikhonov_weight = (
            np.sqrt(tikhonov / len(prior_unknown)) if tikhonov > 0.0 else 0.0
        )
        self.smooth_matrix = smooth_matrix
        self.smooth_target = smooth_target
        self.smooth_weight = (
            np.sqrt(smoothness / smooth_matrix.shape[0])
            if smoothness > 0.0 and smooth_matrix.shape[0]
            else 0.0
        )
        self.last_x: np.ndarray | None = None
        self.last_residual: np.ndarray | None = None
        self.last_jacobian: sparse.csr_matrix | None = None

    def evaluate(self, value: np.ndarray) -> tuple[np.ndarray, sparse.csr_matrix]:
        if self.last_x is not None and np.array_equal(value, self.last_x):
            assert self.last_residual is not None
            assert self.last_jacobian is not None
            return self.last_residual, self.last_jacobian
        force, force_jacobian = self.model.force_and_jacobian(value)
        residuals = [force[self.free] / self.equilibrium_scale]
        jacobians: list[sparse.spmatrix] = [
            force_jacobian[self.free] / self.equilibrium_scale
        ]
        reaction = float(force[self.top_y].sum())
        residuals.append(
            np.asarray(
                [
                    (reaction - self.observed_reaction)
                    * self.reaction_weight
                    / self.reaction_scale
                ]
            )
        )
        reaction_jacobian = np.asarray(
            force_jacobian[self.top_y].sum(axis=0)
        ).reshape(1, -1)
        jacobians.append(
            sparse.csr_matrix(
                reaction_jacobian * self.reaction_weight / self.reaction_scale
            )
        )
        if self.tikhonov_weight:
            residuals.append(self.tikhonov_weight * (value - self.prior))
            jacobians.append(
                self.tikhonov_weight * sparse.eye(len(value), format="csr")
            )
        if self.smooth_weight:
            smooth_residual = (
                np.asarray(self.smooth_matrix @ value).reshape(-1)
                - self.smooth_target
            )
            residuals.append(
                self.smooth_weight * smooth_residual
            )
            jacobians.append(self.smooth_weight * self.smooth_matrix)
        residual = np.concatenate(residuals)
        jacobian = sparse.vstack(jacobians, format="csr")
        self.last_x = value.copy()
        self.last_residual = residual
        self.last_jacobian = jacobian
        return residual, jacobian

    def residual(self, value: np.ndarray) -> np.ndarray:
        return self.evaluate(value)[0]

    def jacobian(self, value: np.ndarray) -> sparse.csr_matrix:
        return self.evaluate(value)[1]


def relative_norm(value: np.ndarray, scale: np.ndarray) -> float:
    denominator = max(float(np.linalg.norm(scale)), np.finfo(float).eps)
    return float(np.linalg.norm(value) / denominator)


def main() -> None:
    args = parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()

    prior_mesh = meshio.read(args.prior_damage_vtk)
    points = np.asarray(prior_mesh.points, dtype=np.float64)[:, :2]
    connectivity = np.asarray(prior_mesh.cells_dict["quad"], dtype=np.int32)
    prior_c84 = np.clip(
        np.asarray(prior_mesh.point_data["d"], dtype=np.float64).reshape(-1),
        0.0,
        1.0,
    )
    kinematics = build_q4_kinematics(points, connectivity)

    with np.load(args.prelock_dataset, allow_pickle=False) as prelock:
        prelock_connectivity = np.asarray(prelock["connectivity"], dtype=np.int32)
        areas = np.asarray(prelock["areas"], dtype=np.float64)
        hidden_target_max_cycle = int(
            np.asarray(prelock["hidden_target_max_cycle"]).item()
        )
    if hidden_target_max_cycle != 85:
        raise ValueError("prelock dataset hidden-target boundary is not c85")
    if not np.array_equal(prelock_connectivity, connectivity):
        raise ValueError("prelock dataset and c84 VTK connectivity differ")
    require_shape("prelock element areas", areas, (len(connectivity),))

    with np.load(args.reaction_calibrated_prior, allow_pickle=False) as calibrated:
        gnn_prior = np.clip(
            np.asarray(calibrated["nodal_damage"], dtype=np.float64), 0.0, 1.0
        )
        front_mask = np.asarray(calibrated["front_mask"], dtype=bool)
        nodal_front_mask = np.asarray(calibrated["nodal_front_mask"], dtype=bool)
    require_shape("reaction-calibrated nodal damage", gnn_prior, prior_c84.shape)
    require_shape("front mask", front_mask, (len(connectivity),))
    require_shape("nodal front mask", nodal_front_mask, prior_c84.shape)

    with np.load(args.sealed_c86_observation, allow_pickle=False) as sealed:
        visible_core = np.asarray(sealed["core95"], dtype=bool)
        observed_reaction = float(np.asarray(sealed["peak_reaction"]).item())
        peak_displacement = float(np.asarray(sealed["peak_displacement"]).item())
        core_threshold = float(np.asarray(sealed["threshold"]).item())
        observation_cycle = int(np.asarray(sealed["observation_cycle"]).item())
    require_shape("sealed visible core", visible_core, prior_c84.shape)
    if observation_cycle != 86:
        raise ValueError("sealed observation is not c86")

    # np.load is lazy for NPZ members. Deliberately do not access the damage key.
    with np.load(args.synthetic_dic, allow_pickle=False) as synthetic_dic:
        observed_u = np.asarray(
            synthetic_dic["displacement"], dtype=np.float64
        ).reshape(-1)
    require_shape("synthetic DIC displacement", observed_u, (2 * len(points),))
    if not np.all(np.isfinite(observed_u)):
        raise ValueError("synthetic DIC displacement contains non-finite values")

    prescribed_dofs, prescribed_values = sens_displacement_boundary_conditions(
        points, peak_displacement
    )
    prescribed_error = float(
        np.max(np.abs(observed_u[prescribed_dofs] - prescribed_values))
    )
    if prescribed_error > 1.0e-8:
        raise ValueError(
            "synthetic DIC violates declared displacement boundary conditions: "
            f"{prescribed_error:.3e}"
        )

    fixed_damage = np.maximum(gnn_prior, prior_c84)
    fixed_damage[visible_core] = np.maximum(
        fixed_damage[visible_core], core_threshold
    )
    saturated_c84 = prior_c84 >= 1.0 - 1.0e-12
    unknown_mask = nodal_front_mask & ~visible_core & ~saturated_c84
    unknown_nodes = np.flatnonzero(unknown_mask)
    if not len(unknown_nodes):
        raise ValueError("saved nodal front mask contains no free damage unknowns")
    prior_unknown = fixed_damage[unknown_nodes]
    lower = prior_c84[unknown_nodes]
    upper = np.ones(len(unknown_nodes), dtype=np.float64)

    model = FixedUNodalModel(
        kinematics,
        observed_u,
        fixed_damage,
        unknown_nodes,
        youngs_modulus=args.youngs_modulus,
        poisson_ratio=args.poisson_ratio,
    )
    free_mask = np.ones(2 * len(points), dtype=bool)
    free_mask[prescribed_dofs] = False
    free = np.flatnonzero(free_mask)
    top = np.flatnonzero(np.isclose(points[:, 1], points[:, 1].max()))
    top_y = 2 * top + 1
    prior_force, prior_jacobian = model.force_and_jacobian(prior_unknown)
    influenced_rows = np.asarray(
        prior_jacobian[free].getnnz(axis=1)
    ).reshape(-1) > 0
    influenced_free = free[influenced_rows]
    reaction_sensitivity = np.asarray(
        prior_jacobian[top_y].sum(axis=0)
    ).reshape(-1)
    equilibrium_scale = max(float(np.linalg.norm(prior_force[free])), 1.0e-15)
    smooth_matrix, smooth_target, smooth_edge_count = smoothness_rows(
        connectivity, unknown_nodes, fixed_damage
    )
    objective = InverseObjective(
        model,
        free,
        top_y,
        observed_reaction,
        equilibrium_scale,
        args.reaction_weight,
        prior_unknown,
        args.tikhonov,
        smooth_matrix,
        smooth_target,
        args.smoothness,
    )

    inverse_started = time.perf_counter()
    fit = least_squares(
        objective.residual,
        prior_unknown,
        jac=objective.jacobian,
        bounds=(lower, upper),
        method="trf",
        tr_solver="lsmr",
        x_scale="jac",
        max_nfev=args.max_nfev,
    )
    inverse_seconds = time.perf_counter() - inverse_started
    if not fit.success or not np.all(np.isfinite(fit.x)):
        raise RuntimeError(f"bounded nodal-damage inverse failed: {fit.message}")

    candidate_damage = fixed_damage.copy()
    candidate_damage[unknown_nodes] = fit.x
    candidate_damage = np.maximum(candidate_damage, prior_c84)
    candidate_damage[visible_core] = np.maximum(
        candidate_damage[visible_core], core_threshold
    )
    inverse_force, _ = model.force_and_jacobian(fit.x)

    forward_started = time.perf_counter()
    forward = solve_amor_equilibrium(
        kinematics,
        candidate_damage,
        prescribed_dofs,
        prescribed_values,
        youngs_modulus=args.youngs_modulus,
        poisson_ratio=args.poisson_ratio,
        residual_stiffness=0.0,
        max_iterations=args.max_equilibrium_iterations,
        tolerance=args.equilibrium_tolerance,
        residual_tolerance=args.equilibrium_residual_tolerance,
        minimum_pivot_ratio=args.minimum_pivot_ratio,
    )
    forward_seconds = time.perf_counter() - forward_started
    forward_force = equilibrium_internal_force(
        kinematics,
        candidate_damage,
        forward.displacement,
        youngs_modulus=args.youngs_modulus,
        poisson_ratio=args.poisson_ratio,
        residual_stiffness=0.0,
    )
    inverse_reaction = float(inverse_force[top_y].sum())
    forward_reaction = float(forward_force[top_y].sum())
    reaction_denominator = max(abs(observed_reaction), np.finfo(float).eps)

    metrics = {
        "warnings": [INVERSE_CRIME_WARNING, TRUTH_FIREWALL],
        "inverse": {
            "success": bool(fit.success),
            "status": int(fit.status),
            "message": fit.message,
            "nfev": int(fit.nfev),
            "njev": int(fit.njev) if fit.njev is not None else None,
            "cost": float(fit.cost),
            "optimality": float(fit.optimality),
            "free_force_residual_l2": float(np.linalg.norm(inverse_force[free])),
            "free_force_residual_relative_to_prior": relative_norm(
                inverse_force[free], prior_force[free]
            ),
            "influenced_free_force_residual_l2": float(
                np.linalg.norm(inverse_force[influenced_free])
            ),
            "influenced_free_force_residual_relative_to_prior": relative_norm(
                inverse_force[influenced_free], prior_force[influenced_free]
            ),
            "predicted_top_reaction": inverse_reaction,
            "observed_top_reaction": observed_reaction,
            "top_reaction_relative_error": abs(
                inverse_reaction - observed_reaction
            )
            / reaction_denominator,
            "lower_bound_count": int(np.count_nonzero(fit.x - lower <= 1.0e-10)),
            "upper_bound_count": int(np.count_nonzero(upper - fit.x <= 1.0e-10)),
            "wall_seconds": inverse_seconds,
        },
        "forward": {
            "free_force_residual_l2": forward.residual_norm,
            "normalized_free_force_residual": forward.normalized_residual,
            "dic_displacement_relative_l2": relative_norm(
                forward.displacement - observed_u, observed_u
            ),
            "dic_free_displacement_relative_l2": relative_norm(
                forward.displacement[free] - observed_u[free], observed_u[free]
            ),
            "predicted_top_reaction": forward_reaction,
            "observed_top_reaction": observed_reaction,
            "top_reaction_relative_error": abs(
                forward_reaction - observed_reaction
            )
            / reaction_denominator,
            "active_set_stable": forward.active_set_stable,
            "iterations": forward.iterations,
            "minimum_pivot_ratio": forward.minimum_pivot_ratio,
            "wall_seconds": forward_seconds,
        },
    }
    metrics_path = args.out / "inverse_forward_metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")

    candidate_path = args.out / "dic_conditioned_nodal_damage.npz"
    np.savez_compressed(
        candidate_path,
        nodal_damage=candidate_damage,
        gnn_prior_nodal_damage=fixed_damage,
        prior_c84_nodal_damage=prior_c84,
        unknown_nodes=unknown_nodes.astype(np.int32),
        unknown_mask=unknown_mask.astype(np.uint8),
        front_mask=front_mask.astype(np.uint8),
        nodal_front_mask=nodal_front_mask.astype(np.uint8),
        visible_core=visible_core.astype(np.uint8),
        observed_displacement=observed_u,
        forward_displacement=forward.displacement,
        inverse_fixed_u_force=inverse_force,
        inverse_crime_warning=np.asarray(INVERSE_CRIME_WARNING),
        c86_truth_firewall=np.asarray(TRUTH_FIREWALL),
    )

    manifest = {
        "scope": "exploratory_fixed_u_amor_front_local_nodal_damage_inverse",
        "observation_cycle": observation_cycle,
        "claim_limits": [INVERSE_CRIME_WARNING, TRUTH_FIREWALL],
        "c86_diffuse_damage_truth_loaded": False,
        "constitutive": {
            "split": "AMOR volumetric-deviatoric",
            "stress_state": "plane strain",
            "gauss_degradation": "g_q=(1-N_q d_e)^2",
            "youngs_modulus": args.youngs_modulus,
            "poisson_ratio": args.poisson_ratio,
            "residual_stiffness": 0.0,
        },
        "inverse": {
            "unknown": "nodal damage in saved nodal_front_mask",
            "fixed_nodes": "outside mask, sealed observed core, saturated c84 nodes",
            "outside_policy": "fixed to reaction-calibrated GNN prior",
            "bounds": "prior_c84 <= d <= 1",
            "equations": "fixed observed-u free-DOF internal force plus top reaction",
            "jacobian": "exact sparse chain rule through g_q=(1-N_q d_e)^2",
            "solver": "scipy least_squares method=trf tr_solver=lsmr",
            "tikhonov": args.tikhonov,
            "nodal_adjacency_smoothness": args.smoothness,
            "reaction_weight": args.reaction_weight,
            "reaction_jacobian_nonzero_count": int(
                np.count_nonzero(reaction_sensitivity)
            ),
            "reaction_jacobian_l2": float(np.linalg.norm(reaction_sensitivity)),
            "unknown_node_count": int(len(unknown_nodes)),
            "variable_element_count": int(len(model.variable_elements)),
            "smooth_edge_count": smooth_edge_count,
            "free_dof_count": int(len(free)),
            "front_influenced_free_dof_count": int(len(influenced_free)),
        },
        "mesh": {"node_count": len(points), "element_count": len(connectivity)},
        "boundary_prescription_max_abs_error": prescribed_error,
        "input_sha256": {
            "prior_damage_vtk": sha256(args.prior_damage_vtk),
            "synthetic_dic": sha256(args.synthetic_dic),
            "sealed_c86_observation": sha256(args.sealed_c86_observation),
            "reaction_calibrated_prior": sha256(args.reaction_calibrated_prior),
            "prelock_dataset": sha256(args.prelock_dataset),
        },
        "output_sha256": {
            candidate_path.name: sha256(candidate_path),
            metrics_path.name: sha256(metrics_path),
        },
        "wall_seconds": time.perf_counter() - started,
    }
    manifest_path = args.out / "RUN_MANIFEST.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"manifest": str(manifest_path), **metrics}, indent=2))


if __name__ == "__main__":
    main()
