function audit = audit_t1_mesh_transfer_edges( ...
        parent_coords, mapped_coords, connectivity, tip_node_id, ell)
%AUDIT_T1_MESH_TRANSFER_EDGES Audit corresponding parent and mapped tip edges.

localValidateInputs(parent_coords, mapped_coords, connectivity, tip_node_id, ell);

elementMask = any(connectivity == tip_node_id, 2);
localGate(any(elementMask), ...
    'The parent notch-tip node is not referenced by Q4 connectivity.');
localConnectivity = connectivity(elementMask, :);
edges = [localConnectivity(:, [1 2]); localConnectivity(:, [2 3]); ...
    localConnectivity(:, [3 4]); localConnectivity(:, [4 1])];
edges = unique(sort(edges, 2), 'rows');
tipEdges = edges(any(edges == tip_node_id, 2), :);
localGate(~isempty(tipEdges), ...
    'No Q4 edge is incident to the parent notch-tip node.');

otherNodeIds = tipEdges(:, 1);
tipInFirstColumn = tipEdges(:, 1) == tip_node_id;
otherNodeIds(tipInFirstColumn) = tipEdges(tipInFirstColumn, 2);
otherNodeIds = sort(otherNodeIds);
incidentEdgeNodeIds = [repmat(tip_node_id, numel(otherNodeIds), 1) otherNodeIds];

parentVectors = parent_coords(otherNodeIds, :) - parent_coords(tip_node_id, :);
mappedVectors = mapped_coords(otherNodeIds, :) - mapped_coords(tip_node_id, :);
parentEdgeLengths = sqrt(sum(parentVectors .^ 2, 2));
mappedEdgeLengths = sqrt(sum(mappedVectors .^ 2, 2));
localGate(all(parentEdgeLengths > 0), ...
    'A parent notch-tip incident edge has zero length.');

mappedOverParentRatios = mappedEdgeLengths ./ parentEdgeLengths;
localGate(all(isfinite(mappedOverParentRatios)), ...
    'Mapped/parent notch-tip incident-edge ratios must be finite.');

ratioLimitMin = 0.75;
ratioLimitMax = 1.25;
ratioTolerance = 1e-12;
ratioMin = min(mappedOverParentRatios);
ratioMax = max(mappedOverParentRatios);
localGate(ratioMin >= ratioLimitMin - ratioTolerance && ...
    ratioMax <= ratioLimitMax + ratioTolerance, ...
    'Mapped/parent notch-tip incident-edge ratios are outside [0.75, 1.25].');

parentHOverEll = parentEdgeLengths / ell;
mappedHOverEll = mappedEdgeLengths / ell;
audit = struct( ...
    'incident_edge_node_ids', incidentEdgeNodeIds, ...
    'parent_incident_edge_lengths', parentEdgeLengths, ...
    'mapped_incident_edge_lengths', mappedEdgeLengths, ...
    'mapped_over_parent_edge_ratios', mappedOverParentRatios, ...
    'parent_h_over_ell_min', min(parentHOverEll), ...
    'parent_h_over_ell_max', max(parentHOverEll), ...
    'mapped_h_over_ell_min', min(mappedHOverEll), ...
    'mapped_h_over_ell_max', max(mappedHOverEll), ...
    'mapped_over_parent_edge_ratio_min', ratioMin, ...
    'mapped_over_parent_edge_ratio_max', ratioMax, ...
    'mapped_over_parent_edge_ratio_limit_min', ratioLimitMin, ...
    'mapped_over_parent_edge_ratio_limit_max', ratioLimitMax, ...
    'mapped_over_parent_edge_ratio_tolerance', ratioTolerance);
end

function localValidateInputs(parentCoords, mappedCoords, connectivity, tipNodeId, ell)
validParent = isnumeric(parentCoords) && isreal(parentCoords) && ...
    size(parentCoords, 2) == 2 && ~isempty(parentCoords) && ...
    all(isfinite(parentCoords), 'all');
validMapped = isnumeric(mappedCoords) && isreal(mappedCoords) && ...
    isequal(size(mappedCoords), size(parentCoords)) && ...
    all(isfinite(mappedCoords), 'all');
localGate(validParent && validMapped, ...
    'Parent and mapped coordinates must be finite real N-by-2 arrays of equal size.');
localGate(isnumeric(connectivity) && isreal(connectivity) && ...
    size(connectivity, 2) == 4 && ~isempty(connectivity) && ...
    all(isfinite(connectivity), 'all') && ...
    all(connectivity == floor(connectivity), 'all') && ...
    all(connectivity >= 1, 'all') && ...
    all(connectivity <= size(parentCoords, 1), 'all'), ...
    'connectivity must be a finite integer Q4 connectivity array.');
localGate(isnumeric(tipNodeId) && isreal(tipNodeId) && isscalar(tipNodeId) && ...
    isfinite(tipNodeId) && tipNodeId == floor(tipNodeId) && ...
    tipNodeId >= 1 && tipNodeId <= size(parentCoords, 1), ...
    'tip_node_id must identify one parent coordinate row.');
localGate(isnumeric(ell) && isreal(ell) && isscalar(ell) && ...
    isfinite(ell) && ell > 0, 'ell must be a positive finite scalar.');
end

function localGate(condition, message)
if ~condition
    error('toyRoad:MeshTransferGateFailed', '%s', message);
end
end
