function summary = finalize_toy_road_package(outputRoot, caseId, launchReceiptPath, mode)
%FINALIZE_TOY_ROAD_PACKAGE Deeply validate and seal one completed case.

if nargin < 4
    mode = "finalize";
    dependencies = struct();
elseif isstruct(mode)
    dependencies = mode;
    mode = "finalize";
else
    dependencies = struct();
end
outputRoot = char(outputRoot);
caseId = string(caseId);
mode = string(mode);
if ~isscalar(mode) || ~any(mode == ["finalize" "verify_manifest"])
    error('toyRoad:PackageValidationFailed', 'Unknown finalizer mode.');
end
if mode == "verify_manifest"
    summary = localVerifyManifest(outputRoot, caseId);
    return;
end

try
    [summary, provenance] = localValidatePackage( ...
        outputRoot, caseId, launchReceiptPath, dependencies);
catch exception
    if strcmp(exception.identifier, 'toyRoad:PackageValidationFailed')
        rethrow(exception);
    end
    wrapped = MException('toyRoad:PackageValidationFailed', ...
        'Package validation failed before publication: %s', exception.message);
    wrapped = addCause(wrapped, exception);
    throw(wrapped);
end

try
    write_toy_road_json(fullfile(outputRoot, 'PRODUCER_PROVENANCE.json'), provenance);
    write_toy_road_json(fullfile(outputRoot, 'VALIDATION_SUMMARY.json'), summary);
    localWriteManifest(outputRoot);
catch exception
    wrapped = MException('toyRoad:PackagePublicationFailed', ...
        'Validated package outputs could not be published without clobbering.');
    wrapped = addCause(wrapped, exception);
    throw(wrapped);
end
end

function [summary, provenance] = localValidatePackage( ...
        outputRoot, caseId, launchReceiptPath, dependencies)
localRequire(isfolder(outputRoot), 'Output root does not exist.');
validCases = ["T1_initial_defect" "T2_material_state" "T3_loading_history"];
localRequire(isscalar(caseId) && any(caseId == validCases), ...
    'Case ID is not one of the three sealed cases.');

finalNames = {'PRODUCER_PROVENANCE.json', 'VALIDATION_SUMMARY.json', ...
    'SHA256SUMS.txt'};
for index = 1:numel(finalNames)
    localRequire(~localPathExists(fullfile(outputRoot, finalNames{index})), ...
        'Refusing to clobber pre-existing final output %s.', finalNames{index});
end
localRejectSymlinksAndCaseCollisions(outputRoot);

runPath = fullfile(outputRoot, 'RUN_RESULT.json');
localRequire(isfile(runPath), ...
    'RUN_RESULT.json sole completion marker is missing.');
runResult = validate_toy_road_run_result(runPath, caseId);
localRequire(runResult.complete && strcmp(string(runResult.status), "complete"), ...
    'RUN_RESULT.json does not mark a complete run.');

handoffDir = fileparts(mfilename('fullpath'));
cfg = build_toy_road_case_config(caseId, handoffDir);
caseLockPath = fullfile(handoffDir, sprintf('%s_INPUT_LOCK.json', ...
    extractBefore(caseId, 3)));
caseLockHash = localFileSha256(caseLockPath);
parentLockHash = localFileSha256(fullfile(handoffDir, 'PARENT_LOCK.json'));
parentLock = localReadJson(fullfile(handoffDir, 'PARENT_LOCK.json'));
meshContract = localLoadParentMeshContract(parentLock, dependencies);

snapshot = localReadJson(fullfile(outputRoot, 'INPUT_SNAPSHOT.json'));
localValidateSnapshot(snapshot, cfg, caseId, caseLockHash);
provenance = localReadLaunchReceipt(launchReceiptPath, outputRoot);
localValidateProvenance(provenance, snapshot, caseId, caseLockHash, ...
    parentLockHash, handoffDir, parentLock);

mesh = load(fullfile(outputRoot, 'mesh_geometry.mat'));
expectedMeshHash = localValidateMesh(mesh, cfg, caseId, meshContract);
localValidateState0(outputRoot, mesh, caseId);

indexRows = localReadCycleIndex(fullfile(outputRoot, 'cycle_index.csv'));
terminalCycle = double(runResult.terminal_cycle);
localRequire(terminalCycle >= 1 && terminalCycle <= cfg.censor_cap && ...
    terminalCycle == floor(terminalCycle), 'Terminal cycle is invalid.');
localRequire(numel(indexRows) == terminalCycle, ...
    'Cycle index row count does not equal the terminal cycle.');
expectedBaseFiles = [ ...
    "EVENT_METADATA.json"; "INPUT_SNAPSHOT.json"; "LAUNCH_RECEIPT.json"; ...
    "RUN_RESULT.json"; ...
    "cycle_index.csv"; "initial_state_metadata.mat"; "mesh_geometry.mat"; ...
    "state0_analysis.mat"; ...
    compose("states/cycle_%04d.mat", (1:terminalCycle).')];
localRequireExactFiles(outputRoot, expectedBaseFiles);

eventState = struct();
previous = [];
damageMin = inf;
damageMax = -inf;
alphaBarMin = inf;
alphaBarMax = -inf;
activeIdentityMax = 0;
for cycle = 1:terminalCycle
    relativePath = sprintf('states/cycle_%04d.mat', cycle);
    state = load(fullfile(outputRoot, relativePath));
    if cycle == 1
        metrics = validate_toy_road_state(state);
    else
        metrics = validate_toy_road_state(state, previous);
    end
    localRequire(isequal(state.node_coords, mesh.node_coords) && ...
        isequal(state.connectivity, mesh.connectivity), ...
        'State %d mesh arrays differ from mesh_geometry.mat.', cycle);
    localRequire(strcmp(string(state.mesh_sha256), string(mesh.mesh_sha256)), ...
        'State %d mesh hash differs from mesh_geometry.mat.', cycle);
    localRequire(strcmp(string(state.mesh_sha256), expectedMeshHash) && ...
        isequal(state.quadrature_points, mesh.quadrature_points) && ...
        isequal(state.quadrature_weights, mesh.quadrature_weights), ...
        'State %d quadrature or case mesh identity differs from mesh_geometry.mat.', ...
        cycle);
    expectedUmax = cfg.umax_for_cycle(cycle);
    localRequire(state.cycle == cycle && abs(state.Umax_N - expectedUmax) <= 1e-14, ...
        'State %d case amplitude or cycle identity is invalid.', cycle);
    localValidateIndexRow(indexRows(cycle), state, relativePath);

    eventState = advance_toy_road_event(eventState, mesh.node_coords, ...
        mesh.connectivity, cycle, state.d_node);
    localRequire(indexRows(cycle).event_hit == eventState.hit && ...
        localOptionalEqual(indexRows(cycle).first_hit, eventState.first_hit) && ...
        indexRows(cycle).consecutive_post_hit == eventState.consecutive_post_hit && ...
        localOptionalEqual(indexRows(cycle).confirmed, eventState.confirmed), ...
        'Cycle index event state is invalid at cycle %d.', cycle);
    localRequire(metrics.right_boundary_hit == eventState.hit, ...
        'State and event hit diagnostics differ at cycle %d.', cycle);
    damageMin = min(damageMin, metrics.damage_min);
    damageMax = max(damageMax, metrics.damage_max);
    alphaBarMin = min(alphaBarMin, metrics.alpha_bar_min);
    alphaBarMax = max(alphaBarMax, metrics.alpha_bar_max);
    activeIdentityMax = max(activeIdentityMax, ...
        metrics.active_identity_max_abs_error);
    previous = state;
end

event = localReadJson(fullfile(outputRoot, 'EVENT_METADATA.json'));
localValidateTerminalMetadata(event, runResult, eventState, caseId, cfg, ...
    terminalCycle);

summary = struct( ...
    'schema_version', 'toy_road_validation_summary_v1', ...
    'is_valid', true, ...
    'case_id', char(caseId), ...
    'source_commit', char(string(snapshot.source_commit)), ...
    'terminal_cycle', terminalCycle, ...
    'terminal_reason', char(string(runResult.terminal_reason)), ...
    'terminal_state_file', char(string(runResult.terminal_state_file)), ...
    'state_count', terminalCycle, ...
    'mesh_sha256', char(string(mesh.mesh_sha256)), ...
    'first_hit', localJsonOptional(eventState.first_hit), ...
    'confirmed', localJsonOptional(eventState.confirmed), ...
    'damage_min', damageMin, ...
    'damage_max', damageMax, ...
    'alpha_bar_min', alphaBarMin, ...
    'alpha_bar_max', alphaBarMax, ...
    'active_identity_max_abs_error', activeIdentityMax, ...
    'run_result_is_sole_completion_marker', true, ...
    'latent_fem_fields_are_direct_road_sensors', false, ...
    'pidl_network_training_authorized', false, ...
    'road_validation_authorized', false);
end

function localValidateSnapshot(snapshot, cfg, caseId, caseLockHash)
required = {'case_configuration', 'case_id', 'lock_sha256', 'source_commit', ...
    'fresh_state', 'line_search', 'cycle_jump', 'normalized_substeps'};
localRequire(isstruct(snapshot) && isscalar(snapshot) && ...
    all(isfield(snapshot, required)), 'INPUT_SNAPSHOT.json is incomplete.');
localRequire(strcmp(string(snapshot.case_id), caseId) && ...
    strcmpi(string(snapshot.lock_sha256), caseLockHash) && ...
    islogical(snapshot.fresh_state) && isscalar(snapshot.fresh_state) && ...
    snapshot.fresh_state && islogical(snapshot.line_search) && ...
    ~snapshot.line_search && islogical(snapshot.cycle_jump) && ...
    ~snapshot.cycle_jump && ...
    isequal(reshape(snapshot.normalized_substeps, 1, []), ...
        [0.25 0.5 0.75 1.0 0.0]), ...
    'INPUT_SNAPSHOT.json violates fresh locked execution.');
sourceCommit = string(snapshot.source_commit);
localRequire(isscalar(sourceCommit) && ...
    ~isempty(regexp(char(sourceCommit), '^[0-9a-f]{40}$', 'once')), ...
    'INPUT_SNAPSHOT source commit is not a full lowercase Git hash.');
cfgSnapshot = rmfield(cfg, 'umax_for_cycle');
snapshotJson = jsonencode(localCanonicalize(snapshot.case_configuration));
lockedJson = jsonencode(localCanonicalize(cfgSnapshot));
localRequire(strcmp(snapshotJson, lockedJson), ...
    'INPUT_SNAPSHOT case configuration differs from the sealed lock.');
end

function provenance = localReadLaunchReceipt(input, outputRoot)
localRequire((ischar(input) && isrow(input)) || ...
    (isstring(input) && isscalar(input)), ...
    'Launch receipt input must be the canonical JSON path.');
expectedPath = fullfile(outputRoot, 'LAUNCH_RECEIPT.json');
localRequire(strcmpi(char(java.io.File(char(input)).getCanonicalPath()), ...
        char(java.io.File(expectedPath).getCanonicalPath())) && ...
    isfile(expectedPath), ...
    'The canonical no-clobber LAUNCH_RECEIPT.json is required.');
provenance = localReadJson(expectedPath);
end

function localValidateProvenance(provenance, snapshot, caseId, ...
        caseLockHash, parentLockHash, handoffDir, parentLock)
required = {'schema_version', 'case_id', 'source_commit', ...
    'source_root', 'source_manifest_sha256', 'source_hashes', ...
    'case_lock_sha256', 'parent_lock_sha256', ...
    'griphfith_commit', 'griphfith_root', 'griphfith_source_hashes', ...
    'runtime_hashes', 'parent_root', 'parent_source_hashes', ...
    'matlab_exit_code'};
localRequire(isstruct(provenance) && isscalar(provenance) && ...
    all(isfield(provenance, required)), 'Producer provenance is incomplete.');
manifestHash = localFileSha256(fullfile(handoffDir, 'SHA256SUMS.txt'));
localRequire(strcmp(string(provenance.schema_version), ...
        "toy_road_launch_receipt_v1") && ...
    strcmp(string(provenance.case_id), caseId) && ...
    strcmp(string(provenance.source_commit), string(snapshot.source_commit)) && ...
    strcmpi(string(provenance.source_manifest_sha256), manifestHash) && ...
    strcmpi(string(provenance.case_lock_sha256), caseLockHash) && ...
    strcmpi(string(provenance.parent_lock_sha256), parentLockHash) && ...
    strcmpi(string(provenance.griphfith_commit), ...
        "355d4c83fefc2db88c32031a2dd2623b3de85c89") && ...
    localValidCommit(provenance.source_commit) && ...
    localNormalizedAbsolutePath(provenance.source_root) && ...
    localNormalizedAbsolutePath(provenance.griphfith_root) && ...
    localNormalizedAbsolutePath(provenance.parent_root) && ...
    isnumeric(provenance.matlab_exit_code) && ...
    isscalar(provenance.matlab_exit_code) && provenance.matlab_exit_code == 0 && ...
    ~isempty(provenance.griphfith_source_hashes) && ...
    ~isempty(provenance.runtime_hashes) && ...
    ~isempty(provenance.parent_source_hashes), ...
    'Producer provenance does not match locked source/runtime identities.');
localValidateHashReceipts(provenance.source_hashes, ...
    localReadSourceManifest(fullfile(handoffDir, 'SHA256SUMS.txt')), ...
    'sealed source');
localValidateHashReceipts(provenance.griphfith_source_hashes, ...
    localExpectedGripfithSourceHashes(), 'GRIPHFiTH source');
localValidateHashReceipts(provenance.runtime_hashes, ...
    localExpectedRuntimeHashes(), 'runtime');
localValidateHashReceipts(provenance.parent_source_hashes, ...
    localExpectedParentHashes(parentLock), 'parent source');
end

function localValidateHashReceipts(records, expectedRecords, label)
localRequire(isstruct(records) && numel(records) == numel(expectedRecords) && ...
    isequal(sort(string(fieldnames(records))), sort(["path"; "sha256"])), ...
    '%s hash receipt schema is invalid.', label);
paths = strings(numel(records), 1);
hashes = strings(numel(records), 1);
for index = 1:numel(records)
    paths(index) = string(records(index).path);
    hashes(index) = string(records(index).sha256);
    localRequire(isscalar(paths(index)) && strlength(paths(index)) > 0 && ...
        isscalar(hashes(index)) && ...
        ~isempty(regexp(char(hashes(index)), '^[0-9a-f]{64}$', 'once')), ...
        '%s hash receipt contains an invalid path or digest.', label);
end
localRequire(numel(unique(lower(paths))) == numel(paths) && ...
    all(~contains(paths, '\')) && all(~startsWith(paths, '/')) && ...
    all(cellfun(@isempty, regexp(cellstr(paths), '(^|/)\.\.(/|$)', 'once'))), ...
    '%s hash receipt contains duplicate, case-colliding, or unsafe paths.', label);
expectedPaths = string({expectedRecords.path}).';
expectedHashes = string({expectedRecords.sha256}).';
[paths, order] = sort(paths);
hashes = hashes(order);
[expectedPaths, order] = sort(expectedPaths);
expectedHashes = expectedHashes(order);
localRequire(isequal(paths, expectedPaths) && isequal(hashes, expectedHashes), ...
    '%s hash receipt does not contain the exact locked path-to-SHA256 mapping.', ...
    label);
end

function records = localReadSourceManifest(path)
bytes = localReadBytes(path);
localRequire(~any(bytes == 13), 'Sealed source manifest must use LF bytes.');
lines = splitlines(string(native2unicode(bytes.', 'UTF-8')));
lines(lines == "") = [];
records = repmat(struct('path', '', 'sha256', ''), numel(lines), 1);
for index = 1:numel(lines)
    token = regexp(char(lines(index)), '^([0-9a-f]{64})  (.+)$', ...
        'tokens', 'once');
    localRequire(~isempty(token), 'Sealed source manifest line is malformed.');
    records(index).path = token{2};
    records(index).sha256 = token{1};
end
end

function records = localExpectedGripfithSourceHashes()
records = localHashRecords( ...
    ["Scripts/fatigue_fracture/solve_fatigue_fracture.m" ...
     "Sources/+phase_field/+fem/+solver/newton_raphson.m" ...
     "Sources/+phase_field/+fem/+solver/+stag/post_iter_update.m" ...
     "Scripts/brittle_fracture/INPUT_SENS_tensile.m" ...
     "Scripts/fatigue_fracture/init_fatigue_fracture.m" ...
     "Sources/+phase_field/System.m" "Dependencies/meshes/sens_mesh.m"], ...
    ["ae1aa2ff4114c67b166e39b377e08a0d7e28761bb0afa038a388e1eb026e9252" ...
     "20afff63d79eeffd3e6a502b996485e47f64a3b550e19b396cd1bf90120ad76d" ...
     "c9ebc6e87ddc1e6340a6fe077903241656feedea5220488035fb49e3efe55831" ...
     "3cc4ba07cf4b0d5a556457567b719c633e65a3519e1a734ddea00c608c292353" ...
     "96365b7f0b6ecf02cd0e2209765310f29122f503b5c2272240f84fb24ea4098d" ...
     "383fe2566a63652b9287fec3172f4135800e7cb605efcc718e90abf3a54ec5fa" ...
     "dbf13237939425b61cde93b841ae2c24e7fccd291861df5508a34800bb9f4706"]);
end

function records = localExpectedRuntimeHashes()
records = localHashRecords( ...
    ["Sources/+phase_field/+mex/+fem/+assembly/+equilibrium/initial.mexw64" ...
     "Sources/+phase_field/+mex/+fem/+assembly/+equilibrium/AMOR.mexw64" ...
     "Sources/+phase_field/+mex/+fem/+assembly/+pf/AT1_HISTORY_FATIGUE.mexw64" ...
     "CHOLMOD/MATLAB/cholmod2.mexw64"], ...
    ["589f3dc793694ea2916fbb6a21dd030bc4bc04ead3d91705e6e882b2d67ca340" ...
     "64abee69f2c441730dc2efa4047ac45ab1d1b40e20c4822ed6e992adcd6b19e7" ...
     "53e8fd0b229817b7c14c52a5b6afaa957692f475057b79b9a9a10195ccb92e60" ...
     "86a2f15543eda1f7223a1733d935d37e9e2f4f2c2d8db3c4adc2c0f675c27329"]);
end

function records = localExpectedParentHashes(parentLock)
source = parentLock.source_files;
initialMetadata = source.(matlab.lang.makeValidName('initial_state_metadata.mat'));
state0 = source.(matlab.lang.makeValidName('state0_analysis.mat'));
preRunLock = source.(matlab.lang.makeValidName('pre_run_lock.mat'));
cycle1 = source.cycle_shards.(matlab.lang.makeValidName('cycle_0001.mat'));
cycle83 = source.cycle_shards.(matlab.lang.makeValidName('cycle_0083.mat'));
cycle86 = source.cycle_shards.(matlab.lang.makeValidName('cycle_0086.mat'));
records = localHashRecords( ...
    [string(initialMetadata.relative_path) string(state0.relative_path) ...
     string(preRunLock.relative_path) string(cycle1.relative_path) ...
     string(cycle83.relative_path) string(cycle86.relative_path) ...
     string(source.parent_package_manifest.relative_path) ...
     string(source.parent_mesh_evidence.relative_path)], ...
    [string(initialMetadata.sha256) string(state0.sha256) ...
     string(preRunLock.sha256) string(cycle1.sha256) ...
     string(cycle83.sha256) string(cycle86.sha256) ...
     string(source.parent_package_manifest.sha256) ...
     string(source.parent_mesh_evidence.sha256)]);
end

function records = localHashRecords(paths, hashes)
records = repmat(struct('path', '', 'sha256', ''), numel(paths), 1);
for index = 1:numel(paths)
    records(index).path = char(paths(index));
    records(index).sha256 = char(hashes(index));
end
end

function contract = localLoadParentMeshContract(parentLock, dependencies)
mesh = parentLock.mesh;
localRequire(mesh.num_nodes == 86756 && mesh.num_elem == 86408 && ...
    strcmp(string(mesh.content_sha256), ...
        "7ea77bf6d4621d746f174eb9c357c4bc554463eea8afb8665b00e918bcd937ab") && ...
    strcmp(string(mesh.content_sha256_semantics), ...
        "analysis_graph_npz_centroids_areas_connectivity_edge_index_v1") && ...
    strcmp(string(mesh.source_sha256), ...
        "bd5b731daeb0718368309cd50c44fa7422e49096b495f619eba429d1c6bde419") && ...
    strcmp(string(mesh.source_sha256_semantics), "raw_analysis_graph_npz_bytes") && ...
    strcmp(string(mesh.source_package_evidence_sha256), ...
        "8e865f5eace05992490885c569f5ca8d9d1e37e10a3d2bd8ade176bfcd23ecf2") && ...
    strcmp(string(mesh.source_package_evidence_sha256_semantics), ...
        "normalized_ascii_vtk_geometry_topology_v1") && ...
    strcmp(string(mesh.source_package_evidence_source_sha256), ...
        "acdc981269024cbb111f7d468c287f2d1ca09f3735131b56aca7fa2fbaec1615") && ...
    strcmp(string(mesh.task4_parent_mesh_sha256), ...
        "4d01985bfe2e80afe7140ab1ead905ddce5843f8495a3558d2d4da3b237df5af") && ...
    strcmp(string(mesh.task4_parent_mesh_sha256_semantics), ...
        "sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1"), ...
    'PARENT_LOCK mesh dimensions, identities, or hash semantics are invalid.');
contract = struct('num_nodes', double(mesh.num_nodes), ...
    'num_elem', double(mesh.num_elem), ...
    'task4_parent_mesh_sha256', string(mesh.task4_parent_mesh_sha256), ...
    'quadrature_points', 1 / sqrt(3) * [-1 -1; 1 -1; 1 1; -1 1], ...
    'quadrature_weights', ones(4, 1));
if isempty(fieldnames(dependencies))
    return;
end
localRequire(isstruct(dependencies) && isscalar(dependencies) && ...
    isequal(sort(string(fieldnames(dependencies))), ...
        sort(["schema_version"; "parent_mesh_contract"])) && ...
    strcmp(string(dependencies.schema_version), ...
        "toy_road_finalizer_test_dependencies_v1"), ...
    'Finalizer test dependency schema is invalid.');
testContract = dependencies.parent_mesh_contract;
required = {'num_nodes', 'num_elem', 'task4_parent_mesh_sha256', ...
    'quadrature_points', 'quadrature_weights'};
localRequire(isstruct(testContract) && isscalar(testContract) && ...
    all(isfield(testContract, required)), ...
    'Finalizer test parent mesh contract is incomplete.');
contract = testContract;
contract.task4_parent_mesh_sha256 = string(contract.task4_parent_mesh_sha256);
end

function value = localValidCommit(commit)
commit = char(string(commit));
value = ~isempty(regexp(commit, '^[0-9a-f]{40}$', 'once')) && ...
    numel(unique(commit)) > 1;
end

function value = localNormalizedAbsolutePath(path)
path = string(path);
value = isscalar(path) && strlength(path) > 0 && ~contains(path, '\') && ...
    (~isempty(regexp(char(path), '^[A-Za-z]:/', 'once')) || startsWith(path, '/'));
end

function expectedMeshHash = localValidateMesh(mesh, cfg, caseId, contract)
required = {'node_coords', 'connectivity', 'element_material_ids', ...
    'element_centroids', 'element_areas', 'quadrature_points', ...
    'quadrature_weights', 'mesh_sha256', 'mesh_ordering_id', ...
    'parent_node_coords', 'mesh_transfer_audit'};
localRequire(isstruct(mesh) && isscalar(mesh) && all(isfield(mesh, required)), ...
    'mesh_geometry.mat is incomplete.');
coords = mesh.node_coords;
connectivity = mesh.connectivity;
localRequire(isnumeric(coords) && isreal(coords) && size(coords, 2) == 2 && ...
    all(isfinite(coords), 'all') && isnumeric(connectivity) && ...
    isreal(connectivity) && size(connectivity, 2) == 4 && ...
    all(isfinite(connectivity), 'all') && ...
    all(connectivity == floor(connectivity), 'all') && ...
    all(connectivity >= 1, 'all') && all(connectivity <= size(coords, 1), 'all'), ...
    'mesh_geometry contains invalid Q4 coordinates/connectivity.');
localRequire(isequal(size(mesh.parent_node_coords), [contract.num_nodes 2]) && ...
    isequal(size(connectivity), [contract.num_elem 4]) && ...
    size(coords, 1) == contract.num_nodes, ...
    'mesh_geometry does not have the exact locked parent dimensions.');
parentMeshHash = toy_road_mesh_sha256(mesh.parent_node_coords, connectivity);
localRequire(strcmp(parentMeshHash, contract.task4_parent_mesh_sha256), ...
    'Parent coordinates/connectivity do not match the sealed Task 4 identity.');
elementCount = size(connectivity, 1);
localRequire(isequal(size(mesh.element_material_ids), [elementCount 1]) && ...
    all(isfinite(mesh.element_material_ids), 'all') && ...
    isequal(size(mesh.element_centroids), [elementCount 2]) && ...
    isequal(size(mesh.element_areas), [elementCount 1]) && ...
    all(mesh.element_areas > 0, 'all') && ...
    size(mesh.quadrature_points, 2) == 2 && ...
    numel(mesh.quadrature_weights) == size(mesh.quadrature_points, 1) && ...
    all(mesh.quadrature_weights > 0, 'all'), ...
    'mesh_geometry dimensions or quadrature data are invalid.');
localRequire(isequal(mesh.quadrature_points, contract.quadrature_points) && ...
    isequal(mesh.quadrature_weights, contract.quadrature_weights), ...
    'mesh_geometry quadrature differs from the locked Q4 rule.');
x = reshape(coords(connectivity, 1), size(connectivity));
y = reshape(coords(connectivity, 2), size(connectivity));
next = [2:4 1];
centroids = [mean(x, 2) mean(y, 2)];
areas = 0.5 * abs(sum(x .* y(:, next) - y .* x(:, next), 2));
localRequire(max(abs(mesh.element_centroids - centroids), [], 'all') <= 1e-14 && ...
    max(abs(mesh.element_areas - areas), [], 'all') <= 1e-14 && ...
    strcmp(string(mesh.mesh_sha256), ...
        toy_road_mesh_sha256(coords, connectivity)) && ...
    strcmp(string(mesh.mesh_ordering_id), ...
        "q4_node_connectivity_1_based_v1"), ...
    'mesh_geometry derived values, ordering, or hash are invalid.');
localRequire(isequal(size(mesh.parent_node_coords), size(coords)) && ...
    all(isfinite(mesh.parent_node_coords), 'all') && ...
    isstruct(mesh.mesh_transfer_audit) && isscalar(mesh.mesh_transfer_audit) && ...
    isfield(mesh.mesh_transfer_audit, 'applied'), ...
    'mesh_geometry parent/audit evidence is invalid.');
if caseId == "T1_initial_defect"
    [expectedCoords, expectedAudit] = apply_t1_mesh_transfer( ...
        mesh.parent_node_coords, connectivity, cfg.physics.ell);
    expectedMeshHash = toy_road_mesh_sha256(expectedCoords, connectivity);
    recordedAudit = rmfield(mesh.mesh_transfer_audit, 'applied');
    localRequire(logical(mesh.mesh_transfer_audit.applied) && ...
        isequal(coords, expectedCoords) && ...
        strcmp(string(mesh.mesh_sha256), expectedMeshHash) && ...
        isequaln(recordedAudit, expectedAudit), ...
        'T1 mesh transfer audit does not reproduce the sealed map.');
else
    expectedMeshHash = contract.task4_parent_mesh_sha256;
    localRequire(~logical(mesh.mesh_transfer_audit.applied) && ...
        isequal(coords, mesh.parent_node_coords) && ...
        strcmp(string(mesh.mesh_sha256), expectedMeshHash), ...
        'Non-T1 case changed the parent mesh.');
end
end

function localValidateState0(outputRoot, mesh, caseId)
state0 = load(fullfile(outputRoot, 'state0_analysis.mat'));
required = {'node_coords', 'connectivity', 'displ', 'p_field', ...
    'p_field_old', 'history_vars', 'recovery_residual', 'state_semantics_id'};
localRequire(all(isfield(state0, required)) && ...
    isequal(state0.node_coords, mesh.node_coords) && ...
    isequal(state0.connectivity, mesh.connectivity), ...
    'state0 mesh or required fields are invalid.');
nodeCount = size(mesh.node_coords, 1);
elementCount = size(mesh.connectivity, 1);
gpCount = size(mesh.quadrature_points, 1);
localRequire(isequal(size(state0.displ), [2 * nodeCount 1]) && ...
    isequal(size(state0.p_field), [nodeCount 1]) && ...
    isequal(state0.p_field_old, state0.p_field) && ...
    all(state0.p_field >= 0 & state0.p_field <= 1, 'all') && ...
    isequal(size(state0.history_vars), [elementCount gpCount 4]) && ...
    all(isfinite(state0.displ), 'all') && ...
    all(isfinite(state0.history_vars), 'all') && ...
    all(state0.history_vars(:, :, 2:3) == 0, 'all') && ...
    all(state0.history_vars(:, :, 4) == 1, 'all') && ...
    isnumeric(state0.recovery_residual) && isreal(state0.recovery_residual) && ...
    isscalar(state0.recovery_residual) && isfinite(state0.recovery_residual) && ...
    strcmp(string(state0.state_semantics_id), ...
        "fresh_hard_recovered_state0_v1"), ...
    'state0 recovery fields violate fresh-state semantics.');

metadataPayload = load(fullfile(outputRoot, 'initial_state_metadata.mat'));
localRequire(isfield(metadataPayload, 'initial_state_metadata') && ...
    isstruct(metadataPayload.initial_state_metadata) && ...
    isscalar(metadataPayload.initial_state_metadata), ...
    'initial_state_metadata.mat is invalid.');
metadata = metadataPayload.initial_state_metadata;
requiredMetadata = {'case_id', 'fresh_state', 'recovery_residual', ...
    'fatigue_alpha_bar_initial', 'fatigue_driver_increment_initial', ...
    'fatigue_degradation_initial'};
localRequire(all(isfield(metadata, requiredMetadata)) && ...
    strcmp(string(metadata.case_id), caseId) && logical(metadata.fresh_state) && ...
    isequal(metadata.recovery_residual, state0.recovery_residual) && ...
    metadata.fatigue_alpha_bar_initial == 0 && ...
    metadata.fatigue_driver_increment_initial == 0 && ...
    metadata.fatigue_degradation_initial == 1, ...
    'Initial-state metadata does not match recovered state0.');
end

function rows = localReadCycleIndex(path)
localRequire(isfile(path), 'cycle_index.csv is missing.');
text = string(fileread(path));
lines = splitlines(text);
if ~isempty(lines) && lines(end) == ""
    lines(end) = [];
end
header = "cycle,Umax_N,peak_substep_ordinal,raw_step_1_based," + ...
    "branch,phase,file,mesh_sha256,event_hit,first_hit," + ...
    "consecutive_post_hit,confirmed";
localRequire(numel(lines) >= 2 && lines(1) == header, ...
    'cycle_index.csv header is invalid.');
template = struct( ...
    'cycle', 0, 'Umax_N', 0, 'peak_substep_ordinal', 0, ...
    'raw_step_1_based', 0, 'branch', "", 'phase', "", 'file', "", ...
    'mesh_sha256', "", 'event_hit', false, 'first_hit', NaN, ...
    'consecutive_post_hit', 0, 'confirmed', NaN);
rows = repmat(template, numel(lines) - 1, 1);
for index = 2:numel(lines)
    fields = split(lines(index), ',');
    localRequire(numel(fields) == 12, ...
        'cycle_index.csv row %d has the wrong field count.', index);
    eventHit = localCsvNumber(fields(9), false);
    localRequire(any(eventHit == [0 1]), ...
        'cycle_index.csv event_hit must be exactly 0 or 1.');
    rows(index - 1) = struct( ...
        'cycle', localCsvNumber(fields(1), false), ...
        'Umax_N', localCsvNumber(fields(2), false), ...
        'peak_substep_ordinal', localCsvNumber(fields(3), false), ...
        'raw_step_1_based', localCsvNumber(fields(4), false), ...
        'branch', fields(5), 'phase', fields(6), 'file', fields(7), ...
        'mesh_sha256', fields(8), ...
        'event_hit', logical(eventHit), ...
        'first_hit', localCsvNumber(fields(10), true), ...
        'consecutive_post_hit', localCsvNumber(fields(11), false), ...
        'confirmed', localCsvNumber(fields(12), true));
end
end

function value = localCsvNumber(text, optional)
if optional && strlength(text) == 0
    value = NaN;
    return;
end
value = str2double(text);
localRequire(isscalar(value) && isfinite(value), ...
    'cycle_index.csv contains a nonnumeric required field.');
end

function localValidateIndexRow(row, state, relativePath)
localRequire(row.cycle == state.cycle && row.Umax_N == state.Umax_N && ...
    row.peak_substep_ordinal == state.peak_substep_ordinal && ...
    row.raw_step_1_based == state.raw_step_1_based && ...
    strcmp(row.branch, string(state.branch)) && ...
    strcmp(row.phase, string(state.phase)) && ...
    strcmp(row.file, string(relativePath)) && ...
    strcmp(row.mesh_sha256, string(state.mesh_sha256)), ...
    'cycle_index.csv differs from state %d metadata.', state.cycle);
end

function localValidateTerminalMetadata(event, runResult, eventState, ...
        caseId, cfg, terminalCycle)
required = {'case_id', 'censor_cap', 'confirmation_cycles', 'confirmed', ...
    'cycle_index_file', 'event_rule', 'first_hit', 'status', ...
    'terminal_cycle', 'terminal_reason', 'terminal_state_file'};
localRequire(isstruct(event) && isscalar(event) && all(isfield(event, required)), ...
    'EVENT_METADATA.json is incomplete.');
expectedState = sprintf('states/cycle_%04d.mat', terminalCycle);
localRequire(strcmp(string(event.case_id), caseId) && ...
    event.censor_cap == cfg.censor_cap && ...
    event.confirmation_cycles == cfg.event_contract.confirmation_cycles && ...
    strcmp(string(event.cycle_index_file), "cycle_index.csv") && ...
    strcmp(string(event.event_rule), string(cfg.event_contract.event_rule)) && ...
    strcmp(string(event.status), "terminal_metadata") && ...
    event.terminal_cycle == terminalCycle && ...
    strcmp(string(event.terminal_state_file), string(expectedState)) && ...
    runResult.terminal_cycle == terminalCycle && ...
    strcmp(string(runResult.terminal_state_file), string(expectedState)) && ...
    localJsonOptionalEqual(event.first_hit, eventState.first_hit) && ...
    localJsonOptionalEqual(event.confirmed, eventState.confirmed), ...
    'Terminal event/run metadata is inconsistent with validated states.');
if isnan(eventState.confirmed)
    localRequire(terminalCycle == cfg.censor_cap && ...
        strcmp(string(event.terminal_reason), "right_censored") && ...
        strcmp(string(runResult.terminal_reason), "right_censored"), ...
        'Right-censored terminal metadata is invalid.');
else
    localRequire(eventState.confirmed == terminalCycle && ...
        strcmp(string(event.terminal_reason), "confirmed") && ...
        strcmp(string(runResult.terminal_reason), "confirmed"), ...
        'Confirmed terminal metadata is invalid.');
end
end

function localRequireExactFiles(outputRoot, expected)
actual = localRelativeFiles(outputRoot, false);
localRequire(isequal(sort(actual), sort(string(expected))), ...
    'Output contains missing or extra pre-finalization artifacts.');
end

function files = localRelativeFiles(outputRoot, includeManifest)
listing = dir(fullfile(outputRoot, '**', '*'));
listing = listing(~[listing.isdir]);
files = strings(numel(listing), 1);
prefixLength = strlength(string(outputRoot)) + 2;
for index = 1:numel(listing)
    fullPath = string(fullfile(listing(index).folder, listing(index).name));
    files(index) = replace(extractAfter(fullPath, prefixLength - 1), '\', '/');
end
if ~includeManifest
    files(files == "SHA256SUMS.txt") = [];
end
end

function localRejectSymlinksAndCaseCollisions(outputRoot)
files = localRelativeFiles(outputRoot, true);
folded = lower(files);
localRequire(numel(unique(folded)) == numel(folded), ...
    'Output contains duplicate or case-colliding paths.');
rootEntries = dir(outputRoot);
rootEntries = rootEntries(~ismember({rootEntries.name}, {'.', '..'}));
rootDirectories = string({rootEntries([rootEntries.isdir]).name});
localRequire(isequal(sort(rootDirectories(:)), "states"), ...
    'Output root must contain exactly the canonical states directory.');
statesPath = fullfile(outputRoot, 'states');
localRequire(~java.nio.file.Files.isSymbolicLink( ...
    java.io.File(statesPath).toPath()) && ~localIsReparsePoint(statesPath), ...
    'The canonical states directory cannot be a symbolic link.');
stateEntries = dir(statesPath);
stateEntries = stateEntries(~ismember({stateEntries.name}, {'.', '..'}));
localRequire(~any([stateEntries.isdir]), ...
    'Nested or extra directories are forbidden inside states.');
for index = 1:numel(files)
    path = fullfile(outputRoot, char(replace(files(index), '/', filesep)));
    localRequire(~java.nio.file.Files.isSymbolicLink(java.io.File(path).toPath()) && ...
        ~localIsReparsePoint(path), ...
        'Output contains a forbidden symlink/reparse point: %s.', files(index));
end
end

function localWriteManifest(outputRoot)
manifestPath = fullfile(outputRoot, 'SHA256SUMS.txt');
if localPathExists(manifestPath)
    error('toyRoad:ManifestExists', ...
        'Refusing to overwrite pre-existing output manifest.');
end
localRejectSymlinksAndCaseCollisions(outputRoot);
files = sort(localRelativeFiles(outputRoot, false));
lines = strings(numel(files), 1);
for index = 1:numel(files)
    path = fullfile(outputRoot, char(replace(files(index), '/', filesep)));
    lines(index) = localFileSha256(path) + "  " + files(index);
end
bytes = unicode2native(char(strjoin(lines, newline) + newline), 'UTF-8');
localPublishBytesNoClobber(manifestPath, bytes);
end

function summary = localVerifyManifest(outputRoot, caseId)
try
    localRequire(isfolder(outputRoot), 'Output root does not exist.');
    localRejectSymlinksAndCaseCollisions(outputRoot);
    runResult = validate_toy_road_run_result( ...
        fullfile(outputRoot, 'RUN_RESULT.json'), caseId);
    localRequire(runResult.complete, 'RUN_RESULT.json is not complete.');
    manifestPath = fullfile(outputRoot, 'SHA256SUMS.txt');
    localRequire(isfile(manifestPath), 'Output manifest is missing.');
    bytes = localReadBytes(manifestPath);
    localRequire(~any(bytes == 13), 'Output manifest must use LF bytes.');
    lines = splitlines(string(native2unicode(bytes.', 'UTF-8')));
    if ~isempty(lines) && lines(end) == ""
        lines(end) = [];
    end
    entries = strings(numel(lines), 2);
    for index = 1:numel(lines)
        token = regexp(char(lines(index)), '^([0-9a-f]{64})  (.+)$', ...
            'tokens', 'once');
        localRequire(~isempty(token), 'Malformed output manifest line.');
        entries(index, :) = string(token);
    end
    paths = entries(:, 2);
    localRequire(isequal(paths, sort(paths)) && ...
        numel(unique(lower(paths))) == numel(paths) && ...
        ~any(paths == "SHA256SUMS.txt"), ...
        'Output manifest paths are unsorted, duplicated, or self-referential.');
    actualFiles = sort(localRelativeFiles(outputRoot, false));
    localRequire(isequal(paths, actualFiles), ...
        'Output manifest has missing or extra artifacts.');
    for index = 1:numel(paths)
        path = fullfile(outputRoot, char(replace(paths(index), '/', filesep)));
        localRequire(strcmp(entries(index, 1), localFileSha256(path)), ...
            'Output manifest SHA256 mismatch: %s.', paths(index));
    end
    summary = struct('is_valid', true, 'file_count', numel(paths), ...
        'manifest_sha256', localFileSha256(manifestPath));
catch exception
    if strcmp(exception.identifier, 'toyRoad:ManifestVerificationFailed')
        rethrow(exception);
    end
    wrapped = MException('toyRoad:ManifestVerificationFailed', ...
        'Output manifest verification failed: %s', exception.message);
    wrapped = addCause(wrapped, exception);
    throw(wrapped);
end
end

function localPublishBytesNoClobber(outputPath, bytes)
outputDir = fileparts(outputPath);
lockPath = [outputPath '.publish.lock'];
localRequire(~localPathExists(outputPath) && ...
    java.io.File(lockPath).createNewFile(), ...
    'Manifest target or publication lock already exists.');
lockCleanup = onCleanup(@() localDeleteIfExists(lockPath));
tempPath = [tempname(outputDir) '.tmp.sha256'];
tempCleanup = onCleanup(@() localDeleteIfExists(tempPath));
fileId = fopen(tempPath, 'wb');
localRequire(fileId >= 0, 'Cannot create manifest temporary file.');
fileCleanup = onCleanup(@() fclose(fileId));
written = fwrite(fileId, bytes, 'uint8');
localRequire(written == numel(bytes), 'Cannot write complete manifest bytes.');
clear fileCleanup
try
    java.nio.file.Files.createLink(java.io.File(outputPath).toPath(), ...
        java.io.File(tempPath).toPath());
catch exception
    wrapped = MException('toyRoad:PackagePublicationFailed', ...
        'No-clobber hard-link manifest publication failed.');
    wrapped = addCause(wrapped, exception);
    throw(wrapped);
end
java.nio.file.Files.delete(java.io.File(tempPath).toPath());
end

function value = localReadJson(path)
localRequire(isfile(path), 'Required JSON file is missing: %s.', path);
value = jsondecode(fileread(path));
end

function value = localCanonicalize(value)
if isstruct(value)
    value = orderfields(value);
    names = fieldnames(value);
    for elementIndex = 1:numel(value)
        for fieldIndex = 1:numel(names)
            name = names{fieldIndex};
            value(elementIndex).(name) = localCanonicalize(value(elementIndex).(name));
        end
    end
elseif iscell(value)
    for index = 1:numel(value)
        value{index} = localCanonicalize(value{index});
    end
end
end

function value = localOptionalEqual(left, right)
value = (isnan(left) && isnan(right)) || isequal(left, right);
end

function value = localJsonOptionalEqual(jsonValue, number)
if isnan(number)
    value = isempty(jsonValue);
else
    value = isequal(jsonValue, number);
end
end

function value = localJsonOptional(number)
if isnan(number)
    value = [];
else
    value = number;
end
end

function digest = localFileSha256(path)
bytes = localReadBytes(path);
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(bytes);
digestBytes = typecast(hasher.digest(), 'uint8');
digest = lower(string(reshape(dec2hex(digestBytes, 2).', 1, [])));
end

function bytes = localReadBytes(path)
fileId = fopen(path, 'rb');
localRequire(fileId >= 0, 'Cannot read required file: %s.', path);
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, '*uint8');
end

function value = localPathExists(path)
value = isfile(path) || isfolder(path);
end

function value = localIsReparsePoint(path)
options = javaArray('java.nio.file.LinkOption', 1);
options(1) = java.nio.file.LinkOption.NOFOLLOW_LINKS;
attributes = java.nio.file.Files.readAttributes( ...
    java.io.File(path).toPath(), ...
    java.lang.Class.forName('java.nio.file.attribute.BasicFileAttributes'), ...
    options);
value = attributes.isSymbolicLink() || attributes.isOther();
end

function localDeleteIfExists(path)
if isfile(path)
    delete(path);
end
end

function localRequire(condition, message, varargin)
if ~condition
    error('toyRoad:PackageValidationFailed', message, varargin{:});
end
end
