function result = main_toy_to_road_case()
%MAIN_TOY_TO_ROAD_CASE Build and run one fresh locked FEM case.

handoffDir = fileparts(mfilename('fullpath'));
environment = localReadEnvironment();
outputRoot = environment.output_root;
if isfile(outputRoot) || isfolder(outputRoot)
    error('toyRoad:OutputExists', ...
        'Refusing to overwrite existing output root: %s', outputRoot);
end

runtime = localRequireRuntime();
cfg = build_toy_road_case_config(environment.case_id, handoffDir);
[created, message] = mkdir(outputRoot);
if ~created
    error('toyRoad:OutputCreateFailed', ...
        'Cannot create fresh output root: %s', message);
end

try
    context = localBuildFreshContext(cfg, outputRoot, runtime);
    localWriteInitialPayloads(context, environment);
    result = solve_toy_to_road_case(context);
catch exception
    try
        localWriteFailureArtifacts(outputRoot, environment, exception);
    catch publicationException
        combined = MException('toyRoad:FailurePublicationFailed', ...
            'The launcher failed and its failure artifacts could not be published.');
        combined = addCause(combined, exception);
        combined = addCause(combined, publicationException);
        throw(combined);
    end
    rethrow(exception);
end
end

function environment = localReadEnvironment()
names = {'TOY_ROAD_CASE_ID', 'TOY_ROAD_OUTPUT_ROOT', ...
    'TOY_ROAD_SOURCE_COMMIT', 'TOY_ROAD_LOCK_SHA256'};
values = cellfun(@getenv, names, 'UniformOutput', false);
missing = names(cellfun(@(value) isempty(strtrim(value)), values));
if ~isempty(missing)
    error('toyRoad:MissingEnvironment', ...
        'Required environment variable is empty: %s', strjoin(missing, ', '));
end
environment = struct( ...
    'case_id', values{1}, ...
    'output_root', values{2}, ...
    'source_commit', values{3}, ...
    'lock_sha256', lower(values{4}));
end

function runtime = localRequireRuntime()
required = { ...
    'phase_field.System', ...
    'specimen.external.gmsh_import', ...
    'phase_field.init.material_characteristic', ...
    'phase_field.fem.bc.set_boundaries', ...
    'phase_field.init.dofs', ...
    'phase_field.init.quadrature', ...
    'phase_field.fem.solver.params', ...
    'phase_field.fem.solver.stag.params', ...
    'phase_field.fem.solver.stag.vars', ...
    'phase_field.fem.solver.step.params', ...
    'phase_field.fem.solver.step.pre_iter_update', ...
    'phase_field.fem.solver.stag.post_iter_update', ...
    'phase_field.fem.solver.cycl_jump.params', ...
    'phase_field.fem.solver.newton_raphson', ...
    'phase_field.mex.fem.assembly.pf.AT1_HISTORY_FATIGUE', ...
    'phase_field.mex.fem.assembly.equilibrium.AMOR', ...
    'cholmod2'};
locations = strings(size(required));
for index = 1:numel(required)
    locations(index) = string(which(required{index}));
end
missing = required(strlength(locations) == 0);
if ~isempty(missing)
    error('toyRoad:MissingRuntimeApi', ...
        'Clean GRIPHFiTH runtime API is absent from the MATLAB path: %s', ...
        strjoin(missing, ', '));
end

systemPath = char(locations(1));
sourcesDir = fileparts(fileparts(systemPath));
griphfithRoot = fileparts(sourcesDir);
meshPath = fullfile(griphfithRoot, 'Dependencies', 'meshes', 'sens_mesh.m');
if ~isfile(meshPath)
    error('toyRoad:MissingRuntimeApi', ...
        'The clean GRIPHFiTH SENS mesh source is absent: %s', meshPath);
end
runtime = struct('griphfith_root', griphfithRoot, 'mesh_path', meshPath);
end

function context = localBuildFreshContext(cfg, outputRoot, runtime)
splitType = 'AMOR';
dissFct = 'AT1';
irrev = 'HISTORY';
[MESH, GEOM] = specimen.external.gmsh_import(runtime.mesh_path, 't', 1.0);
parentNodeCoords = MESH.node;
meshTransferAudit = struct('applied', false);
if strcmp(cfg.case_id, 'T1_initial_defect')
    [MESH.node, meshTransferAudit] = apply_t1_mesh_transfer( ...
        MESH.node, MESH.elem(:, 1:MESH.nel), cfg.physics.ell);
    meshTransferAudit.applied = true;
end

tolerance = 1e-12;
topNodeIds = find(abs(MESH.node(:, 2) - 0.5) <= tolerance);
bottomNodeIds = find(abs(MESH.node(:, 2) + 0.5) <= tolerance);
crackNodeIds = find(abs(parentNodeCoords(:, 2)) <= tolerance & ...
    parentNodeCoords(:, 1) <= tolerance);
NODE_BOUNDARIES = phase_field.fem.bc.set_boundaries( ...
    'fix_X', [bottomNodeIds; topNodeIds], ...
    'fix_Y', bottomNodeIds, ...
    'disp_Y', topNodeIds, ...
    'non_hom_pf', crackNodeIds);
DOFS = phase_field.init.dofs(MESH, NODE_BOUNDARIES);
QUADRATURE = phase_field.init.quadrature(MESH.dim);
stressState = phase_field.StressState.PlaneStrain;

MAT_CHAR(1) = phase_field.init.material_characteristic( ...
    GEOM.L, dissFct, ...
    'E', 1.0, 'ni', 0.3, 'Gc', cfg.physics.Gc, 'ell', 0.01, ...
    'res_stiff', 0.0, 'alpha_T', 0.5, 'p', 2.0);
SOL_PAR = phase_field.fem.solver.params( ...
    'tol_displ', 1e-6, 'tol_p_field', 4e-4, ...
    'max_iter_displ', 250, 'max_iter_pf', 250);
SOL_STAG_PAR = phase_field.fem.solver.stag.params('tol', 4e-4, 'max_iter', 1000);
SOL_STEP_PAR = phase_field.fem.solver.step.params( ...
    'n_step', 8, 'loading', 'cyclic', 'discretization', 'loading', ...
    'uy_final', cfg.physics.umax, 'R', 0.0, 'line_search', false);
SOL_JUMP_PAR = phase_field.fem.solver.cycl_jump.params('cycl_jump', false);
if SOL_STEP_PAR.n_step ~= 5 || SOL_JUMP_PAR.cycl_jump
    error('toyRoad:RuntimeContractMismatch', ...
        'The clean solver did not retain the locked five-step/no-jump contract.');
end

displ = zeros(DOFS.num_dof, 1);
p_field = zeros(MESH.num_node, 1);
p_field(DOFS.non_hom_dirichlet_bc_pf) = 1.0;
p_field_old = zeros(size(p_field));
history_vars_old = zeros(MESH.num_elem, QUADRATURE.num_gauss_pts, 4);
assemblyPf = str2func(sprintf( ...
    'phase_field.mex.fem.assembly.pf.%s_%s_FATIGUE', dissFct, irrev));
assemblyEquilibrium = str2func(sprintf( ...
    'phase_field.mex.fem.assembly.equilibrium.%s', splitType));

sys = phase_field.System(MAT_CHAR, GEOM, QUADRATURE, DOFS, ...
    NODE_BOUNDARIES, SOL_STEP_PAR, MESH, stressState, p_field, dissFct);
zeroRawDriver = zeros(sys.MESH.num_elem, sys.QUADRATURE.num_gauss_pts);
[~, recoveryResidual, p_field, ~, history_vars_old, recoveryFailed] = ...
    phase_field.fem.solver.newton_raphson( ...
    assemblyPf, sys, p_field, p_field_old, zeroRawDriver, history_vars_old, ...
    sys.DOFS.active_dof_pf, sys.STIFFNESS_MATRIX.i_row_pf, ...
    sys.STIFFNESS_MATRIX.j_col_pf, 'max_iter', SOL_PAR.max_iter_pf, ...
    'res_tol', SOL_PAR.tol_p_field, 'line_search', false, ...
    'regularize_pf_only', true);
if recoveryFailed || ~isfinite(recoveryResidual)
    error('toyRoad:RecoveryFailed', ...
        'Fresh zero-load hard recovery did not converge.');
end
p_field = min(max(p_field, 0.0), 1.0);
p_field_old = p_field;
sys = phase_field.System(MAT_CHAR, GEOM, QUADRATURE, DOFS, ...
    NODE_BOUNDARIES, SOL_STEP_PAR, MESH, stressState, p_field, dissFct);
history_vars_old(:, :, 2:3) = 0.0;
history_vars_old(:, :, 4) = 1.0;

context = struct( ...
    'cfg', cfg, 'output_root', outputRoot, 'runtime', runtime, ...
    'sys', sys, 'sol_par', SOL_PAR, 'sol_stag_par', SOL_STAG_PAR, ...
    'sol_step_template', SOL_STEP_PAR, ...
    'assembly_pf_fh', assemblyPf, 'assembly_equilibrium_fh', assemblyEquilibrium, ...
    'displ', displ, 'p_field', p_field, 'p_field_old', p_field_old, ...
    'history_vars_old', history_vars_old, ...
    'top_node_ids', topNodeIds, 'bottom_node_ids', bottomNodeIds, ...
    'parent_node_coords', parentNodeCoords, ...
    'mesh_transfer_audit', meshTransferAudit, ...
    'recovery_residual', recoveryResidual);
end

function localWriteInitialPayloads(context, environment)
cfgSnapshot = rmfield(context.cfg, 'umax_for_cycle');
snapshot = struct( ...
    'case_configuration', cfgSnapshot, ...
    'case_id', environment.case_id, ...
    'lock_sha256', environment.lock_sha256, ...
    'source_commit', environment.source_commit, ...
    'fresh_state', true, ...
    'line_search', false, ...
    'cycle_jump', false, ...
    'normalized_substeps', [0.25 0.5 0.75 1.0 0.0]);
write_toy_road_json(fullfile(context.output_root, 'INPUT_SNAPSHOT.json'), snapshot);

mesh = context.sys.MESH;
connectivity = mesh.elem(:, 1:mesh.nel);
coords = mesh.node;
x = reshape(coords(connectivity, 1), size(connectivity));
y = reshape(coords(connectivity, 2), size(connectivity));
next = [2:mesh.nel 1];
meshPayload = struct( ...
    'node_coords', coords, ...
    'connectivity', connectivity, ...
    'element_material_ids', mesh.elem_material_id, ...
    'element_centroids', [mean(x, 2) mean(y, 2)], ...
    'element_areas', 0.5 * abs(sum(x .* y(:, next) - y .* x(:, next), 2)), ...
    'quadrature_points', context.sys.QUADRATURE.gauss_pts, ...
    'quadrature_weights', context.sys.QUADRATURE.gauss_W, ...
    'mesh_sha256', toy_road_mesh_sha256(coords, connectivity), ...
    'mesh_ordering_id', 'q4_node_connectivity_1_based_v1', ...
    'parent_node_coords', context.parent_node_coords, ...
    'mesh_transfer_audit', context.mesh_transfer_audit);
publish_toy_road_state_no_clobber(meshPayload, ...
    fullfile(context.output_root, 'mesh_geometry.mat'));

state0 = struct( ...
    'node_coords', coords, 'connectivity', connectivity, ...
    'displ', context.displ, 'p_field', context.p_field, ...
    'p_field_old', context.p_field_old, ...
    'history_vars', context.history_vars_old, ...
    'recovery_residual', context.recovery_residual, ...
    'state_semantics_id', 'fresh_hard_recovered_state0_v1');
publish_toy_road_state_no_clobber(state0, ...
    fullfile(context.output_root, 'state0_analysis.mat'));

initialMetadata = struct( ...
    'case_id', environment.case_id, ...
    'fresh_state', true, ...
    'recovery_residual', context.recovery_residual, ...
    'fatigue_alpha_bar_initial', 0.0, ...
    'fatigue_driver_increment_initial', 0.0, ...
    'fatigue_degradation_initial', 1.0);
publish_toy_road_state_no_clobber(struct( ...
    'initial_state_metadata', initialMetadata), ...
    fullfile(context.output_root, 'initial_state_metadata.mat'));
end

function localWriteFailureArtifacts(outputRoot, environment, exception)
if ~isfolder(outputRoot)
    return;
end
runPath = fullfile(outputRoot, 'RUN_RESULT.json');
if isfile(runPath)
    validate_toy_road_run_result(runPath, environment.case_id);
    return;
end
eventPath = fullfile(outputRoot, 'EVENT_METADATA.json');
if ~isfile(eventPath)
    event = struct( ...
        'case_id', environment.case_id, ...
        'confirmed', [], ...
        'first_hit', [], ...
        'status', 'failed');
    write_toy_road_json(eventPath, event);
end
failure = struct( ...
    'case_id', environment.case_id, ...
    'complete', false, ...
    'error_identifier', exception.identifier, ...
    'error_message', exception.message, ...
    'status', 'failed');
write_toy_road_json(runPath, failure);
end
