function [sys, pField, pFieldOld, historyVars, recoveryResidual, details] = ...
        recover_toy_road_initial_state(input, operators)
%RECOVER_TOY_ROAD_INITIAL_STATE Perform fresh zero-load hard recovery.

localValidateInput(input);
if nargin < 2
    operators = struct();
end
operators = localResolveOperators(operators);

initialSystem = operators.system_factory( ...
    input.mat_char, input.geom, input.quadrature, input.dofs, ...
    input.node_boundaries, input.sol_step_par, input.mesh, ...
    input.stress_state, input.p_field, input.diss_fct);
localValidateSystem(initialSystem, 'initial');
zeroRawDriver = zeros(input.mesh.num_elem, input.quadrature.num_gauss_pts);

[initialResidual, recoveryResidual, recoveredField, couplingVars, ...
    recoveredHistory, nonConverged] = operators.newton_raphson( ...
    input.assembly_pf_fh, initialSystem, input.p_field, input.p_field_old, ...
    zeroRawDriver, input.history_vars_old, initialSystem.DOFS.active_dof_pf, ...
    initialSystem.STIFFNESS_MATRIX.i_row_pf, ...
    initialSystem.STIFFNESS_MATRIX.j_col_pf, ...
    'max_iter', input.sol_par.max_iter_pf, ...
    'res_tol', input.sol_par.tol_p_field, ...
    'line_search', false, 'regularize_pf_only', true);

details = struct( ...
    'initial_residual', initialResidual, ...
    'coupling_vars', couplingVars, ...
    'history_vars_before_reset', recoveredHistory, ...
    'non_converged', nonConverged);
localValidateOutputs(input, recoveredField, couplingVars, ...
    recoveredHistory, initialResidual, recoveryResidual, nonConverged);
if nonConverged || ~isfinite(recoveryResidual)
    error('toyRoad:RecoveryFailed', ...
        'Fresh zero-load hard recovery did not converge.');
end

pField = min(max(recoveredField, 0.0), 1.0);
pFieldOld = pField;
sys = operators.system_factory( ...
    input.mat_char, input.geom, input.quadrature, input.dofs, ...
    input.node_boundaries, input.sol_step_par, input.mesh, ...
    input.stress_state, pField, input.diss_fct);
localValidateSystem(sys, 'rebuilt');
if isequal(sys, initialSystem)
    error('toyRoad:StaleRecoverySystem', ...
        'Recovery System factory returned the stale pre-recovery System.');
end

historyVars = recoveredHistory;
historyVars(:, :, 2:3) = 0.0;
historyVars(:, :, 4) = 1.0;
end

function operators = localResolveOperators(overrides)
if ~isstruct(overrides) || ~isscalar(overrides)
    error('toyRoad:InvalidRecoveryInput', ...
        'Recovery operators must be a scalar struct.');
end
operators = struct( ...
    'system_factory', @phase_field.System, ...
    'newton_raphson', @phase_field.fem.solver.newton_raphson);
names = fieldnames(overrides);
for index = 1:numel(names)
    name = names{index};
    if ~isfield(operators, name) || ~isa(overrides.(name), 'function_handle')
        error('toyRoad:InvalidRecoveryInput', ...
            'Unknown or invalid recovery operator: %s.', name);
    end
    operators.(name) = overrides.(name);
end
end

function localValidateInput(input)
required = {'mat_char', 'geom', 'quadrature', 'dofs', 'node_boundaries', ...
    'sol_step_par', 'mesh', 'stress_state', 'diss_fct', 'assembly_pf_fh', ...
    'sol_par', 'p_field', 'p_field_old', 'history_vars_old'};
if ~isstruct(input) || ~isscalar(input) || ~all(isfield(input, required)) || ...
        ~isa(input.assembly_pf_fh, 'function_handle') || ...
        ~isfield(input.mesh, 'num_elem') || ...
        ~isfield(input.quadrature, 'num_gauss_pts') || ...
        ~isfield(input.sol_par, 'max_iter_pf') || ...
        ~isfield(input.sol_par, 'tol_p_field')
    error('toyRoad:InvalidRecoveryInput', ...
        'Fresh recovery input is incomplete.');
end
if ~isnumeric(input.p_field) || ~isreal(input.p_field) || ...
        ~iscolumn(input.p_field) || ~all(isfinite(input.p_field), 'all') || ...
        ~isequal(size(input.p_field_old), size(input.p_field)) || ...
        ~isnumeric(input.history_vars_old) || ndims(input.history_vars_old) ~= 3 || ...
        size(input.history_vars_old, 1) ~= input.mesh.num_elem || ...
        size(input.history_vars_old, 2) ~= input.quadrature.num_gauss_pts || ...
        size(input.history_vars_old, 3) < 4
    error('toyRoad:InvalidRecoveryInput', ...
        'Fresh recovery fields have invalid shapes.');
end
end

function localValidateSystem(sys, stage)
if ~isa(sys, 'handle') || ~isscalar(sys) || ~isprop(sys, 'DOFS') || ...
        ~isprop(sys, 'STIFFNESS_MATRIX') || ...
        ~isfield(sys.DOFS, 'active_dof_pf') || ...
        ~isfield(sys.STIFFNESS_MATRIX, 'i_row_pf') || ...
        ~isfield(sys.STIFFNESS_MATRIX, 'j_col_pf')
    error('toyRoad:InvalidRecoveryOutput', ...
        'The %s recovery System is incompatible with clean solver APIs.', stage);
end
end

function localValidateOutputs(input, recoveredField, couplingVars, ...
        recoveredHistory, initialResidual, recoveryResidual, nonConverged)
validScalar = @(value) isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
if ~validScalar(initialResidual) || ...
        ~(isnumeric(recoveryResidual) && isreal(recoveryResidual) && ...
        isscalar(recoveryResidual)) || ...
        ~isnumeric(recoveredField) || ~isreal(recoveredField) || ...
        ~isequal(size(recoveredField), size(input.p_field)) || ...
        ~all(isfinite(recoveredField), 'all') || ...
        ~isnumeric(couplingVars) || ~isreal(couplingVars) || ...
        ~isequal(size(couplingVars), size(input.p_field)) || ...
        ~all(isfinite(couplingVars), 'all') || ...
        ~isnumeric(recoveredHistory) || ~isreal(recoveredHistory) || ...
        ~isequal(size(recoveredHistory), size(input.history_vars_old)) || ...
        ~all(isfinite(recoveredHistory), 'all') || ...
        ~islogical(nonConverged) || ~isscalar(nonConverged)
    error('toyRoad:InvalidRecoveryOutput', ...
        'Clean recovery Newton returned invalid output shapes or values.');
end
end
