function result = solve_toy_to_road_case(context)
%SOLVE_TOY_TO_ROAD_CASE Run the locked cycle loop from a fresh recovered state.

localValidateContext(context);
operators = localResolveOperators(context);
try
    result = localRunCycles(context, operators);
catch exception
    try
        localPublishFailure(context, operators, exception);
    catch publicationException
        combined = MException('toyRoad:FailurePublicationFailed', ...
            'The solver failed and its failure artifacts could not be published.');
        combined = addCause(combined, exception);
        combined = addCause(combined, publicationException);
        throw(combined);
    end
    rethrow(exception);
end
end

function result = localRunCycles(context, operators)
loadFactors = [0.25 0.5 0.75 1.0 0.0];
peakOrdinal = 4;
indexPath = fullfile(context.output_root, 'cycle_index.csv');
localCreateCycleIndex(indexPath);

sys = context.sys;
displ = context.displ;
p_field = context.p_field;
p_field_old = context.p_field_old;
history_vars_old = context.history_vars_old;
eventState = struct();
terminalCycle = 0;
terminalStateFile = "";

for cycle = 1:context.cfg.censor_cap
    cycleUmax = context.cfg.umax_for_cycle(cycle);
    stepPar = context.sol_step_template;
    stepPar.n_step = numel(loadFactors);
    stepPar.uy_final = cycleUmax;
    stepPar.ux_increment = zeros(size(loadFactors));
    stepPar.uy_increment = cycleUmax * diff([0 loadFactors]);
    stepPar.tx_increment = zeros(size(loadFactors));
    stepPar.ty_increment = zeros(size(loadFactors));
    stopAfterCycle = false;
    peakCaptured = false;

    for iStep = 1:numel(loadFactors)
        [displ, ~, tractionIncrement] = ...
            operators.pre_iter_update(iStep, sys, displ, stepPar);
        stagVars = operators.stag_vars(context.sol_stag_par);
        stagConverged = false;

        for iStag = 1:context.sol_stag_par.max_iter
            [initialDisplResidual, displResidual, displ, rawDriverGp, ~, displFailed] = ...
                operators.newton_raphson( ...
                context.assembly_equilibrium_fh, sys, displ, 0.0, p_field, 0.0, ...
                sys.DOFS.active_dof, sys.STIFFNESS_MATRIX.i_row, ...
                sys.STIFFNESS_MATRIX.j_col, ...
                'D_RHS_tract', tractionIncrement, ...
                'max_iter', context.sol_par.max_iter_displ, ...
                'res_tol', context.sol_par.tol_displ, ...
                'line_search', false);
            if displFailed || ~isfinite(displResidual)
                error('toyRoad:DisplacementSolveFailed', ...
                    'Displacement solve failed at cycle %d step %d.', cycle, iStep);
            end

            [initialPfResidual, pfResidual, p_field, ~, ~, pfFailed] = ...
                operators.newton_raphson( ...
                context.assembly_pf_fh, sys, p_field, p_field_old, rawDriverGp, ...
                history_vars_old, sys.DOFS.active_dof_pf, ...
                sys.STIFFNESS_MATRIX.i_row_pf, sys.STIFFNESS_MATRIX.j_col_pf, ...
                'max_iter', context.sol_par.max_iter_pf, ...
                'res_tol', context.sol_par.tol_p_field, ...
                'line_search', false, 'regularize_pf_only', true);
            if pfFailed || ~isfinite(pfResidual)
                error('toyRoad:PhaseSolveFailed', ...
                    'Phase-field solve failed at cycle %d step %d.', cycle, iStep);
            end
            p_field = min(max(p_field, p_field_old), 1.0);
            if iStag == 1
                firstPfResidual = initialPfResidual;
            end

            [stagVars, rawDriverGp, stagConverged, sys.STIFFNESS_MATRIX.KK] = ...
                operators.stag_post_iter_update( ...
                context.assembly_equilibrium_fh, iStag, stagVars, sys, ...
                tractionIncrement, p_field, displ, firstPfResidual, pfResidual, ...
                initialDisplResidual, context.sol_stag_par);
            if stagConverged
                p_field_old = p_field;
                [~, ~, ~, history_vars_old] = context.assembly_pf_fh( ...
                    sys.MESH, sys.DOFS, sys.GEOM.t, sys.QUADRATURE, ...
                    sys.MAT_CHAR, sys.CC, p_field, p_field_old, rawDriverGp, ...
                    sys.stress_state.as_number, history_vars_old);
                break;
            end
        end
        if ~stagConverged
            error('toyRoad:StaggeredSolveFailed', ...
                'Staggered solve failed at cycle %d step %d.', cycle, iStep);
        end

        if iStep == peakOrdinal
            rawStep = 5 * (cycle - 1) + peakOrdinal;
            [~, reactionVector, peakRawDriverGp, ~] = ...
                context.assembly_equilibrium_fh( ...
                sys.MESH, sys.DOFS, sys.GEOM.t, sys.QUADRATURE, ...
                sys.MAT_CHAR, sys.CC, displ, 0.0, p_field, ...
                sys.stress_state.as_number, 0.0);
            reactionVector = reactionVector - tractionIncrement;
            peakDamage = p_field;
            exportInput = localPeakExportInput(context, displ, peakDamage, ...
                history_vars_old, peakRawDriverGp, reactionVector, ...
                cycle, cycleUmax, peakOrdinal, rawStep);
            exportedState = operators.export_peak_state(exportInput, context.output_root);
            eventState = operators.advance_event(eventState, ...
                sys.MESH.node, sys.MESH.elem(:, 1:sys.MESH.nel), cycle, peakDamage);
            relativeStateFile = exportedState.cycle_index.file;
            localAppendCycleIndex(indexPath, exportedState.cycle_index, eventState);
            terminalCycle = cycle;
            terminalStateFile = string(relativeStateFile);
            peakCaptured = true;
            stopAfterCycle = ~isnan(eventState.confirmed) || cycle == context.cfg.censor_cap;
        end
    end

    if ~peakCaptured
        error('toyRoad:PeakCaptureFailed', ...
            'Cycle %d completed without a converged ordinal-4 peak export.', cycle);
    end
    if stopAfterCycle
        break;
    end
end

if ~isnan(eventState.confirmed)
    terminalReason = 'confirmed';
else
    terminalReason = 'right_censored';
end
eventMetadata = struct( ...
    'case_id', context.cfg.case_id, ...
    'censor_cap', context.cfg.censor_cap, ...
    'confirmation_cycles', context.cfg.event_contract.confirmation_cycles, ...
    'confirmed', localFiniteOrEmpty(eventState.confirmed), ...
    'cycle_index_file', 'cycle_index.csv', ...
    'event_rule', context.cfg.event_contract.event_rule, ...
    'first_hit', localFiniteOrEmpty(eventState.first_hit), ...
    'status', 'terminal_metadata', ...
    'terminal_cycle', terminalCycle, ...
    'terminal_reason', terminalReason, ...
    'terminal_state_file', terminalStateFile);
operators.write_json(fullfile(context.output_root, 'EVENT_METADATA.json'), eventMetadata);

result = struct( ...
    'case_id', context.cfg.case_id, ...
    'complete', true, ...
    'status', 'complete', ...
    'terminal_cycle', terminalCycle, ...
    'terminal_reason', terminalReason, ...
    'terminal_state_file', terminalStateFile);
operators.write_json(fullfile(context.output_root, 'RUN_RESULT.json'), result);
end

function operators = localResolveOperators(context)
operators = struct( ...
    'pre_iter_update', @phase_field.fem.solver.step.pre_iter_update, ...
    'stag_vars', @phase_field.fem.solver.stag.vars, ...
    'newton_raphson', @phase_field.fem.solver.newton_raphson, ...
    'stag_post_iter_update', @phase_field.fem.solver.stag.post_iter_update, ...
    'export_peak_state', @export_toy_road_peak_state, ...
    'advance_event', @advance_toy_road_event, ...
    'write_json', @write_toy_road_json);
if isfield(context, 'operators')
    names = fieldnames(context.operators);
    for index = 1:numel(names)
        if ~isfield(operators, names{index}) || ...
                ~isa(context.operators.(names{index}), 'function_handle')
            error('toyRoad:InvalidSolverContext', ...
                'Unknown or invalid controlled operator: %s.', names{index});
        end
        operators.(names{index}) = context.operators.(names{index});
    end
end
end

function localPublishFailure(context, operators, exception)
runPath = fullfile(context.output_root, 'RUN_RESULT.json');
if isfile(runPath)
    validate_toy_road_run_result(runPath, context.cfg.case_id);
    return;
end
eventPath = fullfile(context.output_root, 'EVENT_METADATA.json');
if ~isfile(eventPath)
    event = struct( ...
        'case_id', context.cfg.case_id, ...
        'confirmed', [], ...
        'first_hit', [], ...
        'status', 'failed');
    operators.write_json(eventPath, event);
end
failure = struct( ...
    'case_id', context.cfg.case_id, ...
    'complete', false, ...
    'error_identifier', exception.identifier, ...
    'error_message', exception.message, ...
    'status', 'failed');
operators.write_json(runPath, failure);
end

function input = localPeakExportInput(context, displ, pField, historyVars, ...
        rawDriverGp, reactionVector, cycle, cycleUmax, peakOrdinal, rawStep)
sys = context.sys;
input = struct( ...
    'displ', displ, ...
    'p_field', pField, ...
    'history_vars', historyVars, ...
    'psi_raw_gp', rawDriverGp, ...
    'node_coords', sys.MESH.node, ...
    'connectivity', sys.MESH.elem(:, 1:sys.MESH.nel), ...
    'quadrature_points', sys.QUADRATURE.gauss_pts, ...
    'quadrature_weights', sys.QUADRATURE.gauss_W, ...
    'reaction_vector', reactionVector, ...
    'top_node_ids', context.top_node_ids, ...
    'bottom_node_ids', context.bottom_node_ids, ...
    'metadata', struct( ...
        'cycle', cycle, ...
        'Umax_N', cycleUmax, ...
        'peak_substep_ordinal', peakOrdinal, ...
        'n_substeps', 5, ...
        'raw_step_1_based', rawStep, ...
        'branch', 'loading_peak', ...
        'phase', 'cycle_peak', ...
        'state_semantics_id', 'cycle_peak_coherent_v1', ...
        'mesh_ordering_id', 'q4_node_connectivity_1_based_v1', ...
        'state_ordering_id', 'component_blocked_u_then_v_v1'), ...
    'validation_tolerances', struct( ...
        'range', 1e-10, 'active_identity', 1e-12, 'irreversibility', 1e-10));
end

function localCreateCycleIndex(indexPath)
if isfile(indexPath) || isfolder(indexPath)
    error('toyRoad:CycleIndexExists', ...
        'Refusing to overwrite existing cycle index: %s', indexPath);
end
try
    created = java.io.File(indexPath).createNewFile();
catch exception
    error('toyRoad:CycleIndexWriteFailed', ...
        'Cannot create cycle index: %s', exception.message);
end
if ~created
    error('toyRoad:CycleIndexExists', ...
        'Refusing to overwrite existing cycle index: %s', indexPath);
end
fileId = fopen(indexPath, 'wt');
if fileId == -1
    error('toyRoad:CycleIndexWriteFailed', 'Cannot open cycle index: %s', indexPath);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, ['cycle,Umax_N,peak_substep_ordinal,raw_step_1_based,' ...
    'branch,phase,file,mesh_sha256,event_hit,first_hit,' ...
    'consecutive_post_hit,confirmed\n']);
end

function localAppendCycleIndex(indexPath, cycleIndex, eventState)
fileId = fopen(indexPath, 'at');
if fileId == -1
    error('toyRoad:CycleIndexWriteFailed', 'Cannot append cycle index: %s', indexPath);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%d,%.17g,%d,%d,%s,%s,%s,%s,%d,%s,%d,%s\n', ...
    cycleIndex.cycle, cycleIndex.Umax_N, cycleIndex.peak_substep_ordinal, ...
    cycleIndex.raw_step_1_based, char(cycleIndex.branch), char(cycleIndex.phase), ...
    char(cycleIndex.file), char(cycleIndex.mesh_sha256), eventState.hit, ...
    localCsvInteger(eventState.first_hit), eventState.consecutive_post_hit, ...
    localCsvInteger(eventState.confirmed));
end

function value = localCsvInteger(number)
if isnan(number)
    value = '';
else
    value = sprintf('%d', number);
end
end

function value = localFiniteOrEmpty(number)
if isnan(number)
    value = [];
else
    value = number;
end
end

function localValidateContext(context)
required = {'cfg', 'output_root', 'sys', 'sol_par', 'sol_stag_par', ...
    'sol_step_template', 'assembly_pf_fh', 'assembly_equilibrium_fh', ...
    'displ', 'p_field', 'p_field_old', 'history_vars_old', ...
    'top_node_ids', 'bottom_node_ids'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, required)) || ~isfolder(context.output_root)
    error('toyRoad:InvalidSolverContext', ...
        'Solver context is incomplete or output_root is not an existing directory.');
end
if context.sol_par.tol_displ ~= 1e-6 || ...
        context.sol_par.tol_p_field ~= 4e-4 || ...
        context.sol_stag_par.tol ~= 4e-4 || ...
        context.sol_step_template.line_search || ...
        context.cfg.n_step ~= 5 || context.cfg.censor_cap ~= 150
    error('toyRoad:InvalidSolverContext', 'Solver context violates locked numerics.');
end
end
