function metrics = validate_toy_road_state(state, previous)
%VALIDATE_TOY_ROAD_STATE Strictly validate one exported cycle-peak state.

if nargin < 2
    previous = [];
end
localRequire(isstruct(state) && isscalar(state), 'state must be a scalar struct.');

required = {'node_coords', 'connectivity', 'quadrature_points', ...
    'quadrature_weights', 'u', 'v', 'd_node', 'd_gp', ...
    'alpha_bar_gp', 'f_alpha_gp', 'psi_raw_gp', 'g_gp', 'psi_active_gp', ...
    'strain_gp', 'd_elem', 'alpha_bar_elem', 'f_alpha_elem', ...
    'psi_raw_elem', 'g_elem', 'psi_active_elem', 'strain_elem', ...
    'reaction_vector', 'top_node_ids', 'bottom_node_ids', ...
    'reaction_top_xy', 'reaction_bottom_xy', 'reaction_top_resultant', ...
    'reaction_bottom_resultant', 'crack_thresholds', 'crack_mask_elem', ...
    'cycle', 'Umax_N', 'peak_substep_ordinal', 'n_substeps', ...
    'raw_step_1_based', 'branch', 'phase', 'state_semantics_id', ...
    'mesh_ordering_id', 'state_ordering_id', 'mesh_sha256', ...
    'validation_tolerances', 'field_semantics', 'cycle_index'};
for index = 1:numel(required)
    localRequire(isfield(state, required{index}), ...
        'Missing state field %s.', required{index});
end
localRequire(localAllNumericFinite(state), 'Every numeric state field must be finite.');

tolerances = state.validation_tolerances;
localRequire(isstruct(tolerances) && isscalar(tolerances), ...
    'validation_tolerances must be a scalar struct.');
for name = {'range', 'active_identity', 'irreversibility'}
    localRequire(isfield(tolerances, name{1}), ...
        'Missing validation tolerance %s.', name{1});
    value = tolerances.(name{1});
    localRequire(isnumeric(value) && isreal(value) && isscalar(value) && ...
        isfinite(value) && value >= 0, ...
        'Validation tolerance %s must be nonnegative and finite.', name{1});
end
rangeTolerance = tolerances.range;
identityTolerance = tolerances.active_identity;

nodeCount = size(state.node_coords, 1);
elementCount = size(state.connectivity, 1);
gpCount = size(state.d_gp, 2);
localRequire(size(state.node_coords, 2) == 2 && nodeCount > 0, ...
    'node_coords must be N-by-2.');
localRequire(size(state.connectivity, 2) == 4 && elementCount > 0 && ...
    all(state.connectivity == floor(state.connectivity), 'all') && ...
    all(state.connectivity >= 1, 'all') && ...
    all(state.connectivity <= nodeCount, 'all'), ...
    'connectivity must be valid one-based Q4 connectivity.');
localRequire(isequal(size(state.u), [nodeCount 1]) && ...
    isequal(size(state.v), [nodeCount 1]) && ...
    isequal(size(state.d_node), [nodeCount 1]), ...
    'Nodal fields must be N-by-1 columns.');
localRequire(isequal(size(state.reaction_vector), [2 * nodeCount 1]), ...
    'reaction_vector must be a component-blocked 2N-by-1 column.');
localValidateNodeIds(state.top_node_ids, nodeCount, 'top_node_ids');
localValidateNodeIds(state.bottom_node_ids, nodeCount, 'bottom_node_ids');
localRequire(isequal(size(state.reaction_top_xy), [1 2]) && ...
    isequal(size(state.reaction_bottom_xy), [1 2]), ...
    'Top and bottom reaction components must be 1-by-2 [x y] arrays.');
localRequire(isnumeric(state.reaction_top_resultant) && ...
    isreal(state.reaction_top_resultant) && isscalar(state.reaction_top_resultant) && ...
    isnumeric(state.reaction_bottom_resultant) && ...
    isreal(state.reaction_bottom_resultant) && isscalar(state.reaction_bottom_resultant), ...
    'Top and bottom reaction resultants must be real numeric scalars.');
localRequire(isequal(size(state.quadrature_points), [gpCount 2]) && ...
    numel(state.quadrature_weights) == gpCount && ...
    all(state.quadrature_weights > 0, 'all'), ...
    'Quadrature data must declare one positive weight per natural point.');

gpScalarFields = {'d_gp', 'alpha_bar_gp', 'f_alpha_gp', 'psi_raw_gp', ...
    'g_gp', 'psi_active_gp'};
for index = 1:numel(gpScalarFields)
    localRequire(isequal(size(state.(gpScalarFields{index})), ...
        [elementCount gpCount]), '%s must be element-by-GP.', gpScalarFields{index});
end
localRequire(isequal(size(state.strain_gp), [elementCount gpCount 3]), ...
    'strain_gp must be element-by-GP-by-3.');
elementScalarFields = {'d_elem', 'alpha_bar_elem', 'f_alpha_elem', ...
    'psi_raw_elem', 'g_elem', 'psi_active_elem'};
for index = 1:numel(elementScalarFields)
    localRequire(isequal(size(state.(elementScalarFields{index})), [elementCount 1]), ...
        '%s must be element-by-1.', elementScalarFields{index});
end
localRequire(isequal(size(state.strain_elem), [elementCount 3]), ...
    'strain_elem must be element-by-3.');

localCheckRange(state.d_node, 0, 1, rangeTolerance, 'd_node');
localCheckRange(state.d_gp, 0, 1, rangeTolerance, 'd_gp');
localCheckRange(state.d_elem, 0, 1, rangeTolerance, 'd_elem');
localCheckRange(state.f_alpha_gp, 0, 1, rangeTolerance, 'f_alpha_gp');
localCheckRange(state.f_alpha_elem, 0, 1, rangeTolerance, 'f_alpha_elem');
localCheckRange(state.g_gp, 0, 1, rangeTolerance, 'g_gp');
localCheckRange(state.g_elem, 0, 1, rangeTolerance, 'g_elem');
localRequire(all(state.alpha_bar_gp >= -rangeTolerance, 'all') && ...
    all(state.alpha_bar_elem >= -rangeTolerance, 'all'), ...
    'alpha_bar fields must be nonnegative within tolerance.');
localRequire(all(state.psi_raw_gp >= -rangeTolerance, 'all') && ...
    all(state.psi_raw_elem >= -rangeTolerance, 'all'), ...
    'psi_raw fields must be nonnegative within tolerance.');
localRequire(all(state.psi_active_gp >= -rangeTolerance, 'all') && ...
    all(state.psi_active_elem >= -rangeTolerance, 'all'), ...
    'psi_active fields must be nonnegative within tolerance.');

shapeFunctions = localQ4ShapeFunctions(state.quadrature_points);
expectedDamageGp = state.d_node(state.connectivity) * shapeFunctions.';
damageGpError = max(abs(state.d_gp - expectedDamageGp), [], 'all');
localRequire(damageGpError <= identityTolerance, ...
    'd_gp does not match native Q4 interpolation from d_node.');
expectedGGp = (1 - state.d_gp) .^ 2;
gGpError = max(abs(state.g_gp - expectedGGp), [], 'all');
localRequire(gGpError <= identityTolerance, ...
    'g_gp does not match (1-d_gp).^2.');
expectedActiveGp = state.g_gp .* state.psi_raw_gp;
expectedActiveElem = mean(expectedActiveGp, 2);
activeGpError = max(abs(state.psi_active_gp - expectedActiveGp), [], 'all');
activeElemError = max(abs(state.psi_active_elem - expectedActiveElem), [], 'all');
localRequire(activeGpError <= identityTolerance && activeElemError <= identityTolerance, ...
    'psi_active must be recomputed as mean(g_gp .* psi_raw_gp, 2).');
localRequire(max(abs(state.d_elem - mean(state.d_gp, 2)), [], 'all') <= identityTolerance, ...
    'd_elem does not match the native GP mean.');
localRequire(max(abs(state.alpha_bar_elem - mean(state.alpha_bar_gp, 2)), [], 'all') <= identityTolerance, ...
    'alpha_bar_elem does not match the native GP mean.');
localRequire(max(abs(state.f_alpha_elem - mean(state.f_alpha_gp, 2)), [], 'all') <= identityTolerance, ...
    'f_alpha_elem does not match the native GP mean.');
localRequire(max(abs(state.psi_raw_elem - mean(state.psi_raw_gp, 2)), [], 'all') <= identityTolerance, ...
    'psi_raw_elem does not match the native GP mean.');
localRequire(max(abs(state.g_elem - mean(state.g_gp, 2)), [], 'all') <= identityTolerance, ...
    'g_elem does not match the native GP mean.');
expectedStrainElem = reshape(mean(state.strain_gp, 2), elementCount, 3);
localRequire(max(abs(state.strain_elem - expectedStrainElem), [], 'all') <= identityTolerance, ...
    'strain_elem does not match the native GP mean.');

reactionX = state.reaction_vector(1:nodeCount);
reactionY = state.reaction_vector(nodeCount + 1:end);
expectedTopXy = [sum(reactionX(state.top_node_ids)) ...
    sum(reactionY(state.top_node_ids))];
expectedBottomXy = [sum(reactionX(state.bottom_node_ids)) ...
    sum(reactionY(state.bottom_node_ids))];
localRequire(max(abs(state.reaction_top_xy - expectedTopXy), [], 'all') <= identityTolerance && ...
    max(abs(state.reaction_bottom_xy - expectedBottomXy), [], 'all') <= identityTolerance, ...
    'Boundary reaction components do not match reaction_vector and node IDs.');
localRequire(abs(state.reaction_top_resultant - hypot(expectedTopXy(1), expectedTopXy(2))) <= ...
    identityTolerance && ...
    abs(state.reaction_bottom_resultant - hypot(expectedBottomXy(1), expectedBottomXy(2))) <= ...
    identityTolerance, ...
    'Boundary reaction resultants do not match hypot(x, y).');

localRequire(isequal(state.crack_thresholds, [0.50 0.75 0.90 0.95]), ...
    'Crack thresholds must be [0.50, 0.75, 0.90, 0.95].');
localRequire(islogical(state.crack_mask_elem) && ...
    isequal(size(state.crack_mask_elem), [elementCount 4]) && ...
    isequal(state.crack_mask_elem, state.d_elem >= state.crack_thresholds), ...
    'crack_mask_elem must be the declared element threshold comparison.');

localRequire(localPositiveInteger(state.cycle) && localPositiveInteger(state.n_substeps) && ...
    localPositiveInteger(state.peak_substep_ordinal) && ...
    state.peak_substep_ordinal <= state.n_substeps && ...
    localPositiveInteger(state.raw_step_1_based), ...
    'Cycle and raw-step metadata must contain valid positive integers.');
expectedRawStep = 1 + state.n_substeps * (state.cycle - 1) + ...
    (state.peak_substep_ordinal - 1);
localRequire(state.raw_step_1_based == expectedRawStep, ...
    'raw_step_1_based does not match the declared cycle/substep mapping.');
localRequire(strcmp(string(state.phase), "cycle_peak") && ...
    strcmp(string(state.branch), "loading_peak") && ...
    strcmp(string(state.state_semantics_id), "cycle_peak_coherent_v1"), ...
    'State phase, branch, or semantics ID is incoherent.');
localRequire(strcmp(string(state.mesh_ordering_id), ...
    "q4_node_connectivity_1_based_v1") && ...
    strcmp(string(state.state_ordering_id), ...
    "component_blocked_u_then_v_v1"), ...
    'Mesh or state ordering ID violates the declared contract.');
localRequire(isstruct(state.field_semantics) && isscalar(state.field_semantics) && ...
    isequal(state.field_semantics, localExpectedFieldSemantics()), ...
    'field_semantics does not match the declared nodal/GP/element contract.');

expectedMeshHash = localMeshSha256(state.node_coords, state.connectivity);
localRequire(strcmp(string(state.mesh_sha256), expectedMeshHash), ...
    'mesh_sha256 does not match coordinates and connectivity.');
localValidateCycleIndex(state);
if ~isempty(previous)
    localValidatePrevious(state, previous, tolerances.irreversibility);
end

metrics = struct( ...
    'is_valid', true, ...
    'cycle', state.cycle, ...
    'raw_step_1_based', state.raw_step_1_based, ...
    'mesh_sha256', string(state.mesh_sha256), ...
    'damage_min', min([state.d_node(:); state.d_gp(:); state.d_elem(:)]), ...
    'damage_max', max([state.d_node(:); state.d_gp(:); state.d_elem(:)]), ...
    'alpha_bar_min', min([state.alpha_bar_gp(:); state.alpha_bar_elem(:)]), ...
    'alpha_bar_max', max([state.alpha_bar_gp(:); state.alpha_bar_elem(:)]), ...
    'f_alpha_min', min([state.f_alpha_gp(:); state.f_alpha_elem(:)]), ...
    'f_alpha_max', max([state.f_alpha_gp(:); state.f_alpha_elem(:)]), ...
    'psi_raw_min', min([state.psi_raw_gp(:); state.psi_raw_elem(:)]), ...
    'psi_active_min', min([state.psi_active_gp(:); state.psi_active_elem(:)]), ...
    'active_identity_max_abs_error', max(activeGpError, activeElemError), ...
    'right_boundary_hit', state.connected_right_boundary_diagnostics.hit, ...
    'right_boundary_component_size', ...
        state.connected_right_boundary_diagnostics.connected_component_size);
end

function shapeFunctions = localQ4ShapeFunctions(points)
xi = points(:, 1);
eta = points(:, 2);
shapeFunctions = 0.25 * [(1 - xi) .* (1 - eta), ...
    (1 + xi) .* (1 - eta), (1 + xi) .* (1 + eta), ...
    (1 - xi) .* (1 + eta)];
end

function localValidateNodeIds(nodeIds, nodeCount, name)
localRequire(isnumeric(nodeIds) && isreal(nodeIds) && isrow(nodeIds) && ...
    ~isempty(nodeIds) && all(isfinite(nodeIds), 'all') && ...
    all(nodeIds == floor(nodeIds), 'all') && all(nodeIds >= 1, 'all') && ...
    all(nodeIds <= nodeCount, 'all') && numel(unique(nodeIds)) == numel(nodeIds), ...
    '%s must be a nonempty row of unique valid one-based node IDs.', name);
end

function semantics = localExpectedFieldSemantics()
semantics = struct( ...
    'node_coords', "nodal_coordinates", ...
    'connectivity', "element_q4_connectivity_1_based", ...
    'u', "nodal", 'v', "nodal", 'd_node', "nodal", ...
    'd_gp', "gauss_point_latent_fem_truth", ...
    'alpha_bar_gp', "gauss_point_latent_fem_truth", ...
    'f_alpha_gp', "gauss_point_latent_fem_truth", ...
    'psi_raw_gp', "gauss_point_latent_fem_truth", ...
    'g_gp', "gauss_point_latent_fem_truth", ...
    'psi_active_gp', "gauss_point_latent_fem_truth", ...
    'strain_gp', "gauss_point_latent_fem_truth", ...
    'd_elem', "element", 'alpha_bar_elem', "element_latent_fem_truth", ...
    'f_alpha_elem', "element_latent_fem_truth", ...
    'psi_raw_elem', "element_latent_fem_truth", ...
    'g_elem', "element_latent_fem_truth", ...
    'psi_active_elem', "element_latent_fem_truth", ...
    'strain_elem', "element_latent_fem_truth", ...
    'reaction_vector', "nodal_component_blocked_x_then_y", ...
    'reaction_top_xy', "boundary_resultant_xy", ...
    'reaction_bottom_xy', "boundary_resultant_xy", ...
    'reaction_top_resultant', "boundary_resultant_l2", ...
    'reaction_bottom_resultant', "boundary_resultant_l2", ...
    'crack_mask_elem', "element_binary_by_threshold");
end

function localValidateCycleIndex(state)
row = state.cycle_index;
localRequire(isstruct(row) && isscalar(row), 'cycle_index must be a scalar struct.');
required = {'cycle', 'Umax_N', 'peak_substep_ordinal', 'raw_step_1_based', ...
    'branch', 'phase', 'file', 'mesh_sha256', 'state_semantics_id', ...
    'mesh_ordering_id', 'state_ordering_id'};
for index = 1:numel(required)
    localRequire(isfield(row, required{index}), ...
        'Missing cycle_index field %s.', required{index});
end
localRequire(row.cycle == state.cycle && row.Umax_N == state.Umax_N && ...
    row.peak_substep_ordinal == state.peak_substep_ordinal && ...
    row.raw_step_1_based == state.raw_step_1_based && ...
    strcmp(string(row.branch), string(state.branch)) && ...
    strcmp(string(row.phase), string(state.phase)) && ...
    strcmp(string(row.mesh_sha256), string(state.mesh_sha256)) && ...
    strcmp(string(row.state_semantics_id), string(state.state_semantics_id)) && ...
    strcmp(string(row.mesh_ordering_id), string(state.mesh_ordering_id)) && ...
    strcmp(string(row.state_ordering_id), string(state.state_ordering_id)), ...
    'cycle_index does not match the exported state metadata.');
localRequire(strcmp(string(row.file), sprintf('states/cycle_%04d.mat', state.cycle)), ...
    'cycle_index.file does not name the canonical cycle shard.');
end

function localValidatePrevious(state, previous, irreversibilityTolerance)
localRequire(isstruct(previous) && isscalar(previous), ...
    'previous metadata/state must be a scalar struct.');
required = {'cycle', 'raw_step_1_based', 'mesh_sha256', 'n_substeps'};
for index = 1:numel(required)
    localRequire(isfield(previous, required{index}), ...
        'Missing previous field %s.', required{index});
end
localRequire(state.cycle == previous.cycle + 1, ...
    'Exported cycles must be consecutive.');
localRequire(state.n_substeps == previous.n_substeps && ...
    state.raw_step_1_based == previous.raw_step_1_based + state.n_substeps, ...
    'Exported raw steps must be consecutive under the locked cadence.');
localRequire(strcmp(string(state.mesh_sha256), string(previous.mesh_sha256)), ...
    'Mesh hash changed between consecutive states.');
if isfield(previous, 'd_node')
    localRequire(isequal(size(previous.d_node), size(state.d_node)) && ...
        all(state.d_node >= previous.d_node - irreversibilityTolerance, 'all'), ...
        'Nodal damage violated the declared irreversibility tolerance.');
end
if isfield(previous, 'alpha_bar_gp')
    localRequire(isequal(size(previous.alpha_bar_gp), size(state.alpha_bar_gp)) && ...
        all(state.alpha_bar_gp >= previous.alpha_bar_gp - irreversibilityTolerance, 'all'), ...
        'GP alpha_bar violated the declared irreversibility tolerance.');
end
end

function localCheckRange(value, lower, upper, tolerance, name)
localRequire(all(value >= lower - tolerance, 'all') && ...
    all(value <= upper + tolerance, 'all'), ...
    '%s lies outside [%g, %g] beyond tolerance.', name, lower, upper);
end

function value = localPositiveInteger(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 1 && value == floor(value);
end

function value = localAllNumericFinite(input)
value = true;
if isstruct(input)
    names = fieldnames(input);
    for index = 1:numel(names)
        value = value && localAllNumericFinite(input.(names{index}));
    end
elseif isnumeric(input)
    value = isreal(input) && all(isfinite(input), 'all');
end
end

function digest = localMeshSha256(coords, connectivity)
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(typecast(double(coords(:)), 'uint8'));
hasher.update(typecast(int64(connectivity(:)), 'uint8'));
digestBytes = typecast(hasher.digest(), 'uint8');
digest = lower(string(reshape(dec2hex(digestBytes, 2).', 1, [])));
end

function localRequire(condition, message, varargin)
if ~condition
    error('toyRoad:StateValidationFailed', message, varargin{:});
end
end
