function input = build_q1_native_input(sourceRoot)
%BUILD_Q1_NATIVE_INPUT Construct the unrecovered native SENS hard-crack state.

if ~(ischar(sourceRoot) || (isstring(sourceRoot) && isscalar(sourceRoot))) || ...
        ~isfolder(sourceRoot)
    error('rebuiltMexQ1:InvalidNativeInput', ...
        'sourceRoot must be the locked GRIPHFiTH checkout.');
end
sourceRoot = char(sourceRoot);
sourcesPath = fullfile(sourceRoot, 'Sources');
meshPath = fullfile(sourceRoot, 'Dependencies', 'meshes', 'sens_mesh.m');
if ~isfolder(sourcesPath) || ~isfile(meshPath)
    error('rebuiltMexQ1:InvalidNativeInput', ...
        'The locked GRIPHFiTH source or native SENS mesh is absent.');
end
addpath(sourcesPath, '-begin');

[MESH, GEOM] = specimen.external.gmsh_import(meshPath, 't', 1.0);
tolerance = 1e-12;
topNodeIds = find(abs(MESH.node(:, 2) - 0.5) <= tolerance);
bottomNodeIds = find(abs(MESH.node(:, 2) + 0.5) <= tolerance);
crackNodeIds = find(abs(MESH.node(:, 2)) <= tolerance & ...
    MESH.node(:, 1) <= tolerance);
if isempty(topNodeIds) || isempty(bottomNodeIds) || isempty(crackNodeIds)
    error('rebuiltMexQ1:InvalidNativeInput', ...
        'The native SENS boundary or hard-crack node set is empty.');
end
nodeBoundaries = phase_field.fem.bc.set_boundaries( ...
    'fix_X', [bottomNodeIds; topNodeIds], ...
    'fix_Y', bottomNodeIds, 'disp_Y', topNodeIds, ...
    'non_hom_pf', crackNodeIds);
DOFS = phase_field.init.dofs(MESH, nodeBoundaries);
QUADRATURE = phase_field.init.quadrature(MESH.dim);
MAT_CHAR(1) = phase_field.init.material_characteristic( ...
    GEOM.L, 'AT1', 'E', 1.0, 'ni', 0.3, 'Gc', 0.01, 'ell', 0.01, ...
    'res_stiff', 0.0, 'alpha_T', 0.5, 'p', 2.0);
stressState = phase_field.StressState.PlaneStrain;
CC = phase_field.init.elastic_stiffness_matrix( ...
    [MAT_CHAR.E], [MAT_CHAR.ni], numel(MAT_CHAR), stressState);
fieldVars = zeros(MESH.num_node, 1);
fieldVars(crackNodeIds) = 1.0;

input = struct('MESH', MESH, 'DOFS', DOFS, 't', GEOM.t, ...
    'QUADRATURE', QUADRATURE, 'MAT_CHAR', MAT_CHAR, 'CC', CC, ...
    'field_vars', fieldVars, 'top_node_ids', topNodeIds(:), ...
    'crack_node_ids', crackNodeIds(:), ...
    'state_semantics', 'unrecovered_native_sens_hard_crack');
end
