function receipt = build_q2_final_receipt(runtime, parent, replay, metrics, ...
        maskArtifact, outputRoot)
%BUILD_Q2_FINAL_RECEIPT Bind Q2 artifacts to runtime/source/parent identity.

validateInputs(runtime, parent, replay, metrics, maskArtifact, outputRoot);
artifacts = struct( ...
    'state', artifactRecord(outputRoot, 'Q2_CYCLE1_STATE.mat'), ...
    'terminal', artifactRecord(outputRoot, 'Q2_CYCLE1_TERMINAL.json'), ...
    'metrics', artifactRecord(outputRoot, 'Q2_METRICS.mat'), ...
    'parent_masks', artifactRecord(outputRoot, 'Q2_PARENT_MASKS.mat'));
artifacts.parent_masks.mask_set_sha256 = maskArtifact.mask_set_sha256;
artifacts.parent_masks = orderfields(artifacts.parent_masks);

receipt = orderfields(struct( ...
    'schema_version', 'rebuilt_initial_mex_q2_result_v2', ...
    'status', conditional(metrics.passed, 'passed', 'failed'), ...
    'passed', logical(metrics.passed), 'blockers', {{}}, ...
    'stage', 'cycle1_metric_gate', ...
    'runtime_lock_sha256', char(runtime.lock_sha256), ...
    'runtime_initial_sha256', char(runtime.initial_sha256), ...
    'source_commit', char(runtime.source_commit), ...
    'q2_input_lock_sha256', char(parent.q2_input_lock_sha256), ...
    'parent_lock_sha256', char(parent.parent_lock_sha256), ...
    'parent_cycle1_sha256', char(parent.parent_cycle1_sha256), ...
    'parent_reference_id', char(parent.parent_reference_id), ...
    'mesh_ordering_sha256', char(replay.mesh_ordering_sha256), ...
    'replay_source_mesh_sha256', char(replay.replay_source_mesh_sha256), ...
    'replay_source_mesh_sha256_semantics', ...
    char(parent.replay_source_mesh_sha256_semantics), ...
    'parent_vtk_mesh_sha256', char(replay.parent_vtk_mesh_sha256), ...
    'parent_vtk_mesh_sha256_semantics', ...
    char(parent.parent_vtk_mesh_sha256_semantics), ...
    'mesh_bridge', replay.mesh_bridge, ...
    'mask_set_sha256', char(maskArtifact.mask_set_sha256), ...
    'q2_terminal_status', char(replay.status), ...
    'constructor_request', replay.constructor_request, ...
    'constructor_return', replay.constructor_return, ...
    'nominal_retained_factors', replay.nominal_retained_factors, ...
    'effective_retained_factors', replay.effective_retained_factors, ...
    'family_terminal_eligible', false, ...
    'metrics', metrics, 'artifacts', orderfields(artifacts)));
end

function validateInputs(runtime, parent, replay, metrics, maskArtifact, outputRoot)
runtimeFields = {'lock_sha256', 'initial_sha256', 'source_commit'};
parentFields = {'q2_input_lock_sha256', 'parent_lock_sha256', ...
    'parent_cycle1_sha256', 'parent_reference_id', ...
    'replay_source_mesh_sha256', 'replay_source_mesh_sha256_semantics', ...
    'parent_vtk_mesh_sha256', 'parent_vtk_mesh_sha256_semantics'};
replayFields = {'status', 'constructor_request', 'constructor_return', ...
    'nominal_retained_factors', 'effective_retained_factors', ...
    'mesh_ordering_sha256', 'replay_source_mesh_sha256', ...
    'parent_vtk_mesh_sha256', 'mesh_bridge'};
if ~isstruct(runtime) || ~all(isfield(runtime, runtimeFields)) || ...
        ~isstruct(parent) || ~all(isfield(parent, parentFields)) || ...
        ~isstruct(replay) || ~all(isfield(replay, replayFields)) || ...
        ~isstruct(metrics) || ...
        ~all(isfield(metrics, {'passed', 'mask_set_sha256'})) || ...
        ~isstruct(maskArtifact) || ...
        ~all(isfield(maskArtifact, {'relative_path', 'sha256', ...
        'mask_set_sha256'})) || ~isfolder(outputRoot)
    error('rebuiltMexQ2:InvalidFinalReceiptInput', ...
        'Q2 final receipt identities or artifacts are incomplete.');
end
if ~strcmp(replay.mesh_ordering_sha256, parent.replay_source_mesh_sha256) || ...
        ~strcmp(replay.replay_source_mesh_sha256, ...
        parent.replay_source_mesh_sha256) || ...
        ~strcmp(replay.parent_vtk_mesh_sha256, parent.parent_vtk_mesh_sha256) || ...
        ~isstruct(replay.mesh_bridge) || ...
        ~isfield(replay.mesh_bridge, 'passed') || ~replay.mesh_bridge.passed || ...
        ~strcmp(replay.mesh_bridge.replay_source_mesh_sha256, ...
        parent.replay_source_mesh_sha256) || ...
        ~strcmp(replay.mesh_bridge.parent_vtk_mesh_sha256, ...
        parent.parent_vtk_mesh_sha256) || ...
        ~strcmp(maskArtifact.mask_set_sha256, metrics.mask_set_sha256) || ...
        ~strcmp(maskArtifact.relative_path, 'Q2_PARENT_MASKS.mat') || ...
        ~strcmp(maskArtifact.sha256, sha256File(fullfile(outputRoot, ...
        maskArtifact.relative_path)))
    error('rebuiltMexQ2:FinalReceiptIdentityMismatch', ...
        'Q2 final receipt identity or mask artifact changed.');
end
end

function record = artifactRecord(root, relativePath)
path = fullfile(char(root), relativePath);
if ~isfile(path)
    error('rebuiltMexQ2:MissingFinalArtifact', ...
        'Required Q2 artifact is absent: %s.', relativePath);
end
details = dir(path);
record = orderfields(struct('relative_path', relativePath, ...
    'sha256', sha256File(path), 'bytes', details.bytes));
end

function digest = sha256File(path)
fileId = fopen(path, 'rb');
if fileId < 0
    error('rebuiltMexQ2:MissingFinalArtifact', ...
        'Unable to hash a required Q2 artifact.');
end
cleanup = onCleanup(@() fclose(fileId));
md = java.security.MessageDigest.getInstance('SHA-256');
while true
    bytes = fread(fileId, 1048576, '*uint8');
    if isempty(bytes)
        break
    end
    md.update(bytes);
end
digest = lower(reshape(dec2hex(typecast(md.digest(), 'uint8'), 2).', 1, []));
end

function value = conditional(condition, whenTrue, whenFalse)
if condition
    value = whenTrue;
else
    value = whenFalse;
end
end
