function metrics = compare_q1_initial_outputs(reference, candidate, input)
%COMPARE_Q1_INITIAL_OUTPUTS Apply the locked Q1 source-equivalence gates.

names = localOutputNames();
indexNames = {'i_row', 'j_col', 'i_row_sig', 'j_col_sig', ...
    'i_row_eps', 'j_col_eps', 'i_row_pf', 'j_col_pf'};
numericNames = {'M_vector', 'eps_vector', 'sig0_vector'};
localRequire(isequal(sort(fieldnames(reference)), sort(names)) && ...
    isequal(sort(fieldnames(candidate)), sort(names)), ...
    'The candidate and reference must contain exactly the 12 gateway outputs.');

expected = localExpectedShapes(input);
for index = 1:numel(names)
    name = names{index};
    localRequire(isnumeric(reference.(name)) && isreal(reference.(name)) && ...
        isnumeric(candidate.(name)) && isreal(candidate.(name)) && ...
        isequal(size(reference.(name)), expected.(name)) && ...
        isequal(size(candidate.(name)), expected.(name)) && ...
        all(isfinite(reference.(name)), 'all') && ...
        all(isfinite(candidate.(name)), 'all'), ...
        'Output %s has an invalid shape or nonfinite value.', name);
end

limits = struct('i_row', input.DOFS.num_dof, 'j_col', input.DOFS.num_dof, ...
    'i_row_sig', input.MESH.tensors * input.MESH.num_node, ...
    'j_col_sig', input.MESH.tensors * input.MESH.num_node, ...
    'i_row_eps', input.MESH.tensors * input.MESH.num_node, ...
    'j_col_eps', input.DOFS.num_dof, ...
    'i_row_pf', input.MESH.num_node, 'j_col_pf', input.MESH.num_node);
indexMetrics = repmat(struct('name', '', 'exact', false), numel(indexNames), 1);
for index = 1:numel(indexNames)
    name = indexNames{index};
    localRequire(all(reference.(name) == fix(reference.(name))) && ...
        all(candidate.(name) == fix(candidate.(name))) && ...
        all(reference.(name) >= 1 & reference.(name) <= limits.(name)) && ...
        all(candidate.(name) >= 1 & candidate.(name) <= limits.(name)), ...
        'Index output %s is outside its prescribed range.', name);
    indexMetrics(index).name = name;
    indexMetrics(index).exact = isequal(reference.(name), candidate.(name));
    localRequire(indexMetrics(index).exact, ...
        'Index output %s differs from the reference.', name);
end

numDof = input.DOFS.num_dof;
numStress = input.MESH.tensors * input.MESH.num_node;
referenceK = sparse(reference.i_row, reference.j_col, reference.K_vect, ...
    numDof, numDof);
candidateK = sparse(candidate.i_row, candidate.j_col, candidate.K_vect, ...
    numDof, numDof);
kDifference = candidateK - referenceK;
kMetric = struct( ...
    'shape', [numDof numDof], ...
    'reference_frobenius', norm(referenceK, 'fro'), ...
    'relative_frobenius', norm(kDifference, 'fro') / ...
        max(norm(referenceK, 'fro'), 1e-30), ...
    'max_absolute', localSparseMaxAbs(kDifference), ...
    'threshold', 1e-12);
localRequire(kMetric.relative_frobenius <= kMetric.threshold, ...
    'Global sparse stiffness exceeds the relative Frobenius gate.');

% Construct every prescribed sparse operator to validate exact dimensions.
referenceM = sparse(reference.i_row_sig, reference.j_col_sig, ...
    reference.M_vector, numStress, numStress);
candidateM = sparse(candidate.i_row_sig, candidate.j_col_sig, ...
    candidate.M_vector, numStress, numStress);
referenceEps = sparse(reference.i_row_eps, reference.j_col_eps, ...
    reference.eps_vector, numStress, numDof);
candidateEps = sparse(candidate.i_row_eps, candidate.j_col_eps, ...
    candidate.eps_vector, numStress, numDof);
referenceSig = sparse(reference.i_row_eps, reference.j_col_eps, ...
    reference.sig0_vector, numStress, numDof);
candidateSig = sparse(candidate.i_row_eps, candidate.j_col_eps, ...
    candidate.sig0_vector, numStress, numDof);
localRequire(isequal(size(referenceM), [numStress numStress]) && ...
    isequal(size(candidateM), [numStress numStress]) && ...
    isequal(size(referenceEps), [numStress numDof]) && ...
    isequal(size(candidateEps), [numStress numDof]) && ...
    isequal(size(referenceSig), [numStress numDof]) && ...
    isequal(size(candidateSig), [numStress numDof]), ...
    'A sparse projection operator has an invalid dimension.');

numericMetrics = repmat(struct('name', '', 'reference_l2', 0, ...
    'relative_l2', [], 'max_absolute', 0, 'identically_zero', false, ...
    'threshold', 0), numel(numericNames), 1);
for index = 1:numel(numericNames)
    name = numericNames{index};
    numericMetrics(index) = localNumericalMetric( ...
        name, reference.(name), candidate.(name));
    if numericMetrics(index).identically_zero
        localRequire(numericMetrics(index).max_absolute <= ...
            numericMetrics(index).threshold, ...
            'Numerical output %s exceeds its zero-reference gate.', name);
    else
        localRequire(numericMetrics(index).relative_l2 <= ...
            numericMetrics(index).threshold, ...
            'Numerical output %s exceeds its relative L2 gate.', name);
    end
end

localRequire(isfield(input, 'top_node_ids') && ...
    isnumeric(input.top_node_ids) && iscolumn(input.top_node_ids) && ...
    ~isempty(input.top_node_ids) && ...
    all(input.top_node_ids == fix(input.top_node_ids)) && ...
    all(input.top_node_ids >= 1 & input.top_node_ids <= input.MESH.num_node), ...
    'The fixed top-boundary node set is invalid.');
probeDisplacement = zeros(numDof, 1);
probeDisplacement(input.top_node_ids + input.MESH.num_node) = 0.03;
referenceProbe = referenceK * probeDisplacement;
candidateProbe = candidateK * probeDisplacement;
probeRelative = norm(candidateProbe - referenceProbe) / max(norm(referenceProbe), 1e-30);
probe = struct('name', 'deterministic_internal_force_probe', ...
    'top_y_value', 0.03, 'reference_l2', norm(referenceProbe), ...
    'relative_l2', probeRelative, ...
    'max_absolute', max(abs(candidateProbe - referenceProbe), [], 'all'), ...
    'threshold', 1e-12);
localRequire(probe.relative_l2 <= probe.threshold, ...
    'The deterministic internal-force probe exceeds its relative L2 gate.');

metrics = orderfields(struct('schema_version', 'rebuilt_initial_mex_q1_metrics_v1', ...
    'passed', true, 'output_shapes', expected, 'index_outputs', indexMetrics, ...
    'stiffness', kMetric, 'numerical_outputs', numericMetrics, 'probe', probe));
end

function metric = localNumericalMetric(name, reference, candidate)
difference = candidate - reference;
referenceNorm = norm(reference);
isZero = all(reference == 0);
metric = struct('name', name, 'reference_l2', referenceNorm, ...
    'relative_l2', [], 'max_absolute', max(abs(difference), [], 'all'), ...
    'identically_zero', isZero, 'threshold', 1e-12);
if isZero
    metric.threshold = 1e-14;
else
    metric.relative_l2 = norm(difference) / max(referenceNorm, 1e-30);
end
end

function value = localSparseMaxAbs(matrix)
values = nonzeros(matrix);
if isempty(values)
    value = 0;
else
    value = max(abs(values));
end
end

function expected = localExpectedShapes(input)
nel = input.MESH.nel;
numElements = input.MESH.num_elem;
numDofNode = input.DOFS.num_dof_node;
tensors = input.MESH.tensors;
kCount = numElements * (nel * numDofNode)^2;
mCount = numElements * tensors * nel^2;
operatorCount = numElements * tensors * nel^2 * numDofNode;
pfCount = numElements * nel^2;
expected = struct('K_vect', [kCount 1], 'i_row', [kCount 1], ...
    'j_col', [kCount 1], 'M_vector', [mCount 1], ...
    'i_row_sig', [mCount 1], 'j_col_sig', [mCount 1], ...
    'eps_vector', [operatorCount 1], 'i_row_eps', [operatorCount 1], ...
    'j_col_eps', [operatorCount 1], 'sig0_vector', [operatorCount 1], ...
    'i_row_pf', [pfCount 1], 'j_col_pf', [pfCount 1]);
end

function names = localOutputNames()
names = {'K_vect'; 'i_row'; 'j_col'; 'M_vector'; 'i_row_sig'; ...
    'j_col_sig'; 'eps_vector'; 'i_row_eps'; 'j_col_eps'; ...
    'sig0_vector'; 'i_row_pf'; 'j_col_pf'};
end

function localRequire(condition, message, varargin)
if ~condition
    error('rebuiltMexQ1:GateFailed', message, varargin{:});
end
end
