function receipt = compare_q2_cycle1_fields(parent, candidate, masks)
%COMPARE_Q2_CYCLE1_FIELDS Apply immutable Q2 cycle-1 field gates.
validateIdentity(parent, candidate);
validateCandidateSources(candidate);
expectedMasks = build_q2_parent_masks(parent);
if ~isequaln(masks, expectedMasks)
    error('rebuiltMexQ2:MaskIdentityMismatch', ...
        'Q2 masks, floors, tolerances, or parent identity changed.');
end

names = requiredFieldNames();
metrics = struct;
passed = true;
for index = 1:numel(names)
    name = names{index};
    reference = fieldValues(parent.fields.(name), parent.num_elem);
    observed = fieldValues(candidate.fields.(name), parent.num_elem);
    fieldMask = masks.fields.(name);
    if strcmp(name, 'damage')
        metric = damageMetrics(reference, observed, fieldMask, masks);
    elseif strcmp(name, 'fatigue_degradation')
        metric = fatigueMetrics(reference, observed, fieldMask, masks);
    else
        metric = logMetrics(reference, observed, fieldMask, masks);
    end
    metrics.(name) = metric;
    passed = passed && metric.passed;
end

receipt = orderfields(struct( ...
    'schema_version', 'rebuilt_initial_mex_q2_metrics_v1', ...
    'passed', passed, ...
    'parent_cycle1_sha256', char(parent.parent_cycle1_sha256), ...
    'mask_set_sha256', char(masks.mask_set_sha256), ...
    'log_transform', 'log10(max(q,0)+1e-14)', ...
    'fields', metrics));
if ~passed
    error('rebuiltMexQ2:GateFailed', ...
        'At least one immutable Q2 cycle-1 field gate failed.');
end
end

function validateIdentity(parent, candidate)
required = {'parent_cycle1_sha256', 'parent_reference_id', ...
    'mesh_ordering_sha256', 'num_elem', 'fields'};
if ~isstruct(candidate) || ~all(isfield(candidate, required)) || ...
        ~strcmp(candidate.parent_cycle1_sha256, parent.parent_cycle1_sha256) || ...
        ~strcmp(candidate.parent_reference_id, parent.parent_reference_id) || ...
        ~strcmp(candidate.mesh_ordering_sha256, parent.mesh_ordering_sha256) || ...
        candidate.num_elem ~= parent.num_elem
    error('rebuiltMexQ2:CandidateIdentityMismatch', ...
        'The Q2 candidate is not bound to the locked parent and ordering.');
end
names = requiredFieldNames();
if ~all(isfield(candidate.fields, names))
    error('rebuiltMexQ2:InvalidCandidateField', ...
        'A required Q2 candidate field is absent.');
end
end

function validateCandidateSources(candidate)
allowed = struct( ...
    'damage', {{'native:d_elem'}}, ...
    'history', {{'native:alpha_bar_elem'}}, ...
    'fatigue_degradation', {{'native:f_alpha_elem'}}, ...
    'raw', {{'native:psi_raw_elem', 'native:psi_elem'}}, ...
    'damage_degradation', {{'native:g_elem', 'sealed_gp:mean_gp(g_gp)'}}, ...
    'active', {{'native:psi_active_elem', ...
        'sealed_gp:mean_gp(g_gp.*psi_raw_gp)'}});
names = requiredFieldNames();
for index = 1:numel(names)
    name = names{index};
    field = candidate.fields.(name);
    if ~isstruct(field) || ~all(isfield(field, {'source', 'values'}))
        error('rebuiltMexQ2:InvalidCandidateField', ...
            'Q2 candidate field provenance is absent.');
    end
    if ~ismember(char(field.source), allowed.(name))
        if strcmp(name, 'active') || strcmp(name, 'damage_degradation')
            error('rebuiltMexQ2:ProhibitedFieldSubstitute', ...
                'Q2 g/active evidence uses a prohibited substitute.');
        end
        error('rebuiltMexQ2:InvalidCandidateField', ...
            'A Q2 candidate field mapping is not authoritative.');
    end
end
end

function values = fieldValues(field, n)
values = field.values;
if ~isnumeric(values) || ~isreal(values) || ~isequal(size(values), [n, 1]) || ...
        any(~isfinite(values))
    error('rebuiltMexQ2:InvalidCandidateField', ...
        'A Q2 field has invalid shape, type, or finite state.');
end
if any(values < -1e-14)
    error('rebuiltMexQ2:NegativeField', ...
        'A Q2 field is below the fixed negative tolerance before clipping.');
end
values = double(values(:));
end

function metric = damageMetrics(reference, candidate, fieldMask, limits)
difference = candidate - reference;
mae = mean(abs(difference));
rmse = sqrt(mean(difference .^ 2));
[correlation, correlationPass] = fixedCorrelation(reference, candidate, ...
    isZeroVariance(reference), 0.995, difference, limits);
[outsideMae, outsideMax, outsidePass] = outsideMetrics( ...
    difference, fieldMask.mask, limits);
metric = orderfields(struct( ...
    'mae', mae, 'rmse', rmse, 'correlation', correlation, ...
    'support_count', fieldMask.support_count, ...
    'outside_absolute_mae', outsideMae, ...
    'outside_absolute_max_error', outsideMax, ...
    'absolute_only', false, ...
    'passed', mae <= 0.002 && rmse <= 0.005 && ...
        correlationPass && outsidePass));
end

function metric = fatigueMetrics(reference, candidate, fieldMask, limits)
difference = candidate - reference;
mae = mean(abs(difference));
maxError = max(abs(difference));
referenceZero = isZeroVariance(reference);
[correlation, correlationPass] = fixedCorrelation(reference, candidate, ...
    referenceZero, 1, difference, limits);
[outsideMae, outsideMax, outsidePass] = outsideMetrics( ...
    difference, fieldMask.mask, limits);
metric = orderfields(struct( ...
    'absolute_mae', mae, 'absolute_max_error', maxError, ...
    'correlation', correlation, 'support_count', fieldMask.support_count, ...
    'outside_absolute_mae', outsideMae, ...
    'outside_absolute_max_error', outsideMax, ...
    'absolute_only', true, ...
    'passed', mae <= 1e-12 && maxError <= 1e-10 && ...
        correlationPass && outsidePass));
end

function metric = logMetrics(reference, candidate, fieldMask, limits)
support = fieldMask.mask;
difference = candidate - reference;
[outsideMae, outsideMax, outsidePass] = outsideMetrics( ...
    difference, support, limits);
if ~any(support)
    wholeMae = mean(abs(difference));
    wholeMax = max(abs(difference));
    metric = orderfields(struct( ...
        'log10_mae', NaN, 'log10_rmse', NaN, ...
        'log10_correlation', 'not_applicable_zero_variance', ...
        'support_count', 0, 'outside_absolute_mae', outsideMae, ...
        'outside_absolute_max_error', outsideMax, ...
        'absolute_only', true, ...
        'passed', wholeMae <= 1e-12 && wholeMax <= 1e-10));
    return
end
referenceSupport = reference(support);
candidateSupport = candidate(support);
referenceLog = log10(max(referenceSupport, 0) + 1e-14);
candidateLog = log10(max(candidateSupport, 0) + 1e-14);
logDifference = candidateLog - referenceLog;
logMae = mean(abs(logDifference));
logRmse = sqrt(mean(logDifference .^ 2));
[correlation, correlationPass] = fixedCorrelation( ...
    referenceLog, candidateLog, fieldMask.reference_zero_variance, ...
    0.99, candidateSupport - referenceSupport, limits);
metric = orderfields(struct( ...
    'log10_mae', logMae, 'log10_rmse', logRmse, ...
    'log10_correlation', correlation, ...
    'support_count', fieldMask.support_count, ...
    'outside_absolute_mae', outsideMae, ...
    'outside_absolute_max_error', outsideMax, ...
    'absolute_only', false, ...
    'passed', logMae <= 0.05 && logRmse <= 0.10 && ...
        correlationPass && outsidePass));
end

function [value, passed] = fixedCorrelation(reference, candidate, ...
        referenceZero, threshold, absoluteDifference, limits)
if referenceZero
    value = 'not_applicable_zero_variance';
    passed = mean(abs(absoluteDifference)) <= ...
        limits.outside_absolute_mae_limit && ...
        max(abs(absoluteDifference)) <= limits.outside_absolute_max_error_limit;
    return
end
if isZeroVariance(candidate)
    value = NaN;
    passed = false;
    return
end
matrix = corrcoef(reference, candidate);
value = matrix(1, 2);
passed = isfinite(value) && value >= threshold;
end

function value = isZeroVariance(values)
if isempty(values)
    value = true;
else
    value = max(values) - min(values) <= ...
        1e-14 * max(1, max(abs(values)));
end
end

function [mae, maxError, passed] = outsideMetrics(difference, support, limits)
outside = difference(~support);
if isempty(outside)
    mae = 0;
    maxError = 0;
else
    mae = mean(abs(outside));
    maxError = max(abs(outside));
end
passed = mae <= limits.outside_absolute_mae_limit && ...
    maxError <= limits.outside_absolute_max_error_limit;
end

function names = requiredFieldNames()
names = {'damage', 'history', 'fatigue_degradation', 'raw', ...
    'damage_degradation', 'active'};
end
