function state = export_q2_cycle1_fields(input)
%EXPORT_Q2_CYCLE1_FIELDS Export exact native/GP Q2 cycle-1 fields.

validateInput(input);
nElem = size(input.connectivity, 1);
meshSha256 = q2_replay_mesh_sha256(input.node_coords, input.connectivity);
if ~strcmp(meshSha256, input.parent_mesh_sha256)
    error('rebuiltMexQ2:ReplayMeshMismatch', ...
        'Q2 export mesh differs from the locked canonical parent mesh.');
end
shapeFunctions = q4ShapeFunctions(input.quadrature_points);
dGp = input.p_field(input.connectivity) * shapeFunctions.';
gGp = (1 - dGp) .^ 2 + input.eta;
activeGp = gGp .* input.psi_raw_GP;
alphaBarGp = input.history_vars(:, :, 2);
fAlphaGp = input.history_vars(:, :, 4);

state = orderfields(struct( ...
    'schema_version', 'rebuilt_initial_mex_q2_cycle1_state_v1', ...
    'cycle', 1, ...
    'peak_substep_ordinal', 4, ...
    'element_ids', int64(input.element_ids(:)), ...
    'connectivity', input.connectivity, ...
    'd_GP', dGp, ...
    'd_elem', mean(dGp, 2), ...
    'alpha_bar_GP', alphaBarGp, ...
    'alpha_bar_elem', mean(alphaBarGp, 2), ...
    'f_alpha_GP', fAlphaGp, ...
    'f_alpha_elem', mean(fAlphaGp, 2), ...
    'psi_raw_GP', input.psi_raw_GP, ...
    'psi_raw_elem', mean(input.psi_raw_GP, 2), ...
    'g_GP', gGp, ...
    'g_elem', mean(gGp, 2), ...
    'psi_active_GP', activeGp, ...
    'psi_active_elem', mean(activeGp, 2), ...
    'field_sources', fieldSources(), ...
    'active_semantics', 'mean_gp(g_gp.*psi_raw_gp)', ...
    'element_ordering', 'native_mesh_element_row_order_1_based_v1', ...
    'mesh_ordering_sha256', meshSha256, ...
    'family_terminal_eligible', false));

if numel(state.d_elem) ~= nElem
    error('rebuiltMexQ2:InvalidExportInput', ...
        'Q2 element ordering changed during export.');
end
end

function validateInput(input)
required = {'node_coords', 'connectivity', 'element_ids', 'quadrature_points', ...
    'p_field', 'history_vars', 'psi_raw_GP', 'eta', 'cycle', ...
    'peak_substep_ordinal', 'parent_mesh_sha256'};
if ~isstruct(input) || ~isscalar(input) || ~all(isfield(input, required))
    invalidInput('Q2 export input is incomplete.');
end
connectivity = input.connectivity;
nElem = size(connectivity, 1);
nGp = size(input.quadrature_points, 1);
if ~finiteReal(connectivity) || size(connectivity, 2) ~= 4 || nElem < 1 || ...
        any(connectivity ~= floor(connectivity), 'all') || ...
        any(connectivity < 1, 'all') || ...
        any(connectivity > numel(input.p_field), 'all')
    invalidInput('Q2 connectivity must be finite one-based Q4 ordering.');
end
if ~finiteReal(input.node_coords) || size(input.node_coords, 2) ~= 2 || ...
        size(input.node_coords, 1) ~= numel(input.p_field) || ...
        isempty(regexp(char(input.parent_mesh_sha256), ...
        '^[0-9a-f]{64}$', 'once'))
    invalidInput('Q2 node coordinates or parent mesh identity are invalid.');
end
if ~isa(input.element_ids, 'int64') || ...
        ~isequal(input.element_ids(:), int64((1:nElem)'))
    invalidInput('Q2 element IDs must preserve exact native row ordering.');
end
if ~finiteReal(input.quadrature_points) || ...
        size(input.quadrature_points, 2) ~= 2 || nGp < 1
    invalidInput('Q2 quadrature points are invalid.');
end
if ~finiteReal(input.p_field) || ~iscolumn(input.p_field) || ...
        any(input.p_field < -1e-14) || any(input.p_field > 1 + 1e-14)
    invalidInput('Q2 nodal damage is invalid.');
end
if ~finiteReal(input.history_vars) || ndims(input.history_vars) ~= 3 || ...
        size(input.history_vars, 1) ~= nElem || ...
        size(input.history_vars, 2) ~= nGp || ...
        size(input.history_vars, 3) < 4
    invalidInput('Q2 history fields are invalid.');
end
if ~finiteReal(input.psi_raw_GP) || ...
        ~isequal(size(input.psi_raw_GP), [nElem nGp]) || ...
        any(input.psi_raw_GP < -1e-14, 'all')
    invalidInput('Q2 raw GP driver is invalid.');
end
if ~isnumeric(input.eta) || ~isscalar(input.eta) || input.eta ~= 0 || ...
        input.cycle ~= 1 || input.peak_substep_ordinal ~= 4
    invalidInput('Q2 export is restricted to eta=0 cycle-1 ordinal-4 peak.');
end
end

function values = q4ShapeFunctions(points)
xi = points(:, 1);
eta = points(:, 2);
values = 0.25 * [(1-xi).*(1-eta), (1+xi).*(1-eta), ...
    (1+xi).*(1+eta), (1-xi).*(1+eta)];
end

function sources = fieldSources()
sources = struct( ...
    'd_elem', 'native:d_elem', ...
    'alpha_bar_elem', 'native:alpha_bar_elem', ...
    'f_alpha_elem', 'native:f_alpha_elem', ...
    'psi_raw_elem', 'native:psi_raw_elem', ...
    'g_elem', 'sealed_gp:mean_gp(g_gp)', ...
    'psi_active_elem', 'sealed_gp:mean_gp(g_gp.*psi_raw_gp)');
end

function value = finiteReal(value)
value = isnumeric(value) && isreal(value) && all(isfinite(value), 'all');
end

function invalidInput(message)
error('rebuiltMexQ2:InvalidExportInput', '%s', message);
end
