function candidate = q2_candidate_fields_from_state(parent, state)
%Q2_CANDIDATE_FIELDS_FROM_STATE Recover authoritative Q2 candidate fields.
fields = struct( ...
    'damage', struct('source', 'native:d_elem', 'values', state.d_elem), ...
    'history', struct('source', 'native:alpha_bar_elem', ...
    'values', state.alpha_bar_elem), ...
    'fatigue_degradation', struct('source', 'native:f_alpha_elem', ...
    'values', state.f_alpha_elem), ...
    'raw', struct('source', 'native:psi_raw_elem', ...
    'values', state.psi_raw_elem), ...
    'damage_degradation', struct('source', ...
    'sealed_gp:mean_gp(g_gp)', 'values', state.g_elem), ...
    'active', struct('source', ...
    'sealed_gp:mean_gp(g_gp.*psi_raw_gp)', ...
    'values', state.psi_active_elem));
candidate = struct( ...
    'parent_cycle1_sha256', parent.parent_cycle1_sha256, ...
    'parent_reference_id', parent.parent_reference_id, ...
    'mesh_ordering_sha256', state.mesh_ordering_sha256, ...
    'num_elem', parent.num_elem, 'fields', fields);
end
