function digest = q2_replay_mesh_sha256(coords, connectivity)
%Q2_REPLAY_MESH_SHA256 Canonical parent/replay mesh and ordering identity.

if ~isnumeric(coords) || ~isreal(coords) || size(coords, 2) ~= 2 || ...
        isempty(coords) || any(~isfinite(coords), 'all') || ...
        ~isnumeric(connectivity) || ~isreal(connectivity) || ...
        size(connectivity, 2) ~= 4 || isempty(connectivity) || ...
        any(~isfinite(connectivity), 'all') || ...
        any(connectivity ~= floor(connectivity), 'all') || ...
        any(connectivity < 1, 'all') || ...
        any(connectivity > size(coords, 1), 'all')
    error('rebuiltMexQ2:InvalidReplayMesh', ...
        'Q2 replay mesh must be finite one-based Q4 geometry and ordering.');
end
md = java.security.MessageDigest.getInstance('SHA-256');
md.update(typecast(double(coords(:)), 'uint8'));
md.update(typecast(int64(connectivity(:)), 'uint8'));
digest = lower(reshape(dec2hex(typecast(md.digest(), 'uint8'), 2).', 1, []));
end
