function [metrics, inputSha256, runtimeReceipt] = ...
        recompute_q1_initial_qualification_metrics(runtimeLockPath, ...
        runtimeRoot, sourceRoot)
%RECOMPUTE_Q1_INITIAL_QUALIFICATION_METRICS Rerun isolated canonical Q1.
runtimeReceipt = validate_runtime_lock(runtimeLockPath, runtimeRoot, sourceRoot);
resolve_q1_initial_runtime(runtimeReceipt, runtimeRoot);
input = build_q1_native_input(sourceRoot);
inputSha256 = hashInput(input);

[referenceValues{1:12}] = assemble_initial_reference_q4( ...
    input.MESH, input.DOFS, input.t, input.QUADRATURE, ...
    input.MAT_CHAR, input.CC, input.field_vars);
reference = cell2struct(referenceValues(:), outputNames(), 1);
[candidateValues{1:12}] = initial(input.MESH, input.DOFS, input.t, ...
    input.QUADRATURE, input.MAT_CHAR, input.CC, input.field_vars);
candidate = cell2struct(candidateValues(:), outputNames(), 1);
metrics = compare_q1_initial_outputs(reference, candidate, input);
end

function hash = hashInput(input)
hasher = java.security.MessageDigest.getInstance('SHA-256');
items = { ...
    'mesh_meta', [input.MESH.num_node input.MESH.num_elem input.MESH.nel ...
        input.MESH.dim input.MESH.tensors]; ...
    'node', input.MESH.node(:, 1:input.MESH.dim); ...
    'elem', input.MESH.elem(:, 1:input.MESH.nel); ...
    'material_id', input.MESH.elem_material_id(:); ...
    'dof_meta', [input.DOFS.num_dof input.DOFS.num_dof_node]; ...
    'thickness', input.t; ...
    'gauss_weights', input.QUADRATURE.gauss_W(:); ...
    'shape_derivatives', input.QUADRATURE.dNdxi; ...
    'shape_functions', input.QUADRATURE.Nxi; ...
    'constitutive', input.CC; ...
    'damage', input.field_vars(:); ...
    'top_nodes', input.top_node_ids(:)};
for index = 1:size(items, 1)
    updateBytes(hasher, unicode2native(items{index, 1}, 'UTF-8'));
    value = double(items{index, 2});
    updateBytes(hasher, typecast(uint64(size(value)), 'uint8'));
    updateBytes(hasher, typecast(value(:), 'uint8'));
end
updateBytes(hasher, typecast(double([input.MAT_CHAR.res_stiff]), 'uint8'));
hash = digestHex(hasher);
end

function updateBytes(hasher, bytes)
hasher.update(uint8(bytes(:)));
end

function hash = digestHex(hasher)
hash = lower(reshape(dec2hex(typecast(hasher.digest(), 'uint8'), 2).', 1, []));
end

function names = outputNames()
names = {'K_vect'; 'i_row'; 'j_col'; 'M_vector'; 'i_row_sig'; ...
    'j_col_sig'; 'eps_vector'; 'i_row_eps'; 'j_col_eps'; ...
    'sig0_vector'; 'i_row_pf'; 'j_col_pf'};
end
