function [sys, pField, pFieldOld, historyVars, recoveryResidual, audit] = ...
        recover_q2_parent_initial_state(input, operators)
%RECOVER_Q2_PARENT_INITIAL_STATE Reproduce historical parent recovery.

validateInput(input);
if nargin < 2
    operators = struct('newton_raphson', ...
        @phase_field.fem.solver.newton_raphson);
end
if ~isstruct(operators) || ~isscalar(operators) || ...
        ~isequal(fieldnames(operators), {'newton_raphson'}) || ...
        ~isa(operators.newton_raphson, 'function_handle')
    error('rebuiltMexQ2:InvalidRecoveryInput', ...
        'Q2 recovery requires the locked Newton API only.');
end

zeroRawDriver = zeros(input.num_elem, input.num_gauss_points);
[initialResidual, recoveryResidual, recoveredField, couplingVars, ...
    recoveredHistory, nonConverged] = operators.newton_raphson( ...
    input.assembly_pf_fh, input.sys, input.p_field, input.p_field_old, ...
    zeroRawDriver, input.history_vars_old, ...
    input.sys.DOFS.active_dof_pf, ...
    input.sys.STIFFNESS_MATRIX.i_row_pf, ...
    input.sys.STIFFNESS_MATRIX.j_col_pf, ...
    'max_iter', input.max_iter_pf, ...
    'res_tol', input.tol_p_field, ...
    'line_search', false, 'regularize_pf_only', true);

validateOutputs(input, initialResidual, recoveryResidual, recoveredField, ...
    couplingVars, recoveredHistory, nonConverged);
if nonConverged || ~isfinite(recoveryResidual)
    error('rebuiltMexQ2:RecoveryFailed', ...
        'Historical parent zero-load recovery did not converge.');
end

sys = input.sys;
pField = min(max(recoveredField, 0), 1);
pFieldOld = pField;
historyVars = recoveredHistory;
historyVars(:, :, 2:3) = 0;
historyVars(:, :, 4) = 1;
audit = orderfields(struct( ...
    'schema_version', 'rebuilt_initial_mex_q2_recovery_v1', ...
    'initial_residual', initialResidual, ...
    'recovery_residual', recoveryResidual, ...
    'recovery_projection', 'clip_[0,1]', ...
    'rebuild_sys_after_recovery', false, ...
    'reset_fatigue_after_recovery', true, ...
    'zero_load', true));
end

function validateInput(input)
required = {'sys', 'assembly_pf_fh', 'p_field', 'p_field_old', ...
    'history_vars_old', 'num_elem', 'num_gauss_points', ...
    'max_iter_pf', 'tol_p_field'};
if ~isstruct(input) || ~isscalar(input) || ~all(isfield(input, required)) || ...
        ~isa(input.assembly_pf_fh, 'function_handle') || ...
        (~isstruct(input.sys) && ~isa(input.sys, 'handle')) || ...
        ~hasMember(input.sys, 'DOFS') || ...
        ~hasMember(input.sys, 'STIFFNESS_MATRIX') || ...
        ~isfield(input.sys.DOFS, 'active_dof_pf') || ...
        ~isfield(input.sys.STIFFNESS_MATRIX, 'i_row_pf') || ...
        ~isfield(input.sys.STIFFNESS_MATRIX, 'j_col_pf')
    error('rebuiltMexQ2:InvalidRecoveryInput', ...
        'Historical parent recovery input is incomplete.');
end
if ~isnumeric(input.p_field) || ~iscolumn(input.p_field) || ...
        any(~isfinite(input.p_field)) || ...
        ~isequal(size(input.p_field_old), size(input.p_field)) || ...
        ~isnumeric(input.history_vars_old) || ...
        ~isequal(size(input.history_vars_old, 1), input.num_elem) || ...
        ~isequal(size(input.history_vars_old, 2), input.num_gauss_points) || ...
        size(input.history_vars_old, 3) < 4
    error('rebuiltMexQ2:InvalidRecoveryInput', ...
        'Historical parent recovery fields have invalid shapes.');
end
end

function value = hasMember(container, name)
value = (isstruct(container) && isfield(container, name)) || ...
    (isobject(container) && isprop(container, name));
end

function validateOutputs(input, initialResidual, finalResidual, field, ...
        coupling, history, failed)
if ~finiteScalar(initialResidual) || ...
        ~(isnumeric(finalResidual) && isscalar(finalResidual)) || ...
        ~isnumeric(field) || ~isreal(field) || ...
        ~isequal(size(field), size(input.p_field)) || any(~isfinite(field)) || ...
        ~isnumeric(coupling) || ~isequal(size(coupling), size(input.p_field)) || ...
        any(~isfinite(coupling)) || ...
        ~isnumeric(history) || ~isequal(size(history), size(input.history_vars_old)) || ...
        any(~isfinite(history), 'all') || ~islogical(failed) || ~isscalar(failed)
    error('rebuiltMexQ2:InvalidRecoveryOutput', ...
        'Historical parent recovery returned malformed fields.');
end
end

function value = finiteScalar(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end
