function receipt = run_q2_parent_cycle1_replay(config)
%RUN_Q2_PARENT_CYCLE1_REPLAY Gate and run one isolated parent replay cycle.

validateConfig(config);
outputRoot = char(config.output_root);
if isfile(outputRoot) || isfolder(outputRoot)
    error('rebuiltMexQ2:OutputExists', ...
        'Refusing to overwrite Q2 output root.');
end
[created, message] = mkdir(outputRoot);
if ~created
    error('rebuiltMexQ2:PublicationFailed', ...
        'Unable to create Q2 output root: %s', message);
end

handoff = fileparts(mfilename('fullpath'));
parentReceipt = validate_q2_parent_fields( ...
    fullfile(handoff, 'Q2_INPUT_LOCK.json'), ...
    config.parent_lock_path, config.parent_root, ...
    struct('blocker_output_path', fullfile(outputRoot, ...
    'Q2_PARENT_BLOCKER.json')));
if ~strcmp(parentReceipt.status, 'ready')
    receipt = blockedReceipt(parentReceipt);
    return
end

[masks, maskArtifact] = prepare_q2_parent_masks_for_replay( ...
    parentReceipt, outputRoot);
runtimeReceipt = validate_runtime_lock(config.runtime_lock_path, ...
    config.runtime_root, config.source_root);
resolve_q1_initial_runtime(runtimeReceipt, config.runtime_root);
[context, oldPath] = buildContext(config, outputRoot, runtimeReceipt, ...
    parentReceipt, maskArtifact);
try
    replay = solve_q2_parent_cycle1(context);
catch exception
    path(oldPath);
    rethrow(exception);
end
path(oldPath);

candidate = candidateFields(parentReceipt, replay.state);
metrics = compare_q2_cycle1_fields(parentReceipt, candidate, masks);
publishMatNoClobber(fullfile(outputRoot, 'Q2_METRICS.mat'), 'metrics', metrics);

receipt = build_q2_final_receipt(runtimeReceipt, parentReceipt, replay, ...
    metrics, maskArtifact, outputRoot);
publishJsonNoClobber(fullfile(outputRoot, 'Q2_RESULT.json'), receipt);
end

function validateConfig(config)
required = {'output_root', 'parent_root', 'parent_lock_path', ...
    'runtime_lock_path', 'runtime_root', 'source_root'};
if ~isstruct(config) || ~isscalar(config) || ...
        ~isequal(sort(fieldnames(config)), sort(required(:)))
    error('rebuiltMexQ2:InvalidConfig', ...
        'Q2 production config must contain only the sealed path fields.');
end
for index = 1:numel(required)
    value = config.(required{index});
    if ~(ischar(value) || (isstring(value) && isscalar(value))) || ...
            strlength(string(value)) == 0
        error('rebuiltMexQ2:InvalidConfig', ...
            'A required Q2 path is empty or malformed.');
    end
end
end

function receipt = blockedReceipt(parent)
receipt = orderfields(struct( ...
    'schema_version', 'rebuilt_initial_mex_q2_result_v1', ...
    'status', 'blocked', 'passed', false, ...
    'blockers', {parent.blockers}, ...
    'stage', 'parent_evidence_gate', ...
    'parent_cycle1_sha256', parent.parent_cycle1_sha256, ...
    'replay_source_mesh_sha256', parent.replay_source_mesh_sha256, ...
    'replay_source_mesh_sha256_semantics', ...
    parent.replay_source_mesh_sha256_semantics, ...
    'parent_vtk_mesh_sha256', parent.parent_vtk_mesh_sha256, ...
    'parent_vtk_mesh_sha256_semantics', ...
    parent.parent_vtk_mesh_sha256_semantics, ...
    'mesh_bridge_contract', parent.mesh_bridge_contract, ...
    'recovery_started', false, 'system_started', false, ...
    'newton_started', false, 'cycle_started', false, ...
    'family_terminal_eligible', false));
end

function [context, oldPath] = buildContext(config, outputRoot, runtimeReceipt, ...
        parentReceipt, maskArtifact)
sourceRoot = char(config.source_root);
sources = fullfile(sourceRoot, 'Sources');
dependencies = fullfile(sourceRoot, 'Dependencies');
if ~isfolder(sources) || ~isfolder(dependencies)
    error('rebuiltMexQ2:MissingSolverApi', ...
        'The locked GRIPHFiTH source runtime is incomplete.');
end
oldPath = path;
addpath(sources, genpath(dependencies));
pathGuard = onCleanup(@() path(oldPath));
requireSolverApis();

meshPath = fullfile(dependencies, 'meshes', 'sens_mesh.m');
[mesh, geom] = specimen.external.gmsh_import(meshPath, 't', 1.0);
connectivity = mesh.elem(:, 1:mesh.nel);
actualMeshSha256 = q2_replay_mesh_sha256(mesh.node, connectivity);
if ~strcmp(actualMeshSha256, parentReceipt.replay_source_mesh_sha256)
    error('rebuiltMexQ2:ReplayMeshMismatch', ...
        'Unmapped replay mesh/order differs from the locked clean source mesh.');
end
meshBridge = validate_q2_mesh_bridge(mesh.node(:, 1:2), connectivity, ...
    config.parent_root, parentReceipt.mesh_bridge_contract);
tolerance = 1e-12;
topNodeIds = find(abs(mesh.node(:, 2) - 0.5) <= tolerance);
bottomNodeIds = find(abs(mesh.node(:, 2) + 0.5) <= tolerance);
crackNodeIds = find(abs(mesh.node(:, 2)) <= tolerance & ...
    mesh.node(:, 1) <= tolerance);
nodeBoundaries = phase_field.fem.bc.set_boundaries( ...
    'fix_X', [bottomNodeIds; topNodeIds], 'fix_Y', bottomNodeIds, ...
    'disp_Y', topNodeIds, 'non_hom_pf', crackNodeIds);
dofs = phase_field.init.dofs(mesh, nodeBoundaries);
quadrature = phase_field.init.quadrature(mesh.dim);
stressState = phase_field.StressState.PlaneStrain;

matChar(1) = phase_field.init.material_characteristic( ...
    geom.L, 'AT1', 'E', 1, 'ni', 0.3, 'Gc', 0.01, 'ell', 0.01, ...
    'res_stiff', 0, 'alpha_T', 0.5, 'p', 2);
solPar = phase_field.fem.solver.params( ...
    'tol_displ', 1e-6, 'tol_p_field', 4e-4, ...
    'max_iter_displ', 250, 'max_iter_pf', 250);
solStagPar = phase_field.fem.solver.stag.params('tol', 4e-4, ...
    'max_iter', 1000);
constructorRequest = struct('n_step', 8, 'loading', 'cyclic', ...
    'discretization', 'loading', 'uy_final', 0.12, 'R', 0, ...
    'line_search', false);
solStepPar = phase_field.fem.solver.step.params( ...
    'n_step', constructorRequest.n_step, ...
    'loading', constructorRequest.loading, ...
    'discretization', constructorRequest.discretization, ...
    'uy_final', constructorRequest.uy_final, 'R', constructorRequest.R, ...
    'line_search', constructorRequest.line_search);
if solStepPar.n_step ~= 5
    error('rebuiltMexQ2:ReplayContractMismatch', ...
        'The locked n_step=8 constructor request did not return n_step=5.');
end

displ = zeros(dofs.num_dof, 1);
pField = zeros(mesh.num_node, 1);
pField(dofs.non_hom_dirichlet_bc_pf) = 1;
pFieldOld = zeros(size(pField));
historyVars = zeros(mesh.num_elem, quadrature.num_gauss_pts, 4);
assemblyPf = @phase_field.mex.fem.assembly.pf.AT1_HISTORY_FATIGUE;
assemblyEq = @phase_field.mex.fem.assembly.equilibrium.AMOR;
sys = phase_field.System(matChar, geom, quadrature, dofs, ...
    nodeBoundaries, solStepPar, mesh, stressState, pField, 'AT1');

recoveryInput = struct('sys', sys, 'assembly_pf_fh', assemblyPf, ...
    'p_field', pField, 'p_field_old', pFieldOld, ...
    'history_vars_old', historyVars, 'num_elem', mesh.num_elem, ...
    'num_gauss_points', quadrature.num_gauss_pts, ...
    'max_iter_pf', solPar.max_iter_pf, 'tol_p_field', solPar.tol_p_field);
[sys, pField, pFieldOld, historyVars, ~, recoveryAudit] = ...
    recover_q2_parent_initial_state(recoveryInput);
if recoveryAudit.rebuild_sys_after_recovery
    error('rebuiltMexQ2:ReplayContractMismatch', ...
        'Historical parent recovery must retain the pre-recovery System.');
end

contract = struct( ...
    'case_id', 'Q2_native_parent_cycle1', 'unmapped_mesh', true, ...
    'eta', 0, 'Umax', 0.12, 'R', 0, 'one_cycle_only', true, ...
    'constructor_request', constructorRequest, ...
    'constructor_return', solStepPar, ...
    'nominal_retained_factors', [0.25 0.5 0.75 1 0], ...
    'effective_retained_factors', cumsum(solStepPar.uy_increment) / 0.12, ...
    'peak_substep_ordinal', 4, 'rebuild_sys_after_recovery', false, ...
    'replay_source_mesh_sha256', actualMeshSha256, ...
    'parent_vtk_mesh_sha256', parentReceipt.parent_vtk_mesh_sha256, ...
    'mesh_bridge', meshBridge);
operators = struct( ...
    'pre_iter_update', @phase_field.fem.solver.step.pre_iter_update, ...
    'stag_vars', @phase_field.fem.solver.stag.vars, ...
    'newton_raphson', @phase_field.fem.solver.newton_raphson, ...
    'stag_post_iter_update', @phase_field.fem.solver.stag.post_iter_update, ...
    'assembly_pf', assemblyPf, 'assembly_equilibrium', assemblyEq);
context = struct('output_root', outputRoot, 'contract', contract, ...
    'sys', sys, 'sol_par', solPar, 'sol_stag_par', solStagPar, ...
    'sol_step_par', solStepPar, 'assembly_pf_fh', assemblyPf, ...
    'assembly_equilibrium_fh', assemblyEq, 'displ', displ, ...
    'p_field', pField, 'p_field_old', pFieldOld, ...
    'history_vars_old', historyVars, 'operators', operators, ...
    'identity', struct( ...
    'runtime_lock_sha256', runtimeReceipt.lock_sha256, ...
    'runtime_initial_sha256', runtimeReceipt.initial_sha256, ...
    'source_commit', runtimeReceipt.source_commit, ...
    'q2_input_lock_sha256', parentReceipt.q2_input_lock_sha256, ...
    'parent_lock_sha256', parentReceipt.parent_lock_sha256, ...
    'parent_cycle1_sha256', parentReceipt.parent_cycle1_sha256, ...
    'mask_set_sha256', maskArtifact.mask_set_sha256, ...
    'mesh_ordering_sha256', actualMeshSha256, ...
    'replay_source_mesh_sha256', actualMeshSha256, ...
    'replay_source_mesh_sha256_semantics', ...
    parentReceipt.replay_source_mesh_sha256_semantics, ...
    'parent_vtk_mesh_sha256', parentReceipt.parent_vtk_mesh_sha256, ...
    'parent_vtk_mesh_sha256_semantics', ...
    parentReceipt.parent_vtk_mesh_sha256_semantics, ...
    'mesh_bridge', meshBridge), ...
    'path_guard', pathGuard);
end

function requireSolverApis()
required = {'phase_field.System', 'specimen.external.gmsh_import', ...
    'phase_field.init.material_characteristic', ...
    'phase_field.fem.bc.set_boundaries', 'phase_field.init.dofs', ...
    'phase_field.init.quadrature', 'phase_field.fem.solver.params', ...
    'phase_field.fem.solver.stag.params', ...
    'phase_field.fem.solver.stag.vars', ...
    'phase_field.fem.solver.step.params', ...
    'phase_field.fem.solver.step.pre_iter_update', ...
    'phase_field.fem.solver.stag.post_iter_update', ...
    'phase_field.fem.solver.newton_raphson', ...
    'phase_field.mex.fem.assembly.pf.AT1_HISTORY_FATIGUE', ...
    'phase_field.mex.fem.assembly.equilibrium.AMOR', 'initial', 'cholmod2'};
missing = required(cellfun(@(name) isempty(which(name)), required));
if ~isempty(missing)
    error('rebuiltMexQ2:MissingSolverApi', ...
        'A complete locked Q2 solver API is absent: %s', strjoin(missing, ', '));
end
end

function candidate = candidateFields(parent, state)
fields = struct( ...
    'damage', struct('source', 'native:d_elem', 'values', state.d_elem), ...
    'history', struct('source', 'native:alpha_bar_elem', ...
    'values', state.alpha_bar_elem), ...
    'fatigue_degradation', struct('source', 'native:f_alpha_elem', ...
    'values', state.f_alpha_elem), ...
    'raw', struct('source', 'native:psi_raw_elem', ...
    'values', state.psi_raw_elem), ...
    'damage_degradation', struct('source', ...
    'sealed_gp:mean_gp(g_gp)', 'values', state.g_elem), ...
    'active', struct('source', ...
    'sealed_gp:mean_gp(g_gp.*psi_raw_gp)', ...
    'values', state.psi_active_elem));
candidate = struct( ...
    'parent_cycle1_sha256', parent.parent_cycle1_sha256, ...
    'parent_reference_id', parent.parent_reference_id, ...
    'mesh_ordering_sha256', state.mesh_ordering_sha256, ...
    'num_elem', parent.num_elem, 'fields', fields);
end

function publishMatNoClobber(path, variableName, value)
if isfile(path) || isfolder(path)
    error('rebuiltMexQ2:OutputExists', 'Refusing to overwrite Q2 MAT artifact.');
end
payload = struct;
payload.(variableName) = value;
temporary = [tempname(fileparts(path)), '.mat'];
cleanup = onCleanup(@() deleteIfFile(temporary));
save(temporary, '-struct', 'payload', '-v7.3');
try
    java.nio.file.Files.createLink(java.io.File(path).toPath(), ...
        java.io.File(temporary).toPath());
catch exception
    error('rebuiltMexQ2:PublicationFailed', ...
        'Unable to publish Q2 MAT artifact: %s', exception.message);
end
end

function publishJsonNoClobber(path, value)
created = java.io.File(path).createNewFile();
if ~created
    error('rebuiltMexQ2:OutputExists', 'Refusing to overwrite Q2 result.');
end
fileId = fopen(path, 'w');
if fileId < 0
    delete(path);
    error('rebuiltMexQ2:PublicationFailed', 'Unable to publish Q2 result.');
end
cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, jsonencode(value, PrettyPrint=true), 'char');
end

function deleteIfFile(path)
if isfile(path)
    delete(path);
end
end
