function result = solve_q2_parent_cycle1(context)
%SOLVE_Q2_PARENT_CYCLE1 Run exactly one isolated parent replay cycle.

validateContext(context);
operators = context.operators;
factors = context.contract.effective_retained_factors;
stepPar = context.sol_step_par;
stepPar.n_step = 5;
stepPar.uy_final = 0.12;
stepPar.ux_increment = zeros(size(factors));
stepPar.uy_increment = 0.12 * diff([0 factors]);
stepPar.tx_increment = zeros(size(factors));
stepPar.ty_increment = zeros(size(factors));

sys = context.sys;
displ = context.displ;
pField = context.p_field;
pFieldOld = context.p_field_old;
historyVars = context.history_vars_old;
peakRawGp = [];
peakDamage = [];
peakHistory = [];

for iStep = 1:5
    [displ, ~, tractionIncrement] = operators.pre_iter_update( ...
        iStep, sys, displ, stepPar);
    stagVars = operators.stag_vars(context.sol_stag_par);
    stagConverged = false;
    for iStag = 1:context.sol_stag_par.max_iter
        [initialDisplResidual, displResidual, displ, rawDriverGp, ~, ...
            displFailed] = operators.newton_raphson( ...
            context.assembly_equilibrium_fh, sys, displ, 0, pField, 0, ...
            sys.DOFS.active_dof, sys.STIFFNESS_MATRIX.i_row, ...
            sys.STIFFNESS_MATRIX.j_col, 'D_RHS_tract', tractionIncrement, ...
            'max_iter', context.sol_par.max_iter_displ, ...
            'res_tol', context.sol_par.tol_displ, 'line_search', false);
        if displFailed || ~isfinite(displResidual)
            error('rebuiltMexQ2:DisplacementSolveFailed', ...
                'Q2 displacement solve failed at retained step %d.', iStep);
        end

        [initialPfResidual, pfResidual, pField, ~, ~, pfFailed] = ...
            operators.newton_raphson(context.assembly_pf_fh, sys, pField, ...
            pFieldOld, rawDriverGp, historyVars, sys.DOFS.active_dof_pf, ...
            sys.STIFFNESS_MATRIX.i_row_pf, ...
            sys.STIFFNESS_MATRIX.j_col_pf, ...
            'max_iter', context.sol_par.max_iter_pf, ...
            'res_tol', context.sol_par.tol_p_field, ...
            'line_search', false, 'regularize_pf_only', true);
        if pfFailed || ~isfinite(pfResidual)
            error('rebuiltMexQ2:PhaseSolveFailed', ...
                'Q2 phase solve failed at retained step %d.', iStep);
        end
        pField = min(max(pField, pFieldOld), 1);
        [stagVars, rawDriverGp, stagConverged, sys.STIFFNESS_MATRIX.KK] = ...
            operators.stag_post_iter_update( ...
            context.assembly_equilibrium_fh, iStag, stagVars, sys, ...
            tractionIncrement, pField, displ, initialPfResidual, pfResidual, ...
            initialDisplResidual, context.sol_stag_par);
        if stagConverged
            pFieldOld = pField;
            [~, ~, ~, historyVars] = operators.assembly_pf( ...
                sys.MESH, sys.DOFS, sys.GEOM.t, sys.QUADRATURE, ...
                sys.MAT_CHAR, sys.CC, pField, pFieldOld, rawDriverGp, ...
                sys.stress_state.as_number, historyVars);
            break
        end
    end
    if ~stagConverged
        error('rebuiltMexQ2:StaggeredSolveFailed', ...
            'Q2 staggered solve failed at retained step %d.', iStep);
    end
    if iStep == 4
        [~, ~, peakRawGp, ~] = operators.assembly_equilibrium( ...
            sys.MESH, sys.DOFS, sys.GEOM.t, sys.QUADRATURE, ...
            sys.MAT_CHAR, sys.CC, displ, 0, pField, ...
            sys.stress_state.as_number, 0);
        peakDamage = pField;
        peakHistory = historyVars;
    end
end

if isempty(peakRawGp)
    error('rebuiltMexQ2:PeakCaptureFailed', ...
        'Q2 cycle 1 did not capture retained ordinal 4.');
end
exportInput = struct( ...
    'connectivity', sys.MESH.elem(:, 1:sys.MESH.nel), ...
    'element_ids', int64((1:sys.MESH.num_elem)'), ...
    'quadrature_points', sys.QUADRATURE.gauss_pts, ...
    'p_field', peakDamage, 'history_vars', peakHistory, ...
    'psi_raw_GP', peakRawGp, 'eta', 0, 'cycle', 1, ...
    'peak_substep_ordinal', 4);
state = export_q2_cycle1_fields(exportInput);
statePath = fullfile(context.output_root, 'Q2_CYCLE1_STATE.mat');
publishStateNoClobber(statePath, state);

result = orderfields(struct( ...
    'schema_version', 'rebuilt_initial_mex_q2_cycle1_terminal_v1', ...
    'status', 'q2_cycle1_diagnostic_complete', ...
    'cycle', 1, ...
    'constructor_request', context.contract.constructor_request, ...
    'constructor_return', context.contract.constructor_return, ...
    'effective_retained_factors', factors, ...
    'peak_substep_ordinal', 4, ...
    'rebuild_sys_after_recovery', false, ...
    'family_terminal_eligible', false, ...
    'state_file', 'Q2_CYCLE1_STATE.mat'));
publishJsonNoClobber(fullfile(context.output_root, ...
    'Q2_CYCLE1_TERMINAL.json'), result);
result.state = state;
end

function validateContext(context)
required = {'output_root', 'contract', 'sys', 'sol_par', ...
    'sol_stag_par', 'sol_step_par', 'assembly_pf_fh', ...
    'assembly_equilibrium_fh', 'displ', 'p_field', 'p_field_old', ...
    'history_vars_old', 'operators'};
if ~isstruct(context) || ~isscalar(context) || ~all(isfield(context, required)) || ...
        ~isfolder(context.output_root)
    error('rebuiltMexQ2:InvalidReplayContext', ...
        'Q2 replay context is incomplete.');
end
validateContract(context.contract);
requiredOperators = {'pre_iter_update', 'stag_vars', 'newton_raphson', ...
    'stag_post_iter_update', 'assembly_pf', 'assembly_equilibrium'};
if ~isstruct(context.operators) || ...
        ~all(isfield(context.operators, requiredOperators))
    error('rebuiltMexQ2:MissingSolverApi', ...
        'Q2 replay lacks a complete locked solver API set.');
end
for index = 1:numel(requiredOperators)
    if ~isa(context.operators.(requiredOperators{index}), 'function_handle')
        error('rebuiltMexQ2:MissingSolverApi', ...
            'Q2 replay solver API is not callable.');
    end
end
if ~isa(context.assembly_pf_fh, 'function_handle') || ...
        ~isa(context.assembly_equilibrium_fh, 'function_handle')
    error('rebuiltMexQ2:MissingSolverApi', ...
        'Q2 replay assembly APIs are not callable.');
end
targets = {'Q2_CYCLE1_STATE.mat', 'Q2_CYCLE1_TERMINAL.json'};
for index = 1:numel(targets)
    if isfile(fullfile(context.output_root, targets{index})) || ...
            isfolder(fullfile(context.output_root, targets{index}))
        error('rebuiltMexQ2:OutputExists', ...
            'Refusing to overwrite Q2 replay artifact %s.', targets{index});
    end
end
end

function validateContract(contract)
required = {'case_id', 'unmapped_mesh', 'eta', 'Umax', 'R', ...
    'one_cycle_only', 'constructor_request', 'constructor_return', ...
    'effective_retained_factors', 'peak_substep_ordinal', ...
    'rebuild_sys_after_recovery'};
valid = isstruct(contract) && isscalar(contract) && all(isfield(contract, required));
if valid
    request = contract.constructor_request;
    returned = contract.constructor_return;
    valid = strcmp(contract.case_id, 'Q2_native_parent_cycle1') && ...
        isequal(contract.unmapped_mesh, true) && contract.eta == 0 && ...
        contract.Umax == 0.12 && contract.R == 0 && ...
        isequal(contract.one_cycle_only, true) && ...
        isstruct(request) && all(isfield(request, ...
        {'n_step', 'loading', 'discretization', 'R'})) && ...
        request.n_step == 8 && strcmp(request.loading, 'cyclic') && ...
        strcmp(request.discretization, 'loading') && request.R == 0 && ...
        isstruct(returned) && isfield(returned, 'n_step') && ...
        returned.n_step == 5 && ...
        isequal(contract.effective_retained_factors, ...
        [0.25 0.5 0.75 1.0 0.0]) && ...
        contract.peak_substep_ordinal == 4 && ...
        isequal(contract.rebuild_sys_after_recovery, false);
end
if ~valid
    error('rebuiltMexQ2:ReplayContractMismatch', ...
        ['Q2 requires nominal n_step=8 -> returned n_step=5 and the exact ' ...
        'historical retained factors.']);
end
end

function publishJsonNoClobber(path, value)
created = java.io.File(path).createNewFile();
if ~created
    error('rebuiltMexQ2:OutputExists', ...
        'Refusing to overwrite Q2 terminal artifact.');
end
fileId = fopen(path, 'w');
if fileId < 0
    delete(path);
    error('rebuiltMexQ2:PublicationFailed', ...
        'Unable to publish Q2 terminal artifact.');
end
cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, jsonencode(value, PrettyPrint=true), 'char');
end

function publishStateNoClobber(path, state)
if isfile(path) || isfolder(path)
    error('rebuiltMexQ2:OutputExists', ...
        'Refusing to overwrite Q2 cycle-1 state.');
end
temporary = [tempname(fileparts(path)), '.mat'];
cleanup = onCleanup(@() deleteIfFile(temporary));
save(temporary, '-struct', 'state', '-v7.3');
try
    java.nio.file.Files.createLink(java.io.File(path).toPath(), ...
        java.io.File(temporary).toPath());
catch exception
    error('rebuiltMexQ2:PublicationFailed', ...
        'Unable to publish Q2 cycle-1 state: %s', exception.message);
end
end

function deleteIfFile(path)
if isfile(path)
    delete(path);
end
end
