function receipt = validate_q2_mesh_bridge(sourceCoords, sourceConnectivity, ...
        parentRoot, contract)
%VALIDATE_Q2_MESH_BRIDGE Reconcile exact source mesh with VTK evidence.

validateContract(contract);
sourceDigest = q2_replay_mesh_sha256(sourceCoords, sourceConnectivity);
if ~strcmp(sourceDigest, contract.replay_source_mesh_sha256)
    error('rebuiltMexQ2:ReplaySourceMeshMismatch', ...
        'Imported replay mesh differs from the locked clean-source mesh.');
end

parent = read_q2_parent_vtk_mesh(parentRoot, ...
    contract.parent_vtk_relative_path);
if ~strcmp(parent.file_sha256, contract.parent_vtk_sha256) || ...
        ~strcmp(parent.mesh_sha256, contract.parent_vtk_mesh_sha256) || ...
        parent.num_node ~= contract.num_node || ...
        parent.num_elem ~= contract.num_elem
    error('rebuiltMexQ2:ParentVtkIdentityMismatch', ...
        'Parsed parent VTK evidence differs from the locked identity.');
end
if ~isequal(size(sourceCoords), size(parent.coords)) || ...
        ~isequal(size(sourceConnectivity), size(parent.connectivity)) || ...
        ~isequal(int64(sourceConnectivity), int64(parent.connectivity))
    error('rebuiltMexQ2:MeshBridgeConnectivityMismatch', ...
        'Source and parent VTK Q4 row/local-node ordering differ.');
end

difference = double(sourceCoords) - double(parent.coords);
maxError = max(abs(difference), [], 'all');
rmsError = sqrt(mean(difference(:) .^ 2));
if maxError > contract.coordinate_max_abs_tolerance || ...
        ~matchesReference(maxError, contract.reference_coordinate_max_abs_error) || ...
        ~matchesReference(rmsError, contract.reference_coordinate_rms_error)
    error('rebuiltMexQ2:MeshBridgeCoordinateMismatch', ...
        'Source/VTK coordinate bridge exceeds or differs from its sealed audit.');
end

receipt = orderfields(struct( ...
    'schema_version', 'rebuilt_initial_mex_q2_mesh_bridge_receipt_v1', ...
    'passed', true, ...
    'semantics_id', char(contract.semantics_id), ...
    'replay_source_mesh_sha256', sourceDigest, ...
    'replay_source_mesh_sha256_semantics', ...
    char(contract.replay_source_mesh_sha256_semantics), ...
    'parent_vtk_relative_path', char(contract.parent_vtk_relative_path), ...
    'parent_vtk_sha256', parent.file_sha256, ...
    'parent_vtk_mesh_sha256', parent.mesh_sha256, ...
    'parent_vtk_mesh_sha256_semantics', ...
    char(contract.parent_vtk_mesh_sha256_semantics), ...
    'connectivity_requirement', char(contract.connectivity_requirement), ...
    'connectivity_exact', true, ...
    'num_node', parent.num_node, 'num_elem', parent.num_elem, ...
    'coordinate_max_abs_tolerance', contract.coordinate_max_abs_tolerance, ...
    'coordinate_max_abs_error', maxError, ...
    'coordinate_rms_error', rmsError));
end

function validateContract(contract)
required = {'semantics_id', 'replay_source_mesh_sha256', ...
    'replay_source_mesh_sha256_semantics', 'parent_vtk_relative_path', ...
    'parent_vtk_sha256', 'parent_vtk_mesh_sha256', ...
    'parent_vtk_mesh_sha256_semantics', 'connectivity_requirement', ...
    'num_node', 'num_elem', 'coordinate_max_abs_tolerance', ...
    'reference_coordinate_max_abs_error', 'reference_coordinate_rms_error'};
digestSemantics = ...
    'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1';
valid = isstruct(contract) && isscalar(contract) && ...
    all(isfield(contract, required)) && ...
    strcmp(contract.semantics_id, 'q2_source_to_parent_vtk_mesh_bridge_v1') && ...
    strcmp(contract.replay_source_mesh_sha256_semantics, digestSemantics) && ...
    strcmp(contract.parent_vtk_mesh_sha256_semantics, digestSemantics) && ...
    strcmp(contract.connectivity_requirement, ...
    'exact_q4_row_and_local_node_order') && ...
    isSha256(contract.replay_source_mesh_sha256) && ...
    isSha256(contract.parent_vtk_sha256) && ...
    isSha256(contract.parent_vtk_mesh_sha256) && ...
    contract.num_node >= 1 && fix(contract.num_node) == contract.num_node && ...
    contract.num_elem >= 1 && fix(contract.num_elem) == contract.num_elem && ...
    isfinite(contract.coordinate_max_abs_tolerance) && ...
    contract.coordinate_max_abs_tolerance > 0 && ...
    isfinite(contract.reference_coordinate_max_abs_error) && ...
    contract.reference_coordinate_max_abs_error >= 0 && ...
    isfinite(contract.reference_coordinate_rms_error) && ...
    contract.reference_coordinate_rms_error >= 0;
if ~valid
    error('rebuiltMexQ2:InvalidMeshBridgeContract', ...
        'The Q2 source-to-parent VTK bridge contract is incomplete.');
end
end

function value = matchesReference(actual, expected)
value = abs(actual - expected) <= max(1e-30, 8 * eps(max(actual, expected)));
end

function value = isSha256(text)
value = (ischar(text) || isstring(text)) && ...
    ~isempty(regexp(char(text), '^[0-9a-f]{64}$', 'once'));
end
