function cfg = build_toy_road_family_case(caseId, parentMesh)
%BUILD_TOY_ROAD_FAMILY_CASE Construct one locked single-axis family case.

caseId = localCaseId(caseId);
parentMesh = localCanonicalParentMesh(parentMesh);
caseMesh = parentMesh;
changedAxes = cell(1,0);
if strcmp(caseId, 'T1_initial_defect')
    [caseMesh.node_coords, caseMesh.transfer_audit] = ...
        localApplyT1MeshTransfer(parentMesh.node_coords, ...
        parentMesh.connectivity, 0.01);
    caseMesh.mesh_sha256 = localMeshSha256( ...
        caseMesh.node_coords, caseMesh.connectivity);
    changedAxes = {'mesh.node_coords'};
end

material = struct( ...
    'E',1,'nu',0.3,'Gc',0.01,'ell',0.01,'alpha_T',0.5,'p',2, ...
    'eta',0,'plane_state','plane_strain','energy_split','AMOR', ...
    'phase_field_model','AT1_history_fatigue');
loading = struct( ...
    'blocks',[1 150 0.12], ...
    'load_factors',[0.25 0.50 0.75 1.00 0.00], ...
    'R',0, ...
    'boundary_condition','reverse_top_bottom_displacement');
if strcmp(caseId, 'T2_material_state')
    material.Gc = 0.008;
    changedAxes = {'material.Gc'};
elseif strcmp(caseId, 'T3_loading_history')
    loading.blocks = [1 30 0.108; 31 60 0.126; 61 150 0.120];
    changedAxes = {'loading.blocks'};
end

numerics = struct( ...
    'tol_displacement',1e-6, ...
    'tol_phase_field',4e-4, ...
    'tol_staggered',4e-4, ...
    'line_search',false, ...
    'cycle_jump',false, ...
    'checkpoint_resume',false, ...
    'right_censor_cap',150);
recovery = struct( ...
    'mode','hard_zero_load', ...
    'project_damage_bounds',[0 1], ...
    'rebuild_system_after_projection',true, ...
    'reset_post_recovery_fatigue_history',true);
event = struct( ...
    'right_boundary_x_min',0.48, ...
    'damage_threshold',0.95, ...
    'minimum_connected_nodes',3, ...
    'confirmation_cycles',3, ...
    'evaluate_at_peak_substep_ordinal',4);
physicalMesh = rmfield(caseMesh, intersect(fieldnames(caseMesh), ...
    {'transfer_audit'}));
casePhysics = struct( ...
    'mesh',physicalMesh, ...
    'material',material, ...
    'loading',loading, ...
    'numerics',numerics, ...
    'recovery',recovery, ...
    'event',event);

cfg = struct( ...
    'case_id',caseId, ...
    'changed_axes',{changedAxes}, ...
    'case_physics',casePhysics, ...
    'mesh',caseMesh, ...
    'sol_step_par',localFiveStepContract(loading.blocks(1,3), ...
        loading.load_factors), ...
    'sol_jump_par',struct('cycle_jump',false), ...
    'resume_allowed',false, ...
    'censor_cap',150, ...
    'umax_for_cycle',@(cycle) localUmaxForCycle( ...
        cycle, loading.blocks, 150), ...
    'advance_event',@(state,cycle,peakDamage) localAdvanceEvent( ...
        state, caseMesh.node_coords, caseMesh.connectivity, cycle, peakDamage));
end

function step = localFiveStepContract(umax,factors)
step = struct( ...
    'n_step',5, ...
    'loading','cyclic', ...
    'discretization','loading', ...
    'uy_final',umax, ...
    'R',0, ...
    'line_search',false, ...
    'ux_increment',zeros(1,5), ...
    'uy_increment',umax*diff([0 factors]), ...
    'tx_increment',zeros(1,5), ...
    'ty_increment',zeros(1,5));
end

function caseId = localCaseId(caseId)
validText = (ischar(caseId) && isrow(caseId)) || ...
    (isstring(caseId) && isscalar(caseId));
localRequire(validText, 'case_id must be scalar text.');
caseId = char(caseId);
roles = {'P0_parent','P0R_parent_repeat','T1_initial_defect', ...
    'T2_material_state','T3_loading_history'};
localRequire(any(strcmp(caseId, roles)), 'case_id is not a declared family role.');
end

function mesh = localCanonicalParentMesh(mesh)
localRequire(isstruct(mesh) && isscalar(mesh) && ...
    all(isfield(mesh, {'node_coords','connectivity'})), ...
    'parent mesh must contain node_coords and connectivity.');
coords = mesh.node_coords;
connectivity = mesh.connectivity;
localRequire(isa(coords,'double') && isreal(coords) && ...
    size(coords,2) == 2 && ~isempty(coords) && all(isfinite(coords),'all'), ...
    'node_coords must be a nonempty finite double N-by-2 array.');
localRequire(isa(connectivity,'double') && isreal(connectivity) && ...
    size(connectivity,2) == 4 && ~isempty(connectivity) && ...
    all(isfinite(connectivity),'all') && ...
    all(connectivity == floor(connectivity),'all') && ...
    all(connectivity >= 1,'all') && all(connectivity <= size(coords,1),'all'), ...
    'connectivity must be valid one-based double Q4 connectivity.');
for element = 1:size(connectivity,1)
    localRequire(numel(unique(connectivity(element,:))) == 4, ...
        'each Q4 element must contain four distinct nodes.');
end
mesh = struct( ...
    'node_coords',coords, ...
    'connectivity',connectivity, ...
    'connectivity_sha256',localConnectivitySha256(connectivity), ...
    'mesh_sha256',localMeshSha256(coords,connectivity), ...
    'mesh_sha256_semantics', ...
        'sha256_matlab_column_major_float64_coords_then_int64_connectivity_v1', ...
    'element_ordering_id','q4_connectivity_1_based_v1', ...
    'gp_ordering_id','q4_2x2_native_order_v1');
end

function [mappedCoords,audit] = localApplyT1MeshTransfer(coords, connectivity, ell)
mappedCoords = coords;
leftFactor = 1.25;
rightFactor = 0.75;
left = coords(:,1) <= 0;
mappedCoords(left,1) = -0.5 + leftFactor * (coords(left,1) + 0.5);
mappedCoords(~left,1) = 0.125 + rightFactor * coords(~left,1);

tolerance = 1e-12;
tipIds = find(abs(coords(:,1)) <= tolerance & abs(coords(:,2)) <= tolerance);
localMeshGate(isscalar(tipIds), ...
    'Expected exactly one parent notch-tip node at (0,0).');
tipId = tipIds(1);
localMeshGate(abs(min(coords(:,1)) + 0.5) <= tolerance && ...
    abs(max(coords(:,1)) - 0.5) <= tolerance && ...
    abs(min(mappedCoords(:,1)) + 0.5) <= tolerance && ...
    abs(max(mappedCoords(:,1)) - 0.5) <= tolerance, ...
    'External x boundaries must remain fixed at -0.5 and 0.5.');
localMeshGate(norm(mappedCoords(tipId,:) - [0.125 0]) <= tolerance, ...
    'The parent notch-tip node must map to (0.125,0).');

jacobians = localQ4CornerJacobians(mappedCoords,connectivity);
localMeshGate(all(jacobians > tolerance,'all'), ...
    'Mapped Q4 elements contain a non-positive corner Jacobian.');
[edgeNodes,parentLengths,mappedLengths] = localIncidentEdges( ...
    coords,mappedCoords,connectivity,tipId);
ratios = mappedLengths ./ parentLengths;
localMeshGate(all(ratios >= 0.75-tolerance & ratios <= 1.25+tolerance), ...
    'Mapped/parent incident-edge ratios violate the declared gate.');
audit = struct( ...
    'applied',true, ...
    'semantics','piecewise_affine_x_v1', ...
    'left_affine_x_factor',leftFactor, ...
    'right_affine_x_factor',rightFactor, ...
    'notch_tip_node_id',tipId, ...
    'incident_edge_node_ids',edgeNodes, ...
    'parent_incident_edge_lengths',parentLengths, ...
    'mapped_incident_edge_lengths',mappedLengths, ...
    'mapped_over_parent_edge_ratios',ratios, ...
    'mapped_over_parent_edge_ratio_min',min(ratios), ...
    'mapped_over_parent_edge_ratio_max',max(ratios), ...
    'parent_h_over_ell_min',min(parentLengths/ell), ...
    'parent_h_over_ell_max',max(parentLengths/ell), ...
    'mapped_h_over_ell_min',min(mappedLengths/ell), ...
    'mapped_h_over_ell_max',max(mappedLengths/ell), ...
    'all_positive_jacobians',true, ...
    'q4_corner_jacobians',jacobians, ...
    'parent_mesh_sha256',localMeshSha256(coords,connectivity), ...
    'candidate_mesh_sha256',localMeshSha256(mappedCoords,connectivity));
end

function jacobians = localQ4CornerJacobians(coords,connectivity)
corners = [-1 -1;1 -1;1 1;-1 1];
jacobians = zeros(size(connectivity,1),4);
for element = 1:size(connectivity,1)
    elementCoords = coords(connectivity(element,:),:);
    for corner = 1:4
        xi = corners(corner,1);
        eta = corners(corner,2);
        dNdxi = 0.25*[-(1-eta),(1-eta),(1+eta),-(1+eta)];
        dNdeta = 0.25*[-(1-xi),-(1+xi),(1+xi),(1-xi)];
        jacobians(element,corner) = det([dNdxi;dNdeta]*elementCoords);
    end
end
end

function [edgeNodes,parentLengths,mappedLengths] = localIncidentEdges( ...
        coords,mappedCoords,connectivity,tipId)
edges = [connectivity(:,[1 2]);connectivity(:,[2 3]); ...
    connectivity(:,[3 4]);connectivity(:,[4 1])];
edges = unique(sort(edges,2),'rows');
incident = edges(any(edges == tipId,2),:);
localMeshGate(~isempty(incident), 'The notch tip has no Q4 incident edges.');
other = incident(:,1);
other(incident(:,1) == tipId) = incident(incident(:,1) == tipId,2);
edgeNodes = sort(other);
parentLengths = vecnorm(coords(edgeNodes,:) - coords(tipId,:),2,2);
mappedLengths = vecnorm(mappedCoords(edgeNodes,:) - mappedCoords(tipId,:),2,2);
localMeshGate(all(parentLengths > 0), 'The parent notch tip has a zero-length edge.');
end

function umax = localUmaxForCycle(cycles,blocks,censorCap)
valid = isa(cycles,'double') && isreal(cycles) && all(isfinite(cycles),'all') && ...
    all(cycles == floor(cycles),'all') && all(cycles >= 1,'all') && ...
    all(cycles <= censorCap,'all');
localRequire(valid, 'cycle values must be double integers in 1:150.');
umax = zeros(size(cycles));
for index = 1:numel(cycles)
    block = find(cycles(index) >= blocks(:,1) & cycles(index) <= blocks(:,2),1);
    localRequire(~isempty(block), 'loading blocks do not cover the requested cycle.');
    umax(index) = blocks(block,3);
end
end

function state = localAdvanceEvent(state,coords,connectivity,cycle,peakDamage)
state = localNormaliseEventState(state);
localValidateEventInput(state,coords,connectivity,cycle,peakDamage);
candidate = coords(:,1) >= 0.48 & peakDamage(:) >= 0.95;
hitNodes = find(candidate);
[component,componentSize] = localLargestComponent( ...
    candidate,connectivity,size(coords,1));
hit = componentSize >= 3;
state.hit_node_ids = hitNodes;
state.connected_component_node_ids = component;
state.connected_component_size = componentSize;
state.hit = hit;
if hit
    if isnan(state.first_hit)
        state.first_hit = cycle;
        state.consecutive_post_hit = 0;
    elseif isnan(state.confirmed)
        state.consecutive_post_hit = state.consecutive_post_hit + 1;
        if state.consecutive_post_hit >= 3
            state.confirmed = cycle;
        end
    end
else
    state.consecutive_post_hit = 0;
end
state.last_processed_cycle = cycle;
end

function state = localNormaliseEventState(state)
if isempty(state)
    state = struct();
end
localRequire(isstruct(state) && isscalar(state), ...
    'event state must be a scalar struct.');
defaults = struct('first_hit',NaN,'confirmed',NaN, ...
    'consecutive_post_hit',0,'hit_node_ids',zeros(0,1), ...
    'connected_component_node_ids',zeros(0,1), ...
    'connected_component_size',0,'hit',false,'last_processed_cycle',NaN);
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(state,names{index})
        state.(names{index}) = defaults.(names{index});
    end
end
end

function localValidateEventInput(state,coords,connectivity,cycle,peakDamage)
validCycle = isa(cycle,'double') && isscalar(cycle) && isfinite(cycle) && ...
    cycle >= 1 && cycle == floor(cycle);
validDamage = isa(peakDamage,'double') && isreal(peakDamage) && ...
    isvector(peakDamage) && numel(peakDamage) == size(coords,1) && ...
    all(isfinite(peakDamage),'all');
localRequire(validCycle && validDamage, 'event cycle or peak damage is invalid.');
last = state.last_processed_cycle;
localRequire(isnan(last) || cycle == last+1, ...
    'event updates must process consecutive physical cycles.');
localRequire(size(connectivity,2) == 4, 'event connectivity must remain Q4.');
end

function [largest,largestSize] = localLargestComponent(candidate,connectivity,nodeCount)
edges = [connectivity(:,[1 2]);connectivity(:,[2 3]); ...
    connectivity(:,[3 4]);connectivity(:,[4 1])];
edges = unique(sort(edges,2),'rows');
edges = edges(candidate(edges(:,1)) & candidate(edges(:,2)),:);
adjacency = sparse([edges(:,1);edges(:,2)],[edges(:,2);edges(:,1)], ...
    true,nodeCount,nodeCount);
unvisited = find(candidate).';
largest = zeros(0,1);
largestSize = 0;
while ~isempty(unvisited)
    component = localConnectedComponent(unvisited(1),adjacency);
    unvisited = setdiff(unvisited,component.');
    if numel(component) > largestSize
        largest = component(:);
        largestSize = numel(component);
    end
end
end

function component = localConnectedComponent(seed,adjacency)
visited = false(size(adjacency,1),1);
queue = seed;
visited(seed) = true;
head = 1;
while head <= numel(queue)
    node = queue(head);
    head = head+1;
    neighbours = find(adjacency(node,:));
    additions = neighbours(~visited(neighbours));
    visited(additions) = true;
    queue = [queue additions]; %#ok<AGROW>
end
component = sort(queue(:));
end

function digest = localConnectivitySha256(connectivity)
payload = sprintf('%dx%d:',size(connectivity,1),size(connectivity,2));
payload = [payload sprintf('%d,',connectivity.')];
digest = localSha256(unicode2native(payload,'UTF-8'));
end

function digest = localMeshSha256(coords,connectivity)
bytes = [reshape(typecast(double(coords(:)),'uint8'),1,[]) ...
    reshape(typecast(int64(connectivity(:)),'uint8'),1,[])];
digest = localSha256(bytes);
end

function digest = localSha256(bytes)
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(bytes);
digestBytes = typecast(hasher.digest(),'uint8');
digest = lower(reshape(dec2hex(digestBytes,2).',1,[]));
end

function localMeshGate(condition,message)
if ~condition
    error('toyRoadP0:MeshTransferGateFailed',message);
end
end

function localRequire(condition,message)
if ~condition
    error('toyRoadP0:InvalidCaseContract',message);
end
end
