function receipt = finalize_toy_road_c5_gate(trace)
%FINALIZE_TOY_ROAD_C5_GATE Bind the converged final row into a PASS receipt.

localValidateTrace(trace);
count = trace.trace_row_count;
localRequire(count > 0, 'at least one completed stagger row is required.');
localRequire(trace.last_row_converged, ...
    'the final appended row was not declared converged by the normal solver.');
localRequire(trace.lifecycle_state.get() == count && ...
    trace.same_process_reassembly_count == count && ...
    isequal(trace.stagger_ordinals, 1:count), ...
    'the c5 lifecycle counts or ordinals are stale or inconsistent.');
traceSha256 = localFileSha256(trace.trace_path);
localRequire(strcmp(traceSha256, trace.trace_sha256), ...
    'the c5 trace bytes changed outside the active lifecycle.');
localRequire(trace.lifecycle_state.compareAndSet(count, -(1000000 + count)), ...
    'the c5 lifecycle was already finalized, copied or poisoned.');

rows = localReadValidatedRows(trace, count);
last = count;
thresholds = struct( ...
    'displacement_residual_threshold', 4e-4, ...
    'projected_phase_kkt_threshold', 4e-4, ...
    'consecutive_stagger_delta_threshold', 1e-3, ...
    'primal_feasibility_threshold', 1e-12);
passed = rows.displacement_residual(last) <= ...
    thresholds.displacement_residual_threshold && ...
    rows.projected_phase_kkt(last) <= ...
    thresholds.projected_phase_kkt_threshold && ...
    rows.consecutive_stagger_delta(last) <= ...
    thresholds.consecutive_stagger_delta_threshold && ...
    rows.primal_feasibility(last) <= thresholds.primal_feasibility_threshold;
if ~passed
    error('toyRoadP0:C5GateFailed', ...
        'The converged c5/s4 row failed a mandatory numerical gate.');
end

receipt = struct( ...
    'authorization_scope', trace.authorization_scope, ...
    'case_id', trace.case_id, ...
    'cycle', 5, ...
    'substep_ordinal', 4, ...
    'status', 'PASS', ...
    'passed', true, ...
    'trace_sha256', traceSha256, ...
    'trace_row_count', count, ...
    'reassembly_count', count, ...
    'final_stagger_iteration', rows.stagger_iteration(last), ...
    'final_reassembly_ordinal', rows.reassembly_ordinal(last), ...
    'final_displacement_residual', rows.displacement_residual(last), ...
    'final_raw_phase_residual', rows.raw_phase_residual(last), ...
    'final_projected_phase_kkt', rows.projected_phase_kkt(last), ...
    'final_consecutive_stagger_delta', rows.consecutive_stagger_delta(last), ...
    'final_primal_feasibility', rows.primal_feasibility(last), ...
    'displacement_residual_threshold', ...
        thresholds.displacement_residual_threshold, ...
    'projected_phase_kkt_threshold', ...
        thresholds.projected_phase_kkt_threshold, ...
    'consecutive_stagger_delta_threshold', ...
        thresholds.consecutive_stagger_delta_threshold, ...
    'primal_feasibility_threshold', thresholds.primal_feasibility_threshold);
localPublishJsonExclusive(trace.receipt_path, receipt);
end

function rows = localReadValidatedRows(trace, count)
rows = readtable(trace.trace_path, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
columns = {'authorization_scope','case_id','cycle','substep_ordinal', ...
    'stagger_iteration','reassembly_ordinal','displacement_residual', ...
    'raw_phase_residual','projected_phase_kkt', ...
    'consecutive_stagger_delta','primal_feasibility'};
localRequire(isequal(rows.Properties.VariableNames, columns) && ...
    height(rows) == count, 'the c5 trace schema or row count is invalid.');
localRequire(all(rows.authorization_scope == string(trace.authorization_scope)) && ...
    all(rows.case_id == string(trace.case_id)) && all(rows.cycle == 5) && ...
    all(rows.substep_ordinal == 4) && ...
    isequal(rows.stagger_iteration, (1:count).') && ...
    isequal(rows.reassembly_ordinal, (1:count).'), ...
    'the c5 trace identity or ordinal sequence is invalid.');
metrics = rows{:,7:end};
localRequire(isa(metrics, 'double') && isreal(metrics) && ...
    all(isfinite(metrics), 'all') && all(metrics >= 0, 'all'), ...
    'the c5 trace metrics must be finite nonnegative doubles.');
end

function localValidateTrace(trace)
required = {'authorization_scope','case_id','cycle','substep_ordinal', ...
    'evidence_method','trace_path','receipt_path','trace_sha256', ...
    'trace_row_count','same_process_reassembly_count','stagger_ordinals', ...
    'last_row_converged','lifecycle_state'};
valid = isstruct(trace) && isscalar(trace) && all(isfield(trace, required));
if valid
    valid = strcmp(trace.evidence_method, ...
        'same_process_post_update_reassembly_v1') && trace.cycle == 5 && ...
        trace.substep_ordinal == 4 && isfile(trace.trace_path) && ...
        isa(trace.lifecycle_state, 'java.util.concurrent.atomic.AtomicInteger') && ...
        localNonnegativeInteger(trace.trace_row_count) && ...
        localNonnegativeInteger(trace.same_process_reassembly_count) && ...
        islogical(trace.last_row_converged) && isscalar(trace.last_row_converged);
end
localRequire(valid, 'trace is not an active same-process c5 lifecycle.');
end

function localPublishJsonExclusive(path, payload)
if isfile(path) || isfolder(path)
    error('toyRoadP0:PublicationClobber', ...
        'Refusing to overwrite c5 receipt destination: %s', path);
end
directory = fileparts(path);
temporaryPath = localCreateReservedTemporary(directory);
cleanup = onCleanup(@() localDeleteIfPresent(temporaryPath));
fileId = fopen(temporaryPath, 'wb');
if fileId < 0
    error('toyRoadP0:PublicationFailed', ...
        'Cannot open temporary c5 receipt: %s', temporaryPath);
end
content = [jsonencode(payload) newline];
count = fwrite(fileId, unicode2native(content, 'UTF-8'), 'uint8');
closeStatus = fclose(fileId);
if count ~= numel(unicode2native(content, 'UTF-8')) || closeStatus ~= 0
    error('toyRoadP0:PublicationFailed', ...
        'Cannot write temporary c5 receipt: %s', temporaryPath);
end
try
    java.nio.file.Files.createLink(java.io.File(path).toPath(), ...
        java.io.File(temporaryPath).toPath());
catch exception
    if isfile(path) || isfolder(path)
        error('toyRoadP0:PublicationClobber', ...
            'Refusing to overwrite c5 receipt destination: %s', path);
    end
    error('toyRoadP0:PublicationFailed', ...
        'Cannot exclusively publish c5 receipt: %s', exception.message);
end
localDeleteIfPresent(temporaryPath);
clear cleanup
end

function path = localCreateReservedTemporary(directory)
try
    attributes = javaArray('java.nio.file.attribute.FileAttribute', 0);
    temporary = java.nio.file.Files.createTempFile( ...
        java.io.File(directory).toPath(), '.c5_receipt_', '.json', attributes);
    path = char(temporary.toString());
catch exception
    error('toyRoadP0:PublicationFailed', ...
        'Cannot reserve temporary c5 receipt: %s', exception.message);
end
end

function localDeleteIfPresent(path)
if isfile(path)
    delete(path);
end
end

function value = localNonnegativeInteger(value)
value = isa(value, 'double') && isscalar(value) && isfinite(value) && ...
    value >= 0 && value == floor(value);
end

function digest = localFileSha256(path)
fileId = fopen(path, 'rb');
if fileId < 0
    error('toyRoadP0:PublicationFailed', 'Cannot hash c5 trace: %s', path);
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, '*uint8');
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(bytes);
digestBytes = typecast(hasher.digest(), 'uint8');
digest = lower(reshape(dec2hex(digestBytes, 2).', 1, []));
end

function localRequire(condition, message)
if ~condition
    error('toyRoadP0:InvalidC5Lifecycle', message);
end
end
