function summary = finalize_toy_road_family_package(root, caseId, contractPath, attemptPath)
%FINALIZE_TOY_ROAD_FAMILY_PACKAGE Close one case package without clobbering.

try
    summary = localFinalize(root, caseId, contractPath, attemptPath);
catch exception
    if startsWith(exception.identifier, 'toyRoadP0:')
        rethrow(exception);
    end
    error('toyRoadP0:InvalidFinalizationInput', '%s', exception.message);
end
end

function summary = localFinalize(root, caseId, contractPath, attemptPath)
root = localFolder(root); caseId = localText(caseId);
outputs = {'TERMINAL_MANIFEST.json','SHA256SUMS.txt','VALIDATION_SUMMARY.json'};
for index = 1:numel(outputs)
    if isfile(fullfile(root, outputs{index})) || isfolder(fullfile(root, outputs{index}))
        error('toyRoadP0:FinalizationClobber', ...
            'Refusing to overwrite finalization output %s.', outputs{index});
    end
end
loaded = load(localFile(contractPath), 'contract');
localRequire(isfield(loaded,'contract') && isstruct(loaded.contract) && ...
    isscalar(loaded.contract), 'Contract is invalid.');
contract = loaded.contract;
attempt = localJson(localFile(attemptPath));
lockPath = fullfile(root, 'EXECUTION_INPUT_LOCK.json');
lock = localJson(localFile(lockPath));
snapshotPath = fullfile(root, 'INPUT_SNAPSHOT.json');
snapshot = localJson(localFile(snapshotPath));
terminal = localJson(localFile(fullfile(root, 'TERMINAL_RESULT.json')));
event = localJson(localFile(fullfile(root, 'EVENT_METADATA.json')));
receipt = localJson(localFile(fullfile(root, 'qualification', ...
    'C5_NUMERICAL_GATE_RECEIPT.json')));
tracePath = localFile(fullfile(root, 'qualification', 'C5_STAGGER_TRACE.csv'));

requiredAttempt = {'attempt_id','case_id','source_commit', ...
    'family_contract_sha256','case_physics_contract_sha256', ...
    'execution_input_lock_sha256','runtime_lock_sha256', ...
    'physical_input_sha256','solver_sha256','recovery_sha256', ...
    'exporter_sha256','numerical_gate_contract_sha256','event_contract_sha256'};
localFields(attempt, requiredAttempt, 'attempt record');
localRequire(strcmp(attempt.case_id,caseId) && strcmp(lock.case_id,caseId) && ...
    strcmp(terminal.case_id,caseId) && strcmp(event.case_id,caseId) && ...
    strcmp(receipt.case_id,caseId), 'Case identities are inconsistent.');
localRequire(strcmp(attempt.source_commit,lock.source_commit) && ...
    strcmp(attempt.runtime_lock_sha256,lock.runtime_lock_sha256) && ...
    strcmp(attempt.runtime_lock_sha256,contract.runtime_lock_sha256) && ...
    strcmp(attempt.family_contract_sha256,contract.family_contract_sha256) && ...
    strcmp(attempt.case_physics_contract_sha256, ...
        contract.case_physics_contract_sha256), ...
    'Attempt, runtime, and physics identities are inconsistent.');
localRequire(strcmp(snapshot.case_id,caseId) && ...
    strcmp(snapshot.source_commit,attempt.source_commit) && ...
    strcmp(snapshot.runtime_lock_sha256,attempt.runtime_lock_sha256) && ...
    strcmp(snapshot.family_contract_sha256,attempt.family_contract_sha256) && ...
    strcmp(snapshot.case_physics_contract_sha256, ...
        attempt.case_physics_contract_sha256) && ...
    strcmp(snapshot.execution_input_lock_sha256, ...
        attempt.execution_input_lock_sha256) && ...
    strcmp(localSha(snapshotPath),attempt.physical_input_sha256), ...
    'Physical input snapshot is inconsistent with the attempt record.');
executionDigest = localSha(lockPath);
localRequire(strcmp(executionDigest,attempt.execution_input_lock_sha256) && ...
    strcmp(executionDigest,contract.execution_input_lock_sha256), ...
    'Execution-input lock digest is inconsistent.');
localRequire(strcmp(receipt.status,'PASS') && receipt.passed && ...
    receipt.cycle == 5 && receipt.substep_ordinal == 4 && ...
    strcmp(receipt.trace_sha256,localSha(tracePath)), ...
    'Case-local c5 receipt is invalid.');
localRequire(strcmp(terminal.terminal_reason,'confirmed_penetration') && ...
    terminal.terminal_cycle == event.terminal_cycle && ...
    terminal.first_hit_cycle == event.first_hit_cycle && ...
    terminal.confirmed_cycle == event.confirmed_cycle && ...
    event.confirmed_cycle == event.first_hit_cycle + 3 && ...
    event.confirmed_cycle == event.terminal_cycle && ...
    event.peak_substep_ordinal == 4, ...
    'Terminal and event metadata are inconsistent.');
terminalCycle = terminal.terminal_cycle;
cycleFiles = dir(fullfile(root,'substeps','cycle_*.mat'));
names = sort(string({cycleFiles.name}));
expected = compose("cycle_%04d.mat",(1:terminalCycle).');
localRequire(isequal(names(:),expected), ...
    'Cycle shards must cover exactly c1 through terminal.');

summary = struct('schema_version','toy_road_terminal_validation_summary_v1', ...
    'status','PASS','is_valid',true,'case_id',caseId, ...
    'terminal_cycle',terminalCycle,'cycle_count',numel(names), ...
    'runtime_lock_sha256',attempt.runtime_lock_sha256, ...
    'c5_receipt_sha256',localSha(fullfile(root,'qualification', ...
        'C5_NUMERICAL_GATE_RECEIPT.json')), ...
    'attempt_id',attempt.attempt_id);
localPublish(fullfile(root,'VALIDATION_SUMMARY.json'), ...
    [jsonencode(summary) newline]);
paths = localPackagePaths(root, {'TERMINAL_MANIFEST.json','SHA256SUMS.txt'});
lines = strings(numel(paths),1);
for index = 1:numel(paths)
    lines(index) = localSha(localFromRelative(root,paths(index))) + ...
        "  " + paths(index);
end
localPublish(fullfile(root,'SHA256SUMS.txt'), char(join(lines,newline)+newline));
paths = localPackagePaths(root, {'TERMINAL_MANIFEST.json'});
files = repmat(struct('path','','sha256',''),numel(paths),1);
for index = 1:numel(paths)
    files(index).path = char(paths(index));
    files(index).sha256 = localSha(localFromRelative(root,paths(index)));
end
manifest = struct('authorization_scope',lock.authorization_scope, ...
    'protocol_version','toy-road-p0-repeatability-v2.1','case_id',caseId, ...
    'source_commit',attempt.source_commit,'mesh_sha256',contract.mesh_sha256, ...
    'element_ordering_id',contract.element_ordering_id, ...
    'gp_ordering_id',contract.gp_ordering_id, ...
    'state_semantics_id',contract.state_semantics_id, ...
    'runtime_lock_sha256',attempt.runtime_lock_sha256, ...
    'family_contract_sha256',attempt.family_contract_sha256, ...
    'case_physics_contract_sha256',attempt.case_physics_contract_sha256, ...
    'physical_input_sha256',attempt.physical_input_sha256, ...
    'solver_sha256',attempt.solver_sha256, ...
    'recovery_sha256',attempt.recovery_sha256, ...
    'exporter_sha256',attempt.exporter_sha256, ...
    'numerical_gate_contract_sha256',attempt.numerical_gate_contract_sha256, ...
    'event_contract_sha256',attempt.event_contract_sha256, ...
    'execution_input_lock_sha256',attempt.execution_input_lock_sha256, ...
    'files',files);
localPublish(fullfile(root,'TERMINAL_MANIFEST.json'), ...
    [jsonencode(manifest) newline]);
summary = validate_toy_road_terminal_package(root,caseId,contractPath);
end

function paths = localPackagePaths(root, excluded)
entries = dir(fullfile(root,'**','*')); entries = entries(~[entries.isdir]);
paths = strings(0,1);
for index = 1:numel(entries)
    relative = replace(erase(string(fullfile(entries(index).folder, ...
        entries(index).name)),string(root)+filesep),'\','/');
    if ~ismember(char(relative),excluded), paths(end+1,1)=relative; end %#ok<AGROW>
end
paths = sort(paths);
localRequire(numel(unique(lower(paths)))==numel(paths), ...
    'Package has a case-folded path collision.');
end

function path = localFromRelative(root,relative)
parts=split(relative,'/'); path=root;
for index=1:numel(parts), path=fullfile(path,char(parts(index))); end
end
function value=localJson(path), value=jsondecode(fileread(path)); localRequire(isstruct(value)&&isscalar(value),'JSON asset is invalid.'); end
function localFields(value,names,label), localRequire(all(isfield(value,names)),'%s is missing required fields.',label); end
function value=localText(value), localRequire((ischar(value)&&isrow(value))||(isstring(value)&&isscalar(value)),'Text input is invalid.'); value=char(value); end
function path=localFolder(path), path=localText(path); localRequire(isfolder(path),'Folder does not exist.'); end
function path=localFile(path), path=localText(path); localRequire(isfile(path),'File does not exist: %s',path); end

function localPublish(path,text)
if isfile(path) || isfolder(path), error('toyRoadP0:FinalizationClobber','Output exists: %s',path); end
temporary=[tempname(fileparts(path)) '.tmp']; cleanup=onCleanup(@() localDelete(temporary));
fileId=fopen(temporary,'wb'); localRequire(fileId>=0,'Cannot create temporary output.');
fileCleanup=onCleanup(@() fclose(fileId));
bytes=unicode2native(char(text),'UTF-8'); localRequire(fwrite(fileId,bytes,'uint8')==numel(bytes),'Short write.');
clear fileCleanup
try
    java.nio.file.Files.createLink(java.io.File(path).toPath(),java.io.File(temporary).toPath());
catch exception
    if isfile(path)||isfolder(path), error('toyRoadP0:FinalizationClobber','Output exists: %s',path); end
    error('toyRoadP0:InvalidFinalizationInput','Cannot publish output: %s',exception.message);
end
delete(temporary); clear cleanup
end
function localDelete(path), if isfile(path), delete(path); end, end

function digest=localSha(path)
fileId=fopen(path,'rb'); localRequire(fileId>=0,'Cannot hash file.'); cleanup=onCleanup(@() fclose(fileId));
bytes=fread(fileId,Inf,'*uint8'); hasher=java.security.MessageDigest.getInstance('SHA-256'); hasher.update(bytes);
raw=typecast(hasher.digest(),'uint8'); alphabet='0123456789abcdef';
digest=reshape([alphabet(bitshift(raw,-4)+1); alphabet(bitand(raw,15)+1)],1,[]);
end
function localRequire(condition,message,varargin)
if ~condition, error('toyRoadP0:InvalidFinalizationInput',message,varargin{:}); end
end
