function capture = init_toy_road_cycle_capture(cycle, previous, state0)
%INIT_TOY_ROAD_CYCLE_CAPTURE Start one immutable five-substep cycle capture.

localRequire(isa(cycle, 'double') && isscalar(cycle) && isfinite(cycle) && ...
    cycle >= 1 && cycle == floor(cycle), 'cycle must be a positive double integer.');
localRequire(isstruct(state0) && isscalar(state0) && ...
    isfield(state0, 'd_node') && isfield(state0, 'alpha_bar_gp'), ...
    'state0 must contain d_node and alpha_bar_gp.');
localRequire(localFiniteDouble(state0.d_node) && iscolumn(state0.d_node) && ...
    ~isempty(state0.d_node), 'state0.d_node must be a nonempty finite double column.');
localRequire(localFiniteDouble(state0.alpha_bar_gp) && ...
    size(state0.alpha_bar_gp, 1) > 0 && size(state0.alpha_bar_gp, 2) == 4 && ...
    ismatrix(state0.alpha_bar_gp), ...
    'state0.alpha_bar_gp must be a finite n_elem-by-4 double array.');
if cycle == 1
    localRequire(isa(previous, 'double') && isequal(previous, []), ...
        'cycle 1 requires the literal empty double predecessor.');
else
    localRequire(isstruct(previous) && isscalar(previous) && ...
        isfield(previous, 'cycle') && isfield(previous, 'd_node') && ...
        isfield(previous, 'alpha_bar_gp'), ...
        'successor cycles require the immediately preceding shard.');
end

capture = struct( ...
    'cycle', cycle, ...
    'previous', previous, ...
    'state0', state0, ...
    'next_substep_ordinal', 1, ...
    'd_node', [], ...
    'd_gp', [], ...
    'alpha_bar_gp', [], ...
    'f_alpha_gp', [], ...
    'psi_raw_gp', []);
end

function value = localFiniteDouble(value)
value = isa(value, 'double') && isreal(value) && all(isfinite(value), 'all');
end

function localRequire(condition, message)
if ~condition
    error('toyRoadP0:InvalidCycleCapture', message);
end
end
