function capture = init_toy_road_cycle_capture(cycle, previous, state0, mesh, contract)
%INIT_TOY_ROAD_CYCLE_CAPTURE Bind one cycle to its trusted Q4 mesh and state.

localRequire(isa(cycle, 'double') && isscalar(cycle) && isfinite(cycle) && ...
    cycle >= 1 && cycle == floor(cycle), 'cycle must be a positive double integer.');
localRequire(isstruct(state0) && isscalar(state0) && ...
    isfield(state0, 'd_node') && isfield(state0, 'alpha_bar_gp'), ...
    'state0 must contain d_node and alpha_bar_gp.');
localRequire(localFiniteDouble(state0.d_node) && iscolumn(state0.d_node) && ...
    ~isempty(state0.d_node), 'state0.d_node must be a nonempty finite double column.');
localRequire(localFiniteDouble(state0.alpha_bar_gp) && ...
    size(state0.alpha_bar_gp, 1) > 0 && size(state0.alpha_bar_gp, 2) == 4 && ...
    ismatrix(state0.alpha_bar_gp), ...
    'state0.alpha_bar_gp must be a finite n_elem-by-4 double array.');
localValidatePredecessor(cycle, previous);

requiredMesh = {'connectivity','connectivity_sha256','mesh_sha256', ...
    'element_ordering_id','gp_ordering_id'};
localRequire(isstruct(mesh) && isscalar(mesh) && all(isfield(mesh, requiredMesh)), ...
    'mesh must contain trusted Q4 connectivity and ordering identity.');
nNode = size(state0.d_node, 1);
nElem = size(state0.alpha_bar_gp, 1);
connectivity = mesh.connectivity;
localRequire(isa(connectivity, 'double') && isequal(size(connectivity), [nElem 4]) && ...
    all(isfinite(connectivity), 'all') && all(connectivity == floor(connectivity), 'all') && ...
    all(connectivity >= 1, 'all') && all(connectivity <= nNode, 'all'), ...
    'mesh connectivity must be a valid n_elem-by-4 one-based double array.');
for element = 1:nElem
    localRequire(numel(unique(connectivity(element,:))) == 4, ...
        'each Q4 element must contain four distinct nodes.');
end
localRequire(strcmp(localText(mesh.connectivity_sha256), ...
    localConnectivitySha256(connectivity)), ...
    'mesh connectivity does not match its immutable connectivity digest.');
localRequire(strcmp(localText(mesh.element_ordering_id), ...
    'q4_connectivity_1_based_v1'), ...
    'mesh element ordering is not the locked Q4 ordering.');
localRequire(strcmp(localText(mesh.gp_ordering_id), 'q4_2x2_native_order_v1'), ...
    'mesh GP ordering is not the locked native 2x2 order.');

requiredContract = {'alpha_T','p','mesh_sha256','element_ordering_id','gp_ordering_id'};
localRequire(isstruct(contract) && isscalar(contract) && ...
    all(isfield(contract, requiredContract)), 'contract is missing capture identities.');
localRequire(localFiniteNumericScalar(contract.alpha_T) && ...
    localFiniteNumericScalar(contract.p), 'alpha_T and p must be finite numeric scalars.');
localRequire(double(contract.alpha_T) == 0.5 && double(contract.p) == 2, ...
    'alpha_T and p must match the locked fatigue law.');
localRequire(strcmp(localText(mesh.mesh_sha256), localText(contract.mesh_sha256)) && ...
    strcmp(localText(mesh.element_ordering_id), localText(contract.element_ordering_id)) && ...
    strcmp(localText(mesh.gp_ordering_id), localText(contract.gp_ordering_id)), ...
    'trusted mesh identities do not match the capture contract.');

capture = struct( ...
    'cycle', cycle, ...
    'previous', previous, ...
    'state0', state0, ...
    'connectivity', connectivity, ...
    'shape_operator', localCanonicalQ4ShapeOperator(), ...
    'mesh_sha256', localText(mesh.mesh_sha256), ...
    'element_ordering_id', localText(mesh.element_ordering_id), ...
    'gp_ordering_id', localText(mesh.gp_ordering_id), ...
    'alpha_T', double(contract.alpha_T), ...
    'p', double(contract.p), ...
    'commit_state', java.util.concurrent.atomic.AtomicInteger(1), ...
    'next_substep_ordinal', 1, ...
    'd_node', [], ...
    'd_gp', [], ...
    'alpha_bar_gp', [], ...
    'f_alpha_gp', [], ...
    'psi_raw_gp', []);
end

function localValidatePredecessor(cycle, previous)
if cycle == 1
    localRequire(isa(previous, 'double') && isequal(previous, []), ...
        'cycle 1 requires the literal empty double predecessor.');
else
    localRequire(isstruct(previous) && isscalar(previous) && ...
        isfield(previous, 'cycle') && isfield(previous, 'd_node') && ...
        isfield(previous, 'alpha_bar_gp'), ...
        'successor cycles require the immediately preceding shard.');
end
end

function operator = localCanonicalQ4ShapeOperator()
a = 1 / sqrt(3);
points = [-a -a; a -a; a a; -a a];
operator = zeros(4,4);
for gp = 1:4
    xi = points(gp,1);
    eta = points(gp,2);
    operator(gp,:) = 0.25 * ...
        [(1-xi)*(1-eta), (1+xi)*(1-eta), ...
         (1+xi)*(1+eta), (1-xi)*(1+eta)];
end
end

function digest = localConnectivitySha256(connectivity)
payload = sprintf('%dx%d:', size(connectivity,1), size(connectivity,2));
payload = [payload sprintf('%d,', connectivity.')];
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(unicode2native(payload, 'UTF-8'));
digestBytes = typecast(hasher.digest(), 'uint8');
digest = lower(reshape(dec2hex(digestBytes, 2).', 1, []));
end

function value = localText(value)
valid = (ischar(value) && isrow(value)) || (isstring(value) && isscalar(value));
localRequire(valid, 'mesh and contract identities must be scalar text.');
value = char(value);
end

function value = localFiniteDouble(value)
value = isa(value, 'double') && isreal(value) && all(isfinite(value), 'all');
end

function value = localFiniteNumericScalar(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function localRequire(condition, message)
if ~condition
    error('toyRoadP0:InvalidCycleCapture', message);
end
end
