function result = main_toy_road_family_case(varargin)
%MAIN_TOY_ROAD_FAMILY_CASE Build state0 and run one authorized fresh case.

if nargin == 0
    request = localReadEnvironment();
    dependencies = localProductionDependencies();
    injected = false;
elseif nargin == 2
    request = varargin{1};
    dependencies = varargin{2};
    injected = true;
else
    error('toyRoadP0:InvalidDriverRequest', ...
        'Use no inputs for production or request/dependencies for controlled tests.');
end
localValidateRequest(request,injected);
localValidateAuthorization(request,injected);
localValidateDependencies(dependencies);
localValidateFreshRoots(request);
localCreateWritableRoots(request);

parentMesh = dependencies.load_parent_mesh(request.input_assets_root);
cfg = build_toy_road_family_case(request.case_id,parentMesh);
localRequire(cfg.sol_step_par.n_step == 5 && ...
    ~cfg.sol_step_par.line_search && ~cfg.sol_jump_par.cycle_jump && ...
    ~cfg.resume_allowed, 'The built case violates the Hard5 solver contract.');
recoveryInput = dependencies.build_recovery_input(cfg,parentMesh);
[sys,d,dOld,history,recoveryDetails] = ...
    recover_toy_road_family_state(recoveryInput);
state0 = struct( ...
    'd_node',d, ...
    'alpha_bar_gp',history(:,:,2), ...
    'history_vars',history, ...
    'd_node_old',dOld, ...
    'recovery_residual',recoveryDetails.recovery_residual, ...
    'state_semantics_id','fresh_hard_recovered_state0_v2');
runtimeReceipt = dependencies.runtime_receipt(request);
localValidateRuntimeReceipt(runtimeReceipt,request);
localPublishInitialAssets(request,cfg,state0,runtimeReceipt);

recovery = struct('sys',sys,'d',d,'d_old',dOld,'history_vars',history, ...
    'details',recoveryDetails);
context = dependencies.build_solver_context(cfg,recovery,request);
context = localBindApprovedSolverContext(context,cfg,state0,request);
result = dependencies.solve_family_case(context);
end

function request = localReadEnvironment()
names = { ...
    'TOY_ROAD_CASE_ROLE', ...
    'TOY_ROAD_SOURCE_COMMIT', ...
    'TOY_ROAD_RUNTIME_LOCK_SHA256', ...
    'TOY_ROAD_FAMILY_CONTRACT_SHA256', ...
    'TOY_ROAD_CASE_PHYSICS_CONTRACT_SHA256', ...
    'TOY_ROAD_EXECUTION_INPUT_LOCK_SHA256', ...
    'TOY_ROAD_OUTPUT_ROOT', ...
    'TOY_ROAD_WORK_ROOT', ...
    'TOY_ROAD_TEMP_ROOT', ...
    'TOY_ROAD_TMP_ROOT', ...
    'TOY_ROAD_PREF_ROOT', ...
    'TOY_ROAD_CACHE_ROOT', ...
    'TOY_ROAD_INPUT_ASSETS_ROOT', ...
    'TOY_ROAD_AUTHORIZATION_RECEIPT'};
values = cellfun(@getenv,names,'UniformOutput',false);
missing = names(cellfun(@(value) isempty(strtrim(value)),values));
if ~isempty(missing)
    error('toyRoadP0:MissingEnvironment', ...
        'Required environment variable is empty: %s',strjoin(missing,', '));
end
authorizationPath = values{14};
if ~isfile(authorizationPath)
    error('toyRoadP0:AuthorizationRejected', ...
        'The launcher authorization receipt is absent.');
end
authorizationReceipt = jsondecode(fileread(authorizationPath));
request = struct( ...
    'authorization_scope',localReceiptScope(authorizationReceipt), ...
    'authorization_receipt',authorizationReceipt, ...
    'case_id',values{1}, ...
    'source_commit',values{2}, ...
    'runtime_lock_sha256',lower(values{3}), ...
    'family_contract_sha256',lower(values{4}), ...
    'case_physics_contract_sha256',lower(values{5}), ...
    'execution_input_lock_sha256',lower(values{6}), ...
    'output_root',values{7}, ...
    'work_root',values{8}, ...
    'temp_root',values{9}, ...
    'tmp_root',values{10}, ...
    'pref_root',values{11}, ...
    'cache_root',values{12}, ...
    'input_assets_root',values{13});
end

function value = localReceiptScope(receipt)
if ~isstruct(receipt) || ~isscalar(receipt) || ...
        ~isfield(receipt,'authorization_scope')
    error('toyRoadP0:AuthorizationRejected', ...
        'The launcher receipt has no authorization scope.');
end
value = receipt.authorization_scope;
end

function localValidateRequest(request,injected)
required = {'authorization_scope','authorization_receipt','case_id', ...
    'source_commit','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256', ...
    'output_root','work_root','temp_root','tmp_root','pref_root','cache_root', ...
    'input_assets_root'};
valid = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)),sort(required(:)));
if valid
    roles = {'P0_parent','P0R_parent_repeat','T1_initial_defect', ...
        'T2_material_state','T3_loading_history'};
    valid = localText(request.authorization_scope) && ...
        localText(request.case_id) && any(strcmp(char(request.case_id),roles)) && ...
        localHex(request.source_commit,40) && ...
        localHex(request.runtime_lock_sha256,64) && ...
        localHex(request.family_contract_sha256,64) && ...
        localHex(request.case_physics_contract_sha256,64) && ...
        localHex(request.execution_input_lock_sha256,64) && ...
        isstruct(request.authorization_receipt) && ...
        isscalar(request.authorization_receipt);
    paths = required(9:end);
    for index = 1:numel(paths)
        valid = valid && localText(request.(paths{index}));
    end
end
if ~valid
    error('toyRoadP0:InvalidDriverRequest', ...
        'Driver request fields, identities, or paths are invalid.');
end
if injected && strcmp(char(request.authorization_scope),'production_authorized')
    error('toyRoadP0:AuthorizationRejected', ...
        'Production authorization may only enter through the no-input launcher path.');
end
end

function localValidateAuthorization(request,injected)
scope = char(request.authorization_scope);
if injected
    allowed = strcmp(scope,'test_only_non_authorizing');
else
    allowed = strcmp(scope,'production_authorized');
end
if ~allowed
    error('toyRoadP0:AuthorizationRejected', ...
        'This authorization scope cannot execute the producer driver.');
end
receipt = request.authorization_receipt;
required = {'status','authorization_scope','authorized_entrypoint','case_id', ...
    'source_commit','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256'};
valid = all(isfield(receipt,required)) && ...
    strcmp(char(receipt.status),'PASS') && ...
    strcmp(char(receipt.authorization_scope),scope) && ...
    strcmp(char(receipt.authorized_entrypoint),'main_toy_road_family_case') && ...
    strcmp(char(receipt.case_id),char(request.case_id)) && ...
    strcmpi(char(receipt.source_commit),char(request.source_commit)) && ...
    strcmpi(char(receipt.runtime_lock_sha256),char(request.runtime_lock_sha256)) && ...
    strcmpi(char(receipt.family_contract_sha256),char(request.family_contract_sha256)) && ...
    strcmpi(char(receipt.case_physics_contract_sha256), ...
        char(request.case_physics_contract_sha256)) && ...
    strcmpi(char(receipt.execution_input_lock_sha256), ...
        char(request.execution_input_lock_sha256));
if ~valid
    error('toyRoadP0:AuthorizationRejected', ...
        'Authorization receipt does not bind this exact execution.');
end
end

function localValidateDependencies(dependencies)
required = {'load_parent_mesh','build_recovery_input','build_solver_context', ...
    'runtime_receipt','solve_family_case'};
valid = isstruct(dependencies) && isscalar(dependencies) && ...
    isequal(sort(fieldnames(dependencies)),sort(required(:)));
for index = 1:numel(required)
    valid = valid && isa(dependencies.(required{index}),'function_handle');
end
if ~valid
    error('toyRoadP0:InvalidDriverDependencies', ...
        'Driver dependencies must contain only the declared callable interfaces.');
end
end

function localValidateFreshRoots(request)
writeFields = {'output_root','work_root','temp_root','tmp_root','pref_root','cache_root'};
canonical = strings(1,numel(writeFields));
for index = 1:numel(writeFields)
    path = char(request.(writeFields{index}));
    canonical(index) = lower(string(java.io.File(path).getCanonicalPath()));
    if isfile(path) || isfolder(path)
        error('toyRoadP0:FreshRootRequired', ...
            'Writable root must be initially absent: %s',path);
    end
end
if numel(unique(canonical)) ~= numel(canonical)
    error('toyRoadP0:FreshRootRequired', ...
        'Output, work, TEMP, TMP, preference, and cache roots must be distinct.');
end
if ~isfolder(request.input_assets_root)
    error('toyRoadP0:InvalidDriverRequest', ...
        'The read-only input-assets root must already exist.');
end
inputCanonical = lower(string(java.io.File( ...
    char(request.input_assets_root)).getCanonicalPath()));
if any(canonical == inputCanonical)
    error('toyRoadP0:FreshRootRequired', ...
        'A writable root cannot alias the input-assets root.');
end
end

function localCreateWritableRoots(request)
fields = {'output_root','work_root','temp_root','tmp_root','pref_root','cache_root'};
for index = 1:numel(fields)
    [created,message] = mkdir(request.(fields{index}));
    if ~created
        error('toyRoadP0:RootCreationFailed', ...
            'Cannot create fresh %s: %s',fields{index},message);
    end
end
end

function localPublishInitialAssets(request,cfg,state0,runtimeReceipt)
snapshot = struct( ...
    'schema_version','toy_road_p0_input_snapshot_v1', ...
    'authorization_scope',char(request.authorization_scope), ...
    'case_id',char(request.case_id), ...
    'source_commit',lower(char(request.source_commit)), ...
    'runtime_lock_sha256',lower(char(request.runtime_lock_sha256)), ...
    'family_contract_sha256',lower(char(request.family_contract_sha256)), ...
    'case_physics_contract_sha256', ...
        lower(char(request.case_physics_contract_sha256)), ...
    'execution_input_lock_sha256', ...
        lower(char(request.execution_input_lock_sha256)), ...
    'input_assets_root',char(request.input_assets_root), ...
    'mesh_sha256',cfg.mesh.mesh_sha256, ...
    'changed_axes',{cfg.changed_axes}, ...
    'case_physics',cfg.case_physics, ...
    'fresh_state0',true, ...
    'resume_allowed',false, ...
    'line_search',false, ...
    'cycle_jump',false);
localPublishJson(fullfile(request.output_root,'INPUT_SNAPSHOT.json'),snapshot);
localPublishMat(fullfile(request.output_root,'mesh_geometry.mat'), ...
    struct('mesh_geometry',cfg.mesh));
localPublishMat(fullfile(request.output_root,'state0_analysis.mat'), ...
    struct('state0',state0));
localPublishJson(fullfile(request.output_root,'RUNTIME_RECEIPT.json'),runtimeReceipt);
end

function context = localBindApprovedSolverContext(context,cfg,state0,request)
required = {'authorization_scope','case_id','output_root','cycle_limit', ...
    'active_u_dofs','active_d_dofs','state0','mesh','contract', ...
    'initial_state','sol_step_template','sol_stag_par','operators'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~isequal(sort(fieldnames(context)),sort(required(:))) || ...
        ~isstruct(context.initial_state) || ...
        ~all(isfield(context.initial_state,{'u','d','history'}))
    error('toyRoadP0:InvalidDriverContext', ...
        'Solver-context factory did not return the approved Task 4 interface.');
end
contract = struct( ...
    'eta',cfg.case_physics.material.eta, ...
    'alpha_T',cfg.case_physics.material.alpha_T, ...
    'p',cfg.case_physics.material.p, ...
    'mesh_sha256',cfg.mesh.mesh_sha256, ...
    'element_ordering_id',cfg.mesh.element_ordering_id, ...
    'gp_ordering_id',cfg.mesh.gp_ordering_id, ...
    'state_semantics_id','five_substep_post_commit_history_v1', ...
    'runtime_lock_sha256',lower(char(request.runtime_lock_sha256)), ...
    'family_contract_sha256',lower(char(request.family_contract_sha256)), ...
    'case_physics_contract_sha256', ...
        lower(char(request.case_physics_contract_sha256)), ...
    'execution_input_lock_sha256', ...
        lower(char(request.execution_input_lock_sha256)));
context.authorization_scope = char(request.authorization_scope);
context.case_id = char(request.case_id);
context.output_root = char(request.output_root);
context.state0 = struct('d_node',state0.d_node, ...
    'alpha_bar_gp',state0.alpha_bar_gp);
context.mesh = cfg.mesh;
context.contract = contract;
context.initial_state.d = state0.d_node;
context.initial_state.history = state0.alpha_bar_gp;
context.sol_step_template = cfg.sol_step_par;
if context.cycle_limit < 5 || context.cycle_limit > cfg.censor_cap
    error('toyRoadP0:InvalidDriverContext', ...
        'Solver cycle limit must remain in the declared interval 5:150.');
end
end

function localValidateRuntimeReceipt(receipt,request)
required = {'status','authorization_scope','case_id','source_commit', ...
    'runtime_lock_sha256'};
valid = isstruct(receipt) && isscalar(receipt) && all(isfield(receipt,required)) && ...
    strcmp(char(receipt.status),'PASS') && ...
    strcmp(char(receipt.authorization_scope),char(request.authorization_scope)) && ...
    strcmp(char(receipt.case_id),char(request.case_id)) && ...
    strcmpi(char(receipt.source_commit),char(request.source_commit)) && ...
    strcmpi(char(receipt.runtime_lock_sha256),char(request.runtime_lock_sha256));
if ~valid
    error('toyRoadP0:InvalidRuntimeReceipt', ...
        'Runtime receipt does not bind the authorized source/runtime/case.');
end
end

function dependencies = localProductionDependencies()
dependencies = struct( ...
    'load_parent_mesh',@localLoadProductionMesh, ...
    'build_recovery_input',@localBuildProductionRecoveryInput, ...
    'build_solver_context',@localBuildProductionSolverContext, ...
    'runtime_receipt',@localProductionRuntimeReceipt, ...
    'solve_family_case',@solve_toy_road_family_case);
end

function parentMesh = localLoadProductionMesh(inputAssetsRoot)
meshPath = fullfile(char(inputAssetsRoot),'sens_mesh.m');
if ~isfile(meshPath)
    error('toyRoadP0:MissingInputAsset', ...
        'The locked SENS mesh source is absent: %s',meshPath);
end
[meshObject,geom] = specimen.external.gmsh_import(meshPath,'t',1.0);
parentMesh = struct( ...
    'node_coords',meshObject.node, ...
    'connectivity',meshObject.elem(:,1:meshObject.nel), ...
    'runtime_mesh',meshObject, ...
    'runtime_geom',geom);
end

function input = localBuildProductionRecoveryInput(cfg,parentMesh)
mesh = parentMesh.runtime_mesh;
geom = parentMesh.runtime_geom;
mesh.node = cfg.mesh.node_coords;
tolerance = 1e-12;
top = find(abs(mesh.node(:,2)-0.5) <= tolerance);
bottom = find(abs(mesh.node(:,2)+0.5) <= tolerance);
crack = find(abs(parentMesh.node_coords(:,2)) <= tolerance & ...
    parentMesh.node_coords(:,1) <= tolerance);
boundaries = phase_field.fem.bc.set_boundaries( ...
    'fix_X',[bottom;top],'fix_Y',bottom,'disp_Y',top,'non_hom_pf',crack);
dofs = phase_field.init.dofs(mesh,boundaries);
quadrature = phase_field.init.quadrature(mesh.dim);
material = phase_field.init.material_characteristic( ...
    geom.L,'AT1','E',1,'ni',0.3,'Gc',cfg.case_physics.material.Gc, ...
    'ell',0.01,'res_stiff',0,'alpha_T',0.5,'p',2);
solPar = phase_field.fem.solver.params( ...
    'tol_displ',1e-6,'tol_p_field',4e-4, ...
    'max_iter_displ',250,'max_iter_pf',250);
stepPar = phase_field.fem.solver.step.params( ...
    'n_step',5,'loading','cyclic','discretization','loading', ...
    'uy_final',cfg.case_physics.loading.blocks(1,3), ...
    'R',0,'line_search',false);
stepPar.n_step = 5;
stepPar.line_search = false;
assemblyPf = str2func( ...
    'phase_field.mex.fem.assembly.pf.AT1_HISTORY_FATIGUE');
stressState = phase_field.StressState.PlaneStrain;
pField = zeros(mesh.num_node,1);
pField(dofs.non_hom_dirichlet_bc_pf) = 1;
history = zeros(mesh.num_elem,quadrature.num_gauss_pts,4);
factory = @(d) phase_field.System(material,geom,quadrature,dofs,boundaries, ...
    stepPar,mesh,stressState,d,'AT1');
newton = @(sys,d,dOld,historyOld,zeroRaw,lockedSolPar) ...
    localProductionRecoveryNewton(assemblyPf,sys,d,dOld,historyOld, ...
    zeroRaw,lockedSolPar);
input = struct( ...
    'p_field',pField, ...
    'p_field_old',zeros(size(pField)), ...
    'history_vars_old',history, ...
    'num_elem',mesh.num_elem, ...
    'num_gauss_pts',quadrature.num_gauss_pts, ...
    'sol_step_par',stepPar, ...
    'sol_par',solPar, ...
    'system_factory',factory, ...
    'recovery_newton',newton);
end

function [d,history,residual,failed,details] = localProductionRecoveryNewton( ...
        assemblyPf,sys,d,dOld,historyOld,zeroRaw,solPar)
[initialResidual,residual,d,coupling,history,failed] = ...
    phase_field.fem.solver.newton_raphson( ...
    assemblyPf,sys,d,dOld,zeroRaw,historyOld,sys.DOFS.active_dof_pf, ...
    sys.STIFFNESS_MATRIX.i_row_pf,sys.STIFFNESS_MATRIX.j_col_pf, ...
    'max_iter',solPar.max_iter_pf,'res_tol',solPar.tol_p_field, ...
    'line_search',false,'regularize_pf_only',true);
details = struct('initial_residual',initialResidual,'coupling_vars',coupling);
end

function context = localBuildProductionSolverContext(cfg,recovery,request)
sys = recovery.sys;
solPar = phase_field.fem.solver.params( ...
    'tol_displ',1e-6,'tol_p_field',4e-4, ...
    'max_iter_displ',250,'max_iter_pf',250);
solStag = phase_field.fem.solver.stag.params('tol',4e-4,'max_iter',1000);
assemblyPf = str2func( ...
    'phase_field.mex.fem.assembly.pf.AT1_HISTORY_FATIGUE');
assemblyEq = str2func('phase_field.mex.fem.assembly.equilibrium.AMOR');
fullHistory = recovery.history_vars;
stagVars = [];
firstPfResidual = NaN;
lastState = struct('u',zeros(sys.DOFS.num_dof,1),'d',recovery.d, ...
    'history',fullHistory(:,:,2));

operators = struct( ...
    'begin_substep',@beginSubstep, ...
    'completed_stagger_update',@completedStaggerUpdate, ...
    'reassemble_equilibrium',@reassembleEquilibrium, ...
    'reassemble_phase',@reassemblePhase, ...
    'commit_history',@commitHistory, ...
    'advance_event',@advanceEvent, ...
    'observe',@observe, ...
    'publish_failed_run',@publishFailedRun);
context = struct( ...
    'authorization_scope',char(request.authorization_scope), ...
    'case_id',char(request.case_id), ...
    'output_root',char(request.output_root), ...
    'cycle_limit',150, ...
    'active_u_dofs',double(sys.DOFS.active_dof(:)), ...
    'active_d_dofs',double(sys.DOFS.active_dof_pf(:)), ...
    'state0',struct('d_node',recovery.d,'alpha_bar_gp',fullHistory(:,:,2)), ...
    'mesh',cfg.mesh, ...
    'contract',struct(), ...
    'initial_state',lastState, ...
    'sol_step_template',cfg.sol_step_par, ...
    'sol_stag_par',struct('max_iter',double(solStag.max_iter)), ...
    'operators',operators);

    function [state,traction] = beginSubstep(cycle,ordinal,state,stepTemplate)
        factors = cfg.case_physics.loading.load_factors;
        umax = cfg.umax_for_cycle(cycle);
        stepTemplate.n_step = 5;
        stepTemplate.uy_final = umax;
        stepTemplate.ux_increment = zeros(size(factors));
        stepTemplate.uy_increment = umax*diff([0 factors]);
        stepTemplate.tx_increment = zeros(size(factors));
        stepTemplate.ty_increment = zeros(size(factors));
        [state.u,~,traction] = phase_field.fem.solver.step.pre_iter_update( ...
            ordinal,sys,state.u,stepTemplate);
        stagVars = phase_field.fem.solver.stag.vars(solStag);
        firstPfResidual = NaN;
    end

    function [state,psiRaw,converged] = completedStaggerUpdate( ...
            ~,~,stagger,state,traction,dLb,~)
        [initialU,residualU,state.u,psiRaw,~,failedU] = ...
            phase_field.fem.solver.newton_raphson( ...
            assemblyEq,sys,state.u,0,state.d,0,sys.DOFS.active_dof, ...
            sys.STIFFNESS_MATRIX.i_row,sys.STIFFNESS_MATRIX.j_col, ...
            'D_RHS_tract',traction,'max_iter',solPar.max_iter_displ, ...
            'res_tol',solPar.tol_displ,'line_search',false);
        if failedU || ~isfinite(residualU)
            error('toyRoadP0:DisplacementSolveFailed', ...
                'The displacement Newton solve failed.');
        end
        [initialD,residualD,state.d,~,~,failedD] = ...
            phase_field.fem.solver.newton_raphson( ...
            assemblyPf,sys,state.d,dLb,psiRaw,fullHistory, ...
            sys.DOFS.active_dof_pf,sys.STIFFNESS_MATRIX.i_row_pf, ...
            sys.STIFFNESS_MATRIX.j_col_pf,'max_iter',solPar.max_iter_pf, ...
            'res_tol',solPar.tol_p_field,'line_search',false, ...
            'regularize_pf_only',true);
        if failedD || ~isfinite(residualD)
            error('toyRoadP0:PhaseSolveFailed','The phase Newton solve failed.');
        end
        state.d = min(max(state.d,dLb),1);
        if stagger == 1
            firstPfResidual = initialD;
        end
        [stagVars,psiRaw,converged,sys.STIFFNESS_MATRIX.KK] = ...
            phase_field.fem.solver.stag.post_iter_update( ...
            assemblyEq,stagger,stagVars,sys,traction,state.d,state.u, ...
            firstPfResidual,residualD,initialU,solStag);
        state.history = fullHistory(:,:,2);
    end

    function [residual,raw] = reassembleEquilibrium(snapshot,u,d)
        [~,residual,raw,~] = assemblyEq(sys.MESH,sys.DOFS,sys.GEOM.t, ...
            sys.QUADRATURE,sys.MAT_CHAR,sys.CC,u,0,d, ...
            sys.stress_state.as_number,0);
        residual = residual-snapshot.traction;
    end

    function residual = reassemblePhase(snapshot,u,d,raw)
        [~,residual,~,~] = assemblyPf(sys.MESH,sys.DOFS,sys.GEOM.t, ...
            sys.QUADRATURE,sys.MAT_CHAR,sys.CC,d,snapshot.d_lb,raw, ...
            sys.stress_state.as_number,fullHistory);
        if isempty(u)
            error('toyRoadP0:InvalidReassembly','Displacement state is absent.');
        end
    end

    function historyPost = commitHistory(~,~,historyPre,snapshot)
        localRequire(max(abs(historyPre-fullHistory(:,:,2)),[],'all') <= 1e-12, ...
            'History commit input does not match the live solver history.');
        [~,~,~,fullHistory] = assemblyPf(sys.MESH,sys.DOFS,sys.GEOM.t, ...
            sys.QUADRATURE,sys.MAT_CHAR,sys.CC,snapshot.d_node, ...
            snapshot.d_node,snapshot.psi_raw_gp,sys.stress_state.as_number, ...
            fullHistory);
        historyPost = fullHistory(:,:,2);
    end

    function state = advanceEvent(state,coords,connectivity,cycle,peakDamage)
        localRequire(isequal(coords,cfg.mesh.node_coords) && ...
            isequal(connectivity,cfg.mesh.connectivity), ...
            'Event evaluation mesh differs from the declared case mesh.');
        state = cfg.advance_event(state,cycle,peakDamage);
    end

    function observe(~)
    end

    function publishFailedRun(outputRoot,scope,caseId,exception)
        payload = struct('authorization_scope',scope,'case_id',caseId, ...
            'complete',false,'status','failed', ...
            'error_identifier',exception.identifier, ...
            'error_message',exception.message);
        localPublishJson(fullfile(outputRoot,'RUN_RESULT.json'),payload);
    end
end

function receipt = localProductionRuntimeReceipt(request)
receipt = struct( ...
    'status','PASS', ...
    'authorization_scope',char(request.authorization_scope), ...
    'case_id',char(request.case_id), ...
    'source_commit',lower(char(request.source_commit)), ...
    'runtime_lock_sha256',lower(char(request.runtime_lock_sha256)), ...
    'matlab_version',version, ...
    'computer',computer, ...
    'blas',version('-blas'), ...
    'lapack',version('-lapack'));
end

function localPublishJson(path,payload)
content = [jsonencode(payload) newline];
localPublishBytes(path,unicode2native(content,'UTF-8'));
end

function localPublishMat(path,payload)
directory = fileparts(path);
temporary = localReserveTemporary(directory,'.asset_','.mat');
cleanup = onCleanup(@() localDeleteIfPresent(temporary));
save(temporary,'-struct','payload','-v7.3');
localCreateExclusiveHardLink(temporary,path);
delete(temporary);
clear cleanup
end

function localPublishBytes(path,bytes)
directory = fileparts(path);
temporary = localReserveTemporary(directory,'.asset_','.tmp');
cleanup = onCleanup(@() localDeleteIfPresent(temporary));
fileId = fopen(temporary,'wb');
if fileId < 0
    error('toyRoadP0:PublicationFailed','Cannot open temporary asset.');
end
fileCleanup = onCleanup(@() fclose(fileId));
count = fwrite(fileId,bytes,'uint8');
if count ~= numel(bytes)
    error('toyRoadP0:PublicationFailed','Cannot write complete temporary asset.');
end
clear fileCleanup
localCreateExclusiveHardLink(temporary,path);
delete(temporary);
clear cleanup
end

function path = localReserveTemporary(directory,prefix,suffix)
try
    attributes = javaArray('java.nio.file.attribute.FileAttribute',0);
    temporary = java.nio.file.Files.createTempFile( ...
        java.io.File(directory).toPath(),prefix,suffix,attributes);
    path = char(temporary.toString());
catch exception
    error('toyRoadP0:PublicationFailed', ...
        'Cannot reserve temporary asset: %s',exception.message);
end
end

function localCreateExclusiveHardLink(temporary,path)
try
    java.nio.file.Files.createLink( ...
        java.io.File(path).toPath(),java.io.File(temporary).toPath());
catch exception
    if isfile(path) || isfolder(path)
        error('toyRoadP0:PublicationClobber', ...
            'Refusing to overwrite published asset: %s',path);
    end
    error('toyRoadP0:PublicationFailed', ...
        'Cannot publish immutable asset: %s',exception.message);
end
end

function localDeleteIfPresent(path)
if isfile(path)
    delete(path);
end
end

function value = localText(value)
value = (ischar(value) && isrow(value) && ~isempty(value)) || ...
    (isstring(value) && isscalar(value) && strlength(value) > 0);
end

function value = localHex(value,lengthRequired)
if ~localText(value)
    value = false;
    return;
end
text = char(value);
value = numel(text) == lengthRequired && ...
    all(ismember(lower(text),'0123456789abcdef'));
end

function localRequire(condition,message)
if ~condition
    error('toyRoadP0:InvalidDriverContext',message);
end
end
