function result = main_toy_road_family_case(varargin)
%MAIN_TOY_ROAD_FAMILY_CASE Build state0 and run one authorized fresh case.

if nargin ~= 0
    error('toyRoadP0:AuthorizationRejected', ...
        ['The production entrypoint accepts no injected request or callback. ' ...
         'Task 6 authorization must enter through the locked environment.']);
end
request = localReadEnvironment();
dependencies = localProductionDependencies();
localValidateRequest(request);
localValidateAuthorization(request);
result = run_toy_road_driver_core(request,dependencies);
end

function request = localReadEnvironment()
names = { ...
    'TOY_ROAD_CASE_ROLE', ...
    'TOY_ROAD_SOURCE_COMMIT', ...
    'TOY_ROAD_RUNTIME_LOCK_SHA256', ...
    'TOY_ROAD_FAMILY_CONTRACT_SHA256', ...
    'TOY_ROAD_CASE_PHYSICS_CONTRACT_SHA256', ...
    'TOY_ROAD_EXECUTION_INPUT_LOCK_SHA256', ...
    'TOY_ROAD_OUTPUT_ROOT', ...
    'TOY_ROAD_WORK_ROOT', ...
    'TOY_ROAD_TEMP_ROOT', ...
    'TOY_ROAD_TMP_ROOT', ...
    'TOY_ROAD_PREF_ROOT', ...
    'TOY_ROAD_CACHE_ROOT', ...
    'TOY_ROAD_INPUT_ASSETS_ROOT', ...
    'TOY_ROAD_AUTHORIZATION_RECEIPT'};
values = cellfun(@getenv,names,'UniformOutput',false);
missing = names(cellfun(@(value) isempty(strtrim(value)),values));
if ~isempty(missing)
    error('toyRoadP0:MissingEnvironment', ...
        'Required environment variable is empty: %s',strjoin(missing,', '));
end
authorizationPath = values{14};
if ~isfile(authorizationPath)
    error('toyRoadP0:AuthorizationRejected', ...
        'The launcher authorization receipt is absent.');
end
authorizationReceipt = jsondecode(fileread(authorizationPath));
request = struct( ...
    'authorization_scope',localReceiptScope(authorizationReceipt), ...
    'authorization_receipt',authorizationReceipt, ...
    'case_id',values{1}, ...
    'source_commit',values{2}, ...
    'runtime_lock_sha256',lower(values{3}), ...
    'family_contract_sha256',lower(values{4}), ...
    'case_physics_contract_sha256',lower(values{5}), ...
    'execution_input_lock_sha256',lower(values{6}), ...
    'output_root',values{7}, ...
    'work_root',values{8}, ...
    'temp_root',values{9}, ...
    'tmp_root',values{10}, ...
    'pref_root',values{11}, ...
    'cache_root',values{12}, ...
    'input_assets_root',values{13});
end

function value = localReceiptScope(receipt)
if ~isstruct(receipt) || ~isscalar(receipt) || ...
        ~isfield(receipt,'authorization_scope')
    error('toyRoadP0:AuthorizationRejected', ...
        'The launcher receipt has no authorization scope.');
end
value = receipt.authorization_scope;
end

function localValidateRequest(request)
required = {'authorization_scope','authorization_receipt','case_id', ...
    'source_commit','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256', ...
    'output_root','work_root','temp_root','tmp_root','pref_root','cache_root', ...
    'input_assets_root'};
valid = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)),sort(required(:)));
if valid
    roles = {'P0_parent','P0R_parent_repeat','T1_initial_defect', ...
        'T2_material_state','T3_loading_history'};
    valid = localText(request.authorization_scope) && ...
        localText(request.case_id) && any(strcmp(char(request.case_id),roles)) && ...
        localHex(request.source_commit,40) && ...
        localHex(request.runtime_lock_sha256,64) && ...
        localHex(request.family_contract_sha256,64) && ...
        localHex(request.case_physics_contract_sha256,64) && ...
        localHex(request.execution_input_lock_sha256,64) && ...
        isstruct(request.authorization_receipt) && ...
        isscalar(request.authorization_receipt);
    paths = required(9:end);
    for index = 1:numel(paths)
        valid = valid && localText(request.(paths{index}));
    end
end
if ~valid
    error('toyRoadP0:InvalidDriverRequest', ...
        'Driver request fields, identities, or paths are invalid.');
end
end

function localValidateAuthorization(request)
scope = char(request.authorization_scope);
if ~strcmp(scope,'production_authorized')
    error('toyRoadP0:AuthorizationRejected', ...
        'This authorization scope cannot execute the producer driver.');
end
receipt = request.authorization_receipt;
required = {'status','authorization_scope','authorized_entrypoint','case_id', ...
    'source_commit','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256', ...
    'upstream_authorized_entrypoint','upstream_launch_receipt_path', ...
    'upstream_launch_receipt_sha256'};
valid = all(isfield(receipt,required)) && ...
    strcmp(char(receipt.status),'PASS') && ...
    strcmp(char(receipt.authorization_scope),scope) && ...
    strcmp(char(receipt.authorized_entrypoint),'main_toy_road_family_case') && ...
    strcmp(char(receipt.upstream_authorized_entrypoint), ...
        'run_toy_road_runtime_bridge') && ...
    strcmp(char(receipt.case_id),char(request.case_id)) && ...
    strcmpi(char(receipt.source_commit),char(request.source_commit)) && ...
    strcmpi(char(receipt.runtime_lock_sha256),char(request.runtime_lock_sha256)) && ...
    strcmpi(char(receipt.family_contract_sha256),char(request.family_contract_sha256)) && ...
    strcmpi(char(receipt.case_physics_contract_sha256), ...
        char(request.case_physics_contract_sha256)) && ...
    strcmpi(char(receipt.execution_input_lock_sha256), ...
        char(request.execution_input_lock_sha256)) && ...
    localText(receipt.upstream_launch_receipt_path) && ...
    localHex(receipt.upstream_launch_receipt_sha256,64) && ...
    isfile(char(receipt.upstream_launch_receipt_path)) && ...
    strcmpi(fileSha256(receipt.upstream_launch_receipt_path), ...
        char(receipt.upstream_launch_receipt_sha256));
if valid
    upstream = jsondecode(fileread(char(receipt.upstream_launch_receipt_path)));
    upstreamRequired = {'status','authorization_scope','authorized_entrypoint', ...
        'case_id','source_commit','runtime_lock_sha256','family_contract_sha256', ...
        'case_physics_contract_sha256','execution_input_lock_sha256'};
    valid = isstruct(upstream) && isscalar(upstream) && ...
        all(isfield(upstream,upstreamRequired)) && ...
        strcmp(char(upstream.status),'PASS') && ...
        strcmp(char(upstream.authorization_scope),scope) && ...
        strcmp(char(upstream.authorized_entrypoint), ...
            'run_toy_road_runtime_bridge') && ...
        strcmp(char(upstream.case_id),char(request.case_id)) && ...
        strcmpi(char(upstream.source_commit),char(request.source_commit)) && ...
        strcmpi(char(upstream.runtime_lock_sha256),char(request.runtime_lock_sha256)) && ...
        strcmpi(char(upstream.family_contract_sha256),char(request.family_contract_sha256)) && ...
        strcmpi(char(upstream.case_physics_contract_sha256), ...
            char(request.case_physics_contract_sha256)) && ...
        strcmpi(char(upstream.execution_input_lock_sha256), ...
            char(request.execution_input_lock_sha256));
end
if ~valid
    error('toyRoadP0:AuthorizationRejected', ...
        'Authorization receipt does not bind this exact execution.');
end

function digest = fileSha256(path)
path = char(path);
fileId = fopen(path, 'rb');
if fileId < 0
    error('toyRoadP0:AuthorizationRejected', ...
        'Cannot read authorization-chain receipt.');
end
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, '*uint8');
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(bytes);
digestBytes = typecast(hasher.digest(), 'uint8');
digest = lower(reshape(dec2hex(digestBytes,2).',1,[]));
end
end

function dependencies = localProductionDependencies()
dependencies = struct( ...
    'load_parent_mesh',@localLoadProductionMesh, ...
    'build_recovery_input',@localBuildProductionRecoveryInput, ...
    'build_solver_context',@localBuildProductionSolverContext, ...
    'runtime_receipt',@localProductionRuntimeReceipt, ...
    'solve_family_case',@solve_toy_road_family_case);
end

function parentMesh = localLoadProductionMesh(inputAssetsRoot)
meshPath = fullfile(char(inputAssetsRoot),'sens_mesh.m');
if ~isfile(meshPath)
    error('toyRoadP0:MissingInputAsset', ...
        'The locked SENS mesh source is absent: %s',meshPath);
end
[meshObject,geom] = specimen.external.gmsh_import(meshPath,'t',1.0);
parentMesh = struct( ...
    'node_coords',meshObject.node, ...
    'connectivity',meshObject.elem(:,1:meshObject.nel), ...
    'runtime_mesh',meshObject, ...
    'runtime_geom',geom);
end

function input = localBuildProductionRecoveryInput(cfg,parentMesh)
mesh = parentMesh.runtime_mesh;
geom = parentMesh.runtime_geom;
mesh.node = cfg.mesh.node_coords;
tolerance = 1e-12;
top = find(abs(mesh.node(:,2)-0.5) <= tolerance);
bottom = find(abs(mesh.node(:,2)+0.5) <= tolerance);
crack = find(abs(parentMesh.node_coords(:,2)) <= tolerance & ...
    parentMesh.node_coords(:,1) <= tolerance);
boundaries = phase_field.fem.bc.set_boundaries( ...
    'fix_X',[bottom;top],'fix_Y',bottom,'disp_Y',top,'non_hom_pf',crack);
dofs = phase_field.init.dofs(mesh,boundaries);
quadrature = phase_field.init.quadrature(mesh.dim);
material = phase_field.init.material_characteristic( ...
    geom.L,'AT1','E',1,'ni',0.3,'Gc',cfg.case_physics.material.Gc, ...
    'ell',0.01,'res_stiff',0,'alpha_T',0.5,'p',2);
solPar = phase_field.fem.solver.params( ...
    'tol_displ',1e-6,'tol_p_field',4e-4, ...
    'max_iter_displ',250,'max_iter_pf',250);
stepPar = build_toy_road_five_step_params( ...
    cfg.case_physics.loading.blocks(1,3));
assemblyPf = str2func( ...
    'phase_field.mex.fem.assembly.pf.AT1_HISTORY_FATIGUE');
stressState = phase_field.StressState.PlaneStrain;
pField = zeros(mesh.num_node,1);
pField(dofs.non_hom_dirichlet_bc_pf) = 1;
history = zeros(mesh.num_elem,quadrature.num_gauss_pts,4);
factoryCallCount = 0;
factory = @buildSystem;
newton = @(sys,d,dOld,historyOld,zeroRaw,lockedSolPar) ...
    localProductionRecoveryNewton(assemblyPf,sys,d,dOld,historyOld, ...
    zeroRaw,lockedSolPar);
input = struct( ...
    'p_field',pField, ...
    'p_field_old',zeros(size(pField)), ...
    'history_vars_old',history, ...
    'num_elem',mesh.num_elem, ...
    'num_gauss_pts',quadrature.num_gauss_pts, ...
    'sol_step_par',stepPar, ...
    'sol_par',solPar, ...
    'system_validation_mode','production_phase_field_system_v1', ...
    'system_factory',factory, ...
    'recovery_newton',newton);

    function [system,record] = buildSystem(d)
        factoryCallCount = factoryCallCount + 1;
        system = phase_field.System(material,geom,quadrature,dofs,boundaries, ...
            stepPar,mesh,stressState,d,'AT1');
        record = struct( ...
            'construction_ordinal',factoryCallCount, ...
            'phase_field',d, ...
            'system_class',class(system), ...
            'system_identity',sprintf('%s#%d',class(system),factoryCallCount));
    end
end

function [d,history,residual,failed,details] = localProductionRecoveryNewton( ...
        assemblyPf,sys,d,dOld,historyOld,zeroRaw,solPar)
[initialResidual,residual,d,coupling,history,failed] = ...
    phase_field.fem.solver.newton_raphson( ...
    assemblyPf,sys,d,dOld,zeroRaw,historyOld,sys.DOFS.active_dof_pf, ...
    sys.STIFFNESS_MATRIX.i_row_pf,sys.STIFFNESS_MATRIX.j_col_pf, ...
    'max_iter',solPar.max_iter_pf,'res_tol',solPar.tol_p_field, ...
    'line_search',false,'regularize_pf_only',true);
details = struct('initial_residual',initialResidual,'coupling_vars',coupling);
end

function context = localBuildProductionSolverContext(cfg,recovery,request)
sys = recovery.sys;
solPar = phase_field.fem.solver.params( ...
    'tol_displ',1e-6,'tol_p_field',4e-4, ...
    'max_iter_displ',250,'max_iter_pf',250);
solStag = phase_field.fem.solver.stag.params('tol',4e-4,'max_iter',1000);
assemblyPf = str2func( ...
    'phase_field.mex.fem.assembly.pf.AT1_HISTORY_FATIGUE');
assemblyEq = str2func('phase_field.mex.fem.assembly.equilibrium.AMOR');
fullHistory = recovery.history_vars;
stagVars = [];
firstPfResidual = NaN;
lastState = struct('u',zeros(sys.DOFS.num_dof,1),'d',recovery.d, ...
    'history',fullHistory(:,:,2));

operators = struct( ...
    'begin_substep',@beginSubstep, ...
    'completed_stagger_update',@completedStaggerUpdate, ...
    'reassemble_equilibrium',@reassembleEquilibrium, ...
    'reassemble_phase',@reassemblePhase, ...
    'commit_history',@commitHistory, ...
    'advance_event',@advanceEvent, ...
    'observe',@observe, ...
    'publish_failed_run',@publishFailedRun);
context = struct( ...
    'authorization_scope',char(request.authorization_scope), ...
    'case_id',char(request.case_id), ...
    'output_root',char(request.output_root), ...
    'cycle_limit',150, ...
    'active_u_dofs',double(sys.DOFS.active_dof(:)), ...
    'active_d_dofs',double(sys.DOFS.active_dof_pf(:)), ...
    'state0',struct('d_node',recovery.d,'alpha_bar_gp',fullHistory(:,:,2)), ...
    'mesh',cfg.mesh, ...
    'contract',struct(), ...
    'initial_state',lastState, ...
    'sol_step_template',cfg.sol_step_par, ...
    'sol_stag_par',struct('max_iter',double(solStag.max_iter)), ...
    'operators',operators);

    function [state,traction] = beginSubstep(cycle,ordinal,state,stepTemplate)
        factors = cfg.case_physics.loading.load_factors;
        umax = cfg.umax_for_cycle(cycle);
        stepTemplate.n_step = 5;
        stepTemplate.uy_final = umax;
        stepTemplate.ux_increment = zeros(size(factors));
        stepTemplate.uy_increment = umax*diff([0 factors]);
        stepTemplate.tx_increment = zeros(size(factors));
        stepTemplate.ty_increment = zeros(size(factors));
        [state.u,~,traction] = phase_field.fem.solver.step.pre_iter_update( ...
            ordinal,sys,state.u,stepTemplate);
        stagVars = phase_field.fem.solver.stag.vars(solStag);
        firstPfResidual = NaN;
    end

    function [state,psiRaw,converged] = completedStaggerUpdate( ...
            ~,~,stagger,state,traction,dLb,~)
        [initialU,residualU,state.u,psiRaw,~,failedU] = ...
            phase_field.fem.solver.newton_raphson( ...
            assemblyEq,sys,state.u,0,state.d,0,sys.DOFS.active_dof, ...
            sys.STIFFNESS_MATRIX.i_row,sys.STIFFNESS_MATRIX.j_col, ...
            'D_RHS_tract',traction,'max_iter',solPar.max_iter_displ, ...
            'res_tol',solPar.tol_displ,'line_search',false);
        if failedU || ~isfinite(residualU)
            error('toyRoadP0:DisplacementSolveFailed', ...
                'The displacement Newton solve failed.');
        end
        [initialD,residualD,state.d,~,~,failedD] = ...
            phase_field.fem.solver.newton_raphson( ...
            assemblyPf,sys,state.d,dLb,psiRaw,fullHistory, ...
            sys.DOFS.active_dof_pf,sys.STIFFNESS_MATRIX.i_row_pf, ...
            sys.STIFFNESS_MATRIX.j_col_pf,'max_iter',solPar.max_iter_pf, ...
            'res_tol',solPar.tol_p_field,'line_search',false, ...
            'regularize_pf_only',true);
        if failedD || ~isfinite(residualD)
            error('toyRoadP0:PhaseSolveFailed','The phase Newton solve failed.');
        end
        state.d = min(max(state.d,dLb),1);
        if stagger == 1
            firstPfResidual = initialD;
        end
        [stagVars,psiRaw,converged,sys.STIFFNESS_MATRIX.KK] = ...
            phase_field.fem.solver.stag.post_iter_update( ...
            assemblyEq,stagger,stagVars,sys,traction,state.d,state.u, ...
            firstPfResidual,residualD,initialU,solStag);
        state.history = fullHistory(:,:,2);
    end

    function [residual,raw] = reassembleEquilibrium(snapshot,u,d)
        [~,residual,raw,~] = assemblyEq(sys.MESH,sys.DOFS,sys.GEOM.t, ...
            sys.QUADRATURE,sys.MAT_CHAR,sys.CC,u,0,d, ...
            sys.stress_state.as_number,0);
        residual = residual-snapshot.traction;
    end

    function residual = reassemblePhase(snapshot,u,d,raw)
        [~,residual,~,~] = assemblyPf(sys.MESH,sys.DOFS,sys.GEOM.t, ...
            sys.QUADRATURE,sys.MAT_CHAR,sys.CC,d,snapshot.d_lb,raw, ...
            sys.stress_state.as_number,fullHistory);
        if isempty(u)
            error('toyRoadP0:InvalidReassembly','Displacement state is absent.');
        end
    end

    function historyPost = commitHistory(~,~,historyPre,snapshot)
        localRequire(max(abs(historyPre-fullHistory(:,:,2)),[],'all') <= 1e-12, ...
            'History commit input does not match the live solver history.');
        [~,~,~,fullHistory] = assemblyPf(sys.MESH,sys.DOFS,sys.GEOM.t, ...
            sys.QUADRATURE,sys.MAT_CHAR,sys.CC,snapshot.d_node, ...
            snapshot.d_node,snapshot.psi_raw_gp,sys.stress_state.as_number, ...
            fullHistory);
        historyPost = fullHistory(:,:,2);
    end

    function state = advanceEvent(state,coords,connectivity,cycle,peakDamage)
        localRequire(isequal(coords,cfg.mesh.node_coords) && ...
            isequal(connectivity,cfg.mesh.connectivity), ...
            'Event evaluation mesh differs from the declared case mesh.');
        state = cfg.advance_event(state,cycle,peakDamage);
    end

    function observe(~)
    end

    function publishFailedRun(outputRoot,scope,caseId,exception)
        payload = struct('authorization_scope',scope,'case_id',caseId, ...
            'complete',false,'status','failed', ...
            'error_identifier',exception.identifier, ...
            'error_message',exception.message);
        localPublishJson(fullfile(outputRoot,'RUN_RESULT.json'),payload);
    end
end

function receipt = localProductionRuntimeReceipt(request)
receipt = struct( ...
    'status','PASS', ...
    'authorization_scope',char(request.authorization_scope), ...
    'case_id',char(request.case_id), ...
    'source_commit',lower(char(request.source_commit)), ...
    'runtime_lock_sha256',lower(char(request.runtime_lock_sha256)), ...
    'matlab_version',version, ...
    'computer',computer, ...
    'blas',version('-blas'), ...
    'lapack',version('-lapack'));
end

function localPublishJson(path,payload)
content = [jsonencode(payload) newline];
localPublishBytes(path,unicode2native(content,'UTF-8'));
end

function localPublishBytes(path,bytes)
directory = fileparts(path);
temporary = localReserveTemporary(directory,'.asset_','.tmp');
cleanup = onCleanup(@() localDeleteIfPresent(temporary));
fileId = fopen(temporary,'wb');
if fileId < 0
    error('toyRoadP0:PublicationFailed','Cannot open temporary asset.');
end
fileCleanup = onCleanup(@() fclose(fileId));
count = fwrite(fileId,bytes,'uint8');
if count ~= numel(bytes)
    error('toyRoadP0:PublicationFailed','Cannot write complete temporary asset.');
end
clear fileCleanup
localCreateExclusiveHardLink(temporary,path);
delete(temporary);
clear cleanup
end

function path = localReserveTemporary(directory,prefix,suffix)
try
    attributes = javaArray('java.nio.file.attribute.FileAttribute',0);
    temporary = java.nio.file.Files.createTempFile( ...
        java.io.File(directory).toPath(),prefix,suffix,attributes);
    path = char(temporary.toString());
catch exception
    error('toyRoadP0:PublicationFailed', ...
        'Cannot reserve temporary asset: %s',exception.message);
end
end

function localCreateExclusiveHardLink(temporary,path)
try
    java.nio.file.Files.createLink( ...
        java.io.File(path).toPath(),java.io.File(temporary).toPath());
catch exception
    if isfile(path) || isfolder(path)
        error('toyRoadP0:PublicationClobber', ...
            'Refusing to overwrite published asset: %s',path);
    end
    error('toyRoadP0:PublicationFailed', ...
        'Cannot publish immutable asset: %s',exception.message);
end
end

function localDeleteIfPresent(path)
if isfile(path)
    delete(path);
end
end

function value = localText(value)
value = (ischar(value) && isrow(value) && ~isempty(value)) || ...
    (isstring(value) && isscalar(value) && strlength(value) > 0);
end

function value = localHex(value,lengthRequired)
if ~localText(value)
    value = false;
    return;
end
text = char(value);
value = numel(text) == lengthRequired && ...
    all(ismember(lower(text),'0123456789abcdef'));
end

function localRequire(condition,message)
if ~condition
    error('toyRoadP0:InvalidDriverContext',message);
end
end
