function [sys,pField,pFieldOld,historyVars,details] = ...
        recover_toy_road_family_state(input)
%RECOVER_TOY_ROAD_FAMILY_STATE Recover, project, rebuild, and reset state0.

localValidateInput(input);
operationOrder = {'initial_system'};
initialSystem = input.system_factory(input.p_field);
zeroRawDriver = zeros(input.num_elem,input.num_gauss_pts);
operationOrder{end+1} = 'zero_load_recovery';
[recoveredField,recoveredHistory,recoveryResidual,nonConverged,newtonDetails] = ...
    input.recovery_newton(initialSystem,input.p_field,input.p_field_old, ...
    input.history_vars_old,zeroRawDriver,input.sol_par);
localValidateOutput(input,recoveredField,recoveredHistory,recoveryResidual, ...
    nonConverged,newtonDetails);
if nonConverged
    error('toyRoadP0:RecoveryFailed', ...
        'Fresh zero-load Hard recovery did not converge.');
end

operationOrder{end+1} = 'project_damage';
pField = min(max(recoveredField,0),1);
pFieldOld = pField;
operationOrder{end+1} = 'rebuild_system';
sys = input.system_factory(pField);

historyVars = recoveredHistory;
operationOrder{end+1} = 'reset_fatigue';
historyVars(:,:,2:3) = 0;
historyVars(:,:,4) = 1;
details = struct( ...
    'recovery_residual',recoveryResidual, ...
    'newton_details',newtonDetails, ...
    'history_vars_before_reset',recoveredHistory, ...
    'system_factory_phase_field',pField, ...
    'system_rebuilt_after_projection',true, ...
    'operation_order',{operationOrder});
end

function localValidateInput(input)
required = {'p_field','p_field_old','history_vars_old','num_elem', ...
    'num_gauss_pts','sol_step_par','sol_par','system_factory','recovery_newton'};
valid = isstruct(input) && isscalar(input) && ...
    isequal(sort(fieldnames(input)),sort(required(:)));
if valid
    valid = isa(input.p_field,'double') && isreal(input.p_field) && ...
        iscolumn(input.p_field) && ~isempty(input.p_field) && ...
        all(isfinite(input.p_field),'all') && ...
        isa(input.p_field_old,'double') && ...
        isequal(size(input.p_field_old),size(input.p_field)) && ...
        all(isfinite(input.p_field_old),'all') && ...
        isa(input.history_vars_old,'double') && ...
        isreal(input.history_vars_old) && ndims(input.history_vars_old) == 3 && ...
        size(input.history_vars_old,1) == input.num_elem && ...
        size(input.history_vars_old,2) == input.num_gauss_pts && ...
        size(input.history_vars_old,3) >= 4 && ...
        all(isfinite(input.history_vars_old),'all') && ...
        localPositiveInteger(input.num_elem) && ...
        localPositiveInteger(input.num_gauss_pts) && ...
        isstruct(input.sol_step_par) && isscalar(input.sol_step_par) && ...
        isfield(input.sol_step_par,'n_step') && ...
        input.sol_step_par.n_step == 5 && ...
        isfield(input.sol_step_par,'line_search') && ...
        islogical(input.sol_step_par.line_search) && ...
        ~input.sol_step_par.line_search && ...
        isstruct(input.sol_par) && isscalar(input.sol_par) && ...
        all(isfield(input.sol_par,{'max_iter_pf','tol_p_field'})) && ...
        localPositiveInteger(input.sol_par.max_iter_pf) && ...
        input.sol_par.tol_p_field == 4e-4 && ...
        isa(input.system_factory,'function_handle') && ...
        isa(input.recovery_newton,'function_handle');
end
if ~valid
    error('toyRoadP0:InvalidRecoveryInput', ...
        'Recovery input must be the exact five-step Hard-recovery contract.');
end
end

function localValidateOutput(input,d,history,residual,failed,newtonDetails)
valid = isa(d,'double') && isreal(d) && ...
    isequal(size(d),size(input.p_field)) && all(isfinite(d),'all') && ...
    isa(history,'double') && isreal(history) && ...
    isequal(size(history),size(input.history_vars_old)) && ...
    all(isfinite(history),'all') && ...
    isnumeric(residual) && isreal(residual) && isscalar(residual) && ...
    isfinite(residual) && residual >= 0 && ...
    islogical(failed) && isscalar(failed) && ...
    isstruct(newtonDetails) && isscalar(newtonDetails);
if ~valid
    error('toyRoadP0:InvalidRecoveryOutput', ...
        'Recovery Newton returned invalid shapes, values, or status.');
end
end

function value = localPositiveInteger(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 1 && value == floor(value);
end
