function [sys,pField,pFieldOld,historyVars,details] = ...
        recover_toy_road_family_state(input)
%RECOVER_TOY_ROAD_FAMILY_STATE Recover, project, rebuild, and reset state0.

localValidateInput(input);
operationOrder = {'initial_system'};
[initialSystem,initialRecord] = input.system_factory(input.p_field);
localValidateFactoryResult(initialSystem,initialRecord,input.p_field,1,[]);
zeroRawDriver = zeros(input.num_elem,input.num_gauss_pts);
operationOrder{end+1} = 'zero_load_recovery';
[recoveredField,recoveredHistory,recoveryResidual,nonConverged,newtonDetails] = ...
    input.recovery_newton(initialSystem,input.p_field,input.p_field_old, ...
    input.history_vars_old,zeroRawDriver,input.sol_par);
localValidateOutput(input,recoveredField,recoveredHistory,recoveryResidual, ...
    nonConverged,newtonDetails);
if nonConverged
    error('toyRoadP0:RecoveryFailed', ...
        'Fresh zero-load Hard recovery did not converge.');
end

operationOrder{end+1} = 'project_damage';
pField = min(max(recoveredField,0),1);
pFieldOld = pField;
operationOrder{end+1} = 'rebuild_system';
[sys,rebuildRecord] = input.system_factory(pField);
localValidateFactoryResult(sys,rebuildRecord,pField,2,initialSystem);
if strcmp(char(initialRecord.system_identity),char(rebuildRecord.system_identity))
    error('toyRoadP0:StaleRecoverySystem', ...
        'System construction records must identify distinct instances.');
end

historyVars = recoveredHistory;
operationOrder{end+1} = 'reset_fatigue';
historyVars(:,:,2:3) = 0;
historyVars(:,:,4) = 1;
details = struct( ...
    'recovery_residual',recoveryResidual, ...
    'newton_details',newtonDetails, ...
    'history_vars_before_reset',recoveredHistory, ...
    'system_factory_phase_field',rebuildRecord.phase_field, ...
    'system_factory_records',[initialRecord rebuildRecord], ...
    'system_rebuilt_after_projection',true, ...
    'operation_order',{operationOrder});
end

function localValidateInput(input)
required = {'p_field','p_field_old','history_vars_old','num_elem', ...
    'num_gauss_pts','sol_step_par','sol_par','system_factory','recovery_newton'};
valid = isstruct(input) && isscalar(input) && ...
    isequal(sort(fieldnames(input)),sort(required(:)));
if valid
    valid = isa(input.p_field,'double') && isreal(input.p_field) && ...
        iscolumn(input.p_field) && ~isempty(input.p_field) && ...
        all(isfinite(input.p_field),'all') && ...
        isa(input.p_field_old,'double') && ...
        isequal(size(input.p_field_old),size(input.p_field)) && ...
        all(isfinite(input.p_field_old),'all') && ...
        isa(input.history_vars_old,'double') && ...
        isreal(input.history_vars_old) && ndims(input.history_vars_old) == 3 && ...
        size(input.history_vars_old,1) == input.num_elem && ...
        size(input.history_vars_old,2) == input.num_gauss_pts && ...
        size(input.history_vars_old,3) >= 4 && ...
        all(isfinite(input.history_vars_old),'all') && ...
        localPositiveInteger(input.num_elem) && ...
        localPositiveInteger(input.num_gauss_pts) && ...
        isstruct(input.sol_step_par) && isscalar(input.sol_step_par) && ...
        localValidFiveStep(input.sol_step_par) && ...
        isstruct(input.sol_par) && isscalar(input.sol_par) && ...
        all(isfield(input.sol_par,{'max_iter_pf','tol_p_field'})) && ...
        localPositiveInteger(input.sol_par.max_iter_pf) && ...
        input.sol_par.tol_p_field == 4e-4 && ...
        isa(input.system_factory,'function_handle') && ...
        isa(input.recovery_newton,'function_handle');
end
if ~valid
    error('toyRoadP0:InvalidRecoveryInput', ...
        'Recovery input must be the exact five-step Hard-recovery contract.');
end
end

function valid = localValidFiveStep(step)
required = {'n_step','loading','discretization','uy_final','R', ...
    'line_search','ux_increment','uy_increment','tx_increment','ty_increment'};
valid = isstruct(step) && isscalar(step) && all(isfield(step,required));
if ~valid
    return
end
factors = [0.25 0.50 0.75 1.00 0.00];
increments = required(7:end);
valid = isequal(step.n_step,5) && localText(step.loading) && ...
    strcmp(char(step.loading),'cyclic') && localText(step.discretization) && ...
    strcmp(char(step.discretization),'loading') && ...
    isa(step.uy_final,'double') && isreal(step.uy_final) && ...
    isscalar(step.uy_final) && isfinite(step.uy_final) && step.uy_final > 0 && ...
    isequal(step.R,0) && islogical(step.line_search) && ...
    isscalar(step.line_search) && ~step.line_search;
for index = 1:numel(increments)
    value = step.(increments{index});
    valid = valid && isa(value,'double') && isreal(value) && ...
        isequal(size(value),[1 5]) && all(isfinite(value),'all');
end
valid = valid && isequal(step.ux_increment,zeros(1,5)) && ...
    isequal(step.tx_increment,zeros(1,5)) && ...
    isequal(step.ty_increment,zeros(1,5)) && ...
    isequal(step.uy_increment,step.uy_final*diff([0 factors]));
end

function localValidateFactoryResult(system,record,requestedField,ordinal,priorSystem)
requiredProperties = {'DOFS','STIFFNESS_MATRIX'};
validSystem = isobject(system) && isa(system,'handle') && isscalar(system) && ...
    all(cellfun(@(name) isprop(system,name),requiredProperties));
requiredRecord = {'construction_ordinal','phase_field','system_class', ...
    'system_identity'};
validRecord = isstruct(record) && isscalar(record) && ...
    isequal(sort(fieldnames(record)),sort(requiredRecord(:))) && ...
    isequal(record.construction_ordinal,ordinal) && ...
    isequal(record.phase_field,requestedField) && ...
    localText(record.system_class) && ...
    strcmp(char(record.system_class),class(system)) && ...
    localText(record.system_identity);
if ~(validSystem && validRecord)
    error('toyRoadP0:InvalidRecoverySystem', ...
        'System factory returned an incompatible handle or invalid construction record.');
end
if ~isempty(priorSystem)
    compatible = strcmp(class(system),class(priorSystem));
    try
        reused = system == priorSystem;
    catch
        reused = isequal(system,priorSystem);
    end
    if ~compatible
        error('toyRoadP0:InvalidRecoverySystem', ...
            'Projected-damage System is incompatible with the initial System.');
    end
    if reused
        error('toyRoadP0:StaleRecoverySystem', ...
            'Projected-damage recovery must construct a distinct System handle.');
    end
end
end

function valid = localText(value)
valid = (ischar(value) && isrow(value) && ~isempty(strtrim(value))) || ...
    (isstring(value) && isscalar(value) && strlength(strtrim(value)) > 0);
end

function localValidateOutput(input,d,history,residual,failed,newtonDetails)
valid = isa(d,'double') && isreal(d) && ...
    isequal(size(d),size(input.p_field)) && all(isfinite(d),'all') && ...
    isa(history,'double') && isreal(history) && ...
    isequal(size(history),size(input.history_vars_old)) && ...
    all(isfinite(history),'all') && ...
    isnumeric(residual) && isreal(residual) && isscalar(residual) && ...
    isfinite(residual) && residual >= 0 && ...
    islogical(failed) && isscalar(failed) && ...
    isstruct(newtonDetails) && isscalar(newtonDetails);
if ~valid
    error('toyRoadP0:InvalidRecoveryOutput', ...
        'Recovery Newton returned invalid shapes, values, or status.');
end
end

function value = localPositiveInteger(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 1 && value == floor(value);
end
