function [result,observations] = run_toy_road_controlled_driver_harness(request)
%RUN_TOY_ROAD_CONTROLLED_DRIVER_HARNESS Exercise the core with local doubles.

if nargin ~= 1 || ~localControlledReceipt(request)
    error('toyRoadP0:ControlledHarnessRejected', ...
        'The controlled harness requires its non-authorizing test receipt.');
end

factoryInputs = {};
solverInvocationCount = 0;
boundContext = struct();
dependencies = struct( ...
    'load_parent_mesh',@loadParentMesh, ...
    'build_recovery_input',@buildRecoveryInput, ...
    'build_solver_context',@buildSolverContext, ...
    'runtime_receipt',@runtimeReceipt, ...
    'solve_family_case',@solveControlled);
result = run_toy_road_driver_core(request,dependencies);
observations = struct( ...
    'solver_invocation_count',solverInvocationCount, ...
    'factory_inputs',{factoryInputs}, ...
    'bound_context',boundContext);
if localContainsExecutable(observations) || localContainsExecutable(result)
    error('toyRoadP0:ControlledHarnessObservationRejected', ...
        'Controlled harness observations must contain values only.');
end

    function mesh = loadParentMesh(~)
        mesh = struct( ...
            'node_coords',[-.5 -.5;.5 -.5;.5 .5;-.5 .5], ...
            'connectivity',[1 2 3 4]);
    end

    function input = buildRecoveryInput(cfg,~)
        input = struct( ...
            'p_field',zeros(4,1), ...
            'p_field_old',zeros(4,1), ...
            'history_vars_old',zeros(1,4,4), ...
            'num_elem',1, ...
            'num_gauss_pts',4, ...
            'sol_step_par',cfg.sol_step_par, ...
            'sol_par',struct('max_iter_pf',25,'tol_p_field',4e-4), ...
            'system_validation_mode','controlled_value_double_v1', ...
            'system_factory',@systemFactory, ...
            'recovery_newton',@recoveryNewton);
    end

    function [system,record] = systemFactory(d)
        factoryInputs{end+1} = d;
        ordinal = numel(factoryInputs);
        system = struct( ...
            'sentinel_kind','toy_road_controlled_system_value_v1', ...
            'construction_ordinal',double(ordinal), ...
            'phase_field_input',d, ...
            'DOFS',double((1:numel(d)).'), ...
            'STIFFNESS_MATRIX',eye(numel(d)));
        record = struct( ...
            'construction_ordinal',double(ordinal), ...
            'phase_field',d, ...
            'system_class','toy_road_controlled_system_value_v1', ...
            'system_identity',sprintf('controlled_value_system_%d',ordinal));
    end

    function [d,history,residual,failed,details] = recoveryNewton(varargin)
        d = [-1e-8;0.25;0.75;1+1e-8];
        history = 7*ones(1,4,4);
        residual = 2e-5;
        failed = false;
        details = struct('kind','local_controlled_zero_load');
    end

    function context = buildSolverContext(~,~,controlledRequest)
        operators = struct( ...
            'begin_substep',@unreachableOperator, ...
            'completed_stagger_update',@unreachableOperator, ...
            'reassemble_equilibrium',@unreachableOperator, ...
            'reassemble_phase',@unreachableOperator, ...
            'commit_history',@unreachableOperator, ...
            'advance_event',@unreachableOperator, ...
            'observe',@unreachableOperator, ...
            'publish_failed_run',@unreachableOperator);
        context = struct( ...
            'authorization_scope','UNBOUND_CONTROLLED_SCOPE', ...
            'case_id',controlledRequest.case_id, ...
            'output_root',controlledRequest.output_root, ...
            'cycle_limit',5, ...
            'active_u_dofs',[1;2], ...
            'active_d_dofs',[1;2], ...
            'state0',struct(), ...
            'mesh',struct(), ...
            'contract',struct(), ...
            'initial_state',struct( ...
                'u',zeros(4,1),'d',zeros(4,1),'history',zeros(1,4)), ...
            'sol_step_template',struct(), ...
            'sol_stag_par',struct('max_iter',8), ...
            'operators',operators);
    end

    function receipt = runtimeReceipt(controlledRequest)
        receipt = struct( ...
            'status','PASS', ...
            'authorization_scope',controlledRequest.authorization_scope, ...
            'case_id',controlledRequest.case_id, ...
            'source_commit',controlledRequest.source_commit, ...
            'runtime_lock_sha256',controlledRequest.runtime_lock_sha256);
    end

    function controlledResult = solveControlled(context)
        solverInvocationCount = solverInvocationCount + 1;
        boundContext = localObserveContext(context);
        controlledResult = struct( ...
            'complete',true, ...
            'case_id',context.case_id, ...
            'controlled_solver_invocations',solverInvocationCount);
    end

    function varargout = unreachableOperator(varargin)
        varargout = cell(1,nargout); %#ok<NASGU>
        error('toyRoadP0:ControlledOperatorUnexpected', ...
            'The controlled core-coverage solver must not invoke Task 4 operators.');
    end
end

function valid = localControlledReceipt(request)
requestFields = {'authorization_scope','authorization_receipt','case_id', ...
    'source_commit','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256', ...
    'output_root','work_root','temp_root','tmp_root','pref_root','cache_root', ...
    'input_assets_root'};
receiptFields = {'status','authorization_scope','authorized_entrypoint', ...
    'case_id','source_commit','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256'};

% Reject executable values before field conversion or caller-controlled dispatch.
valid = localValueOnly(request) && localExactFields(request,requestFields);
if ~valid
    return
end
receipt = request.authorization_receipt;
valid = localExactFields(receipt,receiptFields) && ...
    localExactChar(request.authorization_scope,'test_only_non_authorizing') && ...
    localExactChar(receipt.status,'PASS') && ...
    localExactChar(receipt.authorization_scope,'test_only_non_authorizing') && ...
    localExactChar(receipt.authorized_entrypoint, ...
        'run_toy_road_controlled_driver_harness') && ...
    localCaseId(request.case_id) && ...
    localLowerHex(request.source_commit,40) && ...
    localLowerHex(request.runtime_lock_sha256,64) && ...
    localLowerHex(request.family_contract_sha256,64) && ...
    localLowerHex(request.case_physics_contract_sha256,64) && ...
    localLowerHex(request.execution_input_lock_sha256,64);
if ~valid
    return
end

identityFields = receiptFields(4:end);
for index = 1:numel(identityFields)
    name = identityFields{index};
    valid = valid && localExactChar(receipt.(name),request.(name));
end
pathFields = requestFields(9:end);
for index = 1:numel(pathFields)
    valid = valid && localNonemptyCharRow(request.(pathFields{index}));
end
end

function valid = localValueOnly(value)
if builtin('isa',value,'char')
    valid = builtin('size',value,1) == 1;
    return
end
if ~builtin('isa',value,'struct')
    valid = false;
    return
end
if builtin('numel',value) ~= 1
    valid = false;
    return
end
names = builtin('fieldnames',value);
valid = true;
for index = 1:numel(names)
    if ~localValueOnly(value.(names{index}))
        valid = false;
        return
    end
end
end

function valid = localExactFields(value,required)
valid = builtin('isa',value,'struct') && builtin('numel',value) == 1;
if ~valid
    return
end
actual = builtin('fieldnames',value);
if numel(actual) ~= numel(required)
    valid = false;
    return
end
for index = 1:numel(required)
    found = false;
    for candidate = 1:numel(actual)
        if builtin('strcmp',actual{candidate},required{index})
            found = true;
            break
        end
    end
    if ~found
        valid = false;
        return
    end
end
end

function valid = localExactChar(value,expected)
valid = builtin('isa',value,'char') && builtin('size',value,1) == 1 && ...
    builtin('size',value,2) == builtin('size',expected,2) && ...
    builtin('strcmp',value,expected);
end

function valid = localNonemptyCharRow(value)
valid = builtin('isa',value,'char') && builtin('size',value,1) == 1 && ...
    builtin('size',value,2) > 0 && ~any(value == char(0)) && ...
    any(~isspace(value));
end

function valid = localLowerHex(value,requiredLength)
valid = builtin('isa',value,'char') && builtin('size',value,1) == 1 && ...
    builtin('size',value,2) == requiredLength;
if valid
    valid = all((value >= '0' & value <= '9') | ...
        (value >= 'a' & value <= 'f'));
end
end

function valid = localCaseId(value)
roles = {'P0_parent','P0R_parent_repeat','T1_initial_defect', ...
    'T2_material_state','T3_loading_history'};
valid = false;
for index = 1:numel(roles)
    if localExactChar(value,roles{index})
        valid = true;
        return
    end
end
end

function observation = localObserveContext(context)
observation = struct( ...
    'authorization_scope',context.authorization_scope, ...
    'case_id',context.case_id, ...
    'output_root',context.output_root, ...
    'state0',context.state0, ...
    'contract',context.contract, ...
    'sol_step_template',context.sol_step_template);
end

function found = localContainsExecutable(value)
found = builtin('isa',value,'function_handle') || isobject(value);
if found
    return
end
if isstruct(value)
    names = fieldnames(value);
    found = any(cellfun(@(name) localContainsExecutable(value.(name)),names));
elseif iscell(value)
    found = any(cellfun(@localContainsExecutable,value));
end
end
