function result = solve_toy_road_family_case(context)
%SOLVE_TOY_ROAD_FAMILY_CASE Run the controlled five-substep family solver core.

localValidateContext(context);
try
    result = localRunCycles(context);
catch exception
    try
        context.operators.publish_failed_run(context.output_root, ...
            context.authorization_scope, context.case_id, exception);
    catch publicationException
        combined = MException('toyRoadP0:FailurePublicationFailed', ...
            'The solver failed and its failed run receipt could not be published.');
        combined = addCause(combined, exception);
        combined = addCause(combined, publicationException);
        throw(combined);
    end
    rethrow(exception);
end
end

function result = localRunCycles(context)
operators = context.operators;
state = context.initial_state;
previous = [];
c5Receipt = struct();
c5Trace = struct();
eventState = [];
terminalCycle = 0;
stepTemplate = context.sol_step_template;
stepTemplate.n_step = 5;

for cycle = 1:context.cycle_limit
    capture = init_toy_road_cycle_capture(cycle, previous, context.state0, ...
        context.mesh, context.contract);
    for substep = 1:5
        if cycle == 5 && substep == 5
            operators.observe('c5_s5_unload');
        end
        [state, traction] = operators.begin_substep( ...
            cycle, substep, state, stepTemplate);
        dLb = state.d;
        historyPre = state.history;
        isGateSubstep = cycle == 5 && substep == 4;
        if isGateSubstep
            entry = struct( ...
                'authorization_scope', context.authorization_scope, ...
                'case_id', context.case_id, ...
                'cycle', 5, ...
                'substep_ordinal', 4, ...
                'evidence_method', 'same_process_post_update_reassembly_v1', ...
                'd_lb', dLb, ...
                'd_prev_stag', dLb, ...
                'history_pre', historyPre, ...
                'active_u_dofs', context.active_u_dofs, ...
                'active_d_dofs', context.active_d_dofs, ...
                'traction', traction, ...
                'reassemble_equilibrium', operators.reassemble_equilibrium, ...
                'reassemble_phase', operators.reassemble_phase);
            c5Trace = begin_toy_road_c5_trace(entry, context.output_root);
            operators.observe('c5_trace_begin');
        end

        converged = false;
        psiRaw = [];
        for stagger = 1:context.sol_stag_par.max_iter
            [state, psiRaw, converged] = operators.completed_stagger_update( ...
                cycle, substep, stagger, state, traction, dLb, historyPre);
            localValidateCompletedState(state, psiRaw, context.state0);
            if isGateSubstep
                if converged
                    updateEvent = sprintf('c5_stagger_%d_update_converged', stagger);
                else
                    updateEvent = sprintf('c5_stagger_%d_update', stagger);
                end
                operators.observe(updateEvent);
                row = struct('u', state.u, 'd', state.d, ...
                    'stagger_converged', converged);
                c5Trace = append_toy_road_c5_stagger_row(c5Trace, row);
                operators.observe(sprintf( ...
                    'c5_stagger_%d_reassembly_append', stagger));
                if converged
                    c5Receipt = finalize_toy_road_c5_gate(c5Trace);
                    operators.observe('c5_gate_receipt_passed');
                end
            end
            if converged
                break;
            end
        end
        if ~converged
            error('toyRoadP0:StaggeredSolveFailed', ...
                'Stagger convergence failed at cycle %d substep %d.', ...
                cycle, substep);
        end

        commitCallback = @(alphaPre,snapshot) operators.commit_history( ...
            cycle, substep, alphaPre, snapshot);
        [capture, state.history] = capture_toy_road_substep(capture, ...
            substep, state.d, psiRaw, historyPre, commitCallback);
        if isGateSubstep
            operators.observe('c5_s4_history_committed');
        end
    end
    [previous, ~] = export_toy_road_cycle_shard( ...
        capture, context.output_root, context.contract);
    eventState = operators.advance_event(eventState, ...
        context.mesh.node_coords, context.mesh.connectivity, cycle, ...
        previous.d_node(:,4));
    localValidateEventState(eventState,cycle);
    terminalCycle = cycle;
    if ~isnan(eventState.confirmed)
        break;
    end
end

if isempty(fieldnames(c5Receipt))
    error('toyRoadP0:MissingC5Gate', ...
        'The solver completed without its mandatory physical c5/s4 gate.');
end
if ~isnan(eventState.confirmed)
    terminalReason = 'confirmed';
else
    terminalReason = 'right_censored';
end
result = struct( ...
    'authorization_scope', context.authorization_scope, ...
    'case_id', context.case_id, ...
    'complete', true, ...
    'status', 'complete', ...
    'terminal_cycle', terminalCycle, ...
    'terminal_reason', terminalReason, ...
    'event_state', eventState, ...
    'trace_row_count', c5Receipt.trace_row_count, ...
    'same_process_reassembly_count', c5Receipt.reassembly_count, ...
    'c5_stagger_ordinals', c5Trace.stagger_ordinals, ...
    'c5_receipt', c5Receipt);
end

function localValidateContext(context)
required = {'authorization_scope','case_id','output_root','cycle_limit', ...
    'active_u_dofs','active_d_dofs','state0','mesh','contract', ...
    'initial_state','sol_step_template','sol_stag_par','operators'};
localContextRequire(isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(required(:))), ...
    'solver context must contain exactly the Task 4 fields.');
roles = {'P0_parent','P0R_parent_repeat','T1_initial_defect', ...
    'T2_material_state','T3_loading_history'};
localContextRequire(localScalarText(context.authorization_scope) && ...
    localScalarText(context.case_id) && any(strcmp(char(context.case_id), roles)), ...
    'authorization scope or family role is invalid.');
localContextRequire(isfolder(context.output_root) && ...
    localPositiveInteger(context.cycle_limit) && context.cycle_limit >= 5, ...
    'output root must exist and cycle_limit must reach physical cycle 5.');
localContextRequire(localActiveDofs(context.active_u_dofs) && ...
    localActiveDofs(context.active_d_dofs), 'active DOF lists are invalid.');
localContextRequire(isstruct(context.initial_state) && ...
    isequal(sort(fieldnames(context.initial_state)), {'d';'history';'u'}) && ...
    localFiniteDoubleColumn(context.initial_state.u) && ...
    localFiniteDoubleColumn(context.initial_state.d) && ...
    isa(context.initial_state.history, 'double') && ...
    isreal(context.initial_state.history) && ...
    all(isfinite(context.initial_state.history), 'all'), ...
    'initial solver state is invalid.');
localContextRequire(max(context.active_u_dofs) <= numel(context.initial_state.u) && ...
    max(context.active_d_dofs) <= numel(context.initial_state.d), ...
    'active DOFs exceed the initial solver state.');
localContextRequire(isstruct(context.sol_step_template) && ...
    isscalar(context.sol_step_template) && ...
    isfield(context.sol_step_template, 'line_search') && ...
    islogical(context.sol_step_template.line_search) && ...
    isscalar(context.sol_step_template.line_search) && ...
    ~context.sol_step_template.line_search, ...
    'the solver template must disable line search.');
localContextRequire(isstruct(context.sol_stag_par) && ...
    isscalar(context.sol_stag_par) && ...
    isfield(context.sol_stag_par, 'max_iter') && ...
    localPositiveInteger(context.sol_stag_par.max_iter), ...
    'stagger parameters must contain a positive max_iter.');
operatorFields = {'begin_substep','completed_stagger_update', ...
    'reassemble_equilibrium','reassemble_phase','commit_history','advance_event', ...
    'observe','publish_failed_run'};
localContextRequire(isstruct(context.operators) && isscalar(context.operators) && ...
    isequal(sort(fieldnames(context.operators)), sort(operatorFields(:))), ...
    'controlled solver operators are incomplete or contain an injection.');
for index = 1:numel(operatorFields)
    localContextRequire(isa(context.operators.(operatorFields{index}), ...
        'function_handle'), 'every controlled solver operator must be callable.');
end
end

function localValidateEventState(state,cycle)
required = {'first_hit','confirmed','consecutive_post_hit','hit'};
valid = isstruct(state) && isscalar(state) && all(isfield(state,required)) && ...
    localEventCycle(state.first_hit,cycle) && ...
    localEventCycle(state.confirmed,cycle) && ...
    isnumeric(state.consecutive_post_hit) && ...
    isscalar(state.consecutive_post_hit) && isfinite(state.consecutive_post_hit) && ...
    state.consecutive_post_hit >= 0 && ...
    state.consecutive_post_hit == floor(state.consecutive_post_hit) && ...
    islogical(state.hit) && isscalar(state.hit);
if valid && ~isnan(state.confirmed)
    valid = ~isnan(state.first_hit) && state.confirmed >= state.first_hit+3;
end
if ~valid
    error('toyRoadP0:InvalidEventState', ...
        'The case-local event operator returned an invalid event state.');
end
end

function value = localEventCycle(value,currentCycle)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    (isnan(value) || (isfinite(value) && value >= 1 && ...
    value <= currentCycle && value == floor(value)));
end

function localValidateCompletedState(state, psiRaw, state0)
valid = isstruct(state) && isscalar(state) && ...
    isequal(sort(fieldnames(state)), {'d';'history';'u'}) && ...
    localFiniteDoubleColumn(state.u) && localFiniteDoubleColumn(state.d) && ...
    isequal(size(state.d), size(state0.d_node)) && ...
    isa(state.history, 'double') && isreal(state.history) && ...
    isequal(size(state.history), size(state0.alpha_bar_gp)) && ...
    all(isfinite(state.history), 'all') && isa(psiRaw, 'double') && ...
    isreal(psiRaw) && isequal(size(psiRaw), size(state0.alpha_bar_gp)) && ...
    all(isfinite(psiRaw), 'all');
if ~valid
    error('toyRoadP0:InvalidCompletedStagger', ...
        'A controlled operator returned an invalid completed stagger state.');
end
end

function value = localActiveDofs(value)
value = isa(value, 'double') && iscolumn(value) && ~isempty(value) && ...
    all(isfinite(value)) && all(value == floor(value)) && all(value >= 1) && ...
    numel(unique(value)) == numel(value);
end

function value = localFiniteDoubleColumn(value)
value = isa(value, 'double') && isreal(value) && iscolumn(value) && ...
    ~isempty(value) && all(isfinite(value));
end

function value = localPositiveInteger(value)
value = isa(value, 'double') && isscalar(value) && isfinite(value) && ...
    value >= 1 && value == floor(value);
end

function value = localScalarText(value)
value = (ischar(value) && isrow(value) && ~isempty(value)) || ...
    (isstring(value) && isscalar(value) && strlength(value) > 0);
end

function localContextRequire(condition, message)
if ~condition
    error('toyRoadP0:InvalidSolverContext', message);
end
end
