function metrics = validate_toy_road_cycle_shard(shard, previous, state0, contract)
%VALIDATE_TOY_ROAD_CYCLE_SHARD Validate one immutable five-substep state shard.

localRequire(isstruct(shard) && isscalar(shard), 'shard must be a scalar struct.');
localRequire(isstruct(state0) && isscalar(state0), 'state0 must be a scalar struct.');
localRequire(isstruct(contract) && isscalar(contract), 'contract must be a scalar struct.');

requiredShard = {'cycle', 'd_node', 'd_gp', 'alpha_bar_gp', 'f_alpha_gp', ...
    'psi_raw_gp', 'g_gp', 'psi_active_gp', 'psi_raw_cyclemax_gp', ...
    'substep_ordinal', 'load_factor', 'raw_step_zero_based', 'branch', ...
    'mesh_sha256', 'element_ordering_id', 'gp_ordering_id', ...
    'state_semantics_id', 'runtime_lock_sha256', 'family_contract_sha256', ...
    'case_physics_contract_sha256', 'execution_input_lock_sha256'};
requiredState0 = {'d_node', 'alpha_bar_gp'};
requiredContract = {'eta', 'alpha_T', 'p', 'mesh_sha256', ...
    'element_ordering_id', 'gp_ordering_id', 'state_semantics_id', ...
    'runtime_lock_sha256', 'family_contract_sha256', ...
    'case_physics_contract_sha256', 'execution_input_lock_sha256'};
localRequireFields(shard, requiredShard, 'shard');
localRequireFields(state0, requiredState0, 'state0');
localRequireFields(contract, requiredContract, 'contract');
localRequire(localAllNumericFinite(shard) && localAllNumericFinite(state0) && ...
    localAllNumericFinite(contract), 'All numeric values must be finite and real.');

localRequire(localPositiveInteger(shard.cycle), 'cycle must be a positive integer.');
localRequire(localNonnegativeScalar(contract.eta) && ...
    localPositiveScalar(contract.alpha_T) && localPositiveScalar(contract.p), ...
    'eta, alpha_T, and p must be finite nonnegative/positive real scalars.');

nSubstep = 5;
nGp = 4;
nNode = size(shard.d_node, 1);
localRequire(nNode > 0 && isequal(size(shard.d_node), [nNode nSubstep]), ...
    'd_node must be n_node-by-5.');
nElem = size(shard.d_gp, 1);
localRequire(nElem > 0 && isequal(size(shard.d_gp), [nElem nGp nSubstep]), ...
    'd_gp must be n_elem-by-4-by-5.');
gpFields = {'alpha_bar_gp', 'f_alpha_gp', 'psi_raw_gp', 'g_gp', 'psi_active_gp'};
for index = 1:numel(gpFields)
    localRequire(isequal(size(shard.(gpFields{index})), [nElem nGp nSubstep]), ...
        '%s must be n_elem-by-4-by-5.', gpFields{index});
end
localRequire(isequal(size(shard.psi_raw_cyclemax_gp), [nElem nGp]), ...
    'psi_raw_cyclemax_gp must be n_elem-by-4.');
localRequire(isequal(size(state0.d_node), [nNode 1]) && ...
    isequal(size(state0.alpha_bar_gp), [nElem nGp]), ...
    'state0 must match shard node and GP dimensions.');

localRequire(isequal(shard.substep_ordinal, 1:nSubstep) && ...
    isequal(shard.load_factor, [.25 .5 .75 1 0]) && ...
    isequal(shard.raw_step_zero_based, 5 * (shard.cycle - 1) + (0:4)) && ...
    isequal(shard.branch, {'loading','loading','loading','loading','unloading'}), ...
    'Five-substep chronology metadata does not match the locked schedule.');
localRequire(localTextEquals(shard.mesh_sha256, contract.mesh_sha256) && ...
    localTextEquals(shard.element_ordering_id, contract.element_ordering_id) && ...
    localTextEquals(shard.gp_ordering_id, contract.gp_ordering_id) && ...
    localTextEquals(shard.state_semantics_id, contract.state_semantics_id) && ...
    localTextEquals(shard.runtime_lock_sha256, contract.runtime_lock_sha256) && ...
    localTextEquals(shard.family_contract_sha256, contract.family_contract_sha256) && ...
    localTextEquals(shard.case_physics_contract_sha256, contract.case_physics_contract_sha256) && ...
    localTextEquals(shard.execution_input_lock_sha256, contract.execution_input_lock_sha256), ...
    'Shard ID or digest does not match the locked contract.');

nodalTolerance = 1e-12;
historyTolerance = 1e-12;
fatigueTolerance = 1e-12;
rangeTolerance = 1e-10;
identityTolerance = 1e-12;
[previousDamage, previousAlpha] = localPredecessor(shard, previous, state0, nNode, nElem, nGp);

damageHistoryMinDelta = Inf;
alphaHistoryMinDelta = Inf;
for substep = 1:nSubstep
    localRequire(all(shard.d_node(:,substep) >= previousDamage - nodalTolerance) && ...
        all(shard.d_node(:,substep) <= 1 + nodalTolerance), ...
        'd_node violates primal feasibility at a chronology predecessor.');
    localRequire(all(shard.alpha_bar_gp(:,:,substep) >= previousAlpha - historyTolerance, 'all'), ...
        'alpha_bar_gp decreases at a chronology predecessor.');
    damageHistoryMinDelta = min(damageHistoryMinDelta, ...
        min(shard.d_node(:,substep) - previousDamage, [], 'all'));
    alphaHistoryMinDelta = min(alphaHistoryMinDelta, ...
        min(shard.alpha_bar_gp(:,:,substep) - previousAlpha, [], 'all'));
    previousDamage = shard.d_node(:,substep);
    previousAlpha = shard.alpha_bar_gp(:,:,substep);
end

localRequire(all(shard.d_gp(:) >= -rangeTolerance) && ...
    all(shard.d_gp(:) <= 1 + rangeTolerance), ...
    'd_gp lies outside [0, 1].');
localRequire(all(shard.alpha_bar_gp(:) >= -historyTolerance), ...
    'alpha_bar_gp must be nonnegative.');
localRequire(all(shard.f_alpha_gp(:) >= -fatigueTolerance) && ...
    all(shard.f_alpha_gp(:) <= 1 + fatigueTolerance), ...
    'f_alpha_gp lies outside [0, 1].');
localRequire(all(shard.psi_raw_gp(:) >= -rangeTolerance) && ...
    all(shard.psi_active_gp(:) >= -rangeTolerance), ...
    'Raw and active drivers must be nonnegative.');

fExpected = min(1, ...
    (1 - ((shard.alpha_bar_gp-contract.alpha_T) ./ ...
          (shard.alpha_bar_gp+contract.alpha_T))).^contract.p);
gExpected = (1-shard.d_gp).^2 + contract.eta;
activeExpected = shard.g_gp .* shard.psi_raw_gp;
cyclemaxExpected = max(shard.psi_raw_gp,[],3);

fError = max(abs(shard.f_alpha_gp - fExpected), [], 'all');
gError = max(abs(shard.g_gp - gExpected), [], 'all');
activeError = max(abs(shard.psi_active_gp - activeExpected), [], 'all');
cyclemaxError = max(abs(shard.psi_raw_cyclemax_gp - cyclemaxExpected), [], 'all');
identityMaxError = max([fError gError activeError cyclemaxError]);
localRequire(identityMaxError <= identityTolerance, ...
    'A recomputed shard identity exceeds the locked tolerance.');

metrics = struct( ...
    'is_valid', true, ...
    'chronology_ok', true, ...
    'cycle', shard.cycle, ...
    'damage_min', min([shard.d_node(:); shard.d_gp(:)]), ...
    'damage_max', max([shard.d_node(:); shard.d_gp(:)]), ...
    'alpha_bar_min', min(shard.alpha_bar_gp(:)), ...
    'alpha_bar_max', max(shard.alpha_bar_gp(:)), ...
    'f_alpha_min', min(shard.f_alpha_gp(:)), ...
    'f_alpha_max', max(shard.f_alpha_gp(:)), ...
    'psi_raw_min', min(shard.psi_raw_gp(:)), ...
    'psi_raw_max', max(shard.psi_raw_gp(:)), ...
    'psi_active_min', min(shard.psi_active_gp(:)), ...
    'psi_active_max', max(shard.psi_active_gp(:)), ...
    'f_alpha_identity_max_abs_error', fError, ...
    'g_identity_max_abs_error', gError, ...
    'active_identity_max_abs_error', activeError, ...
    'cyclemax_identity_max_abs_error', cyclemaxError, ...
    'identity_max_abs_error', identityMaxError, ...
    'damage_history_min_delta', damageHistoryMinDelta, ...
    'alpha_history_min_delta', alphaHistoryMinDelta);
end

function [previousDamage, previousAlpha] = localPredecessor(shard, previous, state0, nNode, nElem, nGp)
if shard.cycle == 1
    localRequire(isempty(previous), 'previous must be empty only for cycle 1.');
    previousDamage = state0.d_node;
    previousAlpha = state0.alpha_bar_gp;
    return;
end

localRequire(isstruct(previous) && isscalar(previous), ...
    'previous must be the immediately preceding scalar shard.');
localRequireFields(previous, {'cycle', 'd_node', 'alpha_bar_gp'}, 'previous');
localRequire(localAllNumericFinite(previous), 'previous numeric values must be finite and real.');
localRequire(localPositiveInteger(previous.cycle) && previous.cycle == shard.cycle - 1 && ...
    isequal(size(previous.d_node), [nNode 5]) && ...
    isequal(size(previous.alpha_bar_gp), [nElem nGp 5]), ...
    'previous is not the immediately preceding five-substep shard.');
previousDamage = previous.d_node(:,5);
previousAlpha = previous.alpha_bar_gp(:,:,5);
end

function localRequireFields(value, names, label)
for index = 1:numel(names)
    localRequire(isfield(value, names{index}), ...
        '%s is missing required field %s.', label, names{index});
end
end

function value = localAllNumericFinite(input)
value = true;
if isstruct(input)
    names = fieldnames(input);
    for index = 1:numel(names)
        value = value && localAllNumericFinite(input.(names{index}));
    end
elseif isnumeric(input)
    value = isreal(input) && all(isfinite(input), 'all');
end
end

function value = localPositiveInteger(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 1 && value == floor(value);
end

function value = localNonnegativeScalar(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0;
end

function value = localPositiveScalar(value)
value = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value > 0;
end

function value = localTextEquals(actual, expected)
actualIsText = (ischar(actual) && isrow(actual)) || ...
    (isstring(actual) && isscalar(actual));
expectedIsText = (ischar(expected) && isrow(expected)) || ...
    (isstring(expected) && isscalar(expected));
value = actualIsText && expectedIsText && strcmp(string(actual), string(expected));
end

function localRequire(condition, message, varargin)
if ~condition
    error('toyRoadP0:InvalidCycleShard', message, varargin{:});
end
end
