function summary = validate_toy_road_terminal_package(root, case_id, contract_path)
%VALIDATE_TOY_ROAD_TERMINAL_PACKAGE Validate one closed immutable case package.

try
    summary = localValidate(root, case_id, contract_path);
catch exception
    if strcmp(exception.identifier, 'toyRoadP0:InvalidTerminalPackage')
        rethrow(exception);
    end
    error('toyRoadP0:InvalidTerminalPackage', '%s', exception.message);
end
end

function summary = localValidate(root, caseId, contractPath)
root = localExistingFolder(root, 'root');
localRequireNotLink(root, 'root');
caseId = localText(caseId, 'case_id');
contractPath = localExistingFile(contractPath, 'contract_path');
loadedContract = load(contractPath, 'contract');
localRequire(isfield(loadedContract, 'contract') && ...
    isstruct(loadedContract.contract) && isscalar(loadedContract.contract), ...
    'contract_path must contain one scalar contract struct.');
contract = loadedContract.contract;
protocolVersion = 'toy-road-p0-repeatability-v2.1';
requiredContract = {'eta', 'alpha_T', 'p', 'mesh_sha256', ...
    'element_ordering_id', 'gp_ordering_id', 'state_semantics_id', ...
    'runtime_lock_sha256', 'family_contract_sha256', ...
    'case_physics_contract_sha256', 'execution_input_lock_sha256'};
localRequireFields(contract, requiredContract, 'contract');

manifestPath = fullfile(root, 'TERMINAL_MANIFEST.json');
manifest = localReadJson(manifestPath, 'terminal manifest');
manifestDigest = fileSha256(manifestPath);
manifestFields = {'authorization_scope', 'protocol_version', 'case_id', ...
    'source_commit', 'mesh_sha256', 'element_ordering_id', 'gp_ordering_id', ...
    'state_semantics_id', 'runtime_lock_sha256', 'family_contract_sha256', ...
    'case_physics_contract_sha256', 'physical_input_sha256', 'solver_sha256', ...
    'recovery_sha256', 'exporter_sha256', 'numerical_gate_contract_sha256', ...
    'event_contract_sha256', 'execution_input_lock_sha256', 'files'};
localRequireExactFields(manifest, manifestFields, 'terminal manifest');
localRequire(strcmp(localText(manifest.protocol_version, ...
    'manifest protocol_version'), protocolVersion), ...
    'Terminal manifest protocol_version is invalid.');
localRequire(strcmp(localText(manifest.case_id, 'manifest case_id'), caseId), ...
    'Terminal manifest case_id does not match the requested case.');
authorizationScope = localText(manifest.authorization_scope, ...
    'manifest authorization_scope');
localRequire(localCanonicalGitCommit(manifest.source_commit), ...
    'Manifest source_commit must be canonical lowercase hexadecimal text.');
digestFields = {'mesh_sha256', 'runtime_lock_sha256', ...
    'family_contract_sha256', 'case_physics_contract_sha256', ...
    'physical_input_sha256', 'solver_sha256', 'recovery_sha256', ...
    'exporter_sha256', 'numerical_gate_contract_sha256', ...
    'event_contract_sha256', 'execution_input_lock_sha256'};
for index = 1:numel(digestFields)
    localRequire(localCanonicalSha(manifest.(digestFields{index})), ...
        'Manifest %s is not canonical SHA-256 text.', digestFields{index});
end
textIdentityFields = {'element_ordering_id', 'gp_ordering_id', ...
    'state_semantics_id'};
for index = 1:numel(textIdentityFields)
    localText(manifest.(textIdentityFields{index}), textIdentityFields{index});
end
localRequireContractIdentity(manifest, contract);

[manifestPaths, manifestHashes] = localManifestEntries(manifest.files);
actualPaths = localPackageFiles(root);
localRequire(isequal(manifestPaths, sort(manifestPaths)) && ...
    numel(unique(manifestPaths)) == numel(manifestPaths), ...
    'Terminal manifest paths must be sorted and unique.');
localRequire(numel(unique(lower(manifestPaths))) == numel(manifestPaths), ...
    'Terminal manifest contains a case-folded path collision.');
localRequire(isequal(manifestPaths, actualPaths), ...
    'Terminal manifest does not exactly close over package files.');
localVerifyHashes(root, manifestPaths, manifestHashes);

requiredPaths = [ ...
    "EXECUTION_INPUT_LOCK.json"; "STATE0.mat"; "EVENT_METADATA.json"; ...
    "TERMINAL_RESULT.json"; "qualification/C5_STAGGER_TRACE.csv"; ...
    "qualification/C5_NUMERICAL_GATE_RECEIPT.json"];
localRequire(all(ismember(requiredPaths, manifestPaths)), ...
    'Terminal package is missing a required case-local artifact.');

executionPath = fullfile(root, 'EXECUTION_INPUT_LOCK.json');
executionDigest = fileSha256(executionPath);
localRequire(strcmp(executionDigest, localText( ...
    manifest.execution_input_lock_sha256, 'manifest execution digest')) && ...
    strcmp(executionDigest, localText( ...
    contract.execution_input_lock_sha256, 'contract execution digest')), ...
    'Execution-lock digest is inconsistent with its own manifest or contract.');
executionLock = localReadJson(executionPath, 'execution lock');
executionLockFields = {'schema_version', 'protocol_version', ...
    'authorization_scope', 'case_id', 'family_contract_sha256', ...
    'case_physics_contract_sha256', 'source_commit', ...
    'runtime_lock_sha256', 'source_manifest_sha256', 'runtime_expectations', ...
    'writable_roots', ...
    'launch_timestamp_utc', 'no_clobber_receipt_id', 'resume_allowed'};
localRequireExactFields(executionLock, executionLockFields, 'execution lock');
localRequire(strcmp(localText(executionLock.authorization_scope, ...
    'execution authorization_scope'), authorizationScope) && ...
    strcmp(localText(executionLock.case_id, 'execution case_id'), caseId) && ...
    strcmp(localText(executionLock.protocol_version, ...
    'execution protocol_version'), protocolVersion) && ...
    strcmp(localText(executionLock.family_contract_sha256, ...
    'execution family contract'), manifest.family_contract_sha256) && ...
    strcmp(localText(executionLock.case_physics_contract_sha256, ...
    'execution case contract'), manifest.case_physics_contract_sha256) && ...
    strcmp(localText(executionLock.source_commit, ...
    'execution source commit'), manifest.source_commit) && ...
    strcmp(localText(executionLock.runtime_lock_sha256, ...
    'execution runtime lock'), manifest.runtime_lock_sha256) && ...
    islogical(executionLock.resume_allowed) && isscalar(executionLock.resume_allowed) && ...
    ~executionLock.resume_allowed, ...
    'Execution lock is not self-consistent for this case.');

tracePath = fullfile(root, 'qualification', 'C5_STAGGER_TRACE.csv');
receiptPath = fullfile(root, 'qualification', 'C5_NUMERICAL_GATE_RECEIPT.json');
receipt = localReadJson(receiptPath, 'c5 receipt');
localValidateC5(tracePath, receipt, authorizationScope, caseId);

event = localReadJson(fullfile(root, 'EVENT_METADATA.json'), 'event metadata');
terminal = localReadJson(fullfile(root, 'TERMINAL_RESULT.json'), 'terminal result');
eventFields = {'authorization_scope', 'case_id', 'first_hit_cycle', ...
    'confirmed_cycle', 'terminal_cycle', 'peak_substep_ordinal', ...
    'cycle_shard', 'cycle_shard_sha256'};
terminalFields = {'authorization_scope', 'case_id', 'terminal_reason', ...
    'terminal_cycle', 'first_hit_cycle', 'confirmed_cycle'};
localRequireExactFields(event, eventFields, 'event metadata');
localRequireExactFields(terminal, terminalFields, 'terminal result');
localRequire(strcmp(localText(event.case_id, 'event case_id'), caseId) && ...
    strcmp(localText(terminal.case_id, 'terminal case_id'), caseId) && ...
    strcmp(localText(event.authorization_scope, ...
    'event authorization_scope'), authorizationScope) && ...
    strcmp(localText(terminal.authorization_scope, ...
    'terminal authorization_scope'), authorizationScope), ...
    'Event, terminal and manifest identities are inconsistent.');
localRequire(localSameScalar(event.first_hit_cycle, terminal.first_hit_cycle) && ...
    localSameScalar(event.confirmed_cycle, terminal.confirmed_cycle) && ...
    localSameScalar(event.terminal_cycle, terminal.terminal_cycle) && ...
    localIntegerEquals(event.peak_substep_ordinal, 4) && ...
    localPositiveInteger(event.first_hit_cycle) && ...
    event.confirmed_cycle == event.first_hit_cycle + 3 && ...
    event.confirmed_cycle == event.terminal_cycle && ...
    strcmp(localText(terminal.terminal_reason, 'terminal reason'), ...
    'confirmed_penetration'), ...
    'Event metadata and terminal result are inconsistent.');
terminalCycle = terminal.terminal_cycle;
localRequire(localPositiveInteger(terminalCycle) && terminalCycle >= 5, ...
    'Terminal cycle must be an integer at or after the case-local c5 gate.');

cyclePaths = manifestPaths(startsWith(manifestPaths, "substeps/cycle_") & ...
    endsWith(manifestPaths, ".mat"));
cycleNumbers = zeros(numel(cyclePaths), 1);
for index = 1:numel(cyclePaths)
    token = regexp(char(cyclePaths(index)), ...
        '^substeps/cycle_([0-9]{4})\.mat$', 'tokens', 'once');
    localRequire(~isempty(token), 'Cycle shard path is not canonical.');
    cycleNumbers(index) = str2double(token{1});
end
localRequire(isequal(cycleNumbers, (1:terminalCycle).'), ...
    'Cycle shards must be exactly consecutive from c1 through terminal.');

state = load(fullfile(root, 'STATE0.mat'), 'state0');
localRequire(isfield(state, 'state0') && isstruct(state.state0) && ...
    isscalar(state.state0), 'STATE0.mat must contain one scalar state0 struct.');
localRequireExactFields(state.state0, {'d_node', 'alpha_bar_gp'}, 'state0');
localRequireDoubleFields(state.state0, {'d_node', 'alpha_bar_gp'}, 'state0');
shardFields = {'cycle', 'd_node', 'd_gp', 'alpha_bar_gp', 'f_alpha_gp', ...
    'psi_raw_gp', 'g_gp', 'psi_active_gp', 'psi_raw_cyclemax_gp', ...
    'substep_ordinal', 'load_factor', 'raw_step_zero_based', 'branch', ...
    'mesh_sha256', 'element_ordering_id', 'gp_ordering_id', ...
    'state_semantics_id', 'runtime_lock_sha256', 'family_contract_sha256', ...
    'case_physics_contract_sha256', 'execution_input_lock_sha256'};
numericShardFields = {'cycle', 'd_node', 'd_gp', 'alpha_bar_gp', ...
    'f_alpha_gp', 'psi_raw_gp', 'g_gp', 'psi_active_gp', ...
    'psi_raw_cyclemax_gp', 'substep_ordinal', 'load_factor', ...
    'raw_step_zero_based'};
previous = [];
maxIdentityError = 0;
minimumDamageDelta = Inf;
minimumAlphaDelta = Inf;
for cycle = 1:terminalCycle
    cyclePath = fullfile(root, 'substeps', sprintf('cycle_%04d.mat', cycle));
    loaded = load(cyclePath, 'shard');
    localRequire(isfield(loaded, 'shard') && isstruct(loaded.shard) && ...
        isscalar(loaded.shard), 'Every cycle MAT must contain one scalar shard.');
    localRequireExactFields(loaded.shard, shardFields, ...
        sprintf('cycle %d shard', cycle));
    localRequireDoubleFields(loaded.shard, numericShardFields, ...
        sprintf('cycle %d shard', cycle));
    metrics = validate_toy_road_cycle_shard( ...
        loaded.shard, previous, state.state0, contract);
    maxIdentityError = max(maxIdentityError, metrics.identity_max_abs_error);
    minimumDamageDelta = min(minimumDamageDelta, ...
        metrics.damage_history_min_delta);
    minimumAlphaDelta = min(minimumAlphaDelta, metrics.alpha_history_min_delta);
    previous = loaded.shard;
end

eventCyclePath = localText(event.cycle_shard, 'event cycle_shard');
expectedEventPath = sprintf('substeps/cycle_%04d.mat', event.confirmed_cycle);
localRequire(strcmp(eventCyclePath, expectedEventPath) && ...
    localCanonicalSha(event.cycle_shard_sha256) && ...
    strcmp(localText(event.cycle_shard_sha256, 'event shard digest'), ...
    fileSha256(localFromRelative(root, string(eventCyclePath)))), ...
    'Event metadata does not byte-identify its cycle peak shard.');

finalPaths = localPackageFiles(root);
localRequire(isequal(finalPaths, manifestPaths) && ...
    strcmp(fileSha256(manifestPath), manifestDigest), ...
    'Package closure or manifest changed during validation.');
localVerifyHashes(root, manifestPaths, manifestHashes);

summary = struct( ...
    'is_valid', true, 'case_id', caseId, ...
    'terminal_cycle', terminalCycle, 'cycle_count', numel(cycleNumbers), ...
    'manifest_sha256', manifestDigest, ...
    'c5_receipt_sha256', fileSha256(receiptPath), ...
    'identity_max_abs_error', maxIdentityError, ...
    'damage_history_min_delta', minimumDamageDelta, ...
    'alpha_history_min_delta', minimumAlphaDelta);
end

function localValidateC5(tracePath, receipt, authorizationScope, caseId)
receiptFields = {'authorization_scope', 'case_id', 'cycle', ...
    'substep_ordinal', 'status', 'passed', 'trace_sha256', ...
    'trace_row_count', 'reassembly_count', 'final_stagger_iteration', ...
    'final_reassembly_ordinal', 'final_displacement_residual', ...
    'final_raw_phase_residual', 'final_projected_phase_kkt', ...
    'final_consecutive_stagger_delta', 'final_primal_feasibility', ...
    'displacement_residual_threshold', 'projected_phase_kkt_threshold', ...
    'consecutive_stagger_delta_threshold', 'primal_feasibility_threshold'};
localRequireExactFields(receipt, receiptFields, 'c5 receipt');
trace = readtable(tracePath, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
traceColumns = {'authorization_scope', 'case_id', 'cycle', ...
    'substep_ordinal', 'stagger_iteration', 'reassembly_ordinal', ...
    'displacement_residual', 'raw_phase_residual', 'projected_phase_kkt', ...
    'consecutive_stagger_delta', 'primal_feasibility'};
localRequire(isequal(trace.Properties.VariableNames, traceColumns), ...
    'Case-local c5 trace columns are invalid.');
localRequire(height(trace) > 0, 'Case-local c5 trace must not be empty.');
numericColumns = traceColumns(3:end);
for index = 1:numel(numericColumns)
    value = trace.(numericColumns{index});
    localRequire(isnumeric(value) && isreal(value) && all(isfinite(value)), ...
        'Case-local c5 trace column %s must be finite numeric.', ...
        numericColumns{index});
end
localRequire(all(trace.authorization_scope == string(authorizationScope)) && ...
    all(trace.case_id == string(caseId)) && all(trace.cycle == 5) && ...
    all(trace.substep_ordinal == 4) && ...
    isequal(trace.stagger_iteration, (1:height(trace)).') && ...
    isequal(trace.reassembly_ordinal, (1:height(trace)).') && ...
    all(trace{:, 7:end} >= 0, 'all'), ...
    'Case-local c5 trace identity, chronology or range is invalid.');
last = height(trace);
localRequire(strcmp(localText(receipt.authorization_scope, ...
    'c5 authorization_scope'), authorizationScope) && ...
    strcmp(localText(receipt.case_id, 'c5 case_id'), caseId) && ...
    localIntegerEquals(receipt.cycle, 5) && ...
    localIntegerEquals(receipt.substep_ordinal, 4) && ...
    strcmp(localText(receipt.status, 'c5 status'), 'PASS') && ...
    islogical(receipt.passed) && isscalar(receipt.passed) && receipt.passed && ...
    localCanonicalSha(receipt.trace_sha256) && ...
    strcmp(localText(receipt.trace_sha256, 'c5 trace_sha256'), ...
    fileSha256(tracePath)) && ...
    localIntegerEquals(receipt.trace_row_count, height(trace)) && ...
    localIntegerEquals(receipt.reassembly_count, height(trace)) && ...
    localIntegerEquals(receipt.final_stagger_iteration, ...
    trace.stagger_iteration(last)) && ...
    localIntegerEquals(receipt.final_reassembly_ordinal, ...
    trace.reassembly_ordinal(last)), ...
    'Case-local c5 receipt identity, hash or counts are invalid.');
metricPairs = { ...
    'final_displacement_residual', 'displacement_residual'; ...
    'final_raw_phase_residual', 'raw_phase_residual'; ...
    'final_projected_phase_kkt', 'projected_phase_kkt'; ...
    'final_consecutive_stagger_delta', 'consecutive_stagger_delta'; ...
    'final_primal_feasibility', 'primal_feasibility'};
for index = 1:size(metricPairs, 1)
    localRequire(localFiniteScalar(receipt.(metricPairs{index, 1})) && ...
        receipt.(metricPairs{index, 1}) == trace.(metricPairs{index, 2})(last), ...
        'Case-local c5 final metric %s is invalid.', metricPairs{index, 1});
end
thresholdPairs = { ...
    'displacement_residual_threshold', 4e-4; ...
    'projected_phase_kkt_threshold', 4e-4; ...
    'consecutive_stagger_delta_threshold', 1e-3; ...
    'primal_feasibility_threshold', 1e-12};
for index = 1:size(thresholdPairs, 1)
    localRequire(localFiniteScalar(receipt.(thresholdPairs{index, 1})) && ...
        receipt.(thresholdPairs{index, 1}) == thresholdPairs{index, 2}, ...
        'Case-local c5 threshold %s is invalid.', thresholdPairs{index, 1});
end
localRequire(receipt.final_displacement_residual <= ...
    receipt.displacement_residual_threshold && ...
    receipt.final_projected_phase_kkt <= ...
    receipt.projected_phase_kkt_threshold && ...
    receipt.final_consecutive_stagger_delta <= ...
    receipt.consecutive_stagger_delta_threshold && ...
    receipt.final_primal_feasibility <= receipt.primal_feasibility_threshold, ...
    'Case-local c5 final metrics do not pass their thresholds.');
end

function [paths, hashes] = localManifestEntries(files)
localRequire(isstruct(files) && ~isempty(files), ...
    'Terminal manifest files must be a nonempty struct array.');
paths = strings(numel(files), 1);
hashes = strings(numel(files), 1);
for index = 1:numel(files)
    localRequireExactFields(files(index), {'path', 'sha256'}, ...
        'manifest file entry');
    paths(index) = string(localText(files(index).path, 'manifest path'));
    hashes(index) = string(localText(files(index).sha256, 'manifest sha256'));
    parts = split(paths(index), '/');
    localRequire(~startsWith(paths(index), "/") && ...
        ~contains(paths(index), "\") && ...
        all(parts ~= "" & parts ~= "." & parts ~= "..") && ...
        localCanonicalSha(hashes(index)), ...
        'Manifest file entry is not canonical.');
end
end

function paths = localPackageFiles(root)
paths = localScanDirectory(root, root);
paths(paths == "TERMINAL_MANIFEST.json") = [];
paths = sort(paths);
localRequire(numel(unique(lower(paths))) == numel(paths), ...
    'Package contains a case-folded path collision.');
end

function paths = localScanDirectory(root, folder)
entries = dir(folder);
entries = entries(~ismember({entries.name}, {'.', '..'}));
paths = strings(0, 1);
for index = 1:numel(entries)
    absolute = fullfile(entries(index).folder, entries(index).name);
    relative = replace(erase(string(absolute), string(root) + filesep), '\', '/');
    localRequireNotLink(absolute, char(relative));
    if entries(index).isdir
        paths = [paths; localScanDirectory(root, absolute)]; %#ok<AGROW>
    else
        paths(end + 1, 1) = relative; %#ok<AGROW>
    end
end
end

function localRequireNotLink(path, label)
if ispc
    attributes = System.IO.File.GetAttributes(path);
    localRequire(~contains(char(attributes.ToString()), 'ReparsePoint'), ...
        'Package path %s must not be a link or reparse point.', label);
end
file = java.io.File(path);
absolute = char(file.getAbsolutePath());
canonical = char(file.getCanonicalPath());
if ispc
    same = strcmpi(absolute, canonical);
else
    same = strcmp(absolute, canonical);
end
localRequire(same, 'Package path %s must not be a link or reparse point.', label);
end

function localVerifyHashes(root, paths, hashes)
for index = 1:numel(paths)
    localRequire(strcmp(fileSha256(localFromRelative(root, paths(index))), ...
        hashes(index)), 'Package bytes do not match the terminal manifest.');
end
end

function path = localFromRelative(root, relative)
parts = split(relative, '/');
path = root;
for index = 1:numel(parts)
    path = fullfile(path, char(parts(index)));
end
end

function localRequireContractIdentity(manifest, contract)
digestNames = {'mesh_sha256', 'runtime_lock_sha256', ...
    'family_contract_sha256', 'case_physics_contract_sha256', ...
    'execution_input_lock_sha256'};
for index = 1:numel(digestNames)
    name = digestNames{index};
    localRequire(localCanonicalSha(contract.(name)) && ...
        strcmp(localText(manifest.(name), name), ...
        localText(contract.(name), name)), ...
        'Manifest identity %s does not match the contract.', name);
end
textNames = {'element_ordering_id', 'gp_ordering_id', 'state_semantics_id'};
for index = 1:numel(textNames)
    name = textNames{index};
    localRequire(strcmp(localText(manifest.(name), name), ...
        localText(contract.(name), name)), ...
        'Manifest identity %s does not match the contract.', name);
end
end

function value = localReadJson(path, label)
path = localExistingFile(path, label);
value = jsondecode(fileread(path));
localRequire(isstruct(value) && isscalar(value), '%s must be one JSON object.', label);
end

function path = localExistingFolder(path, label)
path = localText(path, label);
localRequire(isfolder(path), '%s must name an existing folder.', label);
end

function path = localExistingFile(path, label)
path = localText(path, label);
localRequire(isfile(path), '%s must name an existing file.', label);
end

function value = localText(value, label)
isText = (ischar(value) && isrow(value)) || (isstring(value) && isscalar(value));
localRequire(isText && strlength(string(value)) > 0, '%s must be scalar text.', label);
value = char(value);
end

function localRequireExactFields(value, names, label)
localRequire(isstruct(value) && isscalar(value), '%s must be a scalar struct.', label);
localRequire(isequal(sort(fieldnames(value)), sort(names(:))), ...
    '%s fields do not match the canonical schema.', label);
end

function localRequireFields(value, names, label)
for index = 1:numel(names)
    localRequire(isfield(value, names{index}), ...
        '%s is missing required field %s.', label, names{index});
end
end

function localRequireDoubleFields(value, names, label)
for index = 1:numel(names)
    field = value.(names{index});
    localRequire(isa(field, 'double') && isreal(field) && ...
        all(isfinite(field), 'all'), ...
        '%s.%s must be exact real double and finite.', label, names{index});
end
end

function value = localCanonicalSha(input)
isText = (ischar(input) && isrow(input)) || ...
    (isstring(input) && isscalar(input));
value = isText && ~isempty(regexp(char(input), '^[0-9a-f]{64}$', 'once'));
end

function value = localCanonicalGitCommit(input)
isText = (ischar(input) && isrow(input)) || ...
    (isstring(input) && isscalar(input));
value = isText && ~isempty(regexp(char(input), '^[0-9a-f]{40}$', 'once'));
end

function value = localIntegerEquals(input, expected)
value = localPositiveInteger(input) && input == expected;
end

function value = localPositiveInteger(input)
value = isnumeric(input) && isreal(input) && isscalar(input) && ...
    isfinite(input) && input >= 1 && input == floor(input);
end

function value = localFiniteScalar(input)
value = isnumeric(input) && isreal(input) && isscalar(input) && isfinite(input);
end

function value = localSameScalar(left, right)
value = isnumeric(left) && isnumeric(right) && isscalar(left) && ...
    isscalar(right) && isequaln(left, right);
end

function digest = fileSha256(path)
fileId = fopen(path, 'rb');
localRequire(fileId >= 0, 'Cannot read package file: %s', path);
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, '*uint8');
hasher = java.security.MessageDigest.getInstance('SHA-256');
hasher.update(bytes);
digestBytes = typecast(hasher.digest(), 'uint8');
digest = lower(reshape(dec2hex(digestBytes, 2).', 1, []));
end

function localRequire(condition, message, varargin)
if ~condition
    error('toyRoadP0:InvalidTerminalPackage', message, varargin{:});
end
end
