function result = run_toy_road_driver_core(request,dependencies)
%RUN_TOY_ROAD_DRIVER_CORE Execute the fixed post-authorization driver sequence.

localValidateRequest(request);
localValidateDependencies(dependencies);
reserve_toy_road_writable_roots(request);

parentMesh = dependencies.load_parent_mesh(request.input_assets_root);
cfg = build_toy_road_family_case(request.case_id,parentMesh);
localRequire(cfg.sol_step_par.n_step == 5 && ...
    ~cfg.sol_step_par.line_search && ~cfg.sol_jump_par.cycle_jump && ...
    ~cfg.resume_allowed, 'The built case violates the Hard5 solver contract.');
recoveryInput = dependencies.build_recovery_input(cfg,parentMesh);
[sys,d,dOld,history,recoveryDetails] = ...
    recover_toy_road_family_state(recoveryInput);
state0 = struct( ...
    'd_node',d, ...
    'alpha_bar_gp',history(:,:,2), ...
    'history_vars',history, ...
    'd_node_old',dOld, ...
    'recovery_residual',recoveryDetails.recovery_residual, ...
    'state_semantics_id','fresh_hard_recovered_state0_v2');
runtimeReceipt = dependencies.runtime_receipt(request);
localValidateRuntimeReceipt(runtimeReceipt,request);
localPublishInitialAssets(request,cfg,state0,runtimeReceipt);

recovery = struct('sys',sys,'d',d,'d_old',dOld,'history_vars',history, ...
    'details',recoveryDetails);
context = dependencies.build_solver_context(cfg,recovery,request);
context = localBindApprovedSolverContext(context,cfg,state0,request);
result = dependencies.solve_family_case(context);
end

function localValidateRequest(request)
required = {'authorization_scope','authorization_receipt','case_id', ...
    'source_commit','runtime_lock_sha256','family_contract_sha256', ...
    'case_physics_contract_sha256','execution_input_lock_sha256', ...
    'output_root','work_root','temp_root','tmp_root','pref_root','cache_root', ...
    'input_assets_root'};
valid = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)),sort(required(:)));
if valid
    roles = {'P0_parent','P0R_parent_repeat','T1_initial_defect', ...
        'T2_material_state','T3_loading_history'};
    scopes = {'production_authorized','test_only_non_authorizing'};
    valid = localText(request.authorization_scope) && ...
        any(strcmp(char(request.authorization_scope),scopes)) && ...
        localText(request.case_id) && any(strcmp(char(request.case_id),roles)) && ...
        localHex(request.source_commit,40) && ...
        localHex(request.runtime_lock_sha256,64) && ...
        localHex(request.family_contract_sha256,64) && ...
        localHex(request.case_physics_contract_sha256,64) && ...
        localHex(request.execution_input_lock_sha256,64) && ...
        isstruct(request.authorization_receipt) && ...
        isscalar(request.authorization_receipt);
    paths = required(9:end);
    for index = 1:numel(paths)
        valid = valid && localText(request.(paths{index}));
    end
end
if ~valid
    error('toyRoadP0:InvalidDriverRequest', ...
        'Driver core request fields, identities, or paths are invalid.');
end
end

function localValidateDependencies(dependencies)
required = {'load_parent_mesh','build_recovery_input','build_solver_context', ...
    'runtime_receipt','solve_family_case'};
valid = isstruct(dependencies) && isscalar(dependencies) && ...
    isequal(sort(fieldnames(dependencies)),sort(required(:)));
for index = 1:numel(required)
    valid = valid && isa(dependencies.(required{index}),'function_handle');
end
if ~valid
    error('toyRoadP0:InvalidDriverDependencies', ...
        'Driver dependencies must contain only the declared callable interfaces.');
end
end

function localPublishInitialAssets(request,cfg,state0,runtimeReceipt)
snapshot = struct( ...
    'schema_version','toy_road_p0_input_snapshot_v1', ...
    'authorization_scope',char(request.authorization_scope), ...
    'case_id',char(request.case_id), ...
    'source_commit',lower(char(request.source_commit)), ...
    'runtime_lock_sha256',lower(char(request.runtime_lock_sha256)), ...
    'family_contract_sha256',lower(char(request.family_contract_sha256)), ...
    'case_physics_contract_sha256', ...
        lower(char(request.case_physics_contract_sha256)), ...
    'execution_input_lock_sha256', ...
        lower(char(request.execution_input_lock_sha256)), ...
    'input_assets_root',char(request.input_assets_root), ...
    'mesh_sha256',cfg.mesh.mesh_sha256, ...
    'changed_axes',{cfg.changed_axes}, ...
    'case_physics',cfg.case_physics, ...
    'fresh_state0',true, ...
    'resume_allowed',false, ...
    'line_search',false, ...
    'cycle_jump',false);
localPublishJson(fullfile(request.output_root,'INPUT_SNAPSHOT.json'),snapshot);
localPublishMat(fullfile(request.output_root,'mesh_geometry.mat'), ...
    struct('mesh_geometry',cfg.mesh));
localPublishMat(fullfile(request.output_root,'state0_analysis.mat'), ...
    struct('state0',state0));
localPublishJson(fullfile(request.output_root,'RUNTIME_RECEIPT.json'),runtimeReceipt);
end

function context = localBindApprovedSolverContext(context,cfg,state0,request)
required = {'authorization_scope','case_id','output_root','cycle_limit', ...
    'active_u_dofs','active_d_dofs','state0','mesh','contract', ...
    'initial_state','sol_step_template','sol_stag_par','operators'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~isequal(sort(fieldnames(context)),sort(required(:))) || ...
        ~isstruct(context.initial_state) || ...
        ~all(isfield(context.initial_state,{'u','d','history'}))
    error('toyRoadP0:InvalidDriverContext', ...
        'Solver-context factory did not return the approved Task 4 interface.');
end
contract = struct( ...
    'eta',cfg.case_physics.material.eta, ...
    'alpha_T',cfg.case_physics.material.alpha_T, ...
    'p',cfg.case_physics.material.p, ...
    'mesh_sha256',cfg.mesh.mesh_sha256, ...
    'element_ordering_id',cfg.mesh.element_ordering_id, ...
    'gp_ordering_id',cfg.mesh.gp_ordering_id, ...
    'state_semantics_id','five_substep_post_commit_history_v1', ...
    'runtime_lock_sha256',lower(char(request.runtime_lock_sha256)), ...
    'family_contract_sha256',lower(char(request.family_contract_sha256)), ...
    'case_physics_contract_sha256', ...
        lower(char(request.case_physics_contract_sha256)), ...
    'execution_input_lock_sha256', ...
        lower(char(request.execution_input_lock_sha256)));
context.authorization_scope = char(request.authorization_scope);
context.case_id = char(request.case_id);
context.output_root = char(request.output_root);
context.state0 = struct('d_node',state0.d_node, ...
    'alpha_bar_gp',state0.alpha_bar_gp);
context.mesh = cfg.mesh;
context.contract = contract;
context.initial_state.d = state0.d_node;
context.initial_state.history = state0.alpha_bar_gp;
context.sol_step_template = cfg.sol_step_par;
if context.cycle_limit < 5 || context.cycle_limit > cfg.censor_cap
    error('toyRoadP0:InvalidDriverContext', ...
        'Solver cycle limit must remain in the declared interval 5:150.');
end
end

function localValidateRuntimeReceipt(receipt,request)
required = {'status','authorization_scope','case_id','source_commit', ...
    'runtime_lock_sha256'};
valid = isstruct(receipt) && isscalar(receipt) && all(isfield(receipt,required)) && ...
    strcmp(char(receipt.status),'PASS') && ...
    strcmp(char(receipt.authorization_scope),char(request.authorization_scope)) && ...
    strcmp(char(receipt.case_id),char(request.case_id)) && ...
    strcmpi(char(receipt.source_commit),char(request.source_commit)) && ...
    strcmpi(char(receipt.runtime_lock_sha256),char(request.runtime_lock_sha256));
if ~valid
    error('toyRoadP0:InvalidRuntimeReceipt', ...
        'Runtime receipt does not bind the authorized source/runtime/case.');
end
end

function localPublishJson(path,payload)
content = [jsonencode(payload) newline];
localPublishBytes(path,unicode2native(content,'UTF-8'));
end

function localPublishMat(path,payload)
directory = fileparts(path);
temporary = localReserveTemporary(directory,'.asset_','.mat');
cleanup = onCleanup(@() localDeleteIfPresent(temporary));
save(temporary,'-struct','payload','-v7.3');
localCreateExclusiveHardLink(temporary,path);
delete(temporary);
clear cleanup
end

function localPublishBytes(path,bytes)
directory = fileparts(path);
temporary = localReserveTemporary(directory,'.asset_','.tmp');
cleanup = onCleanup(@() localDeleteIfPresent(temporary));
fileId = fopen(temporary,'wb');
if fileId < 0
    error('toyRoadP0:PublicationFailed','Cannot open temporary asset.');
end
fileCleanup = onCleanup(@() fclose(fileId));
count = fwrite(fileId,bytes,'uint8');
if count ~= numel(bytes)
    error('toyRoadP0:PublicationFailed','Cannot write complete temporary asset.');
end
clear fileCleanup
localCreateExclusiveHardLink(temporary,path);
delete(temporary);
clear cleanup
end

function path = localReserveTemporary(directory,prefix,suffix)
try
    attributes = javaArray('java.nio.file.attribute.FileAttribute',0);
    temporary = java.nio.file.Files.createTempFile( ...
        java.io.File(directory).toPath(),prefix,suffix,attributes);
    path = char(temporary.toString());
catch exception
    error('toyRoadP0:PublicationFailed', ...
        'Cannot reserve temporary asset: %s',exception.message);
end
end

function localCreateExclusiveHardLink(temporary,path)
try
    java.nio.file.Files.createLink( ...
        java.io.File(path).toPath(),java.io.File(temporary).toPath());
catch exception
    if isfile(path) || isfolder(path)
        error('toyRoadP0:PublicationClobber', ...
            'Refusing to overwrite published asset: %s',path);
    end
    error('toyRoadP0:PublicationFailed', ...
        'Cannot publish immutable asset: %s',exception.message);
end
end

function localDeleteIfPresent(path)
if isfile(path)
    delete(path);
end
end

function valid = localText(value)
valid = (ischar(value) && isrow(value) && ~isempty(strtrim(value))) || ...
    (isstring(value) && isscalar(value) && strlength(strtrim(value)) > 0);
end

function valid = localHex(value,lengthRequired)
if ~localText(value)
    valid = false;
    return
end
text = char(value);
valid = numel(text) == lengthRequired && ...
    all(ismember(lower(text),'0123456789abcdef'));
end

function localRequire(condition,message)
if ~condition
    error('toyRoadP0:InvalidDriverContext',message);
end
end
